//! リボンの zh-tw 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py zh-tw > ui/src/ribbon_zh-tw.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "檔案", cmds: &[
        c("open", "開啟", "open"),
        c("save", "儲存", "save"),
        c("pdf", "列印", "print"),
    ]},
    Tab { name: "首頁", cmds: &[
        c("copy", "複製", "copy"),
        c("cut", "剪下", "cut"),
        c("paste", "貼上", "paste"),
        c("fontname", "字型", "fontname"),
        c("fontsize", "字型大小", "fontsize"),
        c("incfont", "放大文字", "incfont"),
        c("decfont", "縮小文字", "decfont"),
        c("changecase", "大小寫轉換", "changecase"),
        c("ruby", "注音標示", "ruby"),
        c("bold", "粗體", "bold"),
        c("italic", "斜體", "italic"),
        c("underline", "下劃線", "underline"),
        c("strikeout", "刪除線", "strikeout"),
        c("superscript", "上標", "superscript"),
        c("subscript", "下標", "subscript"),
        c("highlight", "文字醒目提示色彩", "highlight"),
        c("fontcolor", "字型顏色", "fontcolor"),
        c("clearstyle", "清除樣式", "clearstyle"),
        c("markers", "項目符號", "markers"),
        c("numbering", "編號", "numbering"),
        c("multilevels", "多層次清單", "multilevels"),
        c("decoffset", "減少縮排", "decoffset"),
        c("incoffset", "縮排", "incoffset"),
        c("linespace", "段落行距", "linespace"),
        c("direction", "文字方向", "direction"),
        c("align-left", "靠左對齊", "align-left"),
        c("align-center", "置中", "align-center"),
        c("align-right", "靠右對齊", "align-right"),
        c("align-just", "兩端對齊", "align-just"),
        c("align-dist", "分散對齊", "align-dist"),
        c("hidenchars", "顯示/隱藏編輯標記", "hidenchars"),
        c("paracolor", "網底", "paracolor"),
        c("borders", "框線", "borders"),
        c("parastyle", "段落風格", "styles"),
        c("replace", "取代", "replace"),
        c("selectall", "全選", "select-all"),
    ]},
    Tab { name: "插入", cmds: &[
        c("blankpage", "插入空白頁", "blankpage"),
        c("pagebreak", "插入頁面或章節分隔符", "pagebreak"),
        c("instable", "插入表格", "instable"),
        c("insimage", "插入圖片", "insertimage"),
        c("insshape", "插入形狀", "insshape"),
        c("inssmartart", "插入SmartArt", "inssmartart"),
        c("inschart", "插入圖表", "inschart"),
        c("smartpicker", "插入圖表", "smartpicker"),
        c("instext", "插入文字方塊", "instext"),
        c("instextart", "插入藝術文字", "instextart"),
        c("dropcap", "插入首字下沉", "dropcap"),
        c("text-from-file", "從檔案匯入文字", "text-from-file"),
        c("edit-header", "編輯頁首", "edit-header"),
        c("edit-footer", "編輯頁尾", "edit-footer"),
        c("pagenum", "頁碼", "pagenum"),
        c("datetime", "日期與時間", "datetime"),
        c("numpages", "頁數", "numpages"),
        c("insequation", "插入方程式", "insequation"),
        c("inssymbol", "插入符號", "inssymbol"),
        c("controls", "插入內容控制項", "controls"),
    ]},
    Tab { name: "繪製", cmds: &[
        c("pen", "筆", "pen"),
        c("highlighter", "螢光筆", "highlighter"),
        c("eraser", "橡皮擦", "eraser"),
    ]},
    Tab { name: "版面配置", cmds: &[
        c("pagemargins", "邊框", "pagemargins"),
        c("pageorient", "頁面方向", "pageorient"),
        c("pagesize", "頁面大小", "pagesize"),
        c("columns", "插入欄", "columns"),
        c("line-numbers", "顯示行號", "line-numbers"),
        c("hyphenation", "斷字", "hyphenation"),
        c("watermark", "編輯浮水印", "watermark"),
        c("pagecolor", "變更頁面顏色", "pagecolor"),
        c("colorschemas", "變更色彩配置", "colorschemas"),
    ]},
    Tab { name: "參考文獻", cmds: &[
        c("toc", "目錄", "contents"),
        c("add-text", "新增文字", "add-text"),
        c("toc-update", "更新目錄", "contents-update"),
        c("bookmarks", "書籤", "bookmarks"),
        c("caption", "標號", "caption"),
        c("crossref", "交互參照", "crossref"),
        c("footnote", "註腳", "footnote"),
        c("tof", "圖表目錄", "tof"),
        c("tof-update", "更新圖表目錄", "tof-update"),
    ]},
    Tab { name: "表單", cmds: &[
        c("form-text", "文字段落", "form-text"),
        c("form-combo", "下拉式方框", "form-combo"),
        c("form-dropdown", "下拉式選單", "form-dropdown"),
        c("form-checkbox", "核取方塊", "form-checkbox"),
        c("form-radio", "單選按鈕", "form-radio"),
        c("form-image", "圖片", "form-image"),
        c("form-email", "電子郵件", "form-email"),
        c("form-phone", "電話號碼", "form-phone"),
        c("form-complex", "複雜字段", "form-complex"),
        c("form-signature", "簽名", "form-signature"),
        c("form-name", "名稱", "form-name"),
    ]},
    Tab { name: "共同編輯", cmds: &[
        c("coauth-mode", "共同編輯模式", "coauth-mode"),
        c("co-addcomment", "新增註解", "co-addcomment"),
        c("co-delcomment", "刪除註解", "co-delcomment"),
        c("co-showcomment", "顯示註解", "co-showcomment"),
        c("co-chat", "聊天", "co-chat"),
        c("track-changes", "追蹤變更", "track-changes"),
        c("co-history", "版本歷程", "co-history"),
    ]},
    Tab { name: "保護", cmds: &[
        c("prot-encrypt", "加密", "prot-encrypt"),
        c("prot-sign", "新增數位簽章", "prot-sign"),
        c("prot-doc", "保護", "prot-doc"),
    ]},
    Tab { name: "檢視", cmds: &[
        c("nav", "導覽", "nav"),
        c("fit-page", "縮放至整頁", "fit-page"),
        c("fit-width", "縮放至頁面寬度", "fit-width"),
        c("zoom100", "縮放至 100%", "zoom100"),
        c("zoom-in", "放大", "zoom-in"),
        c("zoom-out", "縮小", "zoom-out"),
        c("printview", "整頁模式", "printview"),
        c("multipage", "多頁", "multipage"),
        c("darkmode", "深色模式", "darkmode"),
        c("ruler", "尺規", "ruler"),
        c("show-toolbar", "顯示工具列", "show-toolbar"),
        c("show-statusbar", "狀態列", "show-statusbar"),
        c("show-left", "左側面板", "show-left"),
        c("show-right", "右側面板", "show-right"),
    ]},
    Tab { name: "外掛程式", cmds: &[
        c("plug-macros", "巨集", "plug-macros"),
        c("plug-manage", "管理外掛程式", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "目的地", "ai-where"),
        c("ai-summary", "摘要", "ai-summary"),
        c("ai-rewrite", "改寫", "ai-rewrite"),
        c("ai-polite", "更禮貌", "ai-polite"),
        c("ai-plain", "更淺白", "ai-plain"),
        c("ai-translate", "翻譯", "ai-translate"),
        c("ai-furigana", "注音", "ai-furigana"),
        c("ai-continue", "續寫", "ai-continue"),
        c("ai-table", "轉成表格", "ai-table"),
        c("ai-ask", "提出需求", "ai-ask"),
        c("ai-macro", "撰寫巨集", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "檔案", cmds: &[
        c("open", "開啟", "open"),
        c("save", "儲存", "save"),
        c("pdf", "列印", "print"),
    ]},
    Tab { name: "首頁", cmds: &[
        c("copy", "複製", "copy"),
        c("cut", "剪下", "cut"),
        c("paste", "貼上", "paste"),
        c("copystyle", "複製格式", "copystyle"),
        c("fontname", "字型", "fontname"),
        c("fontsize", "字型大小", "fontsize"),
        c("incfont", "放大文字", "incfont"),
        c("decfont", "縮小文字", "decfont"),
        c("changecase", "大小寫轉換", "changecase"),
        c("bold", "粗體", "bold"),
        c("italic", "斜體", "italic"),
        c("underline", "下劃線", "underline"),
        c("strikeout", "刪除線", "strikeout"),
        c("subscript", "下標", "subscript"),
        c("fontcolor", "字型顏色", "fontcolor"),
        c("fillparag", "填充顏色", "fillparag"),
        c("borders", "邊框", "borders"),
        c("top", "靠上對齊", "top"),
        c("middle", "置中", "middle"),
        c("bottom", "對齊底部", "bottom"),
        c("wrap", "自動換列", "wrap"),
        c("text-orient", "頁面方向", "text-orient"),
        c("align-left", "靠左對齊", "align-left"),
        c("align-center", "置中", "align-center"),
        c("align-right", "靠右對齊", "align-right"),
        c("align-just", "兩端對齊", "align-just"),
        c("align-dist", "分散對齊", "align-dist"),
        c("merge", "合併和居中", "merge"),
        c("direction", "文字方向(右起橫書)", "direction"),
        c("insert-function", "函數", "formula"),
        c("fill-num", "填滿", "fill-num"),
        c("defname", "名稱管理員", "named-range"),
        c("clear", "清除", "clear"),
        c("sort-desc", "降序", "sortdesc"),
        c("sort-asc", "升序", "sortasc"),
        c("setfilter", "過濾器", "setfilter"),
        c("clear-filter", "清除篩選", "clear-filter"),
        c("format", "數字格式", "format"),
        c("currency", "貨幣樣式", "currency"),
        c("percents", "百分比樣式", "percents"),
        c("comma", "千分位樣式", "comma"),
        c("digit-dec", "減少小數位數", "digit-dec"),
        c("digit-inc", "增加小數位數", "digit-inc"),
        c("cell-ins", "插入儲存格", "cell-ins"),
        c("cell-del", "刪除儲存格", "cell-del"),
        c("cell-format", "儲存格樣式", "cell-format"),
        c("condformat", "條件格式設定", "condformat"),
        c("table-tpl", "插入表格", "table-tpl"),
        c("cell-styles", "儲存格樣式", "styles"),
        c("replace", "取代", "replace"),
        c("selectall", "全選", "select-all"),
    ]},
    Tab { name: "插入", cmds: &[
        c("pivot-insert", "插入樞紐分析表", "add-pivot"),
        c("instable", "插入表格", "instable"),
        c("insimage", "插入圖片", "insimage-c"),
        c("insshape", "插入形狀", "insshape"),
        c("inssmartart", "插入SmartArt", "inssmartart"),
        c("inscheckbox", "核取方塊", "inscheckbox"),
        c("insrecommend", "插入建議圖表", "insrecommend"),
        c("inschart", "插入圖表", "inschart"),
        c("inssparkline", "插入迷你圖", "inssparkline"),
        c("addcomment", "評論", "ins-comment"),
        c("insrecommend", "插入圖表", "smartpicker"),
        c("inshyperlink", "新增超連結", "inshyperlink"),
        c("insslicer", "插入切片器", "insslicer"),
        c("instext", "插入文字方塊", "instext"),
        c("instextart", "插入藝術文字", "instextart"),
        c("editheader", "頁首及頁尾", "editheader"),
        c("insequation", "插入方程式", "insequation"),
        c("inssymbol", "插入符號", "inssymbol"),
    ]},
    Tab { name: "繪製", cmds: &[
        c("draw-select", "選擇", "select-tool"),
        c("pen", "筆", "pen"),
        c("highlighter", "螢光筆", "highlighter"),
        c("eraser", "橡皮擦", "eraser"),
    ]},
    Tab { name: "版面配置", cmds: &[
        c("pagemargins", "邊框", "pagemargins"),
        c("pageorient", "頁面方向", "pageorient"),
        c("pagesize", "頁面大小", "pagesize"),
        c("printarea", "列印範圍", "printarea"),
        c("pagebreak", "在您希望下一頁開始列印的位置新增分頁符號", "pagebreak"),
        c("editheader", "頁首及頁尾", "editheader"),
        c("scale", "縮放以適合", "scale"),
        c("fit-pages", "配合紙張大小", "fit-pages"),
        c("printarea-add", "加入列印範圍", "printarea-add"),
        c("show-breaks", "分頁線", "show-breaks"),
        c("printtitles", "列印標題", "printtitles"),
        c("rtl-sheet", "切換工作表方向，使第一列位於右側", "rtl-sheet"),
        c("print-gridlines", "列印格線", "print-gridlines"),
        c("print-headings", "列印標題", "print-headings"),
        x("向前移動", "img-movefrwd"),
        x("向後發送", "img-movebkwd"),
        x("對齊", "img-align"),
        x("分組", "img-group"),
        x("合併圖形", "shapes-merge"),
        c("colorschemas", "變更色彩配置", "colorschemas"),
    ]},
    Tab { name: "公式", cmds: &[
        c("insert-function", "插入函數", "additional-formula"),
        c("sum", "自動加總", "autosum"),
        c("fn-recent", "最近使用的函數", "recent"),
        c("fn-financial", "財務", "financial"),
        c("fn-logical", "邏輯", "logical"),
        c("fn-text", "文字操作", "text"),
        c("fn-datetime", "日期與時間", "datetime"),
        c("fn-lookup", "查閱與參照", "lookup"),
        c("fn-math", "數學與三角函數", "math"),
        c("fn-more", "更多函數", "more"),
        c("defname", "名稱管理員", "named-range-huge"),
        c("paste-name", "貼上名稱", "paste-name"),
        c("trace-prec", "追蹤前導參照", "trace-prec"),
        c("trace-dep", "追蹤從屬參照", "trace-dep"),
        c("remove-arrows", "移除箭號", "remove-arrows"),
        c("show-formulas", "顯示公式", "show-formulas"),
        c("watch", "監看視窗", "watch-window"),
        c("calc-mode", "計算方式", "calculate"),
    ]},
    Tab { name: "資料", cmds: &[
        c("data-from-text", "文字轉資料", "data-from-text"),
        c("data-external-links", "外部連結(以值匯入)", "data-external-links"),
        c("setfilter", "過濾器", "setfilter"),
        c("clear-filter", "清除篩選", "clear-filter"),
        c("sort-desc", "降序", "sortdesc"),
        c("sort-asc", "升序", "sortasc"),
        c("custom-sort", "排序", "custom-sort"),
        c("text-column", "資料剖析", "text-column"),
        c("rem-duplicates", "移除重複", "rem-duplicates"),
        c("data-validation", "資料驗證", "data-validation"),
        c("goal-seek", "單變數求解", "goal-seek"),
        c("solver", "規劃求解", "solver"),
        c("group", "分組", "group"),
        c("ungroup", "取消分組", "ungroup"),
        c("show-details", "顯示詳細資料", "show-details"),
        c("hide-details", "隱藏詳細資料", "hide-details"),
        c("subtotal", "小計", "subtotal"),
        c("datatable", "運算列表", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "CSV 格式", "csv-kind"),
        c("flash-fill", "快速填入", "flash-fill"),
    ]},
    Tab { name: "Python", cmds: &[
        c("py-edit", "編輯函式", "py-edit"),
        c("py-new", "新增 .py", "py-new"),
        c("py-run", "執行程序", "py-run"),
        c("py-list", "清單", "py-list"),
        c("py-line", "單行程式碼", "py-line"),
        c("py-calc", "重新計算", "py-calc"),
        c("py-folder", "開啟資料夾", "py-folder"),
    ]},
    Tab { name: "樞紐分析表", cmds: &[
        c("pivot-insert", "插入樞紐分析表", "pivot-insert"),
        c("pivot-fields", "欄位清單", "pivot-fields"),
        c("pivot-refresh", "更新", "pivot-refresh"),
        c("pivot-refresh-all", "全部更新", "pivot-refresh-all"),
        c("pivot-select", "選擇", "pivot-select"),
        c("pivot-totals", "總計", "pivot-totals"),
        c("pivot-subtotals", "小計", "pivot-subtotals"),
        c("pivot-blank", "空白行", "pivot-blank"),
        c("pivot-showas", "值的顯示方式", "pivot-showas"),
        c("pivot-layout", "報表版面配置", "pivot-layout"),
        c("pivot-style", "樣式", "pivot-style"),
    ]},
    Tab { name: "表格設計", cmds: &[
        c("td-header", "頁首列", "td-header"),
        c("td-total", "總行數", "td-total"),
        c("td-band-row", "交替行", "td-band-row"),
        c("td-first", "第一欄", "td-first"),
        c("td-last", "最後一欄", "td-last"),
        c("td-band-col", "帶狀欄", "td-band-col"),
        c("td-filter", "篩選按鈕", "td-filter"),
        c("rem-duplicates", "移除重複項目", "td-remdup"),
        c("td-torange", "轉換為範圍", "td-torange"),
        c("td-resize", "調整表格大小", "td-resize"),
    ]},
    Tab { name: "共同編輯", cmds: &[
        c("coauth-mode", "共同編輯模式", "coauth-mode"),
        c("addcomment", "新增註解", "co-addcomment"),
        c("co-delcomment", "刪除註解", "co-delcomment"),
        c("co-showcomment", "顯示註解", "co-showcomment"),
        c("co-chat", "聊天", "co-chat"),
        c("co-history", "版本歷程", "co-history"),
    ]},
    Tab { name: "保護", cmds: &[
        c("prot-encrypt", "加密", "prot-encrypt"),
        x("保護工作簿", "protect-workbook"),
        c("prot-doc", "保護工作表", "protect-sheet"),
        x("保護範圍", "protect-range"),
        c("prot-sign", "新增數位簽章", "prot-sign"),
        c("cell-lock", "鎖定儲存格", "cell-lock"),
        c("prot-allow", "允許的操作", "prot-allow"),
        c("recover", "檔案復原", "recover"),
        c("recover-every", "備份間隔", "recover-every"),
        c("read-only-rec", "建議唯讀", "read-only-rec"),
    ]},
    Tab { name: "檢視", cmds: &[
        c("sheet-view", "工作表檢視", "sheet-view"),
        x("一般", "view-normal"),
        x("分頁預覽", "view-pagebreak"),
        c("zoom-in", "放大", "zoom-in"),
        c("zoom-out", "縮小", "zoom-out"),
        c("ui-bigger", "放大介面文字", "ui-bigger"),
        c("ui-smaller", "縮小介面文字", "ui-smaller"),
        c("theme", "介面佈景主題", "theme"),
        c("freeze", "凍結窗格", "freeze"),
        c("formula-bar", "公式欄", "formula-bar"),
        c("show-gridlines", "網格線", "show-gridlines"),
        c("show-headings", "標題", "show-headings"),
        c("show-zeros", "顯示 0", "show-zeros"),
    ]},
    Tab { name: "外掛程式", cmds: &[
        c("plug-macros", "巨集", "plug-macros"),
        c("plug-manage", "管理外掛程式", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "目的地", "ai-where"),
        c("ai-summary", "摘要", "ai-summary"),
        c("ai-rewrite", "改寫", "ai-rewrite"),
        c("ai-polite", "更禮貌", "ai-polite"),
        c("ai-plain", "更淺白", "ai-plain"),
        c("ai-translate", "翻譯", "ai-translate"),
        c("ai-furigana", "注音", "ai-furigana"),
        c("ai-continue", "續寫", "ai-continue"),
        c("ai-table", "轉成表格", "ai-table"),
        c("ai-ask", "提出需求", "ai-ask"),
    ]},
];

