//! リボンの zh 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py zh > ui/src/ribbon_zh.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "文件", cmds: &[
        c("open", "打开", "open"),
        c("save", "保存", "save"),
        c("pdf", "打印", "print"),
    ]},
    Tab { name: "开始", cmds: &[
        c("copy", "复制", "copy"),
        c("cut", "剪切", "cut"),
        c("paste", "粘贴", "paste"),
        c("fontname", "字体 ", "fontname"),
        c("fontsize", "字体大小", "fontsize"),
        c("incfont", "增加字体大小", "incfont"),
        c("decfont", "减小字体大小", "decfont"),
        c("changecase", "更改大小写", "changecase"),
        c("ruby", "注音", "ruby"),
        c("bold", "粗体", "bold"),
        c("italic", "斜体", "italic"),
        c("underline", "下划线", "underline"),
        c("strikeout", "删除线", "strikeout"),
        c("superscript", "上标", "superscript"),
        c("subscript", "下标", "subscript"),
        c("highlight", "高亮色", "highlight"),
        c("fontcolor", "字体颜色", "fontcolor"),
        c("clearstyle", "清除样式", "clearstyle"),
        c("markers", "项目符号", "markers"),
        c("numbering", "编号", "numbering"),
        c("multilevels", "多级列表", "multilevels"),
        c("decoffset", "减少缩进", "decoffset"),
        c("incoffset", "增加缩进", "incoffset"),
        c("linespace", "段落行距", "linespace"),
        c("direction", "文字方向", "direction"),
        c("align-left", "左对齐", "align-left"),
        c("align-center", "中心", "align-center"),
        c("align-right", "右对齐", "align-right"),
        c("align-just", "两端对齐", "align-just"),
        c("align-dist", "分散对齐", "align-dist"),
        c("hidenchars", "非打印字符", "hidenchars"),
        c("paracolor", "阴影", "paracolor"),
        c("borders", "边框", "borders"),
        c("parastyle", "段落样式", "styles"),
        c("replace", "替换", "replace"),
        c("selectall", "全选", "select-all"),
    ]},
    Tab { name: "插入", cmds: &[
        c("blankpage", "插入空白页", "blankpage"),
        c("pagebreak", "插入分页符或分节符", "pagebreak"),
        c("instable", "插入表格", "instable"),
        c("insimage", "插入图片", "insertimage"),
        c("insshape", "插入形狀", "insshape"),
        c("inssmartart", "插入智能图形", "inssmartart"),
        c("inschart", "插入图表", "inschart"),
        c("smartpicker", "插入图表", "smartpicker"),
        c("instext", "插入文本框", "instext"),
        c("instextart", "插入艺术字", "instextart"),
        c("dropcap", "插入首字下沉", "dropcap"),
        c("text-from-file", "来自文件的文本", "text-from-file"),
        c("edit-header", "编辑页眉", "edit-header"),
        c("edit-footer", "编辑页脚", "edit-footer"),
        c("pagenum", "页面编号", "pagenum"),
        c("datetime", "日期与时间", "datetime"),
        c("numpages", "页数", "numpages"),
        c("insequation", "插入方程", "insequation"),
        c("inssymbol", "插入符号", "inssymbol"),
        c("controls", "插入內容控件", "controls"),
    ]},
    Tab { name: "绘图", cmds: &[
        c("pen", "笔", "pen"),
        c("highlighter", "荧光笔", "highlighter"),
        c("eraser", "橡皮擦", "eraser"),
    ]},
    Tab { name: "布局", cmds: &[
        c("pagemargins", "边距", "pagemargins"),
        c("pageorient", "页面方向", "pageorient"),
        c("pagesize", "页面大小", "pagesize"),
        c("columns", "插入列", "columns"),
        c("line-numbers", "显示行号", "line-numbers"),
        c("hyphenation", "更改连字符号", "hyphenation"),
        c("watermark", "编辑水印", "watermark"),
        c("pagecolor", "更改页面颜色", "pagecolor"),
        c("colorschemas", "更改配色主题", "colorschemas"),
    ]},
    Tab { name: "引用", cmds: &[
        c("toc", "目录", "contents"),
        c("add-text", "添加文字", "add-text"),
        c("toc-update", "更新目录", "contents-update"),
        c("bookmarks", "书签", "bookmarks"),
        c("caption", "题注", "caption"),
        c("crossref", "交叉引用", "crossref"),
        c("tof", "图表目录", "tof"),
        c("tof-update", "更新图表目录", "tof-update"),
    ]},
    Tab { name: "表单", cmds: &[
        c("form-text", "文本字段", "form-text"),
        c("form-combo", "下拉式方框", "form-combo"),
        c("form-dropdown", "下拉菜单", "form-dropdown"),
        c("form-checkbox", "复选框", "form-checkbox"),
        c("form-radio", "单选按钮", "form-radio"),
        c("form-image", "图片", "form-image"),
        c("form-email", "Email地址", "form-email"),
        c("form-phone", "电话号码", "form-phone"),
        c("form-complex", "复合字段", "form-complex"),
        c("form-signature", "签名", "form-signature"),
        c("form-name", "名称", "form-name"),
    ]},
    Tab { name: "协作", cmds: &[
        c("coauth-mode", "共同编辑模式", "coauth-mode"),
        c("co-addcomment", "添加批注", "co-addcomment"),
        c("co-delcomment", "删除批注", "co-delcomment"),
        c("co-showcomment", "显示批注", "co-showcomment"),
        c("co-chat", "聊天", "co-chat"),
        c("track-changes", "跟踪更改", "track-changes"),
        c("co-history", "版本历史", "co-history"),
    ]},
    Tab { name: "保护", cmds: &[
        c("prot-encrypt", "加密", "prot-encrypt"),
        c("prot-sign", "添加数字签名", "prot-sign"),
        c("prot-doc", "保护", "prot-doc"),
    ]},
    Tab { name: "显示", cmds: &[
        c("nav", "导航", "nav"),
        c("fit-page", "调整至页面大小", "fit-page"),
        c("fit-width", "调整至合适宽度", "fit-width"),
        c("zoom100", "缩放到 100%", "zoom100"),
        c("zoom-in", "放大", "zoom-in"),
        c("zoom-out", "缩小", "zoom-out"),
        c("multipage", "多页", "multipage"),
        c("darkmode", "深色模式", "darkmode"),
        c("ruler", "标尺", "ruler"),
        c("show-toolbar", "始终显示工具栏", "show-toolbar"),
        c("show-statusbar", "状态栏", "show-statusbar"),
        c("show-left", "左侧面パネル", "show-left"),
        c("show-right", "右侧面パネル", "show-right"),
    ]},
    Tab { name: "插件", cmds: &[
        c("plug-macros", "宏", "plug-macros"),
        c("plug-manage", "管理插件", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "目标地址", "ai-where"),
        c("ai-summary", "摘要", "ai-summary"),
        c("ai-rewrite", "改写", "ai-rewrite"),
        c("ai-polite", "更礼貌", "ai-polite"),
        c("ai-plain", "更通俗", "ai-plain"),
        c("ai-translate", "翻译", "ai-translate"),
        c("ai-furigana", "注音假名", "ai-furigana"),
        c("ai-continue", "续写", "ai-continue"),
        c("ai-table", "转为表格", "ai-table"),
        c("ai-ask", "询问", "ai-ask"),
        c("ai-macro", "编写宏", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "文件", cmds: &[
        c("open", "打开", "open"),
        c("save", "保存", "save"),
        c("pdf", "打印", "print"),
    ]},
    Tab { name: "开始", cmds: &[
        c("copy", "复制", "copy"),
        c("cut", "剪切", "cut"),
        c("paste", "粘贴", "paste"),
        c("copystyle", "格式刷", "copystyle"),
        c("fontname", "字体 ", "fontname"),
        c("fontsize", "字体大小", "fontsize"),
        c("incfont", "增加字体大小", "incfont"),
        c("decfont", "减小字体大小", "decfont"),
        c("changecase", "更改大小写", "changecase"),
        c("bold", "粗体", "bold"),
        c("italic", "斜体", "italic"),
        c("underline", "下划线", "underline"),
        c("strikeout", "删除线", "strikeout"),
        c("subscript", "下标", "subscript"),
        c("fontcolor", "字体颜色", "fontcolor"),
        c("fillparag", "填充顏色", "fillparag"),
        c("borders", "边框", "borders"),
        c("top", "顶端对齐", "top"),
        c("middle", "中心", "middle"),
        c("bottom", "底部对齐", "bottom"),
        c("wrap", "文字换行", "wrap"),
        c("text-orient", "页面方向", "text-orient"),
        c("align-left", "左对齐", "align-left"),
        c("align-center", "中心", "align-center"),
        c("align-right", "右对齐", "align-right"),
        c("align-just", "两端对齐", "align-just"),
        c("merge", "合并和居中", "merge"),
        c("direction", "文字方向(从右横排)", "direction"),
        c("insert-function", "函数", "formula"),
        c("fill-num", "填充", "fill-num"),
        c("defname", "名称管理", "named-range"),
        c("clear", "清除", "clear"),
        c("sort-desc", "降序排序", "sortdesc"),
        c("sort-asc", "升序排序", "sortasc"),
        c("setfilter", "筛选", "setfilter"),
        c("clear-filter", "清除筛选", "clear-filter"),
        c("format", "数字格式", "format"),
        c("currency", "货币样式", "currency"),
        c("percents", "百分比样式", "percents"),
        c("comma", "逗号样式", "comma"),
        c("digit-dec", "减少小数", "digit-dec"),
        c("digit-inc", "增加小数", "digit-inc"),
        c("cell-ins", "插入单元格", "cell-ins"),
        c("cell-del", "删除单元格", "cell-del"),
        c("cell-format", "单元格样式", "cell-format"),
        c("condformat", "条件格式", "condformat"),
        c("table-tpl", "插入表格", "table-tpl"),
        c("cell-styles", "单元格样式", "styles"),
        c("replace", "替换", "replace"),
        c("selectall", "全选", "select-all"),
    ]},
    Tab { name: "插入", cmds: &[
        c("pivot-insert", "插入数据透视表", "add-pivot"),
        c("instable", "插入表格", "instable"),
        c("insimage", "插入图片", "insimage-c"),
        c("insshape", "插入形狀", "insshape"),
        c("inssmartart", "插入智能图形", "inssmartart"),
        c("inscheckbox", "复选框", "inscheckbox"),
        c("insrecommend", "插入推荐图表", "insrecommend"),
        c("inschart", "插入图表", "inschart"),
        c("inssparkline", "插入迷你图", "inssparkline"),
        c("addcomment", "批注", "ins-comment"),
        c("insrecommend", "插入图表", "smartpicker"),
        c("inshyperlink", "添加链接", "inshyperlink"),
        c("insslicer", "插入切片器", "insslicer"),
        c("instext", "插入文本框", "instext"),
        c("instextart", "插入艺术字", "instextart"),
        c("editheader", "页眉和页脚", "editheader"),
        c("insequation", "插入方程", "insequation"),
        c("inssymbol", "插入符号", "inssymbol"),
    ]},
    Tab { name: "绘图", cmds: &[
        c("draw-select", "选择", "select-tool"),
        c("pen", "笔", "pen"),
        c("highlighter", "荧光笔", "highlighter"),
        c("eraser", "橡皮擦", "eraser"),
    ]},
    Tab { name: "布局", cmds: &[
        c("pagemargins", "边距", "pagemargins"),
        c("pageorient", "页面方向", "pageorient"),
        c("pagesize", "页面大小", "pagesize"),
        c("printarea", "打印区域", "printarea"),
        c("pagebreak", "在打印副本中你希望下一页开始的位置添加一个分隔符", "pagebreak"),
        c("editheader", "页眉和页脚", "editheader"),
        c("scale", "缩放以适合", "scale"),
        c("fit-pages", "调整为页数", "fit-pages"),
        c("printarea-add", "添加到打印区域", "printarea-add"),
        c("show-breaks", "分页符", "show-breaks"),
        c("printtitles", "打印标题", "printtitles"),
        c("rtl-sheet", "切换工作表方向，使第一列在右侧", "rtl-sheet"),
        c("print-gridlines", "打印网格线", "print-gridlines"),
        c("print-headings", "打印标题", "print-headings"),
        x("向前移动", "img-movefrwd"),
        x("下移一层", "img-movebkwd"),
        x("对齐", "img-align"),
        x("组", "img-group"),
        x("合并形状", "shapes-merge"),
        c("colorschemas", "更改配色主题", "colorschemas"),
    ]},
    Tab { name: "公式", cmds: &[
        c("insert-function", "插入函数", "additional-formula"),
        c("sum", "自动求和", "autosum"),
        c("fn-recent", "最近使用的函数", "recent"),
        c("fn-financial", "金融", "financial"),
        c("fn-logical", "合乎逻辑", "logical"),
        c("fn-text", "文本", "text"),
        c("fn-datetime", "日期与时间", "datetime"),
        c("fn-lookup", "查找和参考", "lookup"),
        c("fn-math", "数学与三角函数", "math"),
        c("fn-more", "更多函数", "more"),
        c("defname", "名称管理", "named-range-huge"),
        c("paste-name", "粘贴名称", "paste-name"),
        c("trace-prec", "追踪引用单元格", "trace-prec"),
        c("trace-dep", "追踪从属单元格", "trace-dep"),
        c("remove-arrows", "删除追踪箭头", "remove-arrows"),
        c("show-formulas", "显示公式", "show-formulas"),
        c("watch", "监视窗口", "watch-window"),
        c("calc-mode", "计算选项", "calculate"),
    ]},
    Tab { name: "数据", cmds: &[
        c("data-from-text", "文本转数据", "data-from-text"),
        c("data-external-links", "外部链接(以值导入)", "data-external-links"),
        c("setfilter", "筛选", "setfilter"),
        c("clear-filter", "清除筛选", "clear-filter"),
        c("sort-desc", "降序排序", "sortdesc"),
        c("sort-asc", "升序排序", "sortasc"),
        c("custom-sort", "分类", "custom-sort"),
        c("text-column", "分列", "text-column"),
        c("rem-duplicates", "删除重复项", "rem-duplicates"),
        c("data-validation", "数据验证", "data-validation"),
        c("goal-seek", "单变量求解", "goal-seek"),
        c("solver", "规划求解", "solver"),
        c("group", "组", "group"),
        c("ungroup", "取消组合", "ungroup"),
        c("show-details", "显示详细资料", "show-details"),
        c("hide-details", "隐藏明细", "hide-details"),
        c("subtotal", "分类汇总", "subtotal"),
        c("datatable", "模拟运算表", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "CSV 格式", "csv-kind"),
    ]},
    // Python タブ(2026-08-09)。**語だけが違う** — id と並びは ja と同じ
    Tab { name: "Python", cmds: &[
        c("py-edit", "编辑函数", "py-edit"),
        c("py-new", "新建 .py", "py-new"),
        c("py-run", "运行过程", "py-run"),
        c("py-list", "列表", "py-list"),
        c("py-line", "单行代码", "py-line"),
        c("py-calc", "重新计算", "py-calc"),
        c("py-folder", "打开文件夹", "py-folder"),
    ]},
    Tab { name: "数据透视表", cmds: &[
        c("pivot-insert", "插入数据透视表", "pivot-insert"),
        c("pivot-fields", "字段列表", "pivot-fields"),
        c("pivot-refresh", "更新", "pivot-refresh"),
        c("pivot-refresh-all", "全部更新", "pivot-refresh-all"),
        c("pivot-select", "选择", "pivot-select"),
        c("pivot-totals", "总计", "pivot-totals"),
        c("pivot-subtotals", "分类汇总", "pivot-subtotals"),
        c("pivot-blank", "空白行", "pivot-blank"),
        c("pivot-showas", "值显示方式", "pivot-showas"),
        c("pivot-layout", "报表布局", "pivot-layout"),
        c("pivot-style", "样式", "pivot-style"),
    ]},
    Tab { name: "表格设计", cmds: &[
        c("td-header", "标题行", "td-header"),
        c("td-total", "汇总行", "td-total"),
        c("td-band-row", "镶边行", "td-band-row"),
        c("td-first", "第一列", "td-first"),
        c("td-last", "最后一列", "td-last"),
        c("td-band-col", "镶边列", "td-band-col"),
        c("td-filter", "筛选按钮", "td-filter"),
        c("rem-duplicates", "删除重复项", "td-remdup"),
        c("td-torange", "转换为范围", "td-torange"),
        c("td-resize", "调整表格大小", "td-resize"),
    ]},
    Tab { name: "协作", cmds: &[
        c("coauth-mode", "共同编辑模式", "coauth-mode"),
        c("addcomment", "添加批注", "co-addcomment"),
        c("co-delcomment", "删除批注", "co-delcomment"),
        c("co-showcomment", "显示批注", "co-showcomment"),
        c("co-chat", "聊天", "co-chat"),
        c("co-history", "版本历史", "co-history"),
    ]},
    Tab { name: "保护", cmds: &[
        c("prot-encrypt", "加密", "prot-encrypt"),
        x("保护工作簿", "protect-workbook"),
        c("prot-doc", "保护工作表", "protect-sheet"),
        x("保护范围", "protect-range"),
        c("prot-sign", "添加数字签名", "prot-sign"),
        c("cell-lock", "锁定单元格", "cell-lock"),
        c("prot-allow", "允许的操作", "prot-allow"),
        c("recover", "恢复", "recover"),
        c("recover-every", "备份间隔", "recover-every"),
    ]},
    Tab { name: "显示", cmds: &[
        c("sheet-view", "工作表视图", "sheet-view"),
        x("常规", "view-normal"),
        x("分页预览", "view-pagebreak"),
        c("zoom-in", "放大", "zoom-in"),
        c("zoom-out", "缩小", "zoom-out"),
        c("ui-bigger", "放大界面文字", "ui-bigger"),
        c("ui-smaller", "缩小界面文字", "ui-smaller"),
        c("theme", "界面主题", "theme"),
        c("freeze", "冻结窗格", "freeze"),
        c("formula-bar", "公式栏", "formula-bar"),
        c("show-gridlines", "网格线", "show-gridlines"),
        c("show-headings", "标题", "show-headings"),
        c("show-zeros", "显示 0", "show-zeros"),
    ]},
    Tab { name: "插件", cmds: &[
        c("plug-macros", "宏", "plug-macros"),
        c("plug-manage", "管理插件", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "目标地址", "ai-where"),
        c("ai-summary", "摘要", "ai-summary"),
        c("ai-rewrite", "改写", "ai-rewrite"),
        c("ai-polite", "更礼貌", "ai-polite"),
        c("ai-plain", "更通俗", "ai-plain"),
        c("ai-translate", "翻译", "ai-translate"),
        c("ai-furigana", "注音假名", "ai-furigana"),
        c("ai-continue", "续写", "ai-continue"),
        c("ai-table", "转为表格", "ai-table"),
        c("ai-ask", "询问", "ai-ask"),
    ]},
];

