//! リボンの vi 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py vi > ui/src/ribbon_vi.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Mở", "open"),
        c("save", "Lưu", "save"),
        c("pdf", "In", "print"),
    ]},
    Tab { name: "Trang chủ", cmds: &[
        c("copy", "Sao chép", "copy"),
        c("cut", "Cắt", "cut"),
        c("paste", "Dán", "paste"),
        c("fontname", "Phông chữ", "fontname"),
        c("fontsize", "Cỡ chữ", "fontsize"),
        c("incfont", "Tăng kích thước phông chữ", "incfont"),
        c("decfont", "Giảm cỡ chữ", "decfont"),
        c("changecase", "Đổi chữ hoa/thường", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("bold", "Đậm", "bold"),
        c("italic", "Nghiêng", "italic"),
        c("underline", "Gạch chân", "underline"),
        c("strikeout", "Gạch bỏ", "strikeout"),
        c("superscript", "Chỉ số trên", "superscript"),
        c("subscript", "Chỉ số dưới", "subscript"),
        c("highlight", "Màu tô sáng", "highlight"),
        c("fontcolor", "Màu chữ", "fontcolor"),
        c("clearstyle", "Xóa Kiểu", "clearstyle"),
        c("markers", "Dấu đầu dòng", "markers"),
        c("numbering", "Đánh số", "numbering"),
        c("multilevels", "Danh sách Đa cấp", "multilevels"),
        c("decoffset", "Giảm thụt lề", "decoffset"),
        c("incoffset", "Tăng thụt lề", "incoffset"),
        c("linespace", "Khoảng cách Dòng trong Đoạn văn bản", "linespace"),
        c("direction", "Hướng văn bản", "direction"),
        c("align-left", "Căn trái", "align-left"),
        c("align-center", "Trung tâm", "align-center"),
        c("align-right", "Căn phải", "align-right"),
        c("align-just", "Canh đều", "align-just"),
        c("align-dist", "Phân bố đều", "align-dist"),
        c("hidenchars", "Ký tự không in", "hidenchars"),
        c("paracolor", "Màu nền đoạn văn bản", "paracolor"),
        c("borders", "Viền", "borders"),
        c("parastyle", "Kiểu đoạn", "styles"),
        c("replace", "Thay thế", "replace"),
        c("selectall", "Chọn tất cả", "select-all"),
    ]},
    Tab { name: "Chèn", cmds: &[
        c("blankpage", "Chèn trang trống", "blankpage"),
        c("pagebreak", "Chèn trang hoặc ngắt phần", "pagebreak"),
        c("instable", "Chèn bảng", "instable"),
        c("insimage", "Chèn hình ảnh", "insertimage"),
        c("insshape", "Chèn Autoshape", "insshape"),
        c("inssmartart", "Chèn SmartArt", "inssmartart"),
        c("inschart", "Chèn biểu đồ", "inschart"),
        c("smartpicker", "Chèn biểu đồ", "smartpicker"),
        c("instext", "Chèn văn bản", "instext"),
        c("instextart", "Chèn chữ nghệ thuật", "instextart"),
        c("dropcap", "Chèn Drop Cap", "dropcap"),
        c("text-from-file", "Văn bản từ tệp", "text-from-file"),
        c("edit-header", "Chỉnh sửa Header", "edit-header"),
        c("edit-footer", "Chỉnh sửa Footer", "edit-footer"),
        c("pagenum", "Số trang hiện tại", "pagenum"),
        c("datetime", "Ngày & Giờ", "datetime"),
        c("numpages", "Số trang", "numpages"),
        c("insequation", "Chèn phương trình", "insequation"),
        c("inssymbol", "Chèn ký hiệu", "inssymbol"),
        c("controls", "Chèn điều khiển nội dung", "controls"),
    ]},
    Tab { name: "Vẽ", cmds: &[
        c("pen", "Bút", "pen"),
        c("highlighter", "Bút dạ quang", "highlighter"),
        c("eraser", "Tẩy", "eraser"),
    ]},
    Tab { name: "Bố cục", cmds: &[
        c("pagemargins", "Lề", "pagemargins"),
        c("pageorient", "Hướng trang", "pageorient"),
        c("pagesize", "Kích thước trang", "pagesize"),
        c("columns", "Chèn Cột", "columns"),
        c("line-numbers", "Hiện số dòng", "line-numbers"),
        c("hyphenation", "Ngắt từ bằng dấu gạch nối", "hyphenation"),
        c("watermark", "Sửa hình mờ", "watermark"),
        c("pagecolor", "Màu trang", "pagecolor"),
        c("colorschemas", "Thay đổi Phối màu", "colorschemas"),
    ]},
    Tab { name: "Tham khảo", cmds: &[
        c("toc", "Mục lục", "contents"),
        c("add-text", "Thêm văn bản", "add-text"),
        c("toc-update", "Cập nhật mục lục", "contents-update"),
        c("bookmarks", "Dấu trang", "bookmarks"),
        c("caption", "Chú thích hình/bảng", "caption"),
        c("crossref", "Tham chiếu chéo", "crossref"),
        c("tof", "Mục lục hình/bảng", "tof"),
        c("tof-update", "Cập nhật mục lục hình/bảng", "tof-update"),
    ]},
    Tab { name: "Biểu mẫu", cmds: &[
        c("form-text", "Trường văn bản", "form-text"),
        c("form-combo", "Hộp tổ hợp", "form-combo"),
        c("form-dropdown", "Danh sách thả xuống", "form-dropdown"),
        c("form-checkbox", "Hộp kiểm", "form-checkbox"),
        c("form-radio", "Nút radio", "form-radio"),
        c("form-image", "Hình ảnh", "form-image"),
        c("form-email", "Địa chỉ email", "form-email"),
        c("form-phone", "Số điện thoại", "form-phone"),
        c("form-complex", "Trường phức hợp", "form-complex"),
        c("form-signature", "Chữ ký", "form-signature"),
        c("form-name", "Tên", "form-name"),
    ]},
    Tab { name: "Cộng tác", cmds: &[
        c("coauth-mode", "Chế độ đồng soạn thảo", "coauth-mode"),
        c("co-addcomment", "Thêm bình luận", "co-addcomment"),
        c("co-delcomment", "Xóa nhận xét", "co-delcomment"),
        c("co-showcomment", "Hiển thị bình luận", "co-showcomment"),
        c("co-chat", "Trò chuyện", "co-chat"),
        c("track-changes", "Theo dõi Thay đổi", "track-changes"),
        c("co-history", "Lịch sử phiên bản", "co-history"),
    ]},
    Tab { name: "Bảo vệ", cmds: &[
        c("prot-encrypt", "Mã hóa", "prot-encrypt"),
        c("prot-sign", "Thêm chữ ký số", "prot-sign"),
        c("prot-doc", "Bảo vệ", "prot-doc"),
    ]},
    Tab { name: "Hiển thị", cmds: &[
        c("nav", "Dẫn hướng", "nav"),
        c("fit-page", "Vừa với trang", "fit-page"),
        c("fit-width", "Vừa với Chiều rộng", "fit-width"),
        c("zoom100", "Thu phóng về 100%", "zoom100"),
        c("zoom-in", "Phóng to", "zoom-in"),
        c("zoom-out", "Thu nhỏ", "zoom-out"),
        c("multipage", "Nhiều trang", "multipage"),
        c("darkmode", "Chế độ tối", "darkmode"),
        c("ruler", "Thước", "ruler"),
        c("show-toolbar", "Luôn hiện thanh công cụ", "show-toolbar"),
        c("show-statusbar", "Thanh trạng thái", "show-statusbar"),
        c("show-left", "Bảng bên trái", "show-left"),
        c("show-right", "Bảng bên phải", "show-right"),
    ]},
    Tab { name: "Plugin", cmds: &[
        c("plug-macros", "Macro", "plug-macros"),
        c("plug-manage", "Quản lý plugin", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Đích", "ai-where"),
        c("ai-summary", "Tóm tắt", "ai-summary"),
        c("ai-rewrite", "Viết lại", "ai-rewrite"),
        c("ai-polite", "Lịch sự hơn", "ai-polite"),
        c("ai-plain", "Dễ hiểu hơn", "ai-plain"),
        c("ai-translate", "Dịch", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Viết tiếp", "ai-continue"),
        c("ai-table", "Thành bảng", "ai-table"),
        c("ai-ask", "Yêu cầu", "ai-ask"),
        c("ai-macro", "Viết macro", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Mở", "open"),
        c("save", "Lưu", "save"),
        c("pdf", "In", "print"),
    ]},
    Tab { name: "Trang chủ", cmds: &[
        c("copy", "Sao chép", "copy"),
        c("cut", "Cắt", "cut"),
        c("paste", "Dán", "paste"),
        c("copystyle", "Sao chép định dạng", "copystyle"),
        c("fontname", "Phông chữ", "fontname"),
        c("fontsize", "Cỡ chữ", "fontsize"),
        c("incfont", "Tăng kích thước phông chữ", "incfont"),
        c("decfont", "Giảm cỡ chữ", "decfont"),
        c("changecase", "Đổi chữ hoa/thường", "changecase"),
        c("bold", "Đậm", "bold"),
        c("italic", "Nghiêng", "italic"),
        c("underline", "Gạch chân", "underline"),
        c("strikeout", "Gạch bỏ", "strikeout"),
        c("subscript", "Chỉ số dưới", "subscript"),
        c("fontcolor", "Màu chữ", "fontcolor"),
        c("fillparag", "Màu nền", "fillparag"),
        c("borders", "Đường viền", "borders"),
        c("top", "Căn trên cùng", "top"),
        c("middle", "Trung tâm", "middle"),
        c("bottom", "Căn dưới cùng", "bottom"),
        c("wrap", "Ngắt dòng", "wrap"),
        c("text-orient", "Hướng trang", "text-orient"),
        c("align-left", "Căn trái", "align-left"),
        c("align-center", "Trung tâm", "align-center"),
        c("align-right", "Căn phải", "align-right"),
        c("align-just", "Canh đều", "align-just"),
        c("align-dist", "Phân bố đều", "align-dist"),
        c("merge", "Gộp", "merge"),
        c("direction", "Hướng chữ (phải sang trái)", "direction"),
        c("insert-function", "Hàm số", "formula"),
        c("fill-num", "Điền", "fill-num"),
        c("defname", "Quản lý tên", "named-range"),
        c("clear", "Xóa", "clear"),
        c("sort-desc", "Sắp xếp giảm dần", "sortdesc"),
        c("sort-asc", "Sắp xếp tăng dần", "sortasc"),
        c("setfilter", "Bộ lọc", "setfilter"),
        c("clear-filter", "Bỏ lọc", "clear-filter"),
        c("format", "Định dạng số", "format"),
        c("currency", "Kiểu tiền tệ", "currency"),
        c("percents", "Kiểu phần trăm", "percents"),
        c("comma", "Kiểu dấu phẩy", "comma"),
        c("digit-dec", "Giảm thập phân", "digit-dec"),
        c("digit-inc", "Tăng thập phân", "digit-inc"),
        c("cell-ins", "Chèn ô", "cell-ins"),
        c("cell-del", "Xóa Ô", "cell-del"),
        c("cell-format", "Kiểu ô", "cell-format"),
        c("condformat", "Định dạng có điều kiện", "condformat"),
        c("table-tpl", "Chèn bảng", "table-tpl"),
        c("cell-styles", "Kiểu ô", "styles"),
        c("replace", "Thay thế", "replace"),
        c("selectall", "Chọn tất cả", "select-all"),
    ]},
    Tab { name: "Chèn", cmds: &[
        c("pivot-insert", "Chèn PivotTable", "add-pivot"),
        c("instable", "Chèn bảng", "instable"),
        c("insimage", "Chèn hình ảnh", "insimage-c"),
        c("insshape", "Chèn Autoshape", "insshape"),
        c("inssmartart", "Chèn SmartArt", "inssmartart"),
        c("inscheckbox", "Hộp kiểm", "inscheckbox"),
        c("insrecommend", "Chèn biểu đồ đề xuất", "insrecommend"),
        c("inschart", "Chèn biểu đồ", "inschart"),
        c("inssparkline", "Chèn biểu đồ thu nhỏ", "inssparkline"),
        c("addcomment", "Bình luận", "ins-comment"),
        c("insrecommend", "Chèn biểu đồ", "smartpicker"),
        c("inshyperlink", "Thêm siêu liên kết", "inshyperlink"),
        c("insslicer", "Chèn slicer", "insslicer"),
        c("instext", "Chèn văn bản", "instext"),
        c("instextart", "Chèn chữ nghệ thuật", "instextart"),
        c("editheader", "Header/Footer", "editheader"),
        c("insequation", "Chèn phương trình", "insequation"),
        c("inssymbol", "Chèn ký hiệu", "inssymbol"),
    ]},
    Tab { name: "Vẽ", cmds: &[
        c("draw-select", "Chọn", "select-tool"),
        c("pen", "Bút", "pen"),
        c("highlighter", "Bút dạ quang", "highlighter"),
        c("eraser", "Tẩy", "eraser"),
    ]},
    Tab { name: "Bố cục", cmds: &[
        c("pagemargins", "Lề", "pagemargins"),
        c("pageorient", "Hướng trang", "pageorient"),
        c("pagesize", "Kích thước trang", "pagesize"),
        c("printarea", "Vùng in", "printarea"),
        c("pagebreak", "Chèn ngắt trang tại vị trí bắt đầu trang mới", "pagebreak"),
        c("editheader", "Header/Footer", "editheader"),
        c("scale", "Co giãn khi in", "scale"),
        c("fit-pages", "Vừa với số trang", "fit-pages"),
        c("printarea-add", "Thêm vào vùng in", "printarea-add"),
        c("show-breaks", "Ngắt trang", "show-breaks"),
        c("printtitles", "In tiêu đề", "printtitles"),
        c("rtl-sheet", "Đổi hướng trang tính để cột đầu ở bên phải", "rtl-sheet"),
        c("print-gridlines", "In cả đường lưới", "print-gridlines"),
        c("print-headings", "In cả tiêu đề", "print-headings"),
        x("Đưa lên trước", "img-movefrwd"),
        x("Gửi về phía sau", "img-movebkwd"),
        x("Căn chỉnh", "img-align"),
        x("Nhóm", "img-group"),
        x("Hợp nhất hình dạng", "shapes-merge"),
        c("colorschemas", "Thay đổi Phối màu", "colorschemas"),
    ]},
    Tab { name: "Công thức", cmds: &[
        c("insert-function", "Chèn hàm", "additional-formula"),
        c("sum", "AutoSum", "autosum"),
        c("fn-recent", "Dùng gần đây", "recent"),
        c("fn-financial", "Tài chính", "financial"),
        c("fn-logical", "Lôgic", "logical"),
        c("fn-text", "Xử lý văn bản", "text"),
        c("fn-datetime", "Ngày & Giờ", "datetime"),
        c("fn-lookup", "Tra cứu & tham chiếu", "lookup"),
        c("fn-math", "Toán & Lượng giác", "math"),
        c("fn-more", "Hàm khác", "more"),
        c("defname", "Quản lý tên", "named-range-huge"),
        c("paste-name", "Dán tên", "paste-name"),
        c("trace-prec", "Truy vết ô ảnh hưởng", "trace-prec"),
        c("trace-dep", "Truy vết ô phụ thuộc", "trace-dep"),
        c("remove-arrows", "Xóa mũi tên truy vết", "remove-arrows"),
        c("show-formulas", "Hiển thị công thức", "show-formulas"),
        c("watch", "Cửa sổ theo dõi", "watch-window"),
        c("calc-mode", "Cách tính", "calculate"),
    ]},
    Tab { name: "Dữ liệu", cmds: &[
        c("data-from-text", "Văn bản thành dữ liệu", "data-from-text"),
        c("data-external-links", "Liên kết ngoài (nhập theo giá trị)", "data-external-links"),
        c("setfilter", "Bộ lọc", "setfilter"),
        c("clear-filter", "Bỏ lọc", "clear-filter"),
        c("sort-desc", "Sắp xếp giảm dần", "sortdesc"),
        c("sort-asc", "Sắp xếp tăng dần", "sortasc"),
        c("custom-sort", "Sắp xếp", "custom-sort"),
        c("text-column", "Tách cột", "text-column"),
        c("rem-duplicates", "Xóa trùng lặp", "rem-duplicates"),
        c("data-validation", "Xác thực dữ liệu", "data-validation"),
        c("goal-seek", "Tìm mục tiêu", "goal-seek"),
        c("solver", "Solver", "solver"),
        c("group", "Nhóm", "group"),
        c("ungroup", "Bỏ nhóm", "ungroup"),
        c("show-details", "Hiển thị chi tiết", "show-details"),
        c("hide-details", "Ẩn chi tiết", "hide-details"),
        c("subtotal", "Tổng phụ", "subtotal"),
        c("datatable", "Bảng dữ liệu", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Định dạng CSV", "csv-kind"),
        c("flash-fill", "Điền nhanh", "flash-fill"),
    ]},
    // Python タブ(2026-08-09)。**語だけが違う** — id と並びは ja と同じ
    Tab { name: "Python", cmds: &[
        c("py-edit", "Sửa hàm", "py-edit"),
        c("py-new", "Tệp .py mới", "py-new"),
        c("py-run", "Chạy thủ tục", "py-run"),
        c("py-list", "Danh sách", "py-list"),
        c("py-line", "Mã một dòng", "py-line"),
        c("py-calc", "Tính lại", "py-calc"),
        c("py-folder", "Mở thư mục", "py-folder"),
    ]},
    Tab { name: "PivotTable", cmds: &[
        c("pivot-insert", "Chèn PivotTable", "pivot-insert"),
        c("pivot-fields", "Danh sách trường", "pivot-fields"),
        c("pivot-refresh", "Làm mới", "pivot-refresh"),
        c("pivot-refresh-all", "Làm mới tất cả", "pivot-refresh-all"),
        c("pivot-select", "Chọn", "pivot-select"),
        c("pivot-totals", "Tổng cộng", "pivot-totals"),
        c("pivot-subtotals", "Tổng phụ", "pivot-subtotals"),
        c("pivot-blank", "Dòng trống", "pivot-blank"),
        c("pivot-showas", "Hiển thị giá trị", "pivot-showas"),
        c("pivot-layout", "Bố cục báo cáo", "pivot-layout"),
        c("pivot-style", "Kiểu", "pivot-style"),
    ]},
    Tab { name: "Thiết kế bảng", cmds: &[
        c("td-header", "Hàng tiêu đề", "td-header"),
        c("td-total", "Hàng tổng", "td-total"),
        c("td-band-row", "Hàng xen kẽ màu", "td-band-row"),
        c("td-first", "Cột đầu", "td-first"),
        c("td-last", "Cột cuối cùng", "td-last"),
        c("td-band-col", "Cột sọc xen kẽ", "td-band-col"),
        c("td-filter", "Nút lọc", "td-filter"),
        c("rem-duplicates", "Xóa dữ liệu trùng lặp", "td-remdup"),
        c("td-torange", "Chuyển đổi sang phạm vi", "td-torange"),
        c("td-resize", "Đổi cỡ bảng", "td-resize"),
    ]},
    Tab { name: "Cộng tác", cmds: &[
        c("coauth-mode", "Chế độ đồng soạn thảo", "coauth-mode"),
        c("addcomment", "Thêm bình luận", "co-addcomment"),
        c("co-delcomment", "Xóa nhận xét", "co-delcomment"),
        c("co-showcomment", "Hiển thị bình luận", "co-showcomment"),
        c("co-chat", "Trò chuyện", "co-chat"),
        c("co-history", "Lịch sử phiên bản", "co-history"),
    ]},
    Tab { name: "Bảo vệ", cmds: &[
        c("prot-encrypt", "Mã hóa", "prot-encrypt"),
        x("Bảo vệ sổ làm việc", "protect-workbook"),
        c("prot-doc", "Bảo vệ trang tính", "protect-sheet"),
        x("Bảo vệ phạm vi", "protect-range"),
        c("prot-sign", "Thêm chữ ký số", "prot-sign"),
        c("cell-lock", "Khóa ô", "cell-lock"),
        c("prot-allow", "Thao tác được phép", "prot-allow"),
        c("recover", "Khôi phục", "recover"),
        c("recover-every", "Khoảng lưu dự phòng", "recover-every"),
        c("read-only-rec", "Đề nghị chỉ đọc", "read-only-rec"),
    ]},
    Tab { name: "Hiển thị", cmds: &[
        c("sheet-view", "Hiện trang tính", "sheet-view"),
        x("Thường", "view-normal"),
        x("Xem trước ngắt trang", "view-pagebreak"),
        c("zoom-in", "Phóng to", "zoom-in"),
        c("zoom-out", "Thu nhỏ", "zoom-out"),
        c("ui-bigger", "Phóng to chữ màn hình", "ui-bigger"),
        c("ui-smaller", "Thu nhỏ chữ màn hình", "ui-smaller"),
        c("theme", "Chủ đề giao diện", "theme"),
        c("freeze", "Cố định ngăn", "freeze"),
        c("formula-bar", "Thanh công thức", "formula-bar"),
        c("show-gridlines", "Đường lưới", "show-gridlines"),
        c("show-headings", "Tiêu đề", "show-headings"),
        c("show-zeros", "Hiển thị số 0", "show-zeros"),
    ]},
    Tab { name: "Plugin", cmds: &[
        c("plug-macros", "Macro", "plug-macros"),
        c("plug-manage", "Quản lý plugin", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Đích", "ai-where"),
        c("ai-summary", "Tóm tắt", "ai-summary"),
        c("ai-rewrite", "Viết lại", "ai-rewrite"),
        c("ai-polite", "Lịch sự hơn", "ai-polite"),
        c("ai-plain", "Dễ hiểu hơn", "ai-plain"),
        c("ai-translate", "Dịch", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Viết tiếp", "ai-continue"),
        c("ai-table", "Thành bảng", "ai-table"),
        c("ai-ask", "Yêu cầu", "ai-ask"),
    ]},
];

