//! リボンの ru 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py ru > ui/src/ribbon_ru.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Файл", cmds: &[
        c("open", "Открыть", "open"),
        c("save", "Сохранить", "save"),
        c("pdf", "Печать", "print"),
    ]},
    Tab { name: "Главная", cmds: &[
        c("copy", "Копировать", "copy"),
        c("cut", "Вырезать", "cut"),
        c("paste", "Вставить", "paste"),
        c("fontname", "Шрифт", "fontname"),
        c("fontsize", "Размер шрифта", "fontsize"),
        c("incfont", "Увеличить размер шрифта", "incfont"),
        c("decfont", "Уменьшить размер шрифта", "decfont"),
        c("changecase", "Изменить регистр", "changecase"),
        c("ruby", "Руби", "ruby"),
        c("bold", "Полужирный", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Подчёркнутый", "underline"),
        c("strikeout", "Зачёркнутый", "strikeout"),
        c("superscript", "Надстрочный", "superscript"),
        c("subscript", "Подстрочные", "subscript"),
        c("highlight", "Цвет выделения", "highlight"),
        c("fontcolor", "Цвет шрифта", "fontcolor"),
        c("clearstyle", "Очистить стиль", "clearstyle"),
        c("markers", "Маркер", "markers"),
        c("numbering", "Нумерация", "numbering"),
        c("multilevels", "Многоуровневый список", "multilevels"),
        c("decoffset", "Уменьшить отступ", "decoffset"),
        c("incoffset", "Увеличить отступ", "incoffset"),
        c("linespace", "Междустрочный интервал в абзацах", "linespace"),
        c("direction", "Направление текста", "direction"),
        c("align-left", "Выровнять по левому краю", "align-left"),
        c("align-center", "По центру", "align-center"),
        c("align-right", "Выровнять по правому краю", "align-right"),
        c("align-just", "По ширине", "align-just"),
        c("align-dist", "Распределённый", "align-dist"),
        c("hidenchars", "Непечатаемые символы", "hidenchars"),
        c("paracolor", "Заливка", "paracolor"),
        c("borders", "Границы", "borders"),
        c("parastyle", "Стиль абзаца", "styles"),
        c("replace", "Заменить", "replace"),
        c("selectall", "Выделить всё", "select-all"),
    ]},
    Tab { name: "Вставить", cmds: &[
        c("blankpage", "Вставить пустую страницу", "blankpage"),
        c("pagebreak", "Вставить разрыв страницы или раздела", "pagebreak"),
        c("instable", "Вставить таблицу", "instable"),
        c("insimage", "Вставить изображение", "insertimage"),
        c("insshape", "Вставить фигуру", "insshape"),
        c("inssmartart", "Вставить SmartArt", "inssmartart"),
        c("inschart", "Вставить диаграмму", "inschart"),
        c("smartpicker", "Вставить диаграмму", "smartpicker"),
        c("instext", "Вставить надпись", "instext"),
        c("instextart", "Вставить объект Text Art", "instextart"),
        c("dropcap", "Вставить буквицу", "dropcap"),
        c("text-from-file", "Текст из файла", "text-from-file"),
        c("edit-header", "Изменить верхний колонтитул", "edit-header"),
        c("edit-footer", "Изменить нижний колонтитул", "edit-footer"),
        c("pagenum", "Нумерация страниц", "pagenum"),
        c("datetime", "Дата и время", "datetime"),
        c("numpages", "Количество страниц", "numpages"),
        c("insequation", "Вставить уравнение", "insequation"),
        c("inssymbol", "Вставить символ", "inssymbol"),
        c("controls", "Вставить элемент управления содержимым", "controls"),
    ]},
    Tab { name: "Рисование", cmds: &[
        c("pen", "Ручка", "pen"),
        c("highlighter", "Маркер", "highlighter"),
        c("eraser", "Ластик", "eraser"),
    ]},
    Tab { name: "Макет", cmds: &[
        c("pagemargins", "Поля", "pagemargins"),
        c("pageorient", "Ориентация страницы", "pageorient"),
        c("pagesize", "Размер страницы", "pagesize"),
        c("columns", "Вставить колонки", "columns"),
        c("line-numbers", "Показывать номера строк", "line-numbers"),
        c("hyphenation", "Изменить расстановку переносов", "hyphenation"),
        c("watermark", "Изменить подложку", "watermark"),
        c("pagecolor", "Изменить цвет страницы", "pagecolor"),
        c("colorschemas", "Изменение цветовой темы", "colorschemas"),
    ]},
    Tab { name: "Ссылки", cmds: &[
        c("toc", "Оглавление", "contents"),
        c("add-text", "Добавить текст", "add-text"),
        c("toc-update", "Обновить оглавление", "contents-update"),
        c("bookmarks", "Закладка", "bookmarks"),
        c("caption", "Название", "caption"),
        c("crossref", "Перекрестная ссылка", "crossref"),
        c("tof", "Список иллюстраций", "tof"),
        c("tof-update", "Обновить список иллюстраций", "tof-update"),
    ]},
    Tab { name: "Формы", cmds: &[
        c("form-text", "Текстовое поле", "form-text"),
        c("form-combo", "Поле со списком", "form-combo"),
        c("form-dropdown", "Выпадающий список", "form-dropdown"),
        c("form-checkbox", "Флажок", "form-checkbox"),
        c("form-radio", "Переключатель", "form-radio"),
        c("form-image", "Изображение", "form-image"),
        c("form-email", "Адрес email", "form-email"),
        c("form-phone", "Номер телефона", "form-phone"),
        c("form-complex", "Составное поле", "form-complex"),
        c("form-signature", "Подпись", "form-signature"),
        c("form-name", "Имя", "form-name"),
    ]},
    Tab { name: "Совместная работа", cmds: &[
        c("coauth-mode", "Режим совместной работы", "coauth-mode"),
        c("co-addcomment", "Добавить комментарий", "co-addcomment"),
        c("co-delcomment", "Удалить примечание", "co-delcomment"),
        c("co-showcomment", "Показать комментарии", "co-showcomment"),
        c("co-chat", "Чат", "co-chat"),
        c("track-changes", "Отслеживать изменения", "track-changes"),
        c("co-history", "Журнал версий", "co-history"),
    ]},
    Tab { name: "Защита", cmds: &[
        c("prot-encrypt", "Зашифровать", "prot-encrypt"),
        c("prot-sign", "Добавить цифровую подпись", "prot-sign"),
        c("prot-doc", "Защита", "prot-doc"),
    ]},
    Tab { name: "Показать", cmds: &[
        c("nav", "Навигация", "nav"),
        c("fit-page", "По размеру страницы", "fit-page"),
        c("fit-width", "По ширине", "fit-width"),
        c("zoom100", "Масштаб 100%", "zoom100"),
        c("zoom-in", "Увеличить", "zoom-in"),
        c("zoom-out", "Уменьшить", "zoom-out"),
        c("multipage", "Несколько страниц", "multipage"),
        c("darkmode", "Темный режим", "darkmode"),
        c("ruler", "Линейки", "ruler"),
        c("show-toolbar", "Всегда показывать панель инструментов", "show-toolbar"),
        c("show-statusbar", "Строка состояния", "show-statusbar"),
        c("show-left", "Левая панель", "show-left"),
        c("show-right", "Правая панель", "show-right"),
    ]},
    Tab { name: "Плагины", cmds: &[
        c("plug-macros", "Макросы", "plug-macros"),
        c("plug-manage", "Управление плагинами", "plug-manage"),
    ]},
    Tab { name: "ИИ", cmds: &[
        c("ai-where", "Адресат", "ai-where"),
        c("ai-summary", "Сводка", "ai-summary"),
        c("ai-rewrite", "Переписать", "ai-rewrite"),
        c("ai-polite", "Вежливее", "ai-polite"),
        c("ai-plain", "Проще", "ai-plain"),
        c("ai-translate", "Перевести", "ai-translate"),
        c("ai-furigana", "Фуригана", "ai-furigana"),
        c("ai-continue", "Продолжить", "ai-continue"),
        c("ai-table", "В таблицу", "ai-table"),
        c("ai-ask", "Попросить", "ai-ask"),
        c("ai-macro", "Написать макрос", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Файл", cmds: &[
        c("open", "Открыть", "open"),
        c("save", "Сохранить", "save"),
        c("pdf", "Печать", "print"),
    ]},
    Tab { name: "Главная", cmds: &[
        c("copy", "Копировать", "copy"),
        c("cut", "Вырезать", "cut"),
        c("paste", "Вставить", "paste"),
        c("copystyle", "Формат по образцу", "copystyle"),
        c("fontname", "Шрифт", "fontname"),
        c("fontsize", "Размер шрифта", "fontsize"),
        c("incfont", "Увеличить размер шрифта", "incfont"),
        c("decfont", "Уменьшить размер шрифта", "decfont"),
        c("changecase", "Изменить регистр", "changecase"),
        c("bold", "Полужирный", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Подчёркнутый", "underline"),
        c("strikeout", "Зачёркнутый", "strikeout"),
        c("subscript", "Подстрочные", "subscript"),
        c("fontcolor", "Цвет шрифта", "fontcolor"),
        c("fillparag", "Цвет заливки", "fillparag"),
        c("borders", "Границы", "borders"),
        c("top", "Выровнять по верхнему краю", "top"),
        c("middle", "По центру", "middle"),
        c("bottom", "Выровнять по нижнему краю", "bottom"),
        c("wrap", "Перенос текста", "wrap"),
        c("text-orient", "Ориентация страницы", "text-orient"),
        c("align-left", "Выровнять по левому краю", "align-left"),
        c("align-center", "По центру", "align-center"),
        c("align-right", "Выровнять по правому краю", "align-right"),
        c("align-just", "По ширине", "align-just"),
        c("merge", "Объединить и поместить в центре", "merge"),
        c("direction", "Направление текста (справа налево)", "direction"),
        c("insert-function", "Функции", "formula"),
        c("fill-num", "Заполнить", "fill-num"),
        c("defname", "Диспетчер имен", "named-range"),
        c("clear", "Очистить", "clear"),
        c("sort-desc", "Сортировка по убыванию", "sortdesc"),
        c("sort-asc", "Сортировка по возрастанию", "sortasc"),
        c("setfilter", "Фильтры", "setfilter"),
        c("clear-filter", "Снять фильтр", "clear-filter"),
        c("format", "Числовой формат", "format"),
        c("currency", "Денежный формат", "currency"),
        c("percents", "Процентный формат", "percents"),
        c("comma", "Формат с разделителями", "comma"),
        c("digit-dec", "Уменьшить разрядность", "digit-dec"),
        c("digit-inc", "Увеличить разрядность", "digit-inc"),
        c("cell-ins", "Вставить ячейки", "cell-ins"),
        c("cell-del", "Удалить ячейки", "cell-del"),
        c("cell-format", "Стиль ячейки", "cell-format"),
        c("condformat", "Условное форматирование", "condformat"),
        c("table-tpl", "Вставить таблицу", "table-tpl"),
        c("cell-styles", "Стиль ячейки", "styles"),
        c("replace", "Заменить", "replace"),
        c("selectall", "Выделить всё", "select-all"),
    ]},
    Tab { name: "Вставить", cmds: &[
        c("pivot-insert", "Вставить сводную таблицу", "add-pivot"),
        c("instable", "Вставить таблицу", "instable"),
        c("insimage", "Вставить изображение", "insimage-c"),
        c("insshape", "Вставить фигуру", "insshape"),
        c("inssmartart", "Вставить SmartArt", "inssmartart"),
        c("inscheckbox", "Флажок", "inscheckbox"),
        c("insrecommend", "Вставить рекомендованную диаграмму", "insrecommend"),
        c("inschart", "Вставить диаграмму", "inschart"),
        c("inssparkline", "Вставить спарклайн", "inssparkline"),
        c("addcomment", "Комментарии", "ins-comment"),
        c("insrecommend", "Вставить диаграмму", "smartpicker"),
        c("inshyperlink", "Добавить ссылку", "inshyperlink"),
        c("insslicer", "Вставить срез", "insslicer"),
        c("instext", "Вставить надпись", "instext"),
        c("instextart", "Вставить объект Text Art", "instextart"),
        c("editheader", "Колонтитулы", "editheader"),
        c("insequation", "Вставить уравнение", "insequation"),
        c("inssymbol", "Вставить символ", "inssymbol"),
    ]},
    Tab { name: "Рисование", cmds: &[
        c("draw-select", "Выделить", "select-tool"),
        c("pen", "Ручка", "pen"),
        c("highlighter", "Маркер", "highlighter"),
        c("eraser", "Ластик", "eraser"),
    ]},
    Tab { name: "Макет", cmds: &[
        c("pagemargins", "Поля", "pagemargins"),
        c("pageorient", "Ориентация страницы", "pageorient"),
        c("pagesize", "Размер страницы", "pagesize"),
        c("printarea", "Область печати", "printarea"),
        c("pagebreak", "Добавьте разрыв там, где должна начинаться следующая страница в печатной копии.", "pagebreak"),
        c("editheader", "Колонтитулы", "editheader"),
        c("scale", "Вписать", "scale"),
        c("fit-pages", "Вместить на страницы", "fit-pages"),
        c("printarea-add", "Добавить в область печати", "printarea-add"),
        c("show-breaks", "Разрывы страниц", "show-breaks"),
        c("printtitles", "Печатать заголовки", "printtitles"),
        c("rtl-sheet", "Переключить направление листа, чтобы первый столбец был справа", "rtl-sheet"),
        c("print-gridlines", "Печатать сетку", "print-gridlines"),
        c("print-headings", "Печатать заголовки", "print-headings"),
        x("Перенести вперед", "img-movefrwd"),
        x("Перенести назад", "img-movebkwd"),
        x("Выравнивание", "img-align"),
        x("Группировка", "img-group"),
        x("Объединить фигуры", "shapes-merge"),
        c("colorschemas", "Изменение цветовой темы", "colorschemas"),
    ]},
    Tab { name: "Формула", cmds: &[
        c("insert-function", "Вставка функции", "additional-formula"),
        c("sum", "Автосумма", "autosum"),
        c("fn-recent", "Недавно использованные", "recent"),
        c("fn-financial", "Финансовые", "financial"),
        c("fn-logical", "Логические", "logical"),
        c("fn-text", "Текстовые", "text"),
        c("fn-datetime", "Дата и время", "datetime"),
        c("fn-lookup", "Поиск и ссылки", "lookup"),
        c("fn-math", "Математические", "math"),
        c("fn-more", "Другие функции", "more"),
        c("defname", "Диспетчер имен", "named-range-huge"),
        c("paste-name", "Вставить имя", "paste-name"),
        c("trace-prec", "Влияющие ячейки", "trace-prec"),
        c("trace-dep", "Зависимые ячейки", "trace-dep"),
        c("remove-arrows", "Убрать стрелки", "remove-arrows"),
        c("show-formulas", "Показать формулы", "show-formulas"),
        c("watch", "Окно контрольного значения", "watch-window"),
        c("calc-mode", "Вычисления", "calculate"),
    ]},
    Tab { name: "Данные", cmds: &[
        c("data-from-text", "Данные из текста", "data-from-text"),
        c("data-external-links", "Внешние ссылки (импорт значениями)", "data-external-links"),
        c("setfilter", "Фильтры", "setfilter"),
        c("clear-filter", "Снять фильтр", "clear-filter"),
        c("sort-desc", "Сортировка по убыванию", "sortdesc"),
        c("sort-asc", "Сортировка по возрастанию", "sortasc"),
        c("custom-sort", "Сортировка", "custom-sort"),
        c("text-column", "Текст по столбцам", "text-column"),
        c("rem-duplicates", "Удалить дубликаты", "rem-duplicates"),
        c("data-validation", "Проверка данных", "data-validation"),
        c("goal-seek", "Подбор параметра", "goal-seek"),
        c("solver", "Поиск решения", "solver"),
        c("group", "Группировка", "group"),
        c("ungroup", "Разгруппировать", "ungroup"),
        c("show-details", "Показать детали", "show-details"),
        c("hide-details", "Скрыть детали", "hide-details"),
        c("subtotal", "Промежуточные итоги", "subtotal"),
        c("datatable", "Таблица данных", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Формат CSV", "csv-kind"),
    ]},
    Tab { name: "Сводная таблица", cmds: &[
        c("pivot-insert", "Вставить сводную таблицу", "pivot-insert"),
        c("pivot-fields", "Список полей", "pivot-fields"),
        c("pivot-refresh", "Обновить", "pivot-refresh"),
        c("pivot-refresh-all", "Обновить все", "pivot-refresh-all"),
        c("pivot-select", "Выбрать", "pivot-select"),
        c("pivot-totals", "Общий итог", "pivot-totals"),
        c("pivot-subtotals", "Промежуточные итоги", "pivot-subtotals"),
        c("pivot-blank", "Пустые строки", "pivot-blank"),
        c("pivot-showas", "Дополнительные вычисления", "pivot-showas"),
        c("pivot-layout", "Макет отчета", "pivot-layout"),
        c("pivot-style", "Стиль", "pivot-style"),
    ]},
    Tab { name: "Дизайн таблицы", cmds: &[
        c("td-header", "Строка заголовка", "td-header"),
        c("td-total", "Строка итогов", "td-total"),
        c("td-band-row", "Чередовать строки", "td-band-row"),
        c("td-first", "Первый столбец", "td-first"),
        c("td-last", "Последний столбец", "td-last"),
        c("td-band-col", "Чередующиеся столбцы", "td-band-col"),
        c("td-filter", "Кнопка фильтра", "td-filter"),
        c("rem-duplicates", "Удалить дубликаты", "td-remdup"),
        c("td-torange", "Преобразовать в диапазон", "td-torange"),
        c("td-resize", "Размер таблицы", "td-resize"),
    ]},
    Tab { name: "Совместная работа", cmds: &[
        c("coauth-mode", "Режим совместной работы", "coauth-mode"),
        c("addcomment", "Добавить комментарий", "co-addcomment"),
        c("co-delcomment", "Удалить примечание", "co-delcomment"),
        c("co-showcomment", "Показать комментарии", "co-showcomment"),
        c("co-chat", "Чат", "co-chat"),
        c("co-history", "Журнал версий", "co-history"),
    ]},
    Tab { name: "Защита", cmds: &[
        c("prot-encrypt", "Зашифровать", "prot-encrypt"),
        x("Защитить книгу", "protect-workbook"),
        c("prot-doc", "Защитить лист", "protect-sheet"),
        x("Защитить диапазон", "protect-range"),
        c("prot-sign", "Добавить цифровую подпись", "prot-sign"),
        c("cell-lock", "Блокировать ячейку", "cell-lock"),
        c("prot-allow", "Разрешённые действия", "prot-allow"),
        c("recover", "Восстановить", "recover"),
        c("recover-every", "Интервал копии", "recover-every"),
    ]},
    Tab { name: "Показать", cmds: &[
        c("sheet-view", "Представление листа", "sheet-view"),
        x("Обычные", "view-normal"),
        x("Страничный режим", "view-pagebreak"),
        c("zoom-in", "Увеличить", "zoom-in"),
        c("zoom-out", "Уменьшить", "zoom-out"),
        c("ui-bigger", "Крупнее текст интерфейса", "ui-bigger"),
        c("ui-smaller", "Мельче текст интерфейса", "ui-smaller"),
        c("theme", "Тема интерфейса", "theme"),
        c("freeze", "Закрепить области", "freeze"),
        c("formula-bar", "Строка формул", "formula-bar"),
        c("show-gridlines", "Линии сетки", "show-gridlines"),
        c("show-headings", "Заголовки", "show-headings"),
        c("show-zeros", "Показывать нули", "show-zeros"),
    ]},
    Tab { name: "Плагины", cmds: &[
        c("plug-macros", "Макросы", "plug-macros"),
        c("plug-manage", "Управление плагинами", "plug-manage"),
    ]},
    Tab { name: "ИИ", cmds: &[
        c("ai-where", "Адресат", "ai-where"),
        c("ai-summary", "Сводка", "ai-summary"),
        c("ai-rewrite", "Переписать", "ai-rewrite"),
        c("ai-polite", "Вежливее", "ai-polite"),
        c("ai-plain", "Проще", "ai-plain"),
        c("ai-translate", "Перевести", "ai-translate"),
        c("ai-furigana", "Фуригана", "ai-furigana"),
        c("ai-continue", "Продолжить", "ai-continue"),
        c("ai-table", "В таблицу", "ai-table"),
        c("ai-ask", "Попросить", "ai-ask"),
    ]},
];

