//! リボンの id 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py id > ui/src/ribbon_id.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Buka", "open"),
        c("save", "Simpan", "save"),
        c("pdf", "Cetak", "print"),
    ]},
    Tab { name: "Halaman Depan", cmds: &[
        c("copy", "Salin", "copy"),
        c("cut", "Potong", "cut"),
        c("paste", "Tempel", "paste"),
        c("fontname", "Huruf", "fontname"),
        c("fontsize", "Ukuran Huruf", "fontsize"),
        c("incfont", "Perbesar Ukuran Huruf", "incfont"),
        c("decfont", "Perkecil Ukuran Huruf", "decfont"),
        c("changecase", "Ubah case", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("bold", "Tebal", "bold"),
        c("italic", "Miring", "italic"),
        c("underline", "Garis bawah", "underline"),
        c("strikeout", "Coret ganda", "strikeout"),
        c("superscript", "Superskrip", "superscript"),
        c("subscript", "Subskrip", "subscript"),
        c("highlight", "Warna Sorot", "highlight"),
        c("fontcolor", "Warna Huruf", "fontcolor"),
        c("clearstyle", "Hapus Model", "clearstyle"),
        c("markers", "Butir", "markers"),
        c("numbering", "Penomoran", "numbering"),
        c("multilevels", "Ikhtisar", "multilevels"),
        c("decoffset", "Kurangi Indentasi", "decoffset"),
        c("incoffset", "Tambahkan Indentasi", "incoffset"),
        c("linespace", "Spasi Antar Baris Paragraf", "linespace"),
        c("direction", "Arah teks", "direction"),
        c("align-left", "Rata kiri", "align-left"),
        c("align-center", "Tengah", "align-center"),
        c("align-right", "Rata kanan", "align-right"),
        c("align-just", "Rata Kiri-Kanan", "align-just"),
        c("align-dist", "Terdistribusi", "align-dist"),
        c("hidenchars", "Karakter Tidak Dicetak", "hidenchars"),
        c("paracolor", "Bayangan", "paracolor"),
        c("borders", "Batas", "borders"),
        c("parastyle", "Gaya paragraf", "styles"),
        c("replace", "Ganti", "replace"),
        c("selectall", "Pilih semua", "select-all"),
    ]},
    Tab { name: "Sisipkan", cmds: &[
        c("blankpage", "Sisipkan halaman kosong", "blankpage"),
        c("pagebreak", "Sisipkan Halaman atau jeda Bagian", "pagebreak"),
        c("instable", "Sisipkan Tabel", "instable"),
        c("insimage", "Sisipkan Gambar", "insertimage"),
        c("insshape", "Sisipkan Bentuk", "insshape"),
        c("inssmartart", "Sisipkan SmartArt", "inssmartart"),
        c("inschart", "Sisipkan Bagan", "inschart"),
        c("smartpicker", "Sisipkan Bagan", "smartpicker"),
        c("instext", "Sisipkan kotak teks", "instext"),
        c("instextart", "Sisipkan Text Art", "instextart"),
        c("dropcap", "Sisipkan Drop Cap", "dropcap"),
        c("text-from-file", "Teks dari Berkas", "text-from-file"),
        c("edit-header", "Sunting kepala", "edit-header"),
        c("edit-footer", "Sunting kaki", "edit-footer"),
        c("pagenum", "Nomor halaman", "pagenum"),
        c("datetime", "Tanggal & Waktu", "datetime"),
        c("numpages", "Jumlah halaman", "numpages"),
        c("insequation", "Masukkan Persamaan", "insequation"),
        c("inssymbol", "Sisipkan simbol", "inssymbol"),
        c("controls", "Sisipkan kontrol konten", "controls"),
    ]},
    Tab { name: "Gambar", cmds: &[
        c("pen", "Pena", "pen"),
        c("highlighter", "Penyorot", "highlighter"),
        c("eraser", "Penghapus", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margin", "pagemargins"),
        c("pageorient", "Orientasi", "pageorient"),
        c("pagesize", "Ukuran Halaman", "pagesize"),
        c("columns", "Sisipkan kolom", "columns"),
        c("line-numbers", "Tampilkan nomor garis", "line-numbers"),
        c("hyphenation", "Ubah tanda hubung", "hyphenation"),
        c("watermark", "Edit watermark", "watermark"),
        c("pagecolor", "Ubah warna halaman", "pagecolor"),
        c("colorschemas", "Ubah Skema Warna", "colorschemas"),
    ]},
    Tab { name: "Referensi", cmds: &[
        c("toc", "Daftar Isi", "contents"),
        c("add-text", "Tambah Teks", "add-text"),
        c("toc-update", "Perbarui daftar isi", "contents-update"),
        c("bookmarks", "Bookmark", "bookmarks"),
        c("caption", "Keterangan", "caption"),
        c("crossref", "Cross-reference", "crossref"),
        c("tof", "Daftar gambar", "tof"),
        c("tof-update", "Perbarui daftar gambar", "tof-update"),
    ]},
    Tab { name: "Fomulir", cmds: &[
        c("form-text", "Ruas Teks", "form-text"),
        c("form-combo", "Kotak combo", "form-combo"),
        c("form-dropdown", "Dropdown", "form-dropdown"),
        c("form-checkbox", "Kotak centang", "form-checkbox"),
        c("form-radio", "Tombol Radio", "form-radio"),
        c("form-image", "Gambar", "form-image"),
        c("form-email", "Alamat Email", "form-email"),
        c("form-phone", "Nomor Telepon", "form-phone"),
        c("form-complex", "Bidang Kompleks", "form-complex"),
        c("form-signature", "Tanda Tangan", "form-signature"),
        c("form-name", "Nama", "form-name"),
    ]},
    Tab { name: "Kolaborasi", cmds: &[
        c("coauth-mode", "Mode pengeditan bersama", "coauth-mode"),
        c("co-addcomment", "Tambahkan komentar", "co-addcomment"),
        c("co-delcomment", "Hapus komentar", "co-delcomment"),
        c("co-showcomment", "Tampilkan komentar", "co-showcomment"),
        c("co-chat", "Obrolan", "co-chat"),
        c("track-changes", "Lacak perubahan", "track-changes"),
        c("co-history", "Riwayat versi", "co-history"),
    ]},
    Tab { name: "Proteksi", cmds: &[
        c("prot-encrypt", "Enkripsi", "prot-encrypt"),
        c("prot-sign", "Tambahkan tanda tangan digital", "prot-sign"),
        c("prot-doc", "Proteksi", "prot-doc"),
    ]},
    Tab { name: "Lihat", cmds: &[
        c("nav", "Navigasi", "nav"),
        c("fit-page", "Sesuaikan Halaman", "fit-page"),
        c("fit-width", "Sesuaikan Lebar", "fit-width"),
        c("zoom100", "Zoom ke 100%", "zoom100"),
        c("zoom-in", "Perbesar", "zoom-in"),
        c("zoom-out", "Perkecil", "zoom-out"),
        c("multipage", "Gandakan halaman", "multipage"),
        c("darkmode", "Mode gelap", "darkmode"),
        c("ruler", "Penggaris", "ruler"),
        c("show-toolbar", "Selalu Tampilkan Bilah Alat", "show-toolbar"),
        c("show-statusbar", "Bar Status", "show-statusbar"),
        c("show-left", "Panel Kiri", "show-left"),
        c("show-right", "Panel Kanan", "show-right"),
    ]},
    Tab { name: "Plugins", cmds: &[
        c("plug-macros", "Makro", "plug-macros"),
        c("plug-manage", "Kelola plugin", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Tujuan", "ai-where"),
        c("ai-summary", "Ringkas", "ai-summary"),
        c("ai-rewrite", "Tulis ulang", "ai-rewrite"),
        c("ai-polite", "Lebih sopan", "ai-polite"),
        c("ai-plain", "Lebih sederhana", "ai-plain"),
        c("ai-translate", "Terjemahkan", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Lanjutkan", "ai-continue"),
        c("ai-table", "Jadi tabel", "ai-table"),
        c("ai-ask", "Minta", "ai-ask"),
        c("ai-macro", "Tulis makro", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Buka", "open"),
        c("save", "Simpan", "save"),
        c("pdf", "Cetak", "print"),
    ]},
    Tab { name: "Halaman Depan", cmds: &[
        c("copy", "Salin", "copy"),
        c("cut", "Potong", "cut"),
        c("paste", "Tempel", "paste"),
        c("copystyle", "Salin format", "copystyle"),
        c("fontname", "Huruf", "fontname"),
        c("fontsize", "Ukuran Huruf", "fontsize"),
        c("incfont", "Perbesar Ukuran Huruf", "incfont"),
        c("decfont", "Perkecil Ukuran Huruf", "decfont"),
        c("changecase", "Ubah case", "changecase"),
        c("bold", "Tebal", "bold"),
        c("italic", "Miring", "italic"),
        c("underline", "Garis bawah", "underline"),
        c("strikeout", "Coret ganda", "strikeout"),
        c("subscript", "Subskrip", "subscript"),
        c("fontcolor", "Warna Huruf", "fontcolor"),
        c("fillparag", "Isi warna", "fillparag"),
        c("borders", "Pembatas", "borders"),
        c("top", "Rata atas", "top"),
        c("middle", "Tengah", "middle"),
        c("bottom", "Rata bawah", "bottom"),
        c("wrap", "Lipat teks", "wrap"),
        c("text-orient", "Orientasi", "text-orient"),
        c("align-left", "Rata kiri", "align-left"),
        c("align-center", "Tengah", "align-center"),
        c("align-right", "Rata kanan", "align-right"),
        c("align-just", "Rata Kiri-Kanan", "align-just"),
        c("merge", "Merge dan center", "merge"),
        c("direction", "Arah teks (kanan-ke-kiri)", "direction"),
        c("insert-function", "Fungsi", "formula"),
        c("fill-num", "Isi", "fill-num"),
        c("defname", "Pengaturan Nama", "named-range"),
        c("clear", "Hapus", "clear"),
        c("sort-desc", "Sortasi turun", "sortdesc"),
        c("sort-asc", "Sortasi naik", "sortasc"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Bersihkan filter", "clear-filter"),
        c("format", "Format nomor", "format"),
        c("currency", "Gaya mata uang", "currency"),
        c("percents", "Gaya persen", "percents"),
        c("comma", "Gaya koma", "comma"),
        c("digit-dec", "Kurangi desimal", "digit-dec"),
        c("digit-inc", "Tambah desimal", "digit-inc"),
        c("cell-ins", "Sisipkan sel", "cell-ins"),
        c("cell-del", "Hapus Sel", "cell-del"),
        c("cell-format", "Gaya Sel", "cell-format"),
        c("condformat", "Format bersyarat", "condformat"),
        c("table-tpl", "Sisipkan Tabel", "table-tpl"),
        c("cell-styles", "Gaya Sel", "styles"),
        c("replace", "Ganti", "replace"),
        c("selectall", "Pilih semua", "select-all"),
    ]},
    Tab { name: "Sisipkan", cmds: &[
        c("pivot-insert", "Sisipkan Tabel Pivot", "add-pivot"),
        c("instable", "Sisipkan Tabel", "instable"),
        c("insimage", "Sisipkan Gambar", "insimage-c"),
        c("insshape", "Sisipkan Bentuk", "insshape"),
        c("inssmartart", "Sisipkan SmartArt", "inssmartart"),
        c("inscheckbox", "Kotak centang", "inscheckbox"),
        c("insrecommend", "Sisipkan bagan yang disarankan", "insrecommend"),
        c("inschart", "Sisipkan Bagan", "inschart"),
        c("inssparkline", "Sisipkan sparkline", "inssparkline"),
        c("addcomment", "Komentar", "ins-comment"),
        c("insrecommend", "Sisipkan Bagan", "smartpicker"),
        c("inshyperlink", "Tambahkan hyperlink", "inshyperlink"),
        c("insslicer", "Sisipkan Slicer", "insslicer"),
        c("instext", "Sisipkan Teks", "instext"),
        c("instextart", "Sisipkan Text Art", "instextart"),
        c("editheader", "Header & Footer", "editheader"),
        c("insequation", "Masukkan Persamaan", "insequation"),
        c("inssymbol", "Sisipkan simbol", "inssymbol"),
    ]},
    Tab { name: "Gambar", cmds: &[
        c("draw-select", "Pilih", "select-tool"),
        c("pen", "Pena", "pen"),
        c("highlighter", "Penyorot", "highlighter"),
        c("eraser", "Penghapus", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margin", "pagemargins"),
        c("pageorient", "Orientasi", "pageorient"),
        c("pagesize", "Ukuran Halaman", "pagesize"),
        c("printarea", "Print Area", "printarea"),
        c("pagebreak", "Tambahkan jeda pada tempat yang ingin dijadikan awal halaman selanjutnya pada cetakan", "pagebreak"),
        c("editheader", "Header & Footer", "editheader"),
        c("scale", "Skala ke Fit", "scale"),
        c("fit-pages", "Paskan ke halaman", "fit-pages"),
        c("printarea-add", "Tambahkan ke area cetak", "printarea-add"),
        c("show-breaks", "Pemisah halaman", "show-breaks"),
        c("printtitles", "Print judul", "printtitles"),
        c("rtl-sheet", "Ubah arah lembar agar kolom pertama di kanan", "rtl-sheet"),
        c("print-gridlines", "Cetak garis kisi", "print-gridlines"),
        c("print-headings", "Cetak judul", "print-headings"),
        x("Majukan", "img-movefrwd"),
        x("Mundurkan", "img-movebkwd"),
        x("Perataan", "img-align"),
        x("Grup", "img-group"),
        x("Gabungkan bentuk", "shapes-merge"),
        c("colorschemas", "Ubah Skema Warna", "colorschemas"),
    ]},
    Tab { name: "Formula", cmds: &[
        c("insert-function", "Sisipkan fungsi", "additional-formula"),
        c("sum", "JumlahOtomatis", "autosum"),
        c("fn-recent", "Baru digunakan", "recent"),
        c("fn-financial", "Finansial", "financial"),
        c("fn-logical", "Logikal", "logical"),
        c("fn-text", "Teks", "text"),
        c("fn-datetime", "Tanggal & Waktu", "datetime"),
        c("fn-lookup", "Lookup dan referensi", "lookup"),
        c("fn-math", "Matematika & Trigonometri", "math"),
        c("fn-more", "Lebih banyak fungsi", "more"),
        c("defname", "Pengaturan Nama", "named-range-huge"),
        c("paste-name", "Tempel nama", "paste-name"),
        c("trace-prec", "Preseden Jejak", "trace-prec"),
        c("trace-dep", "Dependen Jejak", "trace-dep"),
        c("remove-arrows", "Hapus panah", "remove-arrows"),
        c("show-formulas", "Tampilkan rumus", "show-formulas"),
        c("watch", "Jendela pantauan", "watch-window"),
        c("calc-mode", "Kalkulasi", "calculate"),
    ]},
    Tab { name: "Data", cmds: &[
        c("data-from-text", "Teks ke data", "data-from-text"),
        c("data-external-links", "Tautan eksternal (impor sebagai nilai)", "data-external-links"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Bersihkan filter", "clear-filter"),
        c("sort-desc", "Sortasi turun", "sortdesc"),
        c("sort-asc", "Sortasi naik", "sortasc"),
        c("custom-sort", "Sortasi", "custom-sort"),
        c("text-column", "Teks ke kolom", "text-column"),
        c("rem-duplicates", "Hapus duplikat", "rem-duplicates"),
        c("data-validation", "Validasi data", "data-validation"),
        c("goal-seek", "Pencarian Tujuan", "goal-seek"),
        c("solver", "Solver", "solver"),
        c("group", "Grup", "group"),
        c("ungroup", "Pisahkan dari grup", "ungroup"),
        c("show-details", "Tampilkan Detail", "show-details"),
        c("hide-details", "Sembunyikan rincian", "hide-details"),
        c("subtotal", "Subtotal", "subtotal"),
        c("datatable", "Tabel Data", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Format CSV", "csv-kind"),
        c("flash-fill", "Isi Cepat", "flash-fill"),
    ]},
    // Python タブ(2026-08-09)。**語だけが違う** — id と並びは ja と同じ
    Tab { name: "Python", cmds: &[
        c("py-edit", "Edit fungsi", "py-edit"),
        c("py-new", "Berkas .py baru", "py-new"),
        c("py-run", "Jalankan prosedur", "py-run"),
        c("py-list", "Daftar", "py-list"),
        c("py-line", "Kode satu baris", "py-line"),
        c("py-calc", "Hitung ulang", "py-calc"),
        c("py-folder", "Buka folder", "py-folder"),
    ]},
    Tab { name: "Tabel Pivot", cmds: &[
        c("pivot-insert", "Sisipkan Tabel Pivot", "pivot-insert"),
        c("pivot-fields", "Daftar bidang", "pivot-fields"),
        c("pivot-refresh", "Refresh", "pivot-refresh"),
        c("pivot-refresh-all", "Segarkan Semuanya", "pivot-refresh-all"),
        c("pivot-select", "Pilih", "pivot-select"),
        c("pivot-totals", "Grand Total", "pivot-totals"),
        c("pivot-subtotals", "Subtotal", "pivot-subtotals"),
        c("pivot-blank", "Baris Kosong", "pivot-blank"),
        c("pivot-showas", "Tampilkan Nilai Sebagai", "pivot-showas"),
        c("pivot-layout", "Layout Laporan", "pivot-layout"),
        c("pivot-style", "Gaya", "pivot-style"),
    ]},
    Tab { name: "Desain tabel", cmds: &[
        c("td-header", "Baris header", "td-header"),
        c("td-total", "Baris total", "td-total"),
        c("td-band-row", "Baris Berpita", "td-band-row"),
        c("td-first", "Kolom pertama", "td-first"),
        c("td-last", "Kolom terakhir", "td-last"),
        c("td-band-col", "Kolom berpita", "td-band-col"),
        c("td-filter", "Tombol filter", "td-filter"),
        c("rem-duplicates", "Hapus duplikat", "td-remdup"),
        c("td-torange", "Konversi ke rentang", "td-torange"),
        c("td-resize", "Ubah ukuran tabel", "td-resize"),
    ]},
    Tab { name: "Kolaborasi", cmds: &[
        c("coauth-mode", "Mode pengeditan bersama", "coauth-mode"),
        c("addcomment", "Tambahkan komentar", "co-addcomment"),
        c("co-delcomment", "Hapus komentar", "co-delcomment"),
        c("co-showcomment", "Tampilkan komentar", "co-showcomment"),
        c("co-chat", "Obrolan", "co-chat"),
        c("co-history", "Riwayat versi", "co-history"),
    ]},
    Tab { name: "Proteksi", cmds: &[
        c("prot-encrypt", "Enkripsi", "prot-encrypt"),
        x("Proteksi workbook", "protect-workbook"),
        c("prot-doc", "Proteksi Sheet", "protect-sheet"),
        x("Proteksi Rentang", "protect-range"),
        c("prot-sign", "Tambahkan tanda tangan digital", "prot-sign"),
        c("cell-lock", "Kunci sel", "cell-lock"),
        c("prot-allow", "Tindakan yang diizinkan", "prot-allow"),
        c("recover", "Pulihkan", "recover"),
        c("recover-every", "Interval cadangan", "recover-every"),
        c("read-only-rec", "Sarankan baca-saja", "read-only-rec"),
    ]},
    Tab { name: "Lihat", cmds: &[
        c("sheet-view", "Tampilan sheet", "sheet-view"),
        x("Normal", "view-normal"),
        x("Pratinjau Jeda Halaman", "view-pagebreak"),
        c("zoom-in", "Perbesar", "zoom-in"),
        c("zoom-out", "Perkecil", "zoom-out"),
        c("ui-bigger", "Perbesar teks layar", "ui-bigger"),
        c("ui-smaller", "Perkecil teks layar", "ui-smaller"),
        c("theme", "Tema antarmuka", "theme"),
        c("freeze", "Freeze Panes", "freeze"),
        c("formula-bar", "Bar formula", "formula-bar"),
        c("show-gridlines", "Garis Grid", "show-gridlines"),
        c("show-headings", "Tajuk", "show-headings"),
        c("show-zeros", "Tampilkan nol", "show-zeros"),
    ]},
    Tab { name: "Plugins", cmds: &[
        c("plug-macros", "Makro", "plug-macros"),
        c("plug-manage", "Kelola plugin", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Tujuan", "ai-where"),
        c("ai-summary", "Ringkas", "ai-summary"),
        c("ai-rewrite", "Tulis ulang", "ai-rewrite"),
        c("ai-polite", "Lebih sopan", "ai-polite"),
        c("ai-plain", "Lebih sederhana", "ai-plain"),
        c("ai-translate", "Terjemahkan", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Lanjutkan", "ai-continue"),
        c("ai-table", "Jadi tabel", "ai-table"),
        c("ai-ask", "Minta", "ai-ask"),
    ]},
];

