//! リボンの de 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py de > ui/src/ribbon_de.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Datei", cmds: &[
        c("open", "Offen", "open"),
        c("save", "Speichern", "save"),
        c("pdf", "Drucken", "print"),
    ]},
    Tab { name: "Startseite", cmds: &[
        c("copy", "Kopieren", "copy"),
        c("cut", "Ausschneiden", "cut"),
        c("paste", "Einfügen", "paste"),
        c("fontname", "Schriftart", "fontname"),
        c("fontsize", "Schriftgrad", "fontsize"),
        c("incfont", "Schriftart vergrößern", "incfont"),
        c("decfont", "Schriftart verkleinern", "decfont"),
        c("changecase", "Groß-/Kleinschreibung ändern", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("bold", "Fett", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Unterstrichen", "underline"),
        c("strikeout", "Durchgestrichen", "strikeout"),
        c("superscript", "Hochgestellt", "superscript"),
        c("subscript", "Tiefgestellt", "subscript"),
        c("highlight", "Texthervorhebungsfarbe", "highlight"),
        c("fontcolor", "Schriftfarbe", "fontcolor"),
        c("clearstyle", "Formatierung löschen", "clearstyle"),
        c("markers", "Aufzählungszeichen", "markers"),
        c("numbering", "Nummerierung", "numbering"),
        c("multilevels", "Liste mit mehreren Ebenen", "multilevels"),
        c("decoffset", "Einzug verkleinern", "decoffset"),
        c("incoffset", "Einzug vergrößern", "incoffset"),
        c("linespace", "Zeilenabstand", "linespace"),
        c("direction", "Textrichtung", "direction"),
        c("align-left", "Links ausrichten", "align-left"),
        c("align-center", "Zentriert", "align-center"),
        c("align-right", "Rechts ausrichten", "align-right"),
        c("align-just", "Blocksatz", "align-just"),
        c("align-dist", "Verteilt", "align-dist"),
        c("hidenchars", "Formatierungszeichen", "hidenchars"),
        c("paracolor", "Absatzhintergrundfarbe", "paracolor"),
        c("borders", "Rahmen", "borders"),
        c("parastyle", "Absatzformat", "styles"),
        c("replace", "Ersetzen", "replace"),
        c("selectall", "Alles auswählen", "select-all"),
    ]},
    Tab { name: "Einfügen", cmds: &[
        c("blankpage", "Leere Seite einlegen", "blankpage"),
        c("pagebreak", "Seiten- oder Abschnittsumbruch einfügen", "pagebreak"),
        c("instable", "Tabelle einfügen", "instable"),
        c("insimage", "Bild einfügen", "insertimage"),
        c("insshape", "Form einfügen", "insshape"),
        c("inssmartart", "SmartArt einfügen", "inssmartart"),
        c("inschart", "Diagramm einfügen", "inschart"),
        c("smartpicker", "Diagramm einfügen", "smartpicker"),
        c("instext", "Textfeld einfügen", "instext"),
        c("instextart", "TextArt einfügen", "instextart"),
        c("dropcap", "Initiale einfügen", "dropcap"),
        c("text-from-file", "Text aus Datei", "text-from-file"),
        c("edit-header", "Kopfzeile bearbeiten", "edit-header"),
        c("edit-footer", "Fußzeile bearbeiten", "edit-footer"),
        c("pagenum", "Seitennummerierung", "pagenum"),
        c("datetime", "Datum u. Uhrzeit", "datetime"),
        c("numpages", "Seitenzahl", "numpages"),
        c("insequation", "Formel einfügen", "insequation"),
        c("inssymbol", "Symbol einfügen", "inssymbol"),
        c("controls", "Inhaltssteuerelemente einfügen", "controls"),
    ]},
    Tab { name: "Zeichnen", cmds: &[
        c("pen", "Stift", "pen"),
        c("highlighter", "Textmarker", "highlighter"),
        c("eraser", "Radierer", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Ränder", "pagemargins"),
        c("pageorient", "Orientierung", "pageorient"),
        c("pagesize", "Seitenformat", "pagesize"),
        c("columns", "Spalte einfügen", "columns"),
        c("line-numbers", "Zeilennummern anzeigen", "line-numbers"),
        c("hyphenation", "Trennen ändern", "hyphenation"),
        c("watermark", "Wasserzeichen bearbeiten", "watermark"),
        c("pagecolor", "Seitenfarbe ändern", "pagecolor"),
        c("colorschemas", "Farbschema ändern", "colorschemas"),
    ]},
    Tab { name: "Verweise", cmds: &[
        c("toc", "Inhaltsverzeichnis", "contents"),
        c("add-text", "Text Hinzufügen", "add-text"),
        c("toc-update", "Inhaltsverzeichnis aktualisieren", "contents-update"),
        c("bookmarks", "Lesezeichen", "bookmarks"),
        c("caption", "Beschriftung", "caption"),
        c("crossref", "Querverweis", "crossref"),
        c("footnote", "Fußnote", "footnote"),
        c("tof", "Abbildungsverzeichnis", "tof"),
        c("tof-update", "Abbildungsverzeichnis aktualisieren", "tof-update"),
    ]},
    Tab { name: "Formulare", cmds: &[
        c("form-text", "Textfeld", "form-text"),
        c("form-combo", "Combobox", "form-combo"),
        c("form-dropdown", "Dropdown", "form-dropdown"),
        c("form-checkbox", "Kontrollkästchen", "form-checkbox"),
        c("form-radio", "Radiobutton", "form-radio"),
        c("form-image", "Bild", "form-image"),
        c("form-email", "E-Mail-Adresse", "form-email"),
        c("form-phone", "Telefonnummer", "form-phone"),
        c("form-complex", "Komplexes Feld", "form-complex"),
        c("form-signature", "Signatur", "form-signature"),
        c("form-name", "Name", "form-name"),
    ]},
    Tab { name: "Zusammenarbeit", cmds: &[
        c("coauth-mode", "Co-Bearbeitung", "coauth-mode"),
        c("co-addcomment", "Kommentar hinzufügen", "co-addcomment"),
        c("co-delcomment", "Kommentar löschen", "co-delcomment"),
        c("co-showcomment", "Kommentare anzeigen", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("track-changes", "Nachverfolgen von Änderungen", "track-changes"),
        c("co-history", "Versionsverlauf", "co-history"),
    ]},
    Tab { name: "Schutz", cmds: &[
        c("prot-encrypt", "Verschlüsseln", "prot-encrypt"),
        c("prot-sign", "Digitale Signatur hinzufügen", "prot-sign"),
        c("prot-doc", "Schutz", "prot-doc"),
    ]},
    Tab { name: "Anzeigen", cmds: &[
        c("nav", "Navigation", "nav"),
        c("fit-page", "Seite anpassen", "fit-page"),
        c("fit-width", "Breite anpassen", "fit-width"),
        c("zoom100", "Auf 100 % zoomen", "zoom100"),
        c("zoom-in", "Vergrößern", "zoom-in"),
        c("zoom-out", "Verkleinern", "zoom-out"),
        c("multipage", "Mehrere Seiten", "multipage"),
        c("darkmode", "Dunkelmodus", "darkmode"),
        c("ruler", "Lineale", "ruler"),
        c("show-toolbar", "Symbolleiste immer anzeigen", "show-toolbar"),
        c("show-statusbar", "Statusleiste", "show-statusbar"),
        c("show-left", "Linkes Bedienfeld", "show-left"),
        c("show-right", "Rechtes Bedienungsfeld ", "show-right"),
    ]},
    Tab { name: "Plugins", cmds: &[
        c("plug-macros", "Makros", "plug-macros"),
        c("plug-manage", "Plugins verwalten", "plug-manage"),
    ]},
    Tab { name: "KI", cmds: &[
        c("ai-where", "Ziel", "ai-where"),
        c("ai-summary", "Zusammenfassung", "ai-summary"),
        c("ai-rewrite", "Umschreiben", "ai-rewrite"),
        c("ai-polite", "Höflicher", "ai-polite"),
        c("ai-plain", "Einfacher", "ai-plain"),
        c("ai-translate", "Übersetzung", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Fortsetzen", "ai-continue"),
        c("ai-table", "In Tabelle", "ai-table"),
        c("ai-ask", "Anfragen", "ai-ask"),
        c("ai-macro", "Makro schreiben", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Datei", cmds: &[
        c("open", "Offen", "open"),
        c("save", "Speichern", "save"),
        c("pdf", "Drucken", "print"),
    ]},
    Tab { name: "Startseite", cmds: &[
        c("copy", "Kopieren", "copy"),
        c("cut", "Ausschneiden", "cut"),
        c("paste", "Einfügen", "paste"),
        c("copystyle", "Format übertragen", "copystyle"),
        c("fontname", "Schriftart", "fontname"),
        c("fontsize", "Schriftgrad", "fontsize"),
        c("incfont", "Schriftart vergrößern", "incfont"),
        c("decfont", "Schriftart verkleinern", "decfont"),
        c("changecase", "Groß-/Kleinschreibung ändern", "changecase"),
        c("bold", "Fett", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Unterstrichen", "underline"),
        c("strikeout", "Durchgestrichen", "strikeout"),
        c("subscript", "Tiefgestellt", "subscript"),
        c("fontcolor", "Schriftfarbe", "fontcolor"),
        c("fillparag", "Füllfarbe", "fillparag"),
        c("borders", "Rahmen", "borders"),
        c("top", "Oben ausrichten", "top"),
        c("middle", "Zentriert", "middle"),
        c("bottom", "Unten ausrichten", "bottom"),
        c("wrap", "Text umbrechen", "wrap"),
        c("text-orient", "Orientierung", "text-orient"),
        c("align-left", "Links ausrichten", "align-left"),
        c("align-center", "Zentriert", "align-center"),
        c("align-right", "Rechts ausrichten", "align-right"),
        c("align-just", "Blocksatz", "align-just"),
        c("align-dist", "Verteilt", "align-dist"),
        c("merge", "Verbinden und zentrieren", "merge"),
        c("direction", "Textrichtung (rechts nach links)", "direction"),
        c("insert-function", "Funktion", "formula"),
        c("fill-num", "Ausfüllen", "fill-num"),
        c("defname", "Name-Manager", "named-range"),
        c("clear", "Leeren", "clear"),
        c("sort-desc", "Absteigend sortieren", "sortdesc"),
        c("sort-asc", "Aufsteigend sortieren", "sortasc"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Filter löschen", "clear-filter"),
        c("format", "Zahlenformat", "format"),
        c("currency", "Währungsformat", "currency"),
        c("percents", "Prozentformat", "percents"),
        c("comma", "Komma-Format", "comma"),
        c("digit-dec", "Dezimalstelle löschen", "digit-dec"),
        c("digit-inc", "Dezimalstelle erhöhen", "digit-inc"),
        c("cell-ins", "Zellen einfügen", "cell-ins"),
        c("cell-del", "Zellen löschen", "cell-del"),
        c("cell-format", "Zellenformatvorlage", "cell-format"),
        c("condformat", "Bedingte Formatierung", "condformat"),
        c("table-tpl", "Tabelle einfügen", "table-tpl"),
        c("cell-styles", "Zellenformatvorlage", "styles"),
        c("replace", "Ersetzen", "replace"),
        c("selectall", "Alles auswählen", "select-all"),
    ]},
    Tab { name: "Einfügen", cmds: &[
        c("pivot-insert", "Pivot-Tabelle einfügen", "add-pivot"),
        c("instable", "Tabelle einfügen", "instable"),
        c("insimage", "Bild einfügen", "insimage-c"),
        c("insshape", "Form einfügen", "insshape"),
        c("inssmartart", "SmartArt einfügen", "inssmartart"),
        c("inscheckbox", "Kontrollkästchen", "inscheckbox"),
        c("insrecommend", "Empfohlenes Diagramm einfügen", "insrecommend"),
        c("inschart", "Diagramm einfügen", "inschart"),
        c("inssparkline", "Sparkline einfügen", "inssparkline"),
        c("addcomment", "Kommentar", "ins-comment"),
        c("insrecommend", "Diagramm einfügen", "smartpicker"),
        c("inshyperlink", "Link hinzufügen", "inshyperlink"),
        c("insslicer", "Datenschnitt einfügen", "insslicer"),
        c("instext", "Textfeld einfügen", "instext"),
        c("instextart", "TextArt einfügen", "instextart"),
        c("editheader", "Kopf- und Fußzeile", "editheader"),
        c("insequation", "Formel einfügen", "insequation"),
        c("inssymbol", "Symbol einfügen", "inssymbol"),
    ]},
    Tab { name: "Zeichnen", cmds: &[
        c("draw-select", "Auswahl", "select-tool"),
        c("pen", "Stift", "pen"),
        c("highlighter", "Textmarker", "highlighter"),
        c("eraser", "Radierer", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Ränder", "pagemargins"),
        c("pageorient", "Orientierung", "pageorient"),
        c("pagesize", "Seitenformat", "pagesize"),
        c("printarea", "Druckauswahl", "printarea"),
        c("pagebreak", "Fügen Sie einen Umbruch an der Stelle ein, an der im gedruckten Exemplar die nächste Seite beginnen soll.", "pagebreak"),
        c("editheader", "Kopf- und Fußzeile", "editheader"),
        c("scale", "An Format anpassen", "scale"),
        c("fit-pages", "Aufs Blatt einpassen", "fit-pages"),
        c("printarea-add", "Bereich hinzufügen", "printarea-add"),
        c("show-breaks", "Blattgrenzen", "show-breaks"),
        c("printtitles", "Drucke Titel", "printtitles"),
        c("rtl-sheet", "Ändern Sie die Blattausrichtung, sodass die erste Spalte auf der rechten Seite liegt", "rtl-sheet"),
        c("print-gridlines", "Gitternetzlinien drucken", "print-gridlines"),
        c("print-headings", "Überschriften drucken", "print-headings"),
        x("Eine Ebene nach vorne", "img-movefrwd"),
        x("Eine Ebene nach hinten", "img-movebkwd"),
        x("Ausrichtung", "img-align"),
        x("Gruppieren", "img-group"),
        x("Formen zusammenführen", "shapes-merge"),
        c("colorschemas", "Farbschema ändern", "colorschemas"),
    ]},
    Tab { name: "Formel", cmds: &[
        c("insert-function", "Funktion einfügen", "additional-formula"),
        c("sum", "AutoSumme", "autosum"),
        c("fn-recent", "Zuletzt verwendet", "recent"),
        c("fn-financial", "Finanzmathematik", "financial"),
        c("fn-logical", "Logisch", "logical"),
        c("fn-text", "Text", "text"),
        c("fn-datetime", "Datum u. Uhrzeit", "datetime"),
        c("fn-lookup", "Suchen und Bezüge", "lookup"),
        c("fn-math", "Math. u. Trigonom.", "math"),
        c("fn-more", "Weitere Funktionen", "more"),
        c("defname", "Name-Manager", "named-range-huge"),
        c("paste-name", "Namen einfügen", "paste-name"),
        c("trace-prec", "Präzedenzfälle", "trace-prec"),
        c("trace-dep", "Trace-Abhängige", "trace-dep"),
        c("remove-arrows", "Pfeile entfernen", "remove-arrows"),
        c("show-formulas", "Formeln anzeigen", "show-formulas"),
        c("watch", "Überwachungsfenster", "watch-window"),
        c("calc-mode", "Berechnung", "calculate"),
    ]},
    Tab { name: "Daten", cmds: &[
        c("data-from-text", "Text zu Daten", "data-from-text"),
        c("data-external-links", "Externe Verknüpfungen (als Werte einlesen)", "data-external-links"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Filter löschen", "clear-filter"),
        c("sort-desc", "Absteigend sortieren", "sortdesc"),
        c("sort-asc", "Aufsteigend sortieren", "sortasc"),
        c("custom-sort", "Sortieren", "custom-sort"),
        c("text-column", "Text in Spalten", "text-column"),
        c("rem-duplicates", "Duplikate entfernen", "rem-duplicates"),
        c("data-validation", "Datenüberprüfung", "data-validation"),
        c("goal-seek", "Zielwertsuche", "goal-seek"),
        c("solver", "Solver", "solver"),
        c("group", "Gruppieren", "group"),
        c("ungroup", "Gruppierung aufheben", "ungroup"),
        c("show-details", "Details anzeigen", "show-details"),
        c("hide-details", "Detail ausblenden", "hide-details"),
        c("subtotal", "Teilergebnisse", "subtotal"),
        c("datatable", "Datentabelle", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "CSV-Format", "csv-kind"),
        c("flash-fill", "Musterfüllung", "flash-fill"),
    ]},
    Tab { name: "Python", cmds: &[
        c("py-edit", "Funktion bearbeiten", "py-edit"),
        c("py-new", "Neue .py", "py-new"),
        c("py-run", "Ablauf ausführen", "py-run"),
        c("py-list", "Liste", "py-list"),
        c("py-line", "Eine Zeile Code", "py-line"),
        c("py-calc", "Neu berechnen", "py-calc"),
        c("py-folder", "Ordner öffnen", "py-folder"),
    ]},
    Tab { name: "Pivot-Tabelle", cmds: &[
        c("pivot-insert", "Pivot-Tabelle einfügen", "pivot-insert"),
        c("pivot-fields", "Feldliste", "pivot-fields"),
        c("pivot-refresh", "Aktualisieren", "pivot-refresh"),
        c("pivot-refresh-all", "Alles aktualisieren", "pivot-refresh-all"),
        c("pivot-select", "Auswählen", "pivot-select"),
        c("pivot-totals", "Gesamtsumme", "pivot-totals"),
        c("pivot-subtotals", "Teilergebnisse", "pivot-subtotals"),
        c("pivot-blank", "Leere Zeilen", "pivot-blank"),
        c("pivot-showas", "Berechnungsart", "pivot-showas"),
        c("pivot-layout", "Berichtslayout", "pivot-layout"),
        c("pivot-style", "Typ", "pivot-style"),
    ]},
    Tab { name: "Tabellen-Design", cmds: &[
        c("td-header", "Kopfzeile", "td-header"),
        c("td-total", "Gesamtzeile", "td-total"),
        c("td-band-row", "Verbundene Zeilen", "td-band-row"),
        c("td-first", "Erste Spalte", "td-first"),
        c("td-last", "Letzte Spalte", "td-last"),
        c("td-band-col", "Gebänderte Spalten", "td-band-col"),
        c("td-filter", "Schaltfläche Filter", "td-filter"),
        c("rem-duplicates", "Entferne Duplikate", "td-remdup"),
        c("td-torange", "In Zellenbereich konvertieren", "td-torange"),
        c("td-resize", "Tabellengröße ändern", "td-resize"),
    ]},
    Tab { name: "Zusammenarbeit", cmds: &[
        c("coauth-mode", "Co-Bearbeitung", "coauth-mode"),
        c("addcomment", "Kommentar hinzufügen", "co-addcomment"),
        c("co-delcomment", "Kommentar löschen", "co-delcomment"),
        c("co-showcomment", "Kommentare anzeigen", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("co-history", "Versionsverlauf", "co-history"),
    ]},
    Tab { name: "Schutz", cmds: &[
        c("prot-encrypt", "Verschlüsseln", "prot-encrypt"),
        x("Arbeitsmappe schützen", "protect-workbook"),
        c("prot-doc", "Blatt schützen", "protect-sheet"),
        x("Bereich schützen", "protect-range"),
        c("prot-sign", "Digitale Signatur hinzufügen", "prot-sign"),
        c("cell-lock", "Zelle sperren", "cell-lock"),
        c("prot-allow", "Erlaubte Aktionen", "prot-allow"),
        c("recover", "Wiederherstellen", "recover"),
        c("recover-every", "Sicherungsintervall", "recover-every"),
        c("read-only-rec", "Schreibschutz empfehlen", "read-only-rec"),
    ]},
    Tab { name: "Anzeigen", cmds: &[
        c("sheet-view", "Tabellenansicht", "sheet-view"),
        x("Normal", "view-normal"),
        x("Seitenumbruch-Vorschau", "view-pagebreak"),
        c("zoom-in", "Vergrößern", "zoom-in"),
        c("zoom-out", "Verkleinern", "zoom-out"),
        c("ui-bigger", "Oberflächentext größer", "ui-bigger"),
        c("ui-smaller", "Oberflächentext kleiner", "ui-smaller"),
        c("theme", "Oberflächendesign", "theme"),
        c("freeze", "Fensterausschnitt fixieren", "freeze"),
        c("formula-bar", "Formelleiste", "formula-bar"),
        c("show-gridlines", "Gitternetzlinien ", "show-gridlines"),
        c("show-headings", "Überschriften", "show-headings"),
        c("show-zeros", "Nullen anzeigen", "show-zeros"),
    ]},
    Tab { name: "Plugins", cmds: &[
        c("plug-macros", "Makros", "plug-macros"),
        c("plug-manage", "Plugins verwalten", "plug-manage"),
    ]},
    Tab { name: "KI", cmds: &[
        c("ai-where", "Ziel", "ai-where"),
        c("ai-summary", "Zusammenfassung", "ai-summary"),
        c("ai-rewrite", "Umschreiben", "ai-rewrite"),
        c("ai-polite", "Höflicher", "ai-polite"),
        c("ai-plain", "Einfacher", "ai-plain"),
        c("ai-translate", "Übersetzung", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Fortsetzen", "ai-continue"),
        c("ai-table", "In Tabelle", "ai-table"),
        c("ai-ask", "Anfragen", "ai-ask"),
    ]},
];

