//! リボンの tr 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py tr > ui/src/ribbon_tr.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Dosya", cmds: &[
        c("open", "Aç", "open"),
        c("save", "Kaydet", "save"),
        c("pdf", "Yazdır", "print"),
    ]},
    Tab { name: "Ana Sayfa", cmds: &[
        c("copy", "Kopyala", "copy"),
        c("cut", "Kes", "cut"),
        c("paste", "Yapıştır", "paste"),
        c("fontname", "Yazı Tipi", "fontname"),
        c("fontsize", "Yazıtipi boyutu", "fontsize"),
        c("incfont", "Yazı boyutunu arttır", "incfont"),
        c("decfont", "Yazı boyutunu azalt", "decfont"),
        c("changecase", "Büyük/küçük harf değiştir", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("bold", "Kalın", "bold"),
        c("italic", "Eğik", "italic"),
        c("underline", "Altı çizili", "underline"),
        c("strikeout", "Üstü çizili", "strikeout"),
        c("superscript", "Üst Simge", "superscript"),
        c("subscript", "Altsimge", "subscript"),
        c("highlight", "Vurgu Rengi", "highlight"),
        c("fontcolor", "Yazı Tipi Rengi", "fontcolor"),
        c("clearstyle", "Stili Temizle", "clearstyle"),
        c("markers", "Madde", "markers"),
        c("numbering", "Numaralandırma", "numbering"),
        c("multilevels", "Çok düzeyli liste", "multilevels"),
        c("decoffset", "Girintiyi azalt", "decoffset"),
        c("incoffset", "Girintiyi arttır", "incoffset"),
        c("linespace", "Paragraf satır aralığı", "linespace"),
        c("direction", "Metin yönü", "direction"),
        c("align-left", "Sola Hizala", "align-left"),
        c("align-center", "Orta", "align-center"),
        c("align-right", "Sağa Hizala", "align-right"),
        c("align-just", "İki yana yaslı", "align-just"),
        c("align-dist", "Dağıtılmış", "align-dist"),
        c("hidenchars", "Basılmaz Karakterler", "hidenchars"),
        c("paracolor", "Paragraf Arka Plan Rengi", "paracolor"),
        c("borders", "Kenarlıklar", "borders"),
        c("parastyle", "Paragraf Stili", "styles"),
        c("replace", "Değiştir", "replace"),
        c("selectall", "Tümünü seç", "select-all"),
    ]},
    Tab { name: "Ekle", cmds: &[
        c("blankpage", "Boş sayfa ekle", "blankpage"),
        c("pagebreak", "Sayfa yada Bölüm Kesmesi Ekle", "pagebreak"),
        c("instable", "Tablo ekle", "instable"),
        c("insimage", "Resim ekle", "insertimage"),
        c("insshape", "Şekil ekle", "insshape"),
        c("inssmartart", "SmartArt ekle", "inssmartart"),
        c("inschart", "Tablo ekle", "inschart"),
        c("smartpicker", "Tablo ekle", "smartpicker"),
        c("instext", "Metin kutusu ekle", "instext"),
        c("instextart", "Yazı Sanatı Ekle", "instextart"),
        c("dropcap", "Büyük Harf Ekle", "dropcap"),
        c("text-from-file", "Dosyadan metin", "text-from-file"),
        c("edit-header", "Üst Bilgiyi Düzenle", "edit-header"),
        c("edit-footer", "Altlığı Düzenle", "edit-footer"),
        c("pagenum", "Sayfa Numarası", "pagenum"),
        c("datetime", "Son kullanılan işlevler", "datetime"),
        c("numpages", "Sayfa sayısı", "numpages"),
        c("insequation", "Denklem Ekle", "insequation"),
        c("inssymbol", "Simge ekle", "inssymbol"),
        c("controls", "İçerik kontrolleri ekle ", "controls"),
    ]},
    Tab { name: "Çizim", cmds: &[
        c("pen", "Kalem", "pen"),
        c("highlighter", "Vurgulayıcı", "highlighter"),
        c("eraser", "Silgi", "eraser"),
    ]},
    Tab { name: "Tasarım", cmds: &[
        c("pagemargins", "Kenar Boşlukları", "pagemargins"),
        c("pageorient", "Oryantasyon", "pageorient"),
        c("pagesize", "Sayfa Boyutu", "pagesize"),
        c("columns", "Sütun Ekle", "columns"),
        c("line-numbers", "Satır numaralarını göster", "line-numbers"),
        c("hyphenation", "Hecelemeyi Değiştir", "hyphenation"),
        c("watermark", "Filigranı düzenle", "watermark"),
        c("pagecolor", "Sayfa Rengini Değiştir", "pagecolor"),
        c("colorschemas", "Renk Şemasını Değiştir", "colorschemas"),
    ]},
    Tab { name: "Kaynakça", cmds: &[
        c("toc", "İçindekiler Tablosu", "contents"),
        c("add-text", "Metin Ekle", "add-text"),
        c("toc-update", "Şeritli sütunlar", "contents-update"),
        c("bookmarks", "Yer imi", "bookmarks"),
        c("caption", "Şekiller tablosu", "caption"),
        c("crossref", "Çapraz referans", "crossref"),
        c("footnote", "Dipnot", "footnote"),
        c("tof", "Şekiller tablosunu güncelle", "tof"),
        c("tof-update", "Dış bağlantılar (değer olarak al)", "tof-update"),
    ]},
    Tab { name: "Formlar", cmds: &[
        c("form-text", "Metin Alanı", "form-text"),
        c("form-combo", "Açılan kutu", "form-combo"),
        c("form-dropdown", "Aşağı açılır", "form-dropdown"),
        c("form-checkbox", "Onay kutusu", "form-checkbox"),
        c("form-radio", "Seçenek Düğmesi", "form-radio"),
        c("form-image", "Resim", "form-image"),
        c("form-email", "Eposta adresi", "form-email"),
        c("form-phone", "Telefon numarası", "form-phone"),
        c("form-complex", "Karmaşık alan", "form-complex"),
        c("form-signature", "İmza", "form-signature"),
        c("form-name", "Ad", "form-name"),
    ]},
    Tab { name: "Ortak Çalışma", cmds: &[
        c("coauth-mode", "Birlikte düzenleme modu", "coauth-mode"),
        c("co-addcomment", "Yorum Ekle", "co-addcomment"),
        c("co-delcomment", "Çözücü", "co-delcomment"),
        c("co-showcomment", "Yorumu göster", "co-showcomment"),
        c("co-chat", "Sohbet", "co-chat"),
        c("track-changes", "Değişiklikleri izle", "track-changes"),
        c("co-history", "Sürüm geçmişi", "co-history"),
    ]},
    Tab { name: "Koruma", cmds: &[
        c("prot-encrypt", "Şifrele", "prot-encrypt"),
        c("prot-sign", "Dijital imza ekle", "prot-sign"),
        c("prot-doc", "Koruma", "prot-doc"),
    ]},
    Tab { name: "Görüntüle", cmds: &[
        c("nav", "Gezinti", "nav"),
        c("fit-page", "Sayfaya Sığdır", "fit-page"),
        c("fit-width", "Genişliğe Sığdır", "fit-width"),
        c("zoom100", "%100'e yakınlaştır", "zoom100"),
        c("zoom-in", "Yakınlaştır", "zoom-in"),
        c("zoom-out", "Uzaklaştır", "zoom-out"),
        c("printview", "Yazdırma düzeni", "printview"),
        c("multipage", "Çoklu sayfa", "multipage"),
        c("darkmode", "Karanlık mod", "darkmode"),
        c("ruler", "Cetveller", "ruler"),
        c("show-toolbar", "Her zaman araç çubuğunu göster", "show-toolbar"),
        c("show-statusbar", "Durum Çubuğu", "show-statusbar"),
        c("show-left", "Sol Panel", "show-left"),
        c("show-right", "Sağ Panel", "show-right"),
    ]},
    Tab { name: "Eklentiler", cmds: &[
        c("plug-macros", "Makrolar", "plug-macros"),
        c("plug-manage", "Eklentileri yönet", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Hedef", "ai-where"),
        c("ai-summary", "özet", "ai-summary"),
        c("ai-rewrite", "Yeniden yaz", "ai-rewrite"),
        c("ai-polite", "Daha kibar", "ai-polite"),
        c("ai-plain", "Sadeleştir", "ai-plain"),
        c("ai-translate", "çeviri", "ai-translate"),
        c("ai-furigana", "furigana", "ai-furigana"),
        c("ai-continue", "Devamını yaz", "ai-continue"),
        c("ai-table", "Tabloya çevir", "ai-table"),
        c("ai-ask", "Sor", "ai-ask"),
        c("ai-macro", "Metni sütunlara dönüştür", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Dosya", cmds: &[
        c("open", "Aç", "open"),
        c("save", "Kaydet", "save"),
        c("pdf", "Yazdır", "print"),
    ]},
    Tab { name: "Ana Sayfa", cmds: &[
        c("copy", "Kopyala", "copy"),
        c("cut", "Kes", "cut"),
        c("paste", "Yapıştır", "paste"),
        c("copystyle", "Biçim boyacısı", "copystyle"),
        c("fontname", "Yazı Tipi", "fontname"),
        c("fontsize", "Yazıtipi boyutu", "fontsize"),
        c("incfont", "Yazı boyutunu arttır", "incfont"),
        c("decfont", "Yazı boyutunu azalt", "decfont"),
        c("changecase", "Büyük/küçük harf değiştir", "changecase"),
        c("bold", "Kalın", "bold"),
        c("italic", "Eğik", "italic"),
        c("underline", "Altı çizili", "underline"),
        c("strikeout", "Üstü çizili", "strikeout"),
        c("subscript", "Altsimge", "subscript"),
        c("fontcolor", "Yazı Tipi Rengi", "fontcolor"),
        c("fillparag", "Dolgu Rengi", "fillparag"),
        c("borders", "Sınırlar", "borders"),
        c("top", "Üste Hizala", "top"),
        c("middle", "Orta", "middle"),
        c("bottom", "Alta Hizala", "bottom"),
        c("wrap", "Yordam çalıştır", "wrap"),
        c("text-orient", "Oryantasyon", "text-orient"),
        c("align-left", "Sola Hizala", "align-left"),
        c("align-center", "Orta", "align-center"),
        c("align-right", "Sağa Hizala", "align-right"),
        c("align-just", "İki yana yaslı", "align-just"),
        c("align-dist", "Dağıtılmış", "align-dist"),
        c("merge", "Birleştir ve ortala", "merge"),
        c("direction", "Metin işlevleri", "direction"),
        c("sum", "Otomatik Toplam", "autosum"),
        c("fill-num", "Filtreyi temizle", "fill-num"),
        c("defname", "Manager", "named-range"),
        c("clear", "Temizle", "clear"),
        c("sort-desc", "En yüksekten en aza sırala", "sortdesc"),
        c("sort-asc", "En düşükten en yükseğe sırala", "sortasc"),
        c("setfilter", "Filtreler", "setfilter"),
        c("clear-filter", "Makro yaz", "clear-filter"),
        c("format", "Sayı Formatı", "format"),
        c("currency", "Kur Stili", "currency"),
        c("percents", "Yüzde Stili", "percents"),
        c("comma", "Virgül stili", "comma"),
        c("digit-dec", "Ondalık Azalt", "digit-dec"),
        c("digit-inc", "Ondalık Arttır", "digit-inc"),
        c("cell-ins", "Hücre Ekle", "cell-ins"),
        c("cell-del", "Hücre Sil", "cell-del"),
        c("cell-format", "Hücre Stili", "cell-format"),
        c("condformat", "Koşullu biçimlendirme", "condformat"),
        c("table-tpl", "Tablo ekle", "table-tpl"),
        c("cell-styles", "Hücre Stili", "styles"),
        c("replace", "Değiştir", "replace"),
        c("selectall", "Tümünü seç", "select-all"),
    ]},
    Tab { name: "Ekle", cmds: &[
        c("pivot-insert", "Pivot Tablo Ekle", "add-pivot"),
        c("instable", "Tablo ekle", "instable"),
        c("insimage", "Resim ekle", "insimage-c"),
        c("insshape", "Şekil ekle", "insshape"),
        c("inssmartart", "SmartArt ekle", "inssmartart"),
        c("inscheckbox", "Onay kutusu", "inscheckbox"),
        c("insrecommend", "Önerilen grafik ekle", "insrecommend"),
        c("inschart", "Tablo ekle", "inschart"),
        c("inssparkline", "Mini grafik ekle", "inssparkline"),
        c("addcomment", "Yorumlar", "ins-comment"),
        c("insrecommend", "Tablo ekle", "smartpicker"),
        c("inshyperlink", "Köprü Ekle", "inshyperlink"),
        c("insslicer", "Dilimleyici Ekle ", "insslicer"),
        c("instext", "Metin kutusu ekle", "instext"),
        c("instextart", "Yazı Sanatı Ekle", "instextart"),
        c("editheader", "Üst/Alt Bilgi", "editheader"),
        c("insequation", "Denklem Ekle", "insequation"),
        c("inssymbol", "Simge ekle", "inssymbol"),
    ]},
    Tab { name: "Çizim", cmds: &[
        c("draw-select", "Seç", "select-tool"),
        c("pen", "Kalem", "pen"),
        c("highlighter", "Vurgulayıcı", "highlighter"),
        c("eraser", "Silgi", "eraser"),
    ]},
    Tab { name: "Tasarım", cmds: &[
        c("pagemargins", "Kenar Boşlukları", "pagemargins"),
        c("pageorient", "Oryantasyon", "pageorient"),
        c("pagesize", "Sayfa Boyutu", "pagesize"),
        c("printarea", "Yazdırma Alanı", "printarea"),
        c("pagebreak", "Yeni sayfanın başlayacağı yere sayfa sonu ekle", "pagebreak"),
        c("editheader", "Üst/Alt Bilgi", "editheader"),
        c("scale", "Sığdırmak için Ölçekle", "scale"),
        c("fit-pages", "Aralık ekle", "fit-pages"),
        c("printarea-add", "Yeni .py", "printarea-add"),
        c("show-breaks", "Kâğıda sığdır", "show-breaks"),
        c("printtitles", "Başlıkları yazdır", "printtitles"),
        c("rtl-sheet", "Sayfa yönünü ilk sütun sağda olacak şekilde değiştir", "rtl-sheet"),
        c("print-gridlines", "İçindekiler tablosunu güncelle", "print-gridlines"),
        c("print-headings", "Ayrıntıyı gizle", "print-headings"),
        x("İleri Taşı", "img-movefrwd"),
        x("Geri Gönder", "img-movebkwd"),
        x("Hiza", "img-align"),
        x("Grup", "img-group"),
        x("Şekilleri birleştir", "shapes-merge"),
        c("colorschemas", "Renk Şemasını Değiştir", "colorschemas"),
    ]},
    Tab { name: "Formül", cmds: &[
        c("insert-function", "CSV biçimi", "additional-formula"),
        c("sum", "Otomatik Toplam", "autosum"),
        c("fn-recent", "Kılavuz çizgileri de yazdır", "recent"),
        c("fn-financial", "Finansal", "financial"),
        c("fn-logical", "Mantıksal", "logical"),
        c("fn-text", "Tarih ve Saat", "text"),
        c("fn-datetime", "Son kullanılan işlevler", "datetime"),
        c("fn-lookup", "Arama ve Referans", "lookup"),
        c("fn-math", "Formülleri göster", "math"),
        c("fn-more", "Daha fazla fonksiyon", "more"),
        c("defname", "Manager", "named-range-huge"),
        c("paste-name", "Ad yapıştır", "paste-name"),
        c("trace-prec", "Etkileyenleri izle", "trace-prec"),
        c("trace-dep", "Etkilenenleri izle", "trace-dep"),
        c("remove-arrows", "Doldur", "remove-arrows"),
        c("show-formulas", "Metin yönü (sağdan sola)", "show-formulas"),
        c("watch", "Gözcü penceresi", "watch-window"),
        c("calc-mode", "Hesaplama", "calculate"),
    ]},
    Tab { name: "Veri", cmds: &[
        c("data-from-text", "Okları kaldır", "data-from-text"),
        c("data-external-links", "Matematik ve Trigonometri", "data-external-links"),
        c("setfilter", "Filtreler", "setfilter"),
        c("clear-filter", "Makro yaz", "clear-filter"),
        c("sort-desc", "En yüksekten en aza sırala", "sortdesc"),
        c("sort-asc", "En düşükten en yükseğe sırala", "sortasc"),
        c("custom-sort", "Sırala", "custom-sort"),
        c("text-column", "Resim yazısı", "text-column"),
        c("rem-duplicates", "İşlev ekle", "rem-duplicates"),
        c("data-validation", "Veri doğrulama", "data-validation"),
        c("goal-seek", "Hedef Ara", "goal-seek"),
        c("solver", "Metinden veri", "solver"),
        c("group", "Grup", "group"),
        c("ungroup", "Gruptan çıkar", "ungroup"),
        c("show-details", "Detayları Göster", "show-details"),
        c("hide-details", "Yinelenenleri kaldır", "hide-details"),
        c("subtotal", "Ara toplamlar", "subtotal"),
        c("datatable", "Hızlı doldurma", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Hücre kilidi", "csv-kind"),
        c("flash-fill", "Tek satır kod", "flash-fill"),
    ]},
    Tab { name: "Python", cmds: &[
        c("rec-toggle", "Açıklamayı sil", "py-run"),
        c("py-new", "Yedek aralığı", "py-new"),
        c("py-list", "Liste", "py-list"),
        c("py-folder", "Sayfa sonları", "py-folder"),
    ]},
    Tab { name: "Pivot Tablo", cmds: &[
        c("pivot-insert", "Pivot Tablo Ekle", "pivot-insert"),
        c("pivot-fields", "Alan listesi", "pivot-fields"),
        c("pivot-refresh", "Yenile", "pivot-refresh"),
        c("pivot-refresh-all", "Tümünü yenile", "pivot-refresh-all"),
        c("pivot-select", "Seç", "pivot-select"),
        c("pivot-totals", "Genel Toplamlar", "pivot-totals"),
        c("pivot-subtotals", "Ara toplamlar", "pivot-subtotals"),
        c("pivot-blank", "Boş Satırlar", "pivot-blank"),
        c("pivot-showas", "Klasörü aç", "pivot-showas"),
        c("pivot-layout", "Rapor Düzeni", "pivot-layout"),
        c("pivot-style", "Stil", "pivot-style"),
    ]},
    Tab { name: "Tablo tasarımı", cmds: &[
        c("td-header", "Üst bilgi satırı", "td-header"),
        c("td-total", "Toplam satırı", "td-total"),
        c("td-band-row", "Bantlı Satırlar", "td-band-row"),
        c("td-first", "İlk Sütun", "td-first"),
        c("td-last", "Son sütun", "td-last"),
        c("td-band-col", "Başlıkları da yazdır", "td-band-col"),
        c("td-filter", "Filtre düğmesi", "td-filter"),
        c("rem-duplicates", "Yinelenenleri Kaldır", "td-remdup"),
        c("td-torange", "Aralığa dönüştür", "td-torange"),
        c("td-resize", "Tabloyu yeniden boyutlandır", "td-resize"),
    ]},
    Tab { name: "Ortak Çalışma", cmds: &[
        c("coauth-mode", "Birlikte düzenleme modu", "coauth-mode"),
        c("addcomment", "Yorum Ekle", "co-addcomment"),
        c("co-delcomment", "Çözücü", "co-delcomment"),
        c("co-showcomment", "Yorumu göster", "co-showcomment"),
        c("co-chat", "Sohbet", "co-chat"),
        c("co-history", "Sürüm geçmişi", "co-history"),
    ]},
    Tab { name: "Koruma", cmds: &[
        c("prot-encrypt", "Şifrele", "prot-encrypt"),
        x("Çalışma Kitabını Koru", "protect-workbook"),
        c("prot-doc", "Sayfayı Koruyun", "protect-sheet"),
        x("Aralığı koru", "protect-range"),
        c("prot-sign", "Dijital imza ekle", "prot-sign"),
        c("cell-lock", "Veri tablosu", "cell-lock"),
        c("prot-allow", "Yeniden hesapla", "prot-allow"),
        c("recover", "Kurtarma", "recover"),
        c("recover-every", "Metni kaydır", "recover-every"),
        c("read-only-rec", "Hesaplama türü", "read-only-rec"),
    ]},
    Tab { name: "Görüntüle", cmds: &[
        c("sheet-view", "Sayfa Görünümü", "sheet-view"),
        x("Normal", "view-normal"),
        x("Sayfa Sonu Önizlemesi", "view-pagebreak"),
        c("zoom-in", "Yakınlaştır", "zoom-in"),
        c("zoom-out", "Uzaklaştır", "zoom-out"),
        c("ui-bigger", "Ekran yazısını büyüt", "ui-bigger"),
        c("ui-smaller", "Ekran yazısını küçült", "ui-smaller"),
        c("theme", "Arayüz teması", "theme"),
        c("freeze", "Parçaları Dondur", "freeze"),
        c("formula-bar", "Formül çubuğu", "formula-bar"),
        c("show-gridlines", "Gridlines", "show-gridlines"),
        c("show-headings", "Başlıklar", "show-headings"),
        c("show-zeros", "Sıfırları göster", "show-zeros"),
    ]},
    Tab { name: "Eklentiler", cmds: &[
        c("plug-macros", "Makrolar", "plug-macros"),
        c("plug-manage", "Eklentileri yönet", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Hedef", "ai-where"),
        c("ai-summary", "özet", "ai-summary"),
        c("ai-rewrite", "Yeniden yaz", "ai-rewrite"),
        c("ai-polite", "Daha kibar", "ai-polite"),
        c("ai-plain", "Sadeleştir", "ai-plain"),
        c("ai-translate", "çeviri", "ai-translate"),
        c("ai-furigana", "furigana", "ai-furigana"),
        c("ai-continue", "Devamını yaz", "ai-continue"),
        c("ai-table", "Tabloya çevir", "ai-table"),
        c("ai-ask", "Sor", "ai-ask"),
    ]},
];

