//! リボンの it 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py it > ui/src/ribbon_it.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Apri", "open"),
        c("save", "Salva", "save"),
        c("pdf", "Stampa", "print"),
    ]},
    Tab { name: "Base", cmds: &[
        c("copy", "Copia", "copy"),
        c("cut", "Taglia", "cut"),
        c("paste", "Incolla", "paste"),
        c("fontname", "Carattere", "fontname"),
        c("fontsize", "Dimensione carattere", "fontsize"),
        c("incfont", "Aumenta dimensione caratteri ", "incfont"),
        c("decfont", "Riduci dimensione caratteri", "decfont"),
        c("changecase", "Cambia forma", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("bold", "Grassetto", "bold"),
        c("italic", "Corsivo", "italic"),
        c("underline", "Sottolineato", "underline"),
        c("strikeout", "Barrato", "strikeout"),
        c("superscript", "Apice", "superscript"),
        c("subscript", "Pedice", "subscript"),
        c("highlight", "Colore evidenziatore", "highlight"),
        c("fontcolor", "Colore caratteri", "fontcolor"),
        c("clearstyle", "Cancella stile", "clearstyle"),
        c("markers", "Elenco puntato", "markers"),
        c("numbering", "Numerazione", "numbering"),
        c("multilevels", "Elenco multilivello", "multilevels"),
        c("decoffset", "Riduci rientro", "decoffset"),
        c("incoffset", "Aumenta rientro", "incoffset"),
        c("linespace", "Interlinea tra i paragrafi", "linespace"),
        c("direction", "Direzione del testo", "direction"),
        c("align-left", "Allinea a sinistra", "align-left"),
        c("align-center", "Al centro", "align-center"),
        c("align-right", "Allinea a destra", "align-right"),
        c("align-just", "Giustificato", "align-just"),
        c("align-dist", "Distribuito", "align-dist"),
        c("hidenchars", "Caratteri non stampabili", "hidenchars"),
        c("paracolor", "Ombreggiato", "paracolor"),
        c("borders", "Bordi", "borders"),
        c("parastyle", "Stile paragrafo", "styles"),
        c("replace", "Sostituisci", "replace"),
        c("selectall", "Seleziona tutto", "select-all"),
    ]},
    Tab { name: "Inserisci", cmds: &[
        c("blankpage", "Inserisci pagina vuota", "blankpage"),
        c("pagebreak", "Inserisci interruzione di pagina o di sezione", "pagebreak"),
        c("instable", "Inserisci tabella", "instable"),
        c("insimage", "Inserisci immagine", "insertimage"),
        c("insshape", "Inserisci forma", "insshape"),
        c("inssmartart", "Inserisci SmartArt", "inssmartart"),
        c("inschart", "Inserisci grafico", "inschart"),
        c("smartpicker", "Inserisci grafico", "smartpicker"),
        c("instext", "Inserisci casella di testo", "instext"),
        c("instextart", "Inserisci Text Art", "instextart"),
        c("dropcap", "Inserisci capolettera", "dropcap"),
        c("text-from-file", "Testo da file", "text-from-file"),
        c("edit-header", "Modifica intestazione", "edit-header"),
        c("edit-footer", "Modifica piè di pagina", "edit-footer"),
        c("pagenum", "Numero di pagina", "pagenum"),
        c("datetime", "Data e ora", "datetime"),
        c("numpages", "Numero di pagine", "numpages"),
        c("insequation", "Inserisci equazione", "insequation"),
        c("inssymbol", "Inserisci simbolo", "inssymbol"),
        c("controls", "Inserisci controlli del contenuto", "controls"),
    ]},
    Tab { name: "Disegna", cmds: &[
        c("pen", "Penna", "pen"),
        c("highlighter", "Evidenziatore", "highlighter"),
        c("eraser", "Gomma", "eraser"),
    ]},
    Tab { name: "Schema di pagina", cmds: &[
        c("pagemargins", "Margini", "pagemargins"),
        c("pageorient", "Orientamento pagina", "pageorient"),
        c("pagesize", "Dimensione pagina", "pagesize"),
        c("columns", "Inserisci colonna", "columns"),
        c("line-numbers", "‎Mostra numeri di riga‎", "line-numbers"),
        c("hyphenation", "Cambia suddivisione", "hyphenation"),
        c("watermark", "Modifica filigrana", "watermark"),
        c("pagecolor", "Cambia colore della pagina", "pagecolor"),
        c("colorschemas", "Cambia combinazione di colori", "colorschemas"),
    ]},
    Tab { name: "Riferimenti", cmds: &[
        c("toc", "Sommario", "contents"),
        c("add-text", "Aggiungi testo", "add-text"),
        c("toc-update", "Aggiorna sommario", "contents-update"),
        c("bookmarks", "Segnalibri", "bookmarks"),
        c("caption", "Didascalia", "caption"),
        c("crossref", "‎Riferimento incrociato‎", "crossref"),
        c("footnote", "Nota a piè di pagina", "footnote"),
        c("tof", "Indice delle figure", "tof"),
        c("tof-update", "Aggiorna indice delle figure", "tof-update"),
    ]},
    Tab { name: "Forme‎", cmds: &[
        c("form-text", "‎Campo di testo‎", "form-text"),
        c("form-combo", "Casella combinata", "form-combo"),
        c("form-dropdown", "Menù a discesa", "form-dropdown"),
        c("form-checkbox", "Casella di controllo", "form-checkbox"),
        c("form-radio", "Pulsante Radio", "form-radio"),
        c("form-image", "Immagine", "form-image"),
        c("form-email", "Indirizzo email", "form-email"),
        c("form-phone", "Numero di telefono", "form-phone"),
        c("form-complex", "Campo complesso", "form-complex"),
        c("form-signature", "Firma", "form-signature"),
        c("form-name", "Nome", "form-name"),
    ]},
    Tab { name: "Collaborazione", cmds: &[
        c("coauth-mode", "Modalità collaborativa", "coauth-mode"),
        c("co-addcomment", "Aggiungi commento", "co-addcomment"),
        c("co-delcomment", "Elimina commento", "co-delcomment"),
        c("co-showcomment", "Mostra commento", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("track-changes", "Traccia cambiamenti", "track-changes"),
        c("co-history", "Cronologia versioni", "co-history"),
    ]},
    Tab { name: "Protezione", cmds: &[
        c("prot-encrypt", "Crittografa", "prot-encrypt"),
        c("prot-sign", "Aggiungi firma digitale", "prot-sign"),
        c("prot-doc", "Protezione", "prot-doc"),
    ]},
    Tab { name: "Visualizza", cmds: &[
        c("nav", "Navigazione", "nav"),
        c("fit-page", "Adatta alla pagina", "fit-page"),
        c("fit-width", "Adatta alla larghezza", "fit-width"),
        c("zoom100", "Zoom al 100%", "zoom100"),
        c("zoom-in", "Zoom avanti", "zoom-in"),
        c("zoom-out", "Zoom indietro", "zoom-out"),
        c("multipage", "Pagine multiple", "multipage"),
        c("darkmode", "Modalità scura", "darkmode"),
        c("ruler", "Righelli", "ruler"),
        c("show-toolbar", "Mostra sempre la barra strumenti ", "show-toolbar"),
        c("show-statusbar", "Barra di stato", "show-statusbar"),
        c("show-left", "Pannello sinistro", "show-left"),
        c("show-right", "Pannello destro", "show-right"),
    ]},
    Tab { name: "Componenti", cmds: &[
        c("plug-macros", "Macro", "plug-macros"),
        c("plug-manage", "Gestione plugin", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Destinazione", "ai-where"),
        c("ai-summary", "Riassumi", "ai-summary"),
        c("ai-rewrite", "Riscrivi", "ai-rewrite"),
        c("ai-polite", "Più formale", "ai-polite"),
        c("ai-plain", "Più semplice", "ai-plain"),
        c("ai-translate", "Traduci", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Continua", "ai-continue"),
        c("ai-table", "In tabella", "ai-table"),
        c("ai-ask", "Chiedi", "ai-ask"),
        c("ai-macro", "Scrivi macro", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Apri", "open"),
        c("save", "Salva", "save"),
        c("pdf", "Stampa", "print"),
    ]},
    Tab { name: "Base", cmds: &[
        c("copy", "Copia", "copy"),
        c("cut", "Taglia", "cut"),
        c("paste", "Incolla", "paste"),
        c("copystyle", "Copia formato", "copystyle"),
        c("fontname", "Carattere", "fontname"),
        c("fontsize", "Dimensione carattere", "fontsize"),
        c("incfont", "Aumenta dimensione caratteri ", "incfont"),
        c("decfont", "Riduci dimensione caratteri", "decfont"),
        c("changecase", "Cambia forma", "changecase"),
        c("bold", "Grassetto", "bold"),
        c("italic", "Corsivo", "italic"),
        c("underline", "Sottolineato", "underline"),
        c("strikeout", "Barrato", "strikeout"),
        c("subscript", "Pedice", "subscript"),
        c("fontcolor", "Colore caratteri", "fontcolor"),
        c("fillparag", "Colore di riempimento", "fillparag"),
        c("borders", "Bordi", "borders"),
        c("top", "Allinea in alto", "top"),
        c("middle", "Al centro", "middle"),
        c("bottom", "Allinea in basso", "bottom"),
        c("wrap", "Testo a capo", "wrap"),
        c("text-orient", "Orientamento pagina", "text-orient"),
        c("align-left", "Allinea a sinistra", "align-left"),
        c("align-center", "Al centro", "align-center"),
        c("align-right", "Allinea a destra", "align-right"),
        c("align-just", "Giustificato", "align-just"),
        c("align-dist", "Distribuito", "align-dist"),
        c("merge", "Unisci e centra", "merge"),
        c("direction", "Orientamento del testo (da destra a sinistra)", "direction"),
        c("insert-function", "Funzioni", "formula"),
        c("fill-num", "Riempimento", "fill-num"),
        c("defname", "Gestore nomi", "named-range"),
        c("clear", "Svuota", "clear"),
        c("sort-desc", "Ordine decrescente", "sortdesc"),
        c("sort-asc", "Ordine crescente", "sortasc"),
        c("setfilter", "Filtri", "setfilter"),
        c("clear-filter", "Cancella filtro", "clear-filter"),
        c("format", "Formato del numero", "format"),
        c("currency", "Stile valuta", "currency"),
        c("percents", "Stile percentuale", "percents"),
        c("comma", "Stile della virgola", "comma"),
        c("digit-dec", "Diminuisci decimali", "digit-dec"),
        c("digit-inc", "Aumenta decimali", "digit-inc"),
        c("cell-ins", "Inserisci celle", "cell-ins"),
        c("cell-del", "Elimina celle", "cell-del"),
        c("cell-format", "Stile cella", "cell-format"),
        c("condformat", "Formattazione condizionale", "condformat"),
        c("table-tpl", "Inserisci tabella", "table-tpl"),
        c("cell-styles", "Stile cella", "styles"),
        c("replace", "Sostituisci", "replace"),
        c("selectall", "Seleziona tutto", "select-all"),
    ]},
    Tab { name: "Inserisci", cmds: &[
        c("pivot-insert", "Inserisci tabella pivot", "add-pivot"),
        c("instable", "Inserisci tabella", "instable"),
        c("insimage", "Inserisci immagine", "insimage-c"),
        c("insshape", "Inserisci forma", "insshape"),
        c("inssmartart", "Inserisci SmartArt", "inssmartart"),
        c("inscheckbox", "Casella di controllo", "inscheckbox"),
        c("insrecommend", "Inserisci grafico consigliato", "insrecommend"),
        c("inschart", "Inserisci grafico", "inschart"),
        c("inssparkline", "Inserire grafico sparkline", "inssparkline"),
        c("addcomment", "Commenti", "ins-comment"),
        c("insrecommend", "Inserisci grafico", "smartpicker"),
        c("inshyperlink", "Aggiungi collegamento", "inshyperlink"),
        c("insslicer", "Inserisci filtro dati", "insslicer"),
        c("instext", "Inserisci casella di testo", "instext"),
        c("instextart", "Inserisci Text Art", "instextart"),
        c("editheader", "Intestazione e piè di pagina", "editheader"),
        c("insequation", "Inserisci equazione", "insequation"),
        c("inssymbol", "Inserisci simbolo", "inssymbol"),
    ]},
    Tab { name: "Disegna", cmds: &[
        c("draw-select", "Seleziona", "select-tool"),
        c("pen", "Penna", "pen"),
        c("highlighter", "Evidenziatore", "highlighter"),
        c("eraser", "Gomma", "eraser"),
    ]},
    Tab { name: "Schema di pagina", cmds: &[
        c("pagemargins", "Margini", "pagemargins"),
        c("pageorient", "Orientamento pagina", "pageorient"),
        c("pagesize", "Dimensione pagina", "pagesize"),
        c("printarea", "Area di stampa", "printarea"),
        c("pagebreak", "Aggiungi un'interruzione nel punto in cui vuoi che inizi la pagina successiva nella copia stampata", "pagebreak"),
        c("editheader", "Intestazione e piè di pagina", "editheader"),
        c("scale", "Adatta", "scale"),
        c("fit-pages", "Adatta alla pagina", "fit-pages"),
        c("printarea-add", "Aggiungi intervallo", "printarea-add"),
        c("show-breaks", "Fine pagina", "show-breaks"),
        c("printtitles", "Stampa titoli", "printtitles"),
        c("rtl-sheet", "Inverti la direzione del foglio in modo da visualizzare la prima colonna sul lato destro", "rtl-sheet"),
        c("print-gridlines", "Stampa griglia", "print-gridlines"),
        c("print-headings", "Stampa intestazioni", "print-headings"),
        x("Porta avanti", "img-movefrwd"),
        x("Porta indietro", "img-movebkwd"),
        x("Allineamento", "img-align"),
        x("Raggruppa", "img-group"),
        x("Fondi forme", "shapes-merge"),
        c("colorschemas", "Cambia combinazione di colori", "colorschemas"),
    ]},
    Tab { name: "Formula", cmds: &[
        c("insert-function", "Inserisci funzione", "additional-formula"),
        c("sum", "Somma automatica", "autosum"),
        c("fn-recent", "Usate di recente", "recent"),
        c("fn-financial", "Finanziario", "financial"),
        c("fn-logical", "Logico", "logical"),
        c("fn-text", "Testo", "text"),
        c("fn-datetime", "Data e ora", "datetime"),
        c("fn-lookup", "Ricerca e riferimento", "lookup"),
        c("fn-math", "Matematica e trigonometria", "math"),
        c("fn-more", "Altre funzioni", "more"),
        c("defname", "Gestore nomi", "named-range-huge"),
        c("paste-name", "Incolla nome", "paste-name"),
        c("trace-prec", "Traccia le precedenti", "trace-prec"),
        c("trace-dep", "Traccia le dipendenti", "trace-dep"),
        c("remove-arrows", "Rimuovi frecce", "remove-arrows"),
        c("show-formulas", "Mostra formule", "show-formulas"),
        c("watch", "Finestra controllo celle", "watch-window"),
        c("calc-mode", "Calcolo", "calculate"),
    ]},
    Tab { name: "Dati", cmds: &[
        c("data-from-text", "Da testo a dati", "data-from-text"),
        c("data-external-links", "Collegamenti esterni (importa come valori)", "data-external-links"),
        c("setfilter", "Filtri", "setfilter"),
        c("clear-filter", "Cancella filtro", "clear-filter"),
        c("sort-desc", "Ordine decrescente", "sortdesc"),
        c("sort-asc", "Ordine crescente", "sortasc"),
        c("custom-sort", "Ordina", "custom-sort"),
        c("text-column", "Testo in colonne", "text-column"),
        c("rem-duplicates", "Rimuovi duplicati", "rem-duplicates"),
        c("data-validation", "Validazione dati", "data-validation"),
        c("goal-seek", "Goal seek", "goal-seek"),
        c("solver", "Risolutore", "solver"),
        c("group", "Raggruppa", "group"),
        c("ungroup", "Separa", "ungroup"),
        c("show-details", "Mostra dettagli", "show-details"),
        c("hide-details", "Nascondi dettaglio", "hide-details"),
        c("subtotal", "Subtotale", "subtotal"),
        c("datatable", "Tabella dati", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Formato CSV", "csv-kind"),
        c("flash-fill", "Riempimento rapido", "flash-fill"),
    ]},
    Tab { name: "Python", cmds: &[
        c("py-edit", "Modifica funzione", "py-edit"),
        c("py-new", "Nuovo .py", "py-new"),
        c("py-run", "Esegui procedura", "py-run"),
        c("py-list", "Elenco", "py-list"),
        c("py-line", "Riga di codice", "py-line"),
        c("py-calc", "Ricalcola", "py-calc"),
        c("py-folder", "Apri cartella", "py-folder"),
    ]},
    Tab { name: "Tabella pivot", cmds: &[
        c("pivot-insert", "Inserisci tabella pivot", "pivot-insert"),
        c("pivot-fields", "Elenco campi", "pivot-fields"),
        c("pivot-refresh", "Aggiorna", "pivot-refresh"),
        c("pivot-refresh-all", "Aggiorna tutto", "pivot-refresh-all"),
        c("pivot-select", "Seleziona", "pivot-select"),
        c("pivot-totals", "Totale complessivo", "pivot-totals"),
        c("pivot-subtotals", "Subtotale", "pivot-subtotals"),
        c("pivot-blank", "Righe vuote", "pivot-blank"),
        c("pivot-showas", "Tipo di calcolo", "pivot-showas"),
        c("pivot-layout", "Schema del rapporto", "pivot-layout"),
        c("pivot-style", "Stile", "pivot-style"),
    ]},
    Tab { name: "Struttura tabella", cmds: &[
        c("td-header", "Riga di intestazione", "td-header"),
        c("td-total", "Riga totale", "td-total"),
        c("td-band-row", "Righe a strisce", "td-band-row"),
        c("td-first", "Prima colonna", "td-first"),
        c("td-last", "Ultima colonna", "td-last"),
        c("td-band-col", "Colonne alternate", "td-band-col"),
        c("td-filter", "Pulsante filtro", "td-filter"),
        c("rem-duplicates", "Rimuovi duplicati", "td-remdup"),
        c("td-torange", "Converti in intervallo", "td-torange"),
        c("td-resize", "Ridimensiona tabella", "td-resize"),
    ]},
    Tab { name: "Collaborazione", cmds: &[
        c("coauth-mode", "Modalità collaborativa", "coauth-mode"),
        c("addcomment", "Aggiungi commento", "co-addcomment"),
        c("co-delcomment", "Elimina commento", "co-delcomment"),
        c("co-showcomment", "Mostra commento", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("co-history", "Cronologia versioni", "co-history"),
    ]},
    Tab { name: "Protezione", cmds: &[
        c("prot-encrypt", "Crittografa", "prot-encrypt"),
        x("Proteggere libro di lavoro", "protect-workbook"),
        c("prot-doc", "Proteggi foglio", "protect-sheet"),
        x("Proteggi rango", "protect-range"),
        c("prot-sign", "Aggiungi firma digitale", "prot-sign"),
        c("cell-lock", "Blocca cella", "cell-lock"),
        c("prot-allow", "Operazioni consentite", "prot-allow"),
        c("recover", "Ripristino", "recover"),
        c("recover-every", "Intervallo copie", "recover-every"),
        c("read-only-rec", "Suggerisci sola lettura", "read-only-rec"),
    ]},
    Tab { name: "Visualizza", cmds: &[
        c("sheet-view", "Visualizzazione foglio", "sheet-view"),
        x("Normale", "view-normal"),
        x("Anteprima interruzione di pagina", "view-pagebreak"),
        c("zoom-in", "Zoom avanti", "zoom-in"),
        c("zoom-out", "Zoom indietro", "zoom-out"),
        c("ui-bigger", "Ingrandisci testo dello schermo", "ui-bigger"),
        c("ui-smaller", "Riduci testo dello schermo", "ui-smaller"),
        c("theme", "Tema dell'interfaccia", "theme"),
        c("freeze", "Blocca riquadri", "freeze"),
        c("formula-bar", "Barra della formula", "formula-bar"),
        c("show-gridlines", "Linee griglia", "show-gridlines"),
        c("show-headings", "Intestazioni", "show-headings"),
        c("show-zeros", "Mostra zeri", "show-zeros"),
    ]},
    Tab { name: "Componenti", cmds: &[
        c("plug-macros", "Macro", "plug-macros"),
        c("plug-manage", "Gestione plugin", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "Destinazione", "ai-where"),
        c("ai-summary", "Riassumi", "ai-summary"),
        c("ai-rewrite", "Riscrivi", "ai-rewrite"),
        c("ai-polite", "Più formale", "ai-polite"),
        c("ai-plain", "Più semplice", "ai-plain"),
        c("ai-translate", "Traduci", "ai-translate"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("ai-continue", "Continua", "ai-continue"),
        c("ai-table", "In tabella", "ai-table"),
        c("ai-ask", "Chiedi", "ai-ask"),
    ]},
];

