//! リボンの ko 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py ko > ui/src/ribbon_ko.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "파일", cmds: &[
        c("open", "열기", "open"),
        c("save", "저장", "save"),
        c("pdf", "인쇄", "print"),
    ]},
    Tab { name: "홈", cmds: &[
        c("copy", "복사", "copy"),
        c("cut", "잘라 내기", "cut"),
        c("paste", "붙여 넣기", "paste"),
        c("fontname", "글꼴", "fontname"),
        c("fontsize", "글꼴 크기", "fontsize"),
        c("incfont", "글꼴 크기 증가", "incfont"),
        c("decfont", "글꼴 크기 감소", "decfont"),
        c("changecase", "대소문자 변경", "changecase"),
        c("ruby", "루비", "ruby"),
        c("bold", "굵게", "bold"),
        c("italic", "기울림꼴", "italic"),
        c("underline", "밑줄", "underline"),
        c("strikeout", "취소선", "strikeout"),
        c("superscript", "위첨자", "superscript"),
        c("subscript", "아래 첨자", "subscript"),
        c("highlight", "색상 강조 표시", "highlight"),
        c("fontcolor", "글꼴 색", "fontcolor"),
        c("clearstyle", "스타일 지우기", "clearstyle"),
        c("markers", "글머리 기호", "markers"),
        c("numbering", "번호 매기기", "numbering"),
        c("multilevels", "다중 레벨 목록", "multilevels"),
        c("decoffset", "들여쓰기 줄이기", "decoffset"),
        c("incoffset", "들여쓰기 늘리기", "incoffset"),
        c("linespace", "단락 줄 간격", "linespace"),
        c("direction", "텍스트 방향", "direction"),
        c("align-left", "왼쪽 정렬", "align-left"),
        c("align-center", "Center", "align-center"),
        c("align-right", "오른쪽 정렬", "align-right"),
        c("align-just", "균등분할", "align-just"),
        c("align-dist", "균등 분할", "align-dist"),
        c("hidenchars", "인쇄되지 않는 문자", "hidenchars"),
        c("paracolor", "단락 배경색", "paracolor"),
        c("borders", "테두리", "borders"),
        c("parastyle", "단락 스타일", "styles"),
        c("replace", "바꾸기", "replace"),
        c("selectall", "모두 선택", "select-all"),
    ]},
    Tab { name: "삽입", cmds: &[
        c("blankpage", "빈 페이지 삽입", "blankpage"),
        c("pagebreak", "페이지 또는 섹션 나누기 삽입", "pagebreak"),
        c("instable", "표 삽입", "instable"),
        c("insimage", "그림 삽입", "insertimage"),
        c("insshape", "도형 삽입", "insshape"),
        c("inssmartart", "SmartArt 삽입", "inssmartart"),
        c("inschart", "차트 삽입", "inschart"),
        c("smartpicker", "차트 삽입", "smartpicker"),
        c("instext", "텍스트 상자 삽입", "instext"),
        c("instextart", "텍스트 아트 삽입", "instextart"),
        c("dropcap", "드롭 캡 삽입", "dropcap"),
        c("text-from-file", "파일에서 텍스트 삽입", "text-from-file"),
        c("edit-header", "머리글 편집", "edit-header"),
        c("edit-footer", "바닥글 편집", "edit-footer"),
        c("pagenum", "페이지 번호", "pagenum"),
        c("datetime", "날짜/시간", "datetime"),
        c("numpages", "페이지 수", "numpages"),
        c("insequation", "수식 삽입", "insequation"),
        c("inssymbol", "기호 삽입", "inssymbol"),
        c("controls", "콘텐츠 컨트롤 추가", "controls"),
    ]},
    Tab { name: "그리기", cmds: &[
        c("pen", "펜", "pen"),
        c("highlighter", "하이라이터", "highlighter"),
        c("eraser", "지우개", "eraser"),
    ]},
    Tab { name: "레이아웃", cmds: &[
        c("pagemargins", "여백", "pagemargins"),
        c("pageorient", "페이지 방향", "pageorient"),
        c("pagesize", "페이지 크기", "pagesize"),
        c("columns", "열 삽입", "columns"),
        c("line-numbers", "행 번호 표시", "line-numbers"),
        c("hyphenation", "하이픈 연결 변경", "hyphenation"),
        c("watermark", "워터마크 수정", "watermark"),
        c("pagecolor", "페이지 색 변경", "pagecolor"),
        c("colorschemas", "색상 구성 변경", "colorschemas"),
    ]},
    Tab { name: "참조", cmds: &[
        c("toc", "목차", "contents"),
        c("add-text", "텍스트 추가", "add-text"),
        c("toc-update", "목차 업데이트", "contents-update"),
        c("bookmarks", "즐겨찾기", "bookmarks"),
        c("caption", "캡션", "caption"),
        c("crossref", "상호 참조", "crossref"),
        c("footnote", "각주", "footnote"),
        c("tof", "그림 목차", "tof"),
        c("tof-update", "그림 목차 업데이트", "tof-update"),
    ]},
    Tab { name: "폼", cmds: &[
        c("form-text", "텍스트 필드", "form-text"),
        c("form-combo", "콤보박스", "form-combo"),
        c("form-dropdown", "드롭다운", "form-dropdown"),
        c("form-checkbox", "확인란", "form-checkbox"),
        c("form-radio", "라디오 버튼", "form-radio"),
        c("form-image", "그림", "form-image"),
        c("form-email", "이메일 주소", "form-email"),
        c("form-phone", "전화 번호", "form-phone"),
        c("form-complex", "복합 필드", "form-complex"),
        c("form-signature", "서명", "form-signature"),
        c("form-name", "이름", "form-name"),
    ]},
    Tab { name: "협업", cmds: &[
        c("coauth-mode", "공동 편집 모드", "coauth-mode"),
        c("co-addcomment", "코멘트 추가", "co-addcomment"),
        c("co-delcomment", "메모 삭제", "co-delcomment"),
        c("co-showcomment", "댓글 표시", "co-showcomment"),
        c("co-chat", "채팅", "co-chat"),
        c("track-changes", "변경 내용 추적", "track-changes"),
        c("co-history", "버전 기록", "co-history"),
    ]},
    Tab { name: "보호", cmds: &[
        c("prot-encrypt", "암호화", "prot-encrypt"),
        c("prot-sign", "디지털 서명 추가", "prot-sign"),
        c("prot-doc", "보호", "prot-doc"),
    ]},
    Tab { name: "보기", cmds: &[
        c("nav", "내비게이션", "nav"),
        c("fit-page", "페이지에 맞춤", "fit-page"),
        c("fit-width", "너비에 맞춤", "fit-width"),
        c("zoom100", "100%로 확대", "zoom100"),
        c("zoom-in", "확대", "zoom-in"),
        c("zoom-out", "축소", "zoom-out"),
        c("printview", "인쇄 모양", "printview"),
        c("multipage", "여러 페이지", "multipage"),
        c("darkmode", "다크 모드", "darkmode"),
        c("ruler", "자", "ruler"),
        c("show-toolbar", "항상 도구 모음 표시", "show-toolbar"),
        c("show-statusbar", "상태 바", "show-statusbar"),
        c("show-left", "왼쪽 패널", "show-left"),
        c("show-right", "오른쪽 패널", "show-right"),
    ]},
    Tab { name: "플러그인", cmds: &[
        c("plug-macros", "매크로", "plug-macros"),
        c("plug-manage", "플러그인 관리", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "대상", "ai-where"),
        c("ai-summary", "요약", "ai-summary"),
        c("ai-rewrite", "다시 쓰기", "ai-rewrite"),
        c("ai-polite", "정중하게", "ai-polite"),
        c("ai-plain", "쉽게", "ai-plain"),
        c("ai-translate", "번역", "ai-translate"),
        c("ai-furigana", "후리가나", "ai-furigana"),
        c("ai-continue", "이어 쓰기", "ai-continue"),
        c("ai-table", "표로 만들기", "ai-table"),
        c("ai-ask", "요청", "ai-ask"),
        c("ai-macro", "매크로 작성", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "파일", cmds: &[
        c("open", "열기", "open"),
        c("save", "저장", "save"),
        c("pdf", "인쇄", "print"),
    ]},
    Tab { name: "홈", cmds: &[
        c("copy", "복사", "copy"),
        c("cut", "잘라 내기", "cut"),
        c("paste", "붙여 넣기", "paste"),
        c("copystyle", "서식 복사", "copystyle"),
        c("fontname", "글꼴", "fontname"),
        c("fontsize", "글꼴 크기", "fontsize"),
        c("incfont", "글꼴 크기 증가", "incfont"),
        c("decfont", "글꼴 크기 감소", "decfont"),
        c("changecase", "대소문자 변경", "changecase"),
        c("bold", "굵게", "bold"),
        c("italic", "기울림꼴", "italic"),
        c("underline", "밑줄", "underline"),
        c("strikeout", "취소선", "strikeout"),
        c("subscript", "아래 첨자", "subscript"),
        c("fontcolor", "글꼴 색", "fontcolor"),
        c("fillparag", "채우기 색", "fillparag"),
        c("borders", "테두리", "borders"),
        c("top", "정렬", "top"),
        c("middle", "Center", "middle"),
        c("bottom", "아래쪽 정렬", "bottom"),
        c("wrap", "텍스트 줄 바꿈", "wrap"),
        c("text-orient", "페이지 방향", "text-orient"),
        c("align-left", "왼쪽 정렬", "align-left"),
        c("align-center", "Center", "align-center"),
        c("align-right", "오른쪽 정렬", "align-right"),
        c("align-just", "균등분할", "align-just"),
        c("align-dist", "균등 분할", "align-dist"),
        c("merge", "병합하고 가운데 맞춤", "merge"),
        c("direction", "텍스트 방향(오른쪽부터 쓰기)", "direction"),
        c("insert-function", "함수", "formula"),
        c("fill-num", "채우기", "fill-num"),
        c("defname", "이름 관리자", "named-range"),
        c("clear", "지우기", "clear"),
        c("sort-desc", "텍스트 내림차순 정렬", "sortdesc"),
        c("sort-asc", "텍스트 오름차순 정렬", "sortasc"),
        c("setfilter", "필터", "setfilter"),
        c("clear-filter", "필터 해제", "clear-filter"),
        c("format", "숫자 형식", "format"),
        c("currency", "통화 스타일", "currency"),
        c("percents", "백분율 스타일", "percents"),
        c("comma", "쉼표 스타일", "comma"),
        c("digit-dec", "자리수 줄임", "digit-dec"),
        c("digit-inc", "자리수 늘림", "digit-inc"),
        c("cell-ins", "셀 삽입", "cell-ins"),
        c("cell-del", "셀 삭제", "cell-del"),
        c("cell-format", "셀 스타일", "cell-format"),
        c("condformat", "조건부 서식", "condformat"),
        c("table-tpl", "표 삽입", "table-tpl"),
        c("cell-styles", "셀 스타일", "styles"),
        c("replace", "바꾸기", "replace"),
        c("selectall", "모두 선택", "select-all"),
    ]},
    Tab { name: "삽입", cmds: &[
        c("pivot-insert", "피벗 테이블 삽입", "add-pivot"),
        c("instable", "표 삽입", "instable"),
        c("insimage", "그림 삽입", "insimage-c"),
        c("insshape", "도형 삽입", "insshape"),
        c("inssmartart", "SmartArt 삽입", "inssmartart"),
        c("inscheckbox", "확인란", "inscheckbox"),
        c("insrecommend", "추천 차트 삽입", "insrecommend"),
        c("inschart", "차트 삽입", "inschart"),
        c("inssparkline", "스파크라인 삽입", "inssparkline"),
        c("addcomment", "코멘트", "ins-comment"),
        c("insrecommend", "차트 삽입", "smartpicker"),
        c("inshyperlink", "링크 추가", "inshyperlink"),
        c("insslicer", "슬라이서추가", "insslicer"),
        c("instext", "텍스트 상자 삽입", "instext"),
        c("instextart", "텍스트 아트 삽입", "instextart"),
        c("editheader", "머리말/꼬리말", "editheader"),
        c("insequation", "수식 삽입", "insequation"),
        c("inssymbol", "기호 삽입", "inssymbol"),
    ]},
    Tab { name: "그리기", cmds: &[
        c("draw-select", "선택", "select-tool"),
        c("pen", "펜", "pen"),
        c("highlighter", "하이라이터", "highlighter"),
        c("eraser", "지우개", "eraser"),
    ]},
    Tab { name: "레이아웃", cmds: &[
        c("pagemargins", "여백", "pagemargins"),
        c("pageorient", "페이지 방향", "pageorient"),
        c("pagesize", "페이지 크기", "pagesize"),
        c("printarea", "인쇄 영역", "printarea"),
        c("pagebreak", "인쇄물에서 다음 페이지가 시작되길 원하는 위치에 페이지 나누기를 추가하세요.", "pagebreak"),
        c("editheader", "머리말/꼬리말", "editheader"),
        c("scale", "크기에 맞게 확대/축소", "scale"),
        c("fit-pages", "종이에 맞추기", "fit-pages"),
        c("printarea-add", "범위 더하기", "printarea-add"),
        c("show-breaks", "종이 끊기는 자리", "show-breaks"),
        c("printtitles", "제목 인쇄", "printtitles"),
        c("rtl-sheet", "첫 번째 열이 오른쪽에 오도록 시트 방향을 전환합니다", "rtl-sheet"),
        c("print-gridlines", "눈금선 인쇄", "print-gridlines"),
        c("print-headings", "머리글 인쇄", "print-headings"),
        x("앞으로 보내기", "img-movefrwd"),
        x("뒤로 보내기", "img-movebkwd"),
        x("정렬", "img-align"),
        x("그룹", "img-group"),
        x("도형 병합", "shapes-merge"),
        c("colorschemas", "색상 구성 변경", "colorschemas"),
    ]},
    Tab { name: "수식", cmds: &[
        c("insert-function", "함수 삽입", "additional-formula"),
        c("sum", "자동 합계", "autosum"),
        c("fn-recent", "최근에 사용한 함수", "recent"),
        c("fn-financial", "재무", "financial"),
        c("fn-logical", "논리적", "logical"),
        c("fn-text", "텍스트", "text"),
        c("fn-datetime", "날짜/시간", "datetime"),
        c("fn-lookup", "조회 및 참조", "lookup"),
        c("fn-math", "수학/삼각", "math"),
        c("fn-more", "더 많은 기능", "more"),
        c("defname", "이름 관리자", "named-range-huge"),
        c("paste-name", "이름 붙여넣기", "paste-name"),
        c("trace-prec", "선행 항목 추적", "trace-prec"),
        c("trace-dep", "종속 항목 추적", "trace-dep"),
        c("remove-arrows", "연결선 제거", "remove-arrows"),
        c("show-formulas", "수식 표시", "show-formulas"),
        c("watch", "조사식 창", "watch-window"),
        c("calc-mode", "계산 방법", "calculate"),
    ]},
    Tab { name: "데이터", cmds: &[
        c("data-from-text", "텍스트에서 데이터로", "data-from-text"),
        c("data-external-links", "외부 링크(값으로 가져오기)", "data-external-links"),
        c("setfilter", "필터", "setfilter"),
        c("clear-filter", "필터 해제", "clear-filter"),
        c("sort-desc", "텍스트 내림차순 정렬", "sortdesc"),
        c("sort-asc", "텍스트 오름차순 정렬", "sortasc"),
        c("custom-sort", "정렬", "custom-sort"),
        c("text-column", "텍스트 나누기", "text-column"),
        c("rem-duplicates", "중복된 항목 제거", "rem-duplicates"),
        c("data-validation", "데이터 유효성", "data-validation"),
        c("goal-seek", "목표값 찾기", "goal-seek"),
        c("solver", "해 찾기", "solver"),
        c("group", "그룹", "group"),
        c("ungroup", "그룹 해제", "ungroup"),
        c("show-details", "세부 정보 표시", "show-details"),
        c("hide-details", "하위 수준 숨기기", "hide-details"),
        c("subtotal", "부분합", "subtotal"),
        c("datatable", "데이터 표", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "CSV 형식", "csv-kind"),
        c("flash-fill", "빠른 채우기", "flash-fill"),
    ]},
    Tab { name: "Python", cmds: &[
        c("py-edit", "함수 편집", "py-edit"),
        c("py-new", "새 .py", "py-new"),
        c("py-run", "절차 실행", "py-run"),
        c("py-list", "목록", "py-list"),
        c("py-line", "한 줄 코드", "py-line"),
        c("py-calc", "다시 계산", "py-calc"),
        c("py-folder", "폴더 열기", "py-folder"),
    ]},
    Tab { name: "피벗 테이블", cmds: &[
        c("pivot-insert", "피벗 테이블 삽입", "pivot-insert"),
        c("pivot-fields", "필드 목록", "pivot-fields"),
        c("pivot-refresh", "업데이트", "pivot-refresh"),
        c("pivot-refresh-all", "모두 업데이트", "pivot-refresh-all"),
        c("pivot-select", "선택", "pivot-select"),
        c("pivot-totals", "총합계", "pivot-totals"),
        c("pivot-subtotals", "부분합", "pivot-subtotals"),
        c("pivot-blank", "빈 행", "pivot-blank"),
        c("pivot-showas", "계산 종류", "pivot-showas"),
        c("pivot-layout", "레이아웃 리포트", "pivot-layout"),
        c("pivot-style", "스타일", "pivot-style"),
    ]},
    Tab { name: "표 디자인", cmds: &[
        c("td-header", "머리글 행", "td-header"),
        c("td-total", "총 행", "td-total"),
        c("td-band-row", "줄무늬 행", "td-band-row"),
        c("td-first", "첫째 열", "td-first"),
        c("td-last", "마지막 열", "td-last"),
        c("td-band-col", "줄무늬 열", "td-band-col"),
        c("td-filter", "필터 버튼", "td-filter"),
        c("rem-duplicates", "중복된 항목 제거", "td-remdup"),
        c("td-torange", "범위로 변환", "td-torange"),
        c("td-resize", "크기 조정 테이블", "td-resize"),
    ]},
    Tab { name: "협업", cmds: &[
        c("coauth-mode", "공동 편집 모드", "coauth-mode"),
        c("addcomment", "코멘트 추가", "co-addcomment"),
        c("co-delcomment", "메모 삭제", "co-delcomment"),
        c("co-showcomment", "댓글 표시", "co-showcomment"),
        c("co-chat", "채팅", "co-chat"),
        c("co-history", "버전 기록", "co-history"),
    ]},
    Tab { name: "보호", cmds: &[
        c("prot-encrypt", "암호화", "prot-encrypt"),
        x("통합 문서 보호", "protect-workbook"),
        c("prot-doc", "시트 보호", "protect-sheet"),
        x("보호 범위", "protect-range"),
        c("prot-sign", "디지털 서명 추가", "prot-sign"),
        c("cell-lock", "셀 잠금", "cell-lock"),
        c("prot-allow", "허용할 동작", "prot-allow"),
        c("recover", "복구", "recover"),
        c("recover-every", "사본 간격", "recover-every"),
        c("read-only-rec", "읽기 전용 권하기", "read-only-rec"),
    ]},
    Tab { name: "보기", cmds: &[
        c("sheet-view", "시트보기", "sheet-view"),
        x("일반", "view-normal"),
        x("페이지 나누기 미리보기", "view-pagebreak"),
        c("zoom-in", "확대", "zoom-in"),
        c("zoom-out", "축소", "zoom-out"),
        c("ui-bigger", "화면 글자 크게", "ui-bigger"),
        c("ui-smaller", "화면 글자 작게", "ui-smaller"),
        c("theme", "인터페이스 테마", "theme"),
        c("freeze", "창 고정", "freeze"),
        c("formula-bar", "수식 입력줄", "formula-bar"),
        c("show-gridlines", "눈금선", "show-gridlines"),
        c("show-headings", "제목", "show-headings"),
        c("show-zeros", "0 표시", "show-zeros"),
    ]},
    Tab { name: "플러그인", cmds: &[
        c("plug-macros", "매크로", "plug-macros"),
        c("plug-manage", "플러그인 관리", "plug-manage"),
    ]},
    Tab { name: "AI", cmds: &[
        c("ai-where", "대상", "ai-where"),
        c("ai-summary", "요약", "ai-summary"),
        c("ai-rewrite", "다시 쓰기", "ai-rewrite"),
        c("ai-polite", "정중하게", "ai-polite"),
        c("ai-plain", "쉽게", "ai-plain"),
        c("ai-translate", "번역", "ai-translate"),
        c("ai-furigana", "후리가나", "ai-furigana"),
        c("ai-continue", "이어 쓰기", "ai-continue"),
        c("ai-table", "표로 만들기", "ai-table"),
        c("ai-ask", "요청", "ai-ask"),
    ]},
];

