//! リボンの id 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py id > face/src/ribbon_id.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Buka", "open"),
        c("save", "Simpan", "save"),
        c("pdf", "Cetak", "print"),
    ]},
    Tab { name: "Halaman Depan", cmds: &[
        c("copy", "Salin", "copy"),
        c("cut", "Potong", "cut"),
        c("paste", "Tempel", "paste"),
        c("fontname", "Huruf", "fontname"),
        c("fontsize", "Ukuran Huruf", "fontsize"),
        c("incfont", "Perbesar Ukuran Huruf", "incfont"),
        c("decfont", "Perkecil Ukuran Huruf", "decfont"),
        c("changecase", "Ubah case", "changecase"),
        c("ruby", "Minta", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Tebal", "bold"),
        c("italic", "Miring", "italic"),
        c("underline", "Garis bawah", "underline"),
        c("strikeout", "Coret ganda", "strikeout"),
        c("superscript", "Superskrip", "superscript"),
        c("subscript", "Subskrip", "subscript"),
        c("highlight", "Warna Sorot", "highlight"),
        c("fontcolor", "Warna Huruf", "fontcolor"),
        c("clearstyle", "Hapus Model", "clearstyle"),
        c("markers", "Butir", "markers"),
        c("numbering", "Penomoran", "numbering"),
        c("multilevels", "Ikhtisar", "multilevels"),
        c("decoffset", "Kurangi Indentasi", "decoffset"),
        c("incoffset", "Tambahkan Indentasi", "incoffset"),
        c("linespace", "Spasi Antar Baris Paragraf", "linespace"),
        c("direction", "Ruby", "direction"),
        c("align-left", "Rata kiri", "align-left"),
        c("align-center", "Tengah", "align-center"),
        c("align-right", "Rata kanan", "align-right"),
        c("align-just", "Rata Kiri-Kanan", "align-just"),
        c("align-dist", "Arah teks", "align-dist"),
        c("hidenchars", "Karakter Tidak Dicetak", "hidenchars"),
        c("paracolor", "Bayangan", "paracolor"),
        c("borders", "Batas", "borders"),
        c("parastyle", "Gaya paragraf", "styles"),
        c("replace", "Ganti", "replace"),
        c("selectall", "Pilih semua", "select-all"),
    ]},
    Tab { name: "Sisipkan", cmds: &[
        c("blankpage", "Sisipkan halaman kosong", "blankpage"),
        c("pagebreak", "Jeda", "pagebreak"),
        c("instable", "Sisipkan Tabel", "instable"),
        c("insimage", "Sisipkan Gambar", "insertimage"),
        c("insshape", "Sisipkan Bentuk", "insshape"),
        c("inssmartart", "Sisipkan SmartArt", "inssmartart"),
        c("inschart", "Sisipkan Bagan", "inschart"),
        c("instext", "Sisipkan kotak teks", "instext"),
        c("instextart", "Sisipkan Text Art", "instextart"),
        c("dropcap", "Sisipkan Drop Cap", "dropcap"),
        c("text-from-file", "Teks dari Berkas", "text-from-file"),
        c("edit-header", "Sunting kepala", "edit-header"),
        c("edit-footer", "Sunting kaki", "edit-footer"),
        c("pagenum", "Nomor halaman", "pagenum"),
        c("datetime", "Tanggal & Waktu", "datetime"),
        c("numpages", "Jumlah halaman", "numpages"),
        c("insequation", "Masukkan Persamaan", "insequation"),
        c("inssymbol", "Sisipkan simbol", "inssymbol"),
        c("controls", "Sisipkan kontrol konten", "controls"),
    ]},
    Tab { name: "Gambar", cmds: &[
        c("pen", "Pena", "pen"),
        c("highlighter", "Penyorot", "highlighter"),
        c("eraser", "Penghapus", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margin", "pagemargins"),
        c("pageorient", "Orientasi", "pageorient"),
        c("pagesize", "Ukuran Halaman", "pagesize"),
        c("columns", "Sisipkan kolom", "columns"),
        c("line-numbers", "Tampilkan nomor garis", "line-numbers"),
        c("hyphenation", "Ubah tanda hubung", "hyphenation"),
        x("Majukan", "img-movefrwd"),
        x("Mundurkan", "img-movebkwd"),
        x("Perataan", "img-align"),
        x("Grup", "img-group"),
        x("Gabungkan bentuk", "shapes-merge"),
        c("watermark", "Edit watermark", "watermark"),
        c("pagecolor", "Ubah warna halaman", "pagecolor"),
        c("colorschemas", "Ubah Skema Warna", "colorschemas"),
    ]},
    Tab { name: "Referensi", cmds: &[
        c("toc", "Daftar Isi", "contents"),
        c("add-text", "Tambah Teks", "add-text"),
        c("toc-update", "Arah teks (kanan-ke-kiri)", "contents-update"),
        c("bookmarks", "Bookmark", "bookmarks"),
        c("caption", "Bersihkan filter", "caption"),
        c("crossref", "Cross-reference", "crossref"),
        c("footnote", "Footnote", "footnote"),
        c("tof", "Tulis makro", "tof"),
        c("tof-update", "Teks ke kolom", "tof-update"),
    ]},
    Tab { name: "Fomulir", cmds: &[
        c("form-text", "Ruas Teks", "form-text"),
        c("form-combo", "Kotak combo", "form-combo"),
        c("form-dropdown", "Dropdown", "form-dropdown"),
        c("form-checkbox", "Teks kanan-ke-kiri", "form-checkbox"),
        c("form-radio", "Tombol Radio", "form-radio"),
        c("form-image", "Gambar", "form-image"),
        c("form-email", "Alamat Email", "form-email"),
        c("form-phone", "Nomor Telepon", "form-phone"),
        c("form-complex", "Bidang Kompleks", "form-complex"),
        c("form-signature", "Tanda Tangan", "form-signature"),
        c("form-name", "Nama", "form-name"),
    ]},
    Tab { name: "Kolaborasi", cmds: &[
        c("coauth-mode", "Kotak centang", "coauth-mode"),
        c("co-addcomment", "Tambahkan komentar", "co-addcomment"),
        c("co-delcomment", "Jendela pantauan", "co-delcomment"),
        c("co-showcomment", "Tampilkan komentar", "co-showcomment"),
        c("co-chat", "Grafik yang disarankan", "co-chat"),
        c("track-changes", "Lacak perubahan", "track-changes"),
        c("co-history", "Tautan eksternal", "co-history"),
    ]},
    Tab { name: "Proteksi", cmds: &[
        c("prot-sign", "Riwayat versi", "prot-sign"),
        c("prot-doc", "Proteksi", "prot-doc"),
    ]},
    Tab { name: "Lihat", cmds: &[
        t("nav", "Navigasi", "nav"),
        c("fit-page", "Sesuaikan Halaman", "fit-page"),
        c("fit-width", "Sesuaikan Lebar", "fit-width"),
        c("zoom100", "Tambahkan tanda tangan digital", "zoom100"),
        c("zoom-in", "Perbesar", "zoom-in"),
        c("zoom-out", "Perkecil", "zoom-out"),
        c("printview", "Tata letak cetak", "printview"),
        c("multipage", "Gandakan halaman", "multipage"),
        t("darkmode", "Mode gelap", "darkmode"),
        c("ui-bigger", "Perbesar teks layar", "ui-bigger"),
        c("ui-smaller", "Perkecil teks layar", "ui-smaller"),
        c("ruler", "Penggaris", "ruler"),
        t("show-toolbar", "Selalu Tampilkan Bilah Alat", "show-toolbar"),
        t("show-statusbar", "Bar Status", "show-statusbar"),
        t("show-left", "Panel Kiri", "show-left"),
        t("show-right", "Panel Kanan", "show-right"),
    ]},
    Tab { name: "Makro", cmds: &[
        c("py-list", "Kunci sel", "plug-manage"),
        c("py-folder", "Tambah rentang", "py-folder"),
        c("ai-macro", "Hapus panah", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Buka", "open"),
        c("save", "Simpan", "save"),
        c("pdf", "Cetak", "print"),
    ]},
    Tab { name: "Halaman Depan", cmds: &[
        c("copy", "Salin", "copy"),
        c("cut", "Potong", "cut"),
        c("paste", "Tempel", "paste"),
        c("copystyle", "Salin format", "copystyle"),
        c("fontname", "Huruf", "fontname"),
        c("fontsize", "Ukuran Huruf", "fontsize"),
        c("incfont", "Perbesar Ukuran Huruf", "incfont"),
        c("decfont", "Perkecil Ukuran Huruf", "decfont"),
        c("changecase", "Ubah case", "changecase"),
        c("bold", "Tebal", "bold"),
        c("italic", "Miring", "italic"),
        c("underline", "Garis bawah", "underline"),
        c("strikeout", "Coret ganda", "strikeout"),
        c("subscript", "Subskrip", "subscript"),
        c("fontcolor", "Warna Huruf", "fontcolor"),
        c("fillparag", "Isi warna", "fillparag"),
        c("borders", "Batas", "borders"),
        c("top", "Rata atas", "top"),
        c("middle", "Rata di tengah", "middle"),
        c("bottom", "Rata bawah", "bottom"),
        c("wrap", "Isi menurut contoh", "wrap"),
        c("text-orient", "Arah teks", "text-orient"),
        c("align-left", "Rata kiri", "align-left"),
        c("align-center", "Tengah", "align-center"),
        c("align-right", "Rata kanan", "align-right"),
        c("align-just", "Rata Kiri-Kanan", "align-just"),
        c("align-dist", "Arah teks", "align-dist"),
        c("merge", "Merge dan center", "merge"),
        c("direction", "Perbarui daftar gambar", "direction"),
        c("sum", "Zoom ke 100%", "autosum"),
        c("fill-num", "Solver", "fill-num"),
        c("defname", "Pengaturan Nama", "named-range"),
        c("clear", "Hapus", "clear"),
        c("sort-desc", "Sortasi turun", "sortdesc"),
        c("sort-asc", "Sortasi naik", "sortasc"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Teks ke data", "clear-filter"),
        c("format", "Format nomor", "format"),
        c("currency", "Gaya mata uang", "currency"),
        c("percents", "Gaya persen", "percents"),
        c("comma", "Gaya koma", "comma"),
        c("digit-dec", "Kurangi desimal", "digit-dec"),
        c("digit-inc", "Tambah desimal", "digit-inc"),
        c("cell-ins", "Sisipkan sel", "cell-ins"),
        c("cell-del", "Hapus Sel", "cell-del"),
        c("cell-format", "Format sel", "cell-format"),
        c("condformat", "Format bersyarat", "condformat"),
        c("table-tpl", "Format sebagai template tabel", "table-tpl"),
        c("cell-styles", "Gaya Sel", "styles"),
        c("replace", "Ganti", "replace"),
        c("selectall", "Pilih semua", "select-all"),
    ]},
    Tab { name: "Sisipkan", cmds: &[
        c("pivot-insert", "Sisipkan Tabel Pivot", "add-pivot"),
        c("instable", "Sisipkan Tabel", "instable"),
        c("insimage", "Sisipkan Gambar", "insimage-c"),
        c("insshape", "Sisipkan Bentuk", "insshape"),
        c("inssmartart", "Sisipkan SmartArt", "inssmartart"),
        c("inscheckbox", "Teks kanan-ke-kiri", "inscheckbox"),
        c("insrecommend", "Sisipkan bagan yang disarankan", "insrecommend"),
        c("inschart", "Sisipkan Bagan", "inschart"),
        c("inssparkline", "Sisipkan sparkline", "inssparkline"),
        c("co-addcomment", "Komentar", "ins-comment"),
        c("inshyperlink", "Tambahkan hyperlink", "inshyperlink"),
        c("insslicer", "Sisipkan Slicer", "insslicer"),
        c("instext", "Sisipkan kotak teks", "instext"),
        c("instextart", "Sisipkan Text Art", "instextart"),
        c("edit-header", "Header & Footer", "editheader"),
        c("insequation", "Masukkan Persamaan", "insequation"),
        c("inssymbol", "Sisipkan simbol", "inssymbol"),
    ]},
    Tab { name: "Gambar", cmds: &[
        c("draw-select", "Pilih", "select-tool"),
        c("pen", "Pena", "pen"),
        c("highlighter", "Penyorot", "highlighter"),
        c("eraser", "Penghapus", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margin", "pagemargins"),
        c("pageorient", "Orientasi", "pageorient"),
        c("pagesize", "Ukuran Halaman", "pagesize"),
        c("printarea", "Print Area", "printarea"),
        c("pagebreak", "Jeda", "pagebreak"),
        c("edit-header", "Header & Footer", "editheader"),
        c("scale", "Skala ke Fit", "scale"),
        c("fit-pages", "Selang salinan", "fit-pages"),
        c("printarea-add", "Bungkus teks", "printarea-add"),
        c("show-breaks", ".py baru", "show-breaks"),
        c("printtitles", "Print judul", "printtitles"),
        c("rtl-sheet", "Ubah arah lembar agar kolom pertama di kanan", "rtl-sheet"),
        c("print-gridlines", "Tampilkan rumus", "print-gridlines"),
        c("print-headings", "Cetak garis kisi", "print-headings"),
        x("Majukan", "img-movefrwd"),
        x("Mundurkan", "img-movebkwd"),
        x("Perataan", "img-align"),
        x("Grup", "img-group"),
        x("Gabungkan bentuk", "shapes-merge"),
        c("colorschemas", "Ubah Skema Warna", "colorschemas"),
    ]},
    Tab { name: "Formula", cmds: &[
        c("insert-function", "Sisipkan fungsi", "additional-formula"),
        c("func-list", "Fungsi Python", "py-list"),
        c("sum", "Zoom ke 100%", "autosum"),
        c("fn-recent", "Tautan eksternal (impor sebagai nilai)", "recent"),
        c("fn-financial", "Finansial", "financial"),
        c("fn-logical", "Logikal", "logical"),
        c("fn-text", "Teks", "text"),
        c("fn-datetime", "Tanggal & Waktu", "datetime"),
        c("fn-lookup", "Lookup dan referensi", "lookup"),
        c("fn-math", "Matematika & Trigonometri", "math"),
        c("fn-more", "Lebih banyak fungsi", "more"),
        c("defname", "Pengaturan Nama", "named-range-huge"),
        c("paste-name", "Tabel data", "paste-name"),
        c("trace-prec", "Preseden Jejak", "trace-prec"),
        c("trace-dep", "Dependen Jejak", "trace-dep"),
        c("remove-arrows", "Hapus komentar", "remove-arrows"),
        c("show-formulas", "Daftar gambar", "show-formulas"),
        c("watch", "Tampilkan nol", "watch-window"),
        c("calc-mode", "Salah konversi", "calculate"),
    ]},
    Tab { name: "Data", cmds: &[
        c("data-from-text", "Rekam tindakan", "data-from-text"),
        c("data-external-links", "Keterangan", "data-external-links"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Teks ke data", "clear-filter"),
        c("sort-desc", "Sortasi turun", "sortdesc"),
        c("sort-asc", "Sortasi naik", "sortasc"),
        c("custom-sort", "Sortasi", "custom-sort"),
        c("text-column", "Isi", "text-column"),
        c("rem-duplicates", "Kolom berpita", "rem-duplicates"),
        c("data-validation", "Validasi data", "data-validation"),
        t("dv-mark", "Lingkari data tidak valid", "dv-mark"),
        c("goal-seek", "Pencarian Tujuan", "goal-seek"),
        c("scenario", "Skenario", "scenario"),
        c("forecast", "Lembar ramalan", "forecast"),
        c("solver", "JumlahOtomatis", "solver"),
        c("group", "Grup", "group"),
        c("ungroup", "Pisahkan dari grup", "ungroup"),
        c("show-details", "Tampilkan Detail", "show-details"),
        c("hide-details", "Perbarui daftar isi", "hide-details"),
        c("subtotal", "Subtotals", "subtotal"),
        c("datatable", "Sisipkan fungsi", "datatable"),
        c("python", "Kalkulasi", "python"),
        c("csv-kind", "Sembunyikan rincian", "csv-kind"),
        c("flash-fill", "Format CSV", "flash-fill"),
    ]},
    Tab { name: "Makro", cmds: &[
        c("rec-toggle", "Tema antarmuka", "py-run"),
        c("py-new", "Tempel nama", "py-new"),
        c("py-list", "Kunci sel", "py-list"),
        c("ribbon-list", "Makro pita", "py-line"),
        c("py-folder", "Tambah rentang", "py-folder"),
    ]},
    Tab { name: "Tabel Pivot", cmds: &[
        c("pivot-insert", "Sisipkan Tabel Pivot", "pivot-insert"),
        c("pivot-fields", "Daftar bidang", "pivot-fields"),
        c("pivot-refresh", "Refresh", "pivot-refresh"),
        c("pivot-refresh-all", "Segarkan Semuanya", "pivot-refresh-all"),
        c("pivot-source", "Sumber data", "pivot-source"),
        c("pivot-chart", "PivotChart", "pivot-chart"),
        c("pivot-select", "Pilih", "pivot-select"),
        c("pivot-totals", "Grand Total", "pivot-totals"),
        c("pivot-subtotals", "Subtotals", "pivot-subtotals"),
        c("pivot-blank", "Baris Kosong", "pivot-blank"),
        c("pivot-showas", "Muatkan ke kertas", "pivot-showas"),
        c("pivot-layout", "Layout Laporan", "pivot-layout"),
        c("pivot-style", "Gaya", "pivot-style"),
    ]},
    Tab { name: "Desain tabel", cmds: &[
        c("td-header", "Baris header", "td-header"),
        c("td-total", "Baris total", "td-total"),
        c("td-band-row", "Baris Berpita", "td-band-row"),
        c("td-first", "Kolom pertama", "td-first"),
        c("td-last", "Kolom terakhir", "td-last"),
        c("td-band-col", "Baru digunakan", "td-band-col"),
        c("td-filter", "Tombol filter", "td-filter"),
        c("rem-duplicates", "Hapus duplikat", "td-remdup"),
        c("td-torange", "Konversi ke rentang", "td-torange"),
        c("td-resize", "Ubah ukuran tabel", "td-resize"),
    ]},
    Tab { name: "Kolaborasi", cmds: &[
        c("coauth-mode", "Kotak centang", "coauth-mode"),
        c("co-addcomment", "Tambahkan komentar", "co-addcomment"),
        c("co-delcomment", "Jendela pantauan", "co-delcomment"),
        c("co-showcomment", "Tampilkan komentar", "co-showcomment"),
        c("co-chat", "Grafik yang disarankan", "co-chat"),
        c("co-history", "Tautan eksternal", "co-history"),
    ]},
    Tab { name: "Proteksi", cmds: &[
        c("prot-encrypt", "Mode pengeditan bersama", "prot-encrypt"),
        xt("Proteksi workbook", "protect-workbook"),
        c("prot-doc", "Proteksi Sheet", "protect-sheet"),
        xt("Proteksi Rentang", "protect-range"),
        c("prot-sign", "Riwayat versi", "prot-sign"),
        c("cell-lock", "Hapus duplikat", "cell-lock"),
        c("prot-allow", "Batas kertas", "prot-allow"),
        c("recover", "Pemulihan", "recover"),
        c("recover-every", "Daftar", "recover-every"),
        c("read-only-rec", "Sarankan hanya-baca", "read-only-rec"),
    ]},
    Tab { name: "Lihat", cmds: &[
        c("sheet-view", "Tampilan sheet", "sheet-view"),
        xm("Normal", "view-normal"),
        xm("Pratinjau Jeda Halaman", "view-pagebreak"),
        c("zoom-in", "Perbesar", "zoom-in"),
        c("zoom-out", "Perkecil", "zoom-out"),
        c("zoom100", "Tambahkan tanda tangan digital", "zoom100"),
        c("ui-bigger", "Perbesar teks layar", "ui-bigger"),
        c("ui-smaller", "Perkecil teks layar", "ui-smaller"),
        t("darkmode", "Mode gelap", "theme"),
        c("freeze", "Freeze Panes", "freeze"),
        t("split", "Belah jendela", "split"),
        t("formula-bar", "Bar formula", "formula-bar"),
        c("show-gridlines", "Garis Grid", "show-gridlines"),
        t("show-headings", "Tajuk", "show-headings"),
        t("show-zeros", "Enkripsi", "show-zeros"),
        t("show-left", "Panel Kiri", "show-left"),
        t("show-right", "Panel Kanan", "show-right"),
    ]},
];

