//! リボンの pt の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py pt > face/src/ribbon_pt.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Adicionar comentário"),
    ("Add Text", "Adicionar texto"),
    ("Add digital signature", "Adicionar assinatura digital"),
    ("Add link", "Adicionar hiperligação"),
    ("Add to area", "Acrescentar intervalo"),
    ("Align bottom", "Alinhar em baixo"),
    ("Align left", "Alinhar à esquerda"),
    ("Align middle", "Alinhar ao meio"),
    ("Align right", "Alinhar à direita"),
    ("Align top", "Alinhar em cima"),
    ("Alignment", "Alinhamento"),
    ("Allowed actions", "Operações permitidas"),
    ("Always Show Toolbar", "Mostrar sempre a barra de ferramentas"),
    ("AutoSum", "Soma automática"),
    ("Backup interval", "Intervalo das cópias"),
    ("Banded Rows", "Linhas em bandas"),
    ("Banded columns", "Colunas às riscas"),
    ("Bigger UI text", "Aumentar o texto do ecrã"),
    ("Blank Rows", "Linha vazias"),
    ("Bold", "Negrito"),
    ("Bookmark", "Marcador"),
    ("Borders", "Bordas"),
    ("Breaks", "Quebras"),
    ("Bring forward", "Trazer para a frente"),
    ("Bullet", "Marcador"),
    ("CSV format", "Formato CSV"),
    ("Calculation options", "Método de cálculo"),
    ("Caption", "Legenda"),
    ("Cell Style", "Estilo da célula"),
    ("Cell lock", "Bloquear célula"),
    ("Centre", "Centro"),
    ("Change case", "Alternar maiúscula/minúscula"),
    ("Change colour theme", "Alterar esquema de cor"),
    ("Change hyphenation", "Alterar a hifenização"),
    ("Change page colour", "Alterar a cor da página"),
    ("Chat", "Conversa"),
    ("Checkbox", "Caixa de verificação"),
    ("Circle invalid data", "Circundar dados inválidos"),
    ("Clear", "Limpar"),
    ("Clear filter", "Limpar filtro"),
    ("Clear style", "Limpar estilo"),
    ("Co-editing mode", "Modo de coedição"),
    ("Collaboration", "Colaboração"),
    ("Combo box", "Caixa de combinação"),
    ("Comma style", "Estilo de vírgula"),
    ("Comment", "Comentários"),
    ("Complex Field", "Campo complexo"),
    ("Conditional formatting", "Formatação condicional"),
    ("Convert to range", "Converter em intervalo"),
    ("Copy", "Copiar"),
    ("Cross-reference", "Referência-cruzada"),
    ("Currency style", "Estilo da moeda"),
    ("Cut", "Cortar"),
    ("Dark mode", "Modo escuro"),
    ("Data", "Dados"),
    ("Data Validation", "Validação dos dados"),
    ("Data source", "Fonte de dados"),
    ("Data table", "Tabela de dados"),
    ("Date & Time", "Data e hora"),
    ("Decrease decimal", "Diminuir casas decimais"),
    ("Decrease indent", "Diminuir o Recuo"),
    ("Decrement font size", "Diminuir tamanho do tipo de letra"),
    ("Delete cells", "Eliminar células"),
    ("Delete comment", "Eliminar comentário"),
    ("Distributed", "Distribuído"),
    ("Draw", "Desenhar"),
    ("Dropdown", "Suspenso"),
    ("Edit footer", "Editar rodapé"),
    ("Edit header", "Editar cabeçalho"),
    ("Edit watermark", "Editar marca d'água"),
    ("Email Address", "Endereço de e-mail"),
    ("Encrypt", "Encriptar"),
    ("Eraser", "Borracha"),
    ("External links (import as values)", "Ligações externas (importar como valores)"),
    ("Field list", "Lista de campos"),
    ("File", "Ficheiro"),
    ("Fill", "Preencher"),
    ("Fill by example", "Preencher pelo exemplo"),
    ("Fill colour", "Cor de preenchimento"),
    ("Filter button", "Botão de filtro"),
    ("Filters", "Filtros"),
    ("Financial", "Financeiras"),
    ("First column", "Primeira coluna"),
    ("Fit to page", "Ajustar à página"),
    ("Fit to paper", "Ajustar ao papel"),
    ("Fit to width", "Ajustar à Largura"),
    ("Font", "Tipo de letra"),
    ("Font colour", "Cor do tipo de letra"),
    ("Font size", "Tamanho do tipo de letra"),
    ("Footnote", "Nota de rodapé"),
    ("Forecast Sheet", "Folha de previsão"),
    ("Format as table template", "Formatar como modelo de tabela"),
    ("Format cells", "Formatar células"),
    ("Format painter", "Copiar formato"),
    ("Forms", "Formulários"),
    ("Formula", "Fórmula"),
    ("Formula Bar", "Barra de fórmulas"),
    ("Freeze panes", "Fixar painéis"),
    ("Goal Seek", "Atingir objetivo"),
    ("Grand Total", "Totais Gerais"),
    ("Group", "Grupo"),
    ("Header & Footer", "Cabeçalho/rodapé"),
    ("Header row", "Linha de cabeçalho"),
    ("Headings", "Títulos"),
    ("Hide detail", "Ocultar detalhes"),
    ("Highlight colour", "Cor de destaque"),
    ("Highlighter", "Marcador"),
    ("Home", "Base"),
    ("Increase decimal", "Aumentar números decimais"),
    ("Increase indent", "Aumentar recuo"),
    ("Increment font size", "Aumentar tamanho do tipo de letra"),
    ("Insert", "Inserir"),
    ("Insert Pivot Table", "Inserir tabela dinâmica"),
    ("Insert SmartArt", "Inserir SmartArt"),
    ("Insert Text Art", "Inserir arte de texto"),
    ("Insert blank page", "Inserir página vazia"),
    ("Insert cells", "Inserir células"),
    ("Insert chart", "Inserir gráfico"),
    ("Insert column", "Inserir coluna"),
    ("Insert content controls", "Adicionar controlos de conteúdo"),
    ("Insert drop cap", "Inserir letra capitular"),
    ("Insert equation", "Inserir equação"),
    ("Insert function", "Inserir função"),
    ("Insert image", "Inserir imagem"),
    ("Insert recommended chart", "Inserir gráfico recomendado"),
    ("Insert shape", "Inserir forma"),
    ("Insert slicer", "Inserir segmentação de dados"),
    ("Insert sparkline", "Inserir sparkline"),
    ("Insert symbol", "Inserir símbolo"),
    ("Insert table", "Inserir tabela"),
    ("Insert text box", "Inserir caixa de texto"),
    ("Italic", "Itálico"),
    ("Justified", "Justificado"),
    ("Last column", "Última coluna"),
    ("Layout", "Disposição"),
    ("Left Panel", "Painel esquerdo"),
    ("Lookup & Reference", "Procura e referência"),
    ("Macro list", "Lista"),
    ("Margins", "Margens"),
    ("Math & Trig", "Matemática e trigonometria"),
    ("Merge and centre", "Unir e centrar"),
    ("Merge shapes", "Unir formas"),
    ("More functions", "Mais funções"),
    ("Multilevel list", "Lista multi-níveis"),
    ("Multiple pages", "Várias páginas"),
    ("Name", "Nome"),
    ("Name manager", "Manager"),
    ("Navigation", "Navegação"),
    ("New .py", "Novo .py"),
    ("Nonprinting characters", "Caracteres não imprimíveis"),
    ("Number format", "Formato de número"),
    ("Number of pages", "Número de páginas"),
    ("Numbering", "Numeração"),
    ("Open", "Abrir"),
    ("Open folder", "Abrir a pasta"),
    ("Page Break Preview", "Pré-visualização da quebra de página"),
    ("Page breaks", "Quebras de página"),
    ("Page number", "Número de página"),
    ("Page orientation", "Orientação da página"),
    ("Page size", "Tamanho da página"),
    ("Paragraph line spacing", "Espaçamento entre linhas do parágrafo"),
    ("Paragraph style", "Estilo do parágrafo"),
    ("Paste", "Colar"),
    ("Paste name", "Colar nome"),
    ("Pen", "Caneta"),
    ("Percent style", "Estilo de percentagem"),
    ("Phone Number", "Número de telefone"),
    ("Picture", "Imagem"),
    ("Pivot Table", "Tabela dinâmica"),
    ("PivotChart", "Gráfico dinâmico"),
    ("Print", "Imprimir"),
    ("Print Area", "Área de impressão"),
    ("Print gridlines", "Imprimir também as linhas de grelha"),
    ("Print headings", "Imprimir também os cabeçalhos"),
    ("Print titles", "Imprimir títulos"),
    ("Protect Range", "Proteger intervalo"),
    ("Protect sheet", "Proteger folha"),
    ("Protect workbook", "Proteger livro"),
    ("Protection", "Proteção"),
    ("Python functions", "Funções Python"),
    ("Radio Button", "Botão Seleção"),
    ("Recently used", "Funções recentes"),
    ("Record actions", "Gravar ações"),
    ("Recover", "Recuperar"),
    ("References", "Referências"),
    ("Remove Duplicates", "Remover duplicados"),
    ("Remove arrows", "Remover setas"),
    ("Remove duplicates", "Remover duplicados"),
    ("Replace", "Substituir"),
    ("Report Layout", "Disposição do relatório"),
    ("Resize table", "Redimensionar tabela"),
    ("Ribbon macros", "Macros do friso"),
    ("Right Panel", "Painel direito"),
    ("Right-to-left text", "Direção do texto (da direita para a esquerda)"),
    ("Rulers", "Réguas"),
    ("Save", "Guardar"),
    ("Scale To Fit", "Ajustar Tamanho"),
    ("Scenario", "Cenário"),
    ("Select", "Selecionar"),
    ("Select all", "Selecionar tudo"),
    ("Send Backward", "Enviar para trás"),
    ("Shading", "Cor de fundo do parágrafo"),
    ("Sheet View", "Vista de folha"),
    ("Show comments", "Mostrar Comentário"),
    ("Show details", "Exibir detalhes"),
    ("Show formulas", "Mostrar fórmulas"),
    ("Show line numbers", "Mostrar número das linhas"),
    ("Show values as", "Mostrar os valores como"),
    ("Show zeros", "Mostrar zeros"),
    ("Signature", "Assinatura"),
    ("Smaller UI text", "Diminuir o texto do ecrã"),
    ("Sort", "Classificar"),
    ("Sort ascending", "Classificar do menor para o maior"),
    ("Sort descending", "Classificar do maior para o menor"),
    ("Split", "Dividir janela"),
    ("Status Bar", "Barra de estado"),
    ("Strikethrough", "Rasurado"),
    ("Style", "Estilo"),
    ("Subscript", "Subscrito"),
    ("Subtotals", "Subtotais"),
    ("Suggest read-only", "Sugerir só leitura"),
    ("Superscript", "Sobrescrito"),
    ("Switch the sheet direction so that the first column is on the right side", "Inverta a direção da folha para que a primeira coluna fique do lado direito"),
    ("Table Design", "Estrutura da Tabela"),
    ("Table of contents", "Índice remissivo"),
    ("Table of figures", "Índice de ilustrações"),
    ("Text Field", "Campo de texto"),
    ("Text direction", "Direção do texto"),
    ("Text from File", "Texto de um ficheiro"),
    ("Text functions", "Texto"),
    ("Text orientation", "Orientação do texto"),
    ("Text to columns", "Texto para colunas"),
    ("Text to data", "Dados a partir de texto"),
    ("Total row", "Linha de totais"),
    ("Trace Dependents", "Rastrear Dependentes"),
    ("Trace Precedents", "Rastrear Precedentes"),
    ("Track changes", "Rastrear alterações"),
    ("Underline", "Sublinhado"),
    ("Ungroup", "Desagrupar"),
    ("Update", "Recarregar"),
    ("Update all", "Recarregar tudo"),
    ("Update table of contents", "Atualizar o índice"),
    ("Update table of figures", "Atualizar o índice de ilustrações"),
    ("Version history", "Histórico de versões"),
    ("View", "Mostrar"),
    ("Watch window", "Janela de inspeção"),
    ("Wrap text", "Moldar o texto"),
    ("Write macro", "Escrever macro"),
    ("Zoom in", "Ampliar"),
    ("Zoom out", "Reduzir"),
    ("Zoom to 100%", "Ampliar para 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

