//! リボンの pt-br 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py pt-br > face/src/ribbon_pt-br.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Arquivo", cmds: &[
        c("open", "Abrir", "open"),
        c("save", "Salvar", "save"),
        c("pdf", "Imprimir", "print"),
    ]},
    Tab { name: "Página Inicial", cmds: &[
        c("copy", "Copiar", "copy"),
        c("cut", "Cortar", "cut"),
        c("paste", "Colar", "paste"),
        c("fontname", "Fonte", "fontname"),
        c("fontsize", "Tamanho da fonte", "fontsize"),
        c("incfont", "Aumentar tamanho da fonte", "incfont"),
        c("decfont", "Diminuir tamanho da fonte", "decfont"),
        c("changecase", "Mudar maiúsculas e minúsculas", "changecase"),
        c("ruby", "Pedir", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Negrito", "bold"),
        c("italic", "Itálico", "italic"),
        c("underline", "Sublinhado", "underline"),
        c("strikeout", "Tachado", "strikeout"),
        c("superscript", "Sobrescrito", "superscript"),
        c("subscript", "Subscrito", "subscript"),
        c("highlight", "Cor de realce", "highlight"),
        c("fontcolor", "Cor da fonte", "fontcolor"),
        c("clearstyle", "Limpar estilo", "clearstyle"),
        c("markers", "Marcador", "markers"),
        c("numbering", "Numeração", "numbering"),
        c("multilevels", "Contorno", "multilevels"),
        c("decoffset", "Diminuir o Recuo", "decoffset"),
        c("incoffset", "Aumentar recuo", "incoffset"),
        c("linespace", "Espaçamento entre linhas do parágrafo", "linespace"),
        c("direction", "Ruby", "direction"),
        c("align-left", "Alinhar à esquerda", "align-left"),
        c("align-center", "Centro", "align-center"),
        c("align-right", "Alinhar à direita", "align-right"),
        c("align-just", "Justificado", "align-just"),
        c("align-dist", "Direção do texto", "align-dist"),
        c("hidenchars", "Caracteres não imprimíveis", "hidenchars"),
        c("paracolor", "Cor do plano de fundo do parágrafo", "paracolor"),
        c("borders", "Bordas", "borders"),
        c("parastyle", "Estilo do parágrafo", "styles"),
        c("replace", "Substituir", "replace"),
        c("selectall", "Selecionar todos", "select-all"),
    ]},
    Tab { name: "Inserir", cmds: &[
        c("blankpage", "Inserir página em branco", "blankpage"),
        c("pagebreak", "Quebras", "pagebreak"),
        c("instable", "Inserir tabela", "instable"),
        c("insimage", "Inserir imagem", "insertimage"),
        c("insshape", "Inserir Forma", "insshape"),
        c("inssmartart", "Inserir SmartArt", "inssmartart"),
        c("inschart", "Inserir gráfico", "inschart"),
        c("instext", "Inserir caixa de texto", "instext"),
        c("instextart", "Inserir arte de texto", "instextart"),
        c("dropcap", "Inserir letra capitular", "dropcap"),
        c("text-from-file", "Texto do arquivo", "text-from-file"),
        c("edit-header", "Editar cabeçalho", "edit-header"),
        c("edit-footer", "Editar rodapé", "edit-footer"),
        c("pagenum", "Número da página", "pagenum"),
        c("datetime", "Data e hora", "datetime"),
        c("numpages", "Número de páginas", "numpages"),
        c("insequation", "Inserir equação", "insequation"),
        c("inssymbol", "Inserir símbolo", "inssymbol"),
        c("controls", "Adicionar controles de conteúdo", "controls"),
    ]},
    Tab { name: "Desenhar", cmds: &[
        c("pen", "Caneta", "pen"),
        c("highlighter", "Marcador", "highlighter"),
        c("eraser", "Apagador", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margens", "pagemargins"),
        c("pageorient", "Orientação da página", "pageorient"),
        c("pagesize", "Tamanho da página", "pagesize"),
        c("columns", "Inserir coluna", "columns"),
        c("line-numbers", "Mostrar números de linha", "line-numbers"),
        c("hyphenation", "Alterar hifenização", "hyphenation"),
        x("Trazer para frente", "img-movefrwd"),
        x("Enviar para trás", "img-movebkwd"),
        x("Alinhamento", "img-align"),
        x("Grupo", "img-group"),
        x("Mesclar formas", "shapes-merge"),
        c("watermark", "Editar marca d'água", "watermark"),
        c("pagecolor", "Alterar a cor da página", "pagecolor"),
        c("colorschemas", "Alterar esquema de cor", "colorschemas"),
    ]},
    Tab { name: "Referências", cmds: &[
        c("toc", "Tabela de Conteúdo", "contents"),
        c("add-text", "Adicionar Texto", "add-text"),
        c("toc-update", "Direção do texto (direita para a esquerda)", "contents-update"),
        c("bookmarks", "Favoritos", "bookmarks"),
        c("caption", "Limpar filtro", "caption"),
        c("crossref", "Referência cruzada", "crossref"),
        c("footnote", "Nota de rodapé", "footnote"),
        c("tof", "Escrever macro", "tof"),
        c("tof-update", "Texto para colunas", "tof-update"),
    ]},
    Tab { name: "Formulários", cmds: &[
        c("form-text", "Campo de texto", "form-text"),
        c("form-combo", "Caixa de combinação", "form-combo"),
        c("form-dropdown", "Suspenso", "form-dropdown"),
        c("form-checkbox", "Texto da direita para a esquerda", "form-checkbox"),
        c("form-radio", "Botao de radio", "form-radio"),
        c("form-image", "Imagem", "form-image"),
        c("form-email", "Endereço de e-mail", "form-email"),
        c("form-phone", "Número de telefone", "form-phone"),
        c("form-complex", "Campo complexo", "form-complex"),
        c("form-signature", "Assinatura", "form-signature"),
        c("form-name", "Nome", "form-name"),
    ]},
    Tab { name: "Colaboração", cmds: &[
        c("coauth-mode", "Caixa de seleção", "coauth-mode"),
        c("co-addcomment", "Adicionar comentário", "co-addcomment"),
        c("co-delcomment", "Janela de Inspeção", "co-delcomment"),
        c("co-showcomment", "Mostrar comentários", "co-showcomment"),
        c("co-chat", "Gráfico recomendado", "co-chat"),
        c("track-changes", "Rastrear alterações", "track-changes"),
        c("co-history", "Links externos", "co-history"),
    ]},
    Tab { name: "Proteção", cmds: &[
        c("prot-sign", "Histórico de versões", "prot-sign"),
        c("prot-doc", "Proteção", "prot-doc"),
    ]},
    Tab { name: "Exibir", cmds: &[
        t("nav", "Navegação", "nav"),
        c("fit-page", "Ajustar a página", "fit-page"),
        c("fit-width", "Ajustar largura", "fit-width"),
        c("zoom100", "Adicionar assinatura digital", "zoom100"),
        c("zoom-in", "Ampliar", "zoom-in"),
        c("zoom-out", "Reduzir", "zoom-out"),
        c("printview", "Layout de impressão", "printview"),
        c("multipage", "Múltiplas páginas", "multipage"),
        t("darkmode", "Modo escuro", "darkmode"),
        c("ui-bigger", "Aumentar texto da tela", "ui-bigger"),
        c("ui-smaller", "Diminuir texto da tela", "ui-smaller"),
        c("ruler", "Regras", "ruler"),
        t("show-toolbar", "Sempre mostrar a barra de ferramentas", "show-toolbar"),
        t("show-statusbar", "Barra de status", "show-statusbar"),
        t("show-left", "Painel esquerdo", "show-left"),
        t("show-right", "Painel direito", "show-right"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("py-list", "Bloquear célula", "plug-manage"),
        c("py-folder", "Acrescentar intervalo", "py-folder"),
        c("ai-macro", "Remover setas", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Arquivo", cmds: &[
        c("open", "Abrir", "open"),
        c("save", "Salvar", "save"),
        c("pdf", "Imprimir", "print"),
    ]},
    Tab { name: "Página Inicial", cmds: &[
        c("copy", "Copiar", "copy"),
        c("cut", "Cortar", "cut"),
        c("paste", "Colar", "paste"),
        c("copystyle", "Copiar formato", "copystyle"),
        c("fontname", "Fonte", "fontname"),
        c("fontsize", "Tamanho da fonte", "fontsize"),
        c("incfont", "Aumentar tamanho da fonte", "incfont"),
        c("decfont", "Diminuir tamanho da fonte", "decfont"),
        c("changecase", "Mudar maiúsculas e minúsculas", "changecase"),
        c("bold", "Negrito", "bold"),
        c("italic", "Itálico", "italic"),
        c("underline", "Sublinhado", "underline"),
        c("strikeout", "Tachado", "strikeout"),
        c("subscript", "Subscrito", "subscript"),
        c("fontcolor", "Cor da fonte", "fontcolor"),
        c("fillparag", "Cor de preenchimento", "fillparag"),
        c("borders", "Bordas", "borders"),
        c("top", "Alinhar à parte superior", "top"),
        c("middle", "Alinhar ao meio", "middle"),
        c("bottom", "Alinhar à parte inferior", "bottom"),
        c("wrap", "Preencher pelo exemplo", "wrap"),
        c("text-orient", "Orientação do texto", "text-orient"),
        c("align-left", "Alinhar à esquerda", "align-left"),
        c("align-center", "Centro", "align-center"),
        c("align-right", "Alinhar à direita", "align-right"),
        c("align-just", "Justificado", "align-just"),
        c("align-dist", "Direção do texto", "align-dist"),
        c("merge", "Mesclar e centralizar", "merge"),
        c("direction", "Atualizar índice de ilustrações", "direction"),
        c("sum", "Zoom de 100%", "autosum"),
        c("fill-num", "Solver", "fill-num"),
        c("defname", "Gerenciador de nomes", "named-range"),
        c("clear", "Limpar", "clear"),
        c("sort-desc", "Classificar do maior para o menor", "sortdesc"),
        c("sort-asc", "Classificar do menor para o maior", "sortasc"),
        c("setfilter", "Filtros", "setfilter"),
        c("clear-filter", "Texto para dados", "clear-filter"),
        c("format", "Formato Numérico", "format"),
        c("currency", "Estilo da moeda", "currency"),
        c("percents", "Estilo de Porcentagem", "percents"),
        c("comma", "Estilo vírgula", "comma"),
        c("digit-dec", "Diminuir casas decimais", "digit-dec"),
        c("digit-inc", "Aumentar números decimais", "digit-inc"),
        c("cell-ins", "Inserir células", "cell-ins"),
        c("cell-del", "Excluir células", "cell-del"),
        c("cell-format", "Formatar celulas", "cell-format"),
        c("condformat", "Formatação condicional", "condformat"),
        c("table-tpl", "Formato como Modelo de tabela", "table-tpl"),
        c("cell-styles", "Estilo da célula", "styles"),
        c("replace", "Substituir", "replace"),
        c("selectall", "Selecionar todos", "select-all"),
    ]},
    Tab { name: "Inserir", cmds: &[
        c("pivot-insert", "Inserir tabela dinâmica", "add-pivot"),
        c("instable", "Inserir tabela", "instable"),
        c("insimage", "Inserir imagem", "insimage-c"),
        c("insshape", "Inserir Forma", "insshape"),
        c("inssmartart", "Inserir SmartArt", "inssmartart"),
        c("inscheckbox", "Texto da direita para a esquerda", "inscheckbox"),
        c("insrecommend", "Inserir gráfico recomendado", "insrecommend"),
        c("inschart", "Inserir gráfico", "inschart"),
        c("inssparkline", "Inserir sparkline", "inssparkline"),
        c("co-addcomment", "Comentários", "ins-comment"),
        c("inshyperlink", "Adicionar Link", "inshyperlink"),
        c("insslicer", "Inserir Segmentação de Dados", "insslicer"),
        c("instext", "Inserir caixa de texto", "instext"),
        c("instextart", "Inserir arte de texto", "instextart"),
        c("edit-header", "Cabeçalho/rodapé", "editheader"),
        c("insequation", "Inserir equação", "insequation"),
        c("inssymbol", "Inserir símbolo", "inssymbol"),
    ]},
    Tab { name: "Desenhar", cmds: &[
        c("draw-select", "Selecionar", "select-tool"),
        c("pen", "Caneta", "pen"),
        c("highlighter", "Marcador", "highlighter"),
        c("eraser", "Apagador", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margens", "pagemargins"),
        c("pageorient", "Orientação da página", "pageorient"),
        c("pagesize", "Tamanho da página", "pagesize"),
        c("printarea", "Área de impressão", "printarea"),
        c("pagebreak", "Quebras", "pagebreak"),
        c("edit-header", "Cabeçalho/rodapé", "editheader"),
        c("scale", "Dimensionar", "scale"),
        c("fit-pages", "Intervalo das cópias", "fit-pages"),
        c("printarea-add", "Moldar texto", "printarea-add"),
        c("show-breaks", "Novo .py", "show-breaks"),
        c("printtitles", "Imprimir títulos", "printtitles"),
        c("rtl-sheet", "Altere a direção da folha de modo que a primeira coluna fique no lado direito", "rtl-sheet"),
        c("print-gridlines", "Mostrar fórmulas", "print-gridlines"),
        c("print-headings", "Imprimir linhas de grade", "print-headings"),
        x("Trazer para frente", "img-movefrwd"),
        x("Enviar para trás", "img-movebkwd"),
        x("Alinhamento", "img-align"),
        x("Grupo", "img-group"),
        x("Mesclar formas", "shapes-merge"),
        c("colorschemas", "Alterar esquema de cor", "colorschemas"),
    ]},
    Tab { name: "Fórmula", cmds: &[
        c("insert-function", "Inserir função", "additional-formula"),
        c("func-list", "Funções Python", "py-list"),
        c("sum", "Zoom de 100%", "autosum"),
        c("fn-recent", "Links externos (importar como valores)", "recent"),
        c("fn-financial", "Financeiro", "financial"),
        c("fn-logical", "Lógico", "logical"),
        c("fn-text", "Texto", "text"),
        c("fn-datetime", "Data e hora", "datetime"),
        c("fn-lookup", "Pesquisa e Referência", "lookup"),
        c("fn-math", "Matemática e trigonometria", "math"),
        c("fn-more", "Mais funções", "more"),
        c("defname", "Gerenciador de nomes", "named-range-huge"),
        c("paste-name", "Tabela de dados", "paste-name"),
        c("trace-prec", "Rastrear precedentes", "trace-prec"),
        c("trace-dep", "Rastrear Dependentes", "trace-dep"),
        c("remove-arrows", "Excluir comentário", "remove-arrows"),
        c("show-formulas", "Índice de ilustrações", "show-formulas"),
        c("watch", "Mostrar zeros", "watch-window"),
        c("calc-mode", "Conversão errada", "calculate"),
    ]},
    Tab { name: "Dados", cmds: &[
        c("data-from-text", "Gravar ações", "data-from-text"),
        c("data-external-links", "Legenda", "data-external-links"),
        c("setfilter", "Filtros", "setfilter"),
        c("clear-filter", "Texto para dados", "clear-filter"),
        c("sort-desc", "Classificar do maior para o menor", "sortdesc"),
        c("sort-asc", "Classificar do menor para o maior", "sortasc"),
        c("custom-sort", "Classificar", "custom-sort"),
        c("text-column", "Preencher", "text-column"),
        c("rem-duplicates", "Colunas em tiras", "rem-duplicates"),
        c("data-validation", "Validação de dados", "data-validation"),
        t("dv-mark", "Circular dados inválidos", "dv-mark"),
        c("goal-seek", "Busca de meta", "goal-seek"),
        c("scenario", "Cenário", "scenario"),
        c("forecast", "Planilha de previsão", "forecast"),
        c("solver", "AutoSoma", "solver"),
        c("group", "Grupo", "group"),
        c("ungroup", "Desagrupar", "ungroup"),
        c("show-details", "Exibir detalhes", "show-details"),
        c("hide-details", "Atualizar sumário", "hide-details"),
        c("subtotal", "Subtotais", "subtotal"),
        c("datatable", "Inserir função", "datatable"),
        c("python", "Cálculo", "python"),
        c("csv-kind", "Ocultar detalhes", "csv-kind"),
        c("flash-fill", "Formato CSV", "flash-fill"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("rec-toggle", "Tema da interface", "py-run"),
        c("py-new", "Colar nome", "py-new"),
        c("py-list", "Bloquear célula", "py-list"),
        c("ribbon-list", "Macros da faixa", "py-line"),
        c("py-folder", "Acrescentar intervalo", "py-folder"),
    ]},
    Tab { name: "Tabela Dinâmica", cmds: &[
        c("pivot-insert", "Inserir tabela dinâmica", "pivot-insert"),
        c("pivot-fields", "Lista de campos", "pivot-fields"),
        c("pivot-refresh", "Atualizar", "pivot-refresh"),
        c("pivot-refresh-all", "Atualize tudo", "pivot-refresh-all"),
        c("pivot-source", "Fonte de dados", "pivot-source"),
        c("pivot-chart", "Gráfico dinâmico", "pivot-chart"),
        c("pivot-select", "Selecionar", "pivot-select"),
        c("pivot-totals", "Total geral", "pivot-totals"),
        c("pivot-subtotals", "Subtotais", "pivot-subtotals"),
        c("pivot-blank", "Linhas em branco", "pivot-blank"),
        c("pivot-showas", "Ajustar ao papel", "pivot-showas"),
        c("pivot-layout", "Layout do Relatório", "pivot-layout"),
        c("pivot-style", "Estilo", "pivot-style"),
    ]},
    Tab { name: "Design da Tabela", cmds: &[
        c("td-header", "Linha de Cabeçalho", "td-header"),
        c("td-total", "Linha de Totais", "td-total"),
        c("td-band-row", "Linhas em faixas", "td-band-row"),
        c("td-first", "Primeira coluna", "td-first"),
        c("td-last", "Última coluna", "td-last"),
        c("td-band-col", "Usadas recentemente", "td-band-col"),
        c("td-filter", "Botão de filtro", "td-filter"),
        c("rem-duplicates", "Remover Duplicatas", "td-remdup"),
        c("td-torange", "Converter para intervalo", "td-torange"),
        c("td-resize", "Redimensionar tabela", "td-resize"),
    ]},
    Tab { name: "Colaboração", cmds: &[
        c("coauth-mode", "Caixa de seleção", "coauth-mode"),
        c("co-addcomment", "Adicionar comentário", "co-addcomment"),
        c("co-delcomment", "Janela de Inspeção", "co-delcomment"),
        c("co-showcomment", "Mostrar comentários", "co-showcomment"),
        c("co-chat", "Gráfico recomendado", "co-chat"),
        c("co-history", "Links externos", "co-history"),
    ]},
    Tab { name: "Proteção", cmds: &[
        c("prot-encrypt", "Modo de coedição", "prot-encrypt"),
        xt("Proteger a pasta de trabalho", "protect-workbook"),
        c("prot-doc", "Proteger folha", "protect-sheet"),
        xt("Proteger Intervalo", "protect-range"),
        c("prot-sign", "Histórico de versões", "prot-sign"),
        c("cell-lock", "Remover duplicatas", "cell-lock"),
        c("prot-allow", "Quebras de página", "prot-allow"),
        c("recover", "Recuperar", "recover"),
        c("recover-every", "Lista", "recover-every"),
        c("read-only-rec", "Sugerir somente leitura", "read-only-rec"),
    ]},
    Tab { name: "Exibir", cmds: &[
        c("sheet-view", "Visualização de folha", "sheet-view"),
        xm("Normal", "view-normal"),
        xm("Visualização de quebra de página", "view-pagebreak"),
        c("zoom-in", "Ampliar", "zoom-in"),
        c("zoom-out", "Reduzir", "zoom-out"),
        c("zoom100", "Adicionar assinatura digital", "zoom100"),
        c("ui-bigger", "Aumentar texto da tela", "ui-bigger"),
        c("ui-smaller", "Diminuir texto da tela", "ui-smaller"),
        t("darkmode", "Modo escuro", "theme"),
        c("freeze", "Congelar painéis", "freeze"),
        t("split", "Dividir janela", "split"),
        t("formula-bar", "Barra de fórmula", "formula-bar"),
        c("show-gridlines", "Gridlines", "show-gridlines"),
        t("show-headings", "Títulos", "show-headings"),
        t("show-zeros", "Criptografar", "show-zeros"),
        t("show-left", "Painel esquerdo", "show-left"),
        t("show-right", "Painel direito", "show-right"),
    ]},
];

