//! リボンの en 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py en > face/src/ribbon_en.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Open", "open"),
        c("save", "Save", "save"),
        c("pdf", "Print", "print"),
    ]},
    Tab { name: "Home", cmds: &[
        c("copy", "Copy", "copy"),
        c("cut", "Cut", "cut"),
        c("paste", "Paste", "paste"),
        c("fontname", "Font", "fontname"),
        c("fontsize", "Font size", "fontsize"),
        c("incfont", "Increment font size", "incfont"),
        c("decfont", "Decrement font size", "decfont"),
        c("changecase", "Change case", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Bold", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Underline", "underline"),
        c("strikeout", "Strikethrough", "strikeout"),
        c("superscript", "Superscript", "superscript"),
        c("subscript", "Subscript", "subscript"),
        c("highlight", "Highlight colour", "highlight"),
        c("fontcolor", "Font colour", "fontcolor"),
        c("clearstyle", "Clear style", "clearstyle"),
        c("markers", "Bullet", "markers"),
        c("numbering", "Numbering", "numbering"),
        c("multilevels", "Multilevel list", "multilevels"),
        c("decoffset", "Decrease indent", "decoffset"),
        c("incoffset", "Increase indent", "incoffset"),
        c("linespace", "Paragraph line spacing", "linespace"),
        c("direction", "Text direction", "direction"),
        c("align-left", "Align left", "align-left"),
        c("align-center", "Centre", "align-center"),
        c("align-right", "Align right", "align-right"),
        c("align-just", "Justified", "align-just"),
        c("align-dist", "Distributed", "align-dist"),
        c("hidenchars", "Nonprinting characters", "hidenchars"),
        c("paracolor", "Shading", "paracolor"),
        c("borders", "Borders", "borders"),
        c("parastyle", "Paragraph style", "styles"),
        c("replace", "Replace", "replace"),
        c("selectall", "Select all", "select-all"),
    ]},
    Tab { name: "Insert", cmds: &[
        c("blankpage", "Insert blank page", "blankpage"),
        c("pagebreak", "Breaks", "pagebreak"),
        c("instable", "Insert table", "instable"),
        c("insimage", "Insert image", "insertimage"),
        c("insshape", "Insert shape", "insshape"),
        c("inssmartart", "Insert SmartArt", "inssmartart"),
        c("inschart", "Insert chart", "inschart"),
        c("instext", "Insert text box", "instext"),
        c("instextart", "Insert Text Art", "instextart"),
        c("dropcap", "Insert drop cap", "dropcap"),
        c("text-from-file", "Text from File", "text-from-file"),
        c("edit-header", "Edit header", "edit-header"),
        c("edit-footer", "Edit footer", "edit-footer"),
        c("pagenum", "Page number", "pagenum"),
        c("datetime", "Date & Time", "datetime"),
        c("numpages", "Number of pages", "numpages"),
        c("insequation", "Insert equation", "insequation"),
        c("inssymbol", "Insert symbol", "inssymbol"),
        c("controls", "Insert content controls", "controls"),
    ]},
    Tab { name: "Draw", cmds: &[
        c("pen", "Pen", "pen"),
        c("highlighter", "Highlighter", "highlighter"),
        c("eraser", "Eraser", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margins", "pagemargins"),
        c("pageorient", "Page orientation", "pageorient"),
        c("pagesize", "Page size", "pagesize"),
        c("columns", "Insert column", "columns"),
        c("line-numbers", "Show line numbers", "line-numbers"),
        c("hyphenation", "Change hyphenation", "hyphenation"),
        c("img-movefrwd", "Bring forward", "img-movefrwd"),
        c("img-movebkwd", "Send Backward", "img-movebkwd"),
        c("img-align", "Alignment", "img-align"),
        c("img-group", "Group", "img-group"),
        x("Merge shapes", "shapes-merge"),
        c("watermark", "Edit watermark", "watermark"),
        c("pagecolor", "Change page colour", "pagecolor"),
        c("colorschemas", "Change colour theme", "colorschemas"),
    ]},
    Tab { name: "References", cmds: &[
        c("toc", "Table of contents", "contents"),
        c("add-text", "Add Text", "add-text"),
        c("toc-update", "Update table of contents", "contents-update"),
        c("bookmarks", "Bookmark", "bookmarks"),
        c("caption", "Caption", "caption"),
        c("crossref", "Cross-reference", "crossref"),
        c("footnote", "Footnote", "footnote"),
        c("tof", "Table of figures", "tof"),
        c("tof-update", "Update table of figures", "tof-update"),
    ]},
    Tab { name: "Forms", cmds: &[
        c("form-text", "Text Field", "form-text"),
        c("form-combo", "Combo box", "form-combo"),
        c("form-dropdown", "Dropdown", "form-dropdown"),
        c("form-checkbox", "Checkbox", "form-checkbox"),
        c("form-radio", "Radio Button", "form-radio"),
        c("form-image", "Picture", "form-image"),
        c("form-email", "Email Address", "form-email"),
        c("form-phone", "Phone Number", "form-phone"),
        c("form-complex", "Complex Field", "form-complex"),
        c("form-signature", "Signature", "form-signature"),
        c("form-name", "Name", "form-name"),
    ]},
    Tab { name: "Collaboration", cmds: &[
        c("coauth-mode", "Co-editing mode", "coauth-mode"),
        c("co-addcomment", "Add Comment", "co-addcomment"),
        c("co-delcomment", "Delete comment", "co-delcomment"),
        c("co-showcomment", "Show comments", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("track-changes", "Track changes", "track-changes"),
        c("co-history", "Version history", "co-history"),
    ]},
    Tab { name: "Protection", cmds: &[
        c("prot-sign", "Add digital signature", "prot-sign"),
        c("prot-doc", "Protection", "prot-doc"),
    ]},
    Tab { name: "View", cmds: &[
        t("nav", "Navigation", "nav"),
        c("fit-page", "Fit to page", "fit-page"),
        c("fit-width", "Fit to width", "fit-width"),
        c("zoom100", "Zoom to 100%", "zoom100"),
        c("zoom-in", "Zoom in", "zoom-in"),
        c("zoom-out", "Zoom out", "zoom-out"),
        c("printview", "Print layout", "printview"),
        c("multipage", "Multiple pages", "multipage"),
        t("darkmode", "Dark mode", "darkmode"),
        c("ui-bigger", "Bigger UI text", "ui-bigger"),
        c("ui-smaller", "Smaller UI text", "ui-smaller"),
        c("ruler", "Rulers", "ruler"),
        t("show-toolbar", "Always Show Toolbar", "show-toolbar"),
        t("show-statusbar", "Status Bar", "show-statusbar"),
        t("show-left", "Left Panel", "show-left"),
        t("show-right", "Right Panel", "show-right"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("py-list", "Macro list", "plug-manage"),
        c("py-folder", "Open folder", "py-folder"),
        c("ai-macro", "Write macro", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Open", "open"),
        c("save", "Save", "save"),
        c("pdf", "Print", "print"),
    ]},
    Tab { name: "Home", cmds: &[
        c("copy", "Copy", "copy"),
        c("cut", "Cut", "cut"),
        c("paste", "Paste", "paste"),
        c("copystyle", "Format painter", "copystyle"),
        c("fontname", "Font", "fontname"),
        c("fontsize", "Font size", "fontsize"),
        c("incfont", "Increment font size", "incfont"),
        c("decfont", "Decrement font size", "decfont"),
        c("changecase", "Change case", "changecase"),
        c("bold", "Bold", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Underline", "underline"),
        c("strikeout", "Strikethrough", "strikeout"),
        c("subscript", "Subscript", "subscript"),
        c("fontcolor", "Font colour", "fontcolor"),
        c("fillparag", "Fill colour", "fillparag"),
        c("borders", "Borders", "borders"),
        c("top", "Align top", "top"),
        c("middle", "Align middle", "middle"),
        c("bottom", "Align bottom", "bottom"),
        c("wrap", "Wrap text", "wrap"),
        c("text-orient", "Text orientation", "text-orient"),
        c("align-left", "Align left", "align-left"),
        c("align-center", "Centre", "align-center"),
        c("align-right", "Align right", "align-right"),
        c("align-just", "Justified", "align-just"),
        c("align-dist", "Distributed", "align-dist"),
        c("merge", "Merge and centre", "merge"),
        c("direction", "Right-to-left text", "direction"),
        c("sum", "AutoSum", "autosum"),
        c("fill-num", "Fill", "fill-num"),
        c("defname", "Name manager", "named-range"),
        c("clear", "Clear", "clear"),
        c("sort-desc", "Sort descending", "sortdesc"),
        c("sort-asc", "Sort ascending", "sortasc"),
        c("setfilter", "Filters", "setfilter"),
        c("clear-filter", "Clear filter", "clear-filter"),
        c("format", "Number format", "format"),
        c("currency", "Currency style", "currency"),
        c("percents", "Percent style", "percents"),
        c("comma", "Comma style", "comma"),
        c("digit-dec", "Decrease decimal", "digit-dec"),
        c("digit-inc", "Increase decimal", "digit-inc"),
        c("cell-ins", "Insert cells", "cell-ins"),
        c("cell-del", "Delete cells", "cell-del"),
        c("cell-format", "Format cells", "cell-format"),
        c("condformat", "Conditional formatting", "condformat"),
        c("table-tpl", "Format as table template", "table-tpl"),
        c("cell-styles", "Cell Style", "styles"),
        c("replace", "Replace", "replace"),
        c("selectall", "Select all", "select-all"),
    ]},
    Tab { name: "Insert", cmds: &[
        c("pivot-insert", "Insert Pivot Table", "add-pivot"),
        c("instable", "Insert table", "instable"),
        c("insimage", "Insert image", "insimage-c"),
        c("insshape", "Insert shape", "insshape"),
        c("inssmartart", "Insert SmartArt", "inssmartart"),
        c("inscheckbox", "Checkbox", "inscheckbox"),
        c("insrecommend", "Insert recommended chart", "insrecommend"),
        c("inschart", "Insert chart", "inschart"),
        c("inssparkline", "Insert sparkline", "inssparkline"),
        c("co-addcomment", "Comment", "ins-comment"),
        c("inshyperlink", "Add link", "inshyperlink"),
        c("insslicer", "Insert slicer", "insslicer"),
        c("instext", "Insert text box", "instext"),
        c("instextart", "Insert Text Art", "instextart"),
        c("edit-header", "Header & Footer", "editheader"),
        c("insequation", "Insert equation", "insequation"),
        c("inssymbol", "Insert symbol", "inssymbol"),
    ]},
    Tab { name: "Draw", cmds: &[
        c("draw-select", "Select", "select-tool"),
        c("pen", "Pen", "pen"),
        c("highlighter", "Highlighter", "highlighter"),
        c("eraser", "Eraser", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Margins", "pagemargins"),
        c("pageorient", "Page orientation", "pageorient"),
        c("pagesize", "Page size", "pagesize"),
        c("printarea", "Print Area", "printarea"),
        c("pagebreak", "Breaks", "pagebreak"),
        c("edit-header", "Header & Footer", "editheader"),
        c("scale", "Scale To Fit", "scale"),
        c("fit-pages", "Fit to paper", "fit-pages"),
        c("printarea-add", "Add to area", "printarea-add"),
        c("show-breaks", "Page breaks", "show-breaks"),
        c("printtitles", "Print titles", "printtitles"),
        c("rtl-sheet", "Switch the sheet direction so that the first column is on the right side", "rtl-sheet"),
        c("print-gridlines", "Print gridlines", "print-gridlines"),
        c("print-headings", "Print headings", "print-headings"),
        c("img-movefrwd", "Bring forward", "img-movefrwd"),
        c("img-movebkwd", "Send Backward", "img-movebkwd"),
        c("img-align", "Alignment", "img-align"),
        c("img-group", "Group", "img-group"),
        c("shapes-merge", "Merge shapes", "shapes-merge"),
        c("colorschemas", "Change colour theme", "colorschemas"),
    ]},
    Tab { name: "Formula", cmds: &[
        c("insert-function", "Insert function", "additional-formula"),
        c("func-list", "Python functions", "py-list"),
        c("sum", "AutoSum", "autosum"),
        c("fn-recent", "Recently used", "recent"),
        c("fn-financial", "Financial", "financial"),
        c("fn-logical", "Logical", "logical"),
        c("fn-text", "Text functions", "text"),
        c("fn-datetime", "Date & Time", "datetime"),
        c("fn-lookup", "Lookup & Reference", "lookup"),
        c("fn-math", "Math & Trig", "math"),
        c("fn-more", "More functions", "more"),
        c("defname", "Name manager", "named-range-huge"),
        c("paste-name", "Paste name", "paste-name"),
        c("trace-prec", "Trace Precedents", "trace-prec"),
        c("trace-dep", "Trace Dependents", "trace-dep"),
        c("remove-arrows", "Remove arrows", "remove-arrows"),
        c("show-formulas", "Show formulas", "show-formulas"),
        c("watch", "Watch window", "watch-window"),
        c("calc-mode", "Calculation options", "calculate"),
    ]},
    Tab { name: "Data", cmds: &[
        c("data-from-text", "Text to data", "data-from-text"),
        c("data-external-links", "External links (import as values)", "data-external-links"),
        c("setfilter", "Filters", "setfilter"),
        c("clear-filter", "Clear filter", "clear-filter"),
        c("sort-desc", "Sort descending", "sortdesc"),
        c("sort-asc", "Sort ascending", "sortasc"),
        c("custom-sort", "Sort", "custom-sort"),
        c("text-column", "Text to columns", "text-column"),
        c("rem-duplicates", "Remove duplicates", "rem-duplicates"),
        c("data-validation", "Data Validation", "data-validation"),
        t("dv-mark", "Circle invalid data", "dv-mark"),
        c("goal-seek", "Goal Seek", "goal-seek"),
        c("scenario", "Scenario", "scenario"),
        c("forecast", "Forecast Sheet", "forecast"),
        c("solver", "Solver", "solver"),
        c("group", "Group", "group"),
        c("ungroup", "Ungroup", "ungroup"),
        c("show-details", "Show details", "show-details"),
        c("hide-details", "Hide detail", "hide-details"),
        c("subtotal", "Subtotals", "subtotal"),
        c("datatable", "Data table", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "CSV format", "csv-kind"),
        c("flash-fill", "Fill by example", "flash-fill"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("rec-toggle", "Record actions", "py-run"),
        c("py-new", "New .py", "py-new"),
        c("py-list", "Macro list", "py-list"),
        c("ribbon-list", "Ribbon macros", "py-line"),
        c("py-folder", "Open folder", "py-folder"),
    ]},
    Tab { name: "Pivot Table", cmds: &[
        c("pivot-insert", "Insert Pivot Table", "pivot-insert"),
        c("pivot-fields", "Field list", "pivot-fields"),
        c("pivot-refresh", "Update", "pivot-refresh"),
        c("pivot-refresh-all", "Update all", "pivot-refresh-all"),
        c("pivot-source", "Data source", "pivot-source"),
        c("pivot-chart", "PivotChart", "pivot-chart"),
        c("pivot-select", "Select", "pivot-select"),
        c("pivot-totals", "Grand Total", "pivot-totals"),
        c("pivot-subtotals", "Subtotals", "pivot-subtotals"),
        c("pivot-blank", "Blank Rows", "pivot-blank"),
        c("pivot-showas", "Show values as", "pivot-showas"),
        c("pivot-layout", "Report Layout", "pivot-layout"),
        c("pivot-style", "Style", "pivot-style"),
    ]},
    Tab { name: "Table Design", cmds: &[
        c("td-header", "Header row", "td-header"),
        c("td-total", "Total row", "td-total"),
        c("td-band-row", "Banded Rows", "td-band-row"),
        c("td-first", "First column", "td-first"),
        c("td-last", "Last column", "td-last"),
        c("td-band-col", "Banded columns", "td-band-col"),
        c("td-filter", "Filter button", "td-filter"),
        c("rem-duplicates", "Remove Duplicates", "td-remdup"),
        c("td-torange", "Convert to range", "td-torange"),
        c("td-resize", "Resize table", "td-resize"),
    ]},
    Tab { name: "Collaboration", cmds: &[
        c("coauth-mode", "Co-editing mode", "coauth-mode"),
        c("co-addcomment", "Add Comment", "co-addcomment"),
        c("co-delcomment", "Delete comment", "co-delcomment"),
        c("co-showcomment", "Show comments", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("co-history", "Version history", "co-history"),
    ]},
    Tab { name: "Protection", cmds: &[
        c("prot-encrypt", "Encrypt", "prot-encrypt"),
        c("prot-book", "Protect workbook", "protect-workbook"),
        c("prot-doc", "Protect sheet", "protect-sheet"),
        xt("Protect Range", "protect-range"),
        c("prot-sign", "Add digital signature", "prot-sign"),
        c("cell-lock", "Cell lock", "cell-lock"),
        c("prot-allow", "Allowed actions", "prot-allow"),
        c("recover", "Recover", "recover"),
        c("recover-every", "Backup interval", "recover-every"),
        c("read-only-rec", "Suggest read-only", "read-only-rec"),
    ]},
    Tab { name: "View", cmds: &[
        c("sheet-view", "Sheet View", "sheet-view"),
        xm("Normal", "view-normal"),
        xm("Page Break Preview", "view-pagebreak"),
        c("zoom-in", "Zoom in", "zoom-in"),
        c("zoom-out", "Zoom out", "zoom-out"),
        c("zoom100", "Zoom to 100%", "zoom100"),
        c("ui-bigger", "Bigger UI text", "ui-bigger"),
        c("ui-smaller", "Smaller UI text", "ui-smaller"),
        t("darkmode", "Dark mode", "theme"),
        c("freeze", "Freeze panes", "freeze"),
        t("split", "Split", "split"),
        t("formula-bar", "Formula Bar", "formula-bar"),
        c("show-gridlines", "Gridlines", "show-gridlines"),
        t("show-headings", "Headings", "show-headings"),
        t("show-zeros", "Show zeros", "show-zeros"),
        t("show-left", "Left Panel", "show-left"),
        t("show-right", "Right Panel", "show-right"),
    ]},
];

