//! リボンの es 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py es > face/src/ribbon_es.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Archivo", cmds: &[
        c("open", "Abrir", "open"),
        c("save", "Guardar", "save"),
        c("pdf", "Imprimir", "print"),
    ]},
    Tab { name: "Inicio", cmds: &[
        c("copy", "Copiar ", "copy"),
        c("cut", "Cortar", "cut"),
        c("paste", "Pegar", "paste"),
        c("fontname", "Fuente", "fontname"),
        c("fontsize", "Tamaño de la fuente", "fontsize"),
        c("incfont", "Aumentar tamaño de letra", "incfont"),
        c("decfont", "Reducir tamaño de letra", "decfont"),
        c("changecase", "Cambiar mayúsculas y minúsculas", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Negrita", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Subrayar", "underline"),
        c("strikeout", "Tachado", "strikeout"),
        c("superscript", "Sobreíndice", "superscript"),
        c("subscript", "Subíndice", "subscript"),
        c("highlight", "Color de resaltado", "highlight"),
        c("fontcolor", "Color de la fuente", "fontcolor"),
        c("clearstyle", "Eliminar estilo", "clearstyle"),
        c("markers", "Viñeta", "markers"),
        c("numbering", "Numeración", "numbering"),
        c("multilevels", "Esquema", "multilevels"),
        c("decoffset", "Reducir sangría", "decoffset"),
        c("incoffset", "Aumentar sangría", "incoffset"),
        c("linespace", "Espaciado de línea de párrafo", "linespace"),
        c("direction", "Dirección del texto", "direction"),
        c("align-left", "Alinear a la izquierda", "align-left"),
        c("align-center", "Alinear al centro", "align-center"),
        c("align-right", "Alinear a la derecha", "align-right"),
        c("align-just", "Alineado", "align-just"),
        c("align-dist", "Distribuido", "align-dist"),
        c("hidenchars", "Caracteres no imprimibles", "hidenchars"),
        c("paracolor", "Sombreado", "paracolor"),
        c("borders", "Bordes", "borders"),
        c("parastyle", "Estilo de párrafo", "styles"),
        c("replace", "Reemplazar", "replace"),
        c("selectall", "Seleccionar todo", "select-all"),
    ]},
    Tab { name: "Insertar", cmds: &[
        c("blankpage", "Insertar página en blanco", "blankpage"),
        c("pagebreak", "Saltos", "pagebreak"),
        c("instable", "Insertar tabla", "instable"),
        c("insimage", "Insertar imagen", "insertimage"),
        c("insshape", "Insertar forma", "insshape"),
        c("inssmartart", "Insertar SmartArt", "inssmartart"),
        c("inschart", "Insertar gráfico", "inschart"),
        c("instext", "Insertar cuadro de texto", "instext"),
        c("instextart", "Insertar Galería de Texto", "instextart"),
        c("dropcap", "Insertar letra capitular", "dropcap"),
        c("text-from-file", "Texto de archivo", "text-from-file"),
        c("edit-header", "Editar encabezado", "edit-header"),
        c("edit-footer", "Editar pie de página", "edit-footer"),
        c("pagenum", "Numeración de páginas", "pagenum"),
        c("datetime", "Fecha y hora", "datetime"),
        c("numpages", "Número de páginas", "numpages"),
        c("insequation", "Insertar ecuación", "insequation"),
        c("inssymbol", "Insertar symboló", "inssymbol"),
        c("controls", "Insertar controles de contenido", "controls"),
    ]},
    Tab { name: "Dibujar", cmds: &[
        c("pen", "Bolígrafo", "pen"),
        c("highlighter", "Marcador de resaltado", "highlighter"),
        c("eraser", "Borrador", "eraser"),
    ]},
    Tab { name: "Diseño", cmds: &[
        c("pagemargins", "Márgenes", "pagemargins"),
        c("pageorient", "Orientación", "pageorient"),
        c("pagesize", "Tamaño de la página", "pagesize"),
        c("columns", "Insertar columna", "columns"),
        c("line-numbers", "Mostrar números de línea", "line-numbers"),
        c("hyphenation", "Cambiar guiones", "hyphenation"),
        x("Traer adelante", "img-movefrwd"),
        x("Enviar atrás", "img-movebkwd"),
        x("Alineación", "img-align"),
        x("Agrupar", "img-group"),
        x("Fusionar formas", "shapes-merge"),
        c("watermark", "Editar marca de agua", "watermark"),
        c("pagecolor", "Cambiar color de página", "pagecolor"),
        c("colorschemas", "Cambiar combinación de colores", "colorschemas"),
    ]},
    Tab { name: "Referencias", cmds: &[
        c("toc", "Tabla de contenidos", "contents"),
        c("add-text", "Añadir texto", "add-text"),
        c("toc-update", "Actualizar tabla de contenido", "contents-update"),
        c("bookmarks", "Marcador", "bookmarks"),
        c("caption", "Título", "caption"),
        c("crossref", "Referencia cruzada", "crossref"),
        c("footnote", "Nota a pie de página", "footnote"),
        c("tof", "Tabla de ilustraciones", "tof"),
        c("tof-update", "Actualizar tabla de ilustraciones", "tof-update"),
    ]},
    Tab { name: "Formularios", cmds: &[
        c("form-text", "Campo de texto", "form-text"),
        c("form-combo", "Cuadro combinado", "form-combo"),
        c("form-dropdown", "Desplegable", "form-dropdown"),
        c("form-checkbox", "Casilla", "form-checkbox"),
        c("form-radio", "Botón de opción", "form-radio"),
        c("form-image", "Imagen", "form-image"),
        c("form-email", "Dirección de correo electrónico", "form-email"),
        c("form-phone", "Número de teléfono", "form-phone"),
        c("form-complex", "Campo complejo", "form-complex"),
        c("form-signature", "Firma", "form-signature"),
        c("form-name", "Nombre", "form-name"),
    ]},
    Tab { name: "Colaboración", cmds: &[
        c("coauth-mode", "Modo de coedición", "coauth-mode"),
        c("co-addcomment", "Añadir comentario", "co-addcomment"),
        c("co-delcomment", "Eliminar comentario", "co-delcomment"),
        c("co-showcomment", "Mostrar comentarios", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("track-changes", "Rastrear cambios", "track-changes"),
        c("co-history", "Historial de versiones", "co-history"),
    ]},
    Tab { name: "Protección", cmds: &[
        c("prot-sign", "Agregar firma digital", "prot-sign"),
        c("prot-doc", "Protección", "prot-doc"),
    ]},
    Tab { name: "Mostrar", cmds: &[
        t("nav", "Navegación", "nav"),
        c("fit-page", "Ajustar a la página", "fit-page"),
        c("fit-width", "Ajustar al ancho", "fit-width"),
        c("zoom100", "Zoom al 100%", "zoom100"),
        c("zoom-in", "Acercar", "zoom-in"),
        c("zoom-out", "Alejar", "zoom-out"),
        c("printview", "Diseño de impresión", "printview"),
        c("multipage", "Múltiples páginas", "multipage"),
        t("darkmode", "Modo oscuro", "darkmode"),
        c("ui-bigger", "Agrandar texto de la pantalla", "ui-bigger"),
        c("ui-smaller", "Reducir texto de la pantalla", "ui-smaller"),
        c("ruler", "Reglas", "ruler"),
        t("show-toolbar", "Mostrar siempre la barra de herramientas", "show-toolbar"),
        t("show-statusbar", "Barra de estado", "show-statusbar"),
        t("show-left", "Panel izquierdo", "show-left"),
        t("show-right", "Panel derecho", "show-right"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("py-list", "Lista", "plug-manage"),
        c("py-folder", "Abrir carpeta", "py-folder"),
        c("ai-macro", "Escribir macro", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Archivo", cmds: &[
        c("open", "Abrir", "open"),
        c("save", "Guardar", "save"),
        c("pdf", "Imprimir", "print"),
    ]},
    Tab { name: "Inicio", cmds: &[
        c("copy", "Copiar ", "copy"),
        c("cut", "Cortar", "cut"),
        c("paste", "Pegar", "paste"),
        c("copystyle", "Copiar formato", "copystyle"),
        c("fontname", "Fuente", "fontname"),
        c("fontsize", "Tamaño de la fuente", "fontsize"),
        c("incfont", "Aumentar tamaño de letra", "incfont"),
        c("decfont", "Reducir tamaño de letra", "decfont"),
        c("changecase", "Cambiar mayúsculas y minúsculas", "changecase"),
        c("bold", "Negrita", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Subrayar", "underline"),
        c("strikeout", "Tachado", "strikeout"),
        c("subscript", "Subíndice", "subscript"),
        c("fontcolor", "Color de la fuente", "fontcolor"),
        c("fillparag", "Color de relleno", "fillparag"),
        c("borders", "Bordes", "borders"),
        c("top", "Alinear hacia arriba", "top"),
        c("middle", "Alinear al medio", "middle"),
        c("bottom", "Alinear hacia abajo", "bottom"),
        c("wrap", "Ajustar texto", "wrap"),
        c("text-orient", "Orientación", "text-orient"),
        c("align-left", "Alinear a la izquierda", "align-left"),
        c("align-center", "Alinear al centro", "align-center"),
        c("align-right", "Alinear a la derecha", "align-right"),
        c("align-just", "Alineado", "align-just"),
        c("align-dist", "Distribuido", "align-dist"),
        c("merge", "Combinar y centrar", "merge"),
        c("direction", "Texto de derecha a izquierda", "direction"),
        c("sum", "Autosuma", "autosum"),
        c("fill-num", "Rellenar", "fill-num"),
        c("defname", "Administrador de nombres", "named-range"),
        c("clear", "Limpiar", "clear"),
        c("sort-desc", "Clasificar en orden descendente", "sortdesc"),
        c("sort-asc", "Clasificar en orden ascendente", "sortasc"),
        c("setfilter", "Filtros", "setfilter"),
        c("clear-filter", "Borrar filtro", "clear-filter"),
        c("format", "Formato de número", "format"),
        c("currency", "Estilo de moneda", "currency"),
        c("percents", "Estilo de porcentajes", "percents"),
        c("comma", "Estilo de coma", "comma"),
        c("digit-dec", "Disminuir decimales", "digit-dec"),
        c("digit-inc", "Aumentar decimales", "digit-inc"),
        c("cell-ins", "Insertar celdas", "cell-ins"),
        c("cell-del", "Eliminar celdas", "cell-del"),
        c("cell-format", "Dar formato a celdas", "cell-format"),
        c("condformat", "Formato condicional", "condformat"),
        c("table-tpl", "Formatear como plantilla de tabla", "table-tpl"),
        c("cell-styles", "Estilo de celda", "styles"),
        c("replace", "Reemplazar", "replace"),
        c("selectall", "Seleccionar todo", "select-all"),
    ]},
    Tab { name: "Insertar", cmds: &[
        c("pivot-insert", "Insertar tabla dinámica", "add-pivot"),
        c("instable", "Insertar tabla", "instable"),
        c("insimage", "Insertar imagen", "insimage-c"),
        c("insshape", "Insertar forma", "insshape"),
        c("inssmartart", "Insertar SmartArt", "inssmartart"),
        c("inscheckbox", "Casilla", "inscheckbox"),
        c("insrecommend", "Insertar gráfico recomendado", "insrecommend"),
        c("inschart", "Insertar gráfico", "inschart"),
        c("inssparkline", "Insertar minigráfico", "inssparkline"),
        c("co-addcomment", "Comentario", "ins-comment"),
        c("inshyperlink", "Añadir enlace ", "inshyperlink"),
        c("insslicer", "Insertar segmentación de datos", "insslicer"),
        c("instext", "Insertar cuadro de texto", "instext"),
        c("instextart", "Insertar Galería de Texto", "instextart"),
        c("edit-header", "Encabezado/Pie de página", "editheader"),
        c("insequation", "Insertar ecuación", "insequation"),
        c("inssymbol", "Insertar symboló", "inssymbol"),
    ]},
    Tab { name: "Dibujar", cmds: &[
        c("draw-select", "Seleccionar", "select-tool"),
        c("pen", "Bolígrafo", "pen"),
        c("highlighter", "Marcador de resaltado", "highlighter"),
        c("eraser", "Borrador", "eraser"),
    ]},
    Tab { name: "Diseño", cmds: &[
        c("pagemargins", "Márgenes", "pagemargins"),
        c("pageorient", "Orientación", "pageorient"),
        c("pagesize", "Tamaño de la página", "pagesize"),
        c("printarea", "Área de impresión", "printarea"),
        c("pagebreak", "Saltos", "pagebreak"),
        c("edit-header", "Encabezado/Pie de página", "editheader"),
        c("scale", "Ajustar área de impresión", "scale"),
        c("fit-pages", "Ajustar al papel", "fit-pages"),
        c("printarea-add", "Añadir rango", "printarea-add"),
        c("show-breaks", "Cortes del papel", "show-breaks"),
        c("printtitles", "Imprimir títulos", "printtitles"),
        c("rtl-sheet", "Cambiar la dirección de la hoja para que la primera columna esté a la derecha", "rtl-sheet"),
        c("print-gridlines", "Imprimir líneas de cuadrícula", "print-gridlines"),
        c("print-headings", "Imprimir encabezados", "print-headings"),
        x("Traer adelante", "img-movefrwd"),
        x("Enviar atrás", "img-movebkwd"),
        x("Alineación", "img-align"),
        x("Agrupar", "img-group"),
        x("Fusionar formas", "shapes-merge"),
        c("colorschemas", "Cambiar combinación de colores", "colorschemas"),
    ]},
    Tab { name: "Fórmula", cmds: &[
        c("insert-function", "Insertar función", "additional-formula"),
        c("func-list", "Funciones de Python", "py-list"),
        c("sum", "Autosuma", "autosum"),
        c("fn-recent", "Usadas recientemente", "recent"),
        c("fn-financial", "Financiero", "financial"),
        c("fn-logical", "Lógico", "logical"),
        c("fn-text", "Texto", "text"),
        c("fn-datetime", "Fecha y hora", "datetime"),
        c("fn-lookup", "Búsqueda y referencia", "lookup"),
        c("fn-math", "Matemáticas y trigonometría", "math"),
        c("fn-more", "Más funciones", "more"),
        c("defname", "Administrador de nombres", "named-range-huge"),
        c("paste-name", "Pegar nombre", "paste-name"),
        c("trace-prec", "Rastrear precedentes", "trace-prec"),
        c("trace-dep", "Rastrear dependientes", "trace-dep"),
        c("remove-arrows", "Quitar flechas", "remove-arrows"),
        c("show-formulas", "Mostrar fórmulas", "show-formulas"),
        c("watch", "Ventana Inspección", "watch-window"),
        c("calc-mode", "Cálculo", "calculate"),
    ]},
    Tab { name: "Datos", cmds: &[
        c("data-from-text", "Texto a datos", "data-from-text"),
        c("data-external-links", "Vínculos externos (importar como valores)", "data-external-links"),
        c("setfilter", "Filtros", "setfilter"),
        c("clear-filter", "Borrar filtro", "clear-filter"),
        c("sort-desc", "Clasificar en orden descendente", "sortdesc"),
        c("sort-asc", "Clasificar en orden ascendente", "sortasc"),
        c("custom-sort", "Ordenar", "custom-sort"),
        c("text-column", "Texto en columnas", "text-column"),
        c("rem-duplicates", "Quitar duplicados", "rem-duplicates"),
        c("data-validation", "Validación de datos", "data-validation"),
        t("dv-mark", "Rodear con un círculo los datos no válidos", "dv-mark"),
        c("goal-seek", "Buscar Objetivo", "goal-seek"),
        c("scenario", "Escenario", "scenario"),
        c("solver", "Solver", "solver"),
        c("group", "Agrupar", "group"),
        c("ungroup", "Desagrupar", "ungroup"),
        c("show-details", "Mostrar detalles", "show-details"),
        c("hide-details", "Ocultar detalle", "hide-details"),
        c("subtotal", "Subtotales", "subtotal"),
        c("datatable", "Tabla de datos", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Formato CSV", "csv-kind"),
        c("flash-fill", "Relleno rápido", "flash-fill"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("rec-toggle", "Grabar acciones", "py-run"),
        c("py-new", "Nuevo .py", "py-new"),
        c("py-list", "Lista", "py-list"),
        c("ribbon-list", "Macros de la cinta", "py-line"),
        c("py-folder", "Abrir carpeta", "py-folder"),
    ]},
    Tab { name: "Tabla dinámica", cmds: &[
        c("pivot-insert", "Insertar tabla dinámica", "pivot-insert"),
        c("pivot-fields", "Lista de campos", "pivot-fields"),
        c("pivot-refresh", "Actualizar", "pivot-refresh"),
        c("pivot-refresh-all", "Actualizar todo", "pivot-refresh-all"),
        c("pivot-source", "Origen de datos", "pivot-source"),
        c("pivot-select", "Seleccionar", "pivot-select"),
        c("pivot-totals", "Total general", "pivot-totals"),
        c("pivot-subtotals", "Subtotales", "pivot-subtotals"),
        c("pivot-blank", "Filas en blanco", "pivot-blank"),
        c("pivot-showas", "Tipo de cálculo", "pivot-showas"),
        c("pivot-layout", "Diseño de informe", "pivot-layout"),
        c("pivot-style", "Estilo", "pivot-style"),
    ]},
    Tab { name: "Diseño de tabla", cmds: &[
        c("td-header", "Fila de encabezado", "td-header"),
        c("td-total", "Fila de totales", "td-total"),
        c("td-band-row", "Filas con bandas", "td-band-row"),
        c("td-first", "Primera columna", "td-first"),
        c("td-last", "Última columna", "td-last"),
        c("td-band-col", "Columnas con bandas", "td-band-col"),
        c("td-filter", "Botón de filtro", "td-filter"),
        c("rem-duplicates", "Eliminar duplicados", "td-remdup"),
        c("td-torange", "Convertir al intervalo ", "td-torange"),
        c("td-resize", "Tamaño de la tabla", "td-resize"),
    ]},
    Tab { name: "Colaboración", cmds: &[
        c("coauth-mode", "Modo de coedición", "coauth-mode"),
        c("co-addcomment", "Añadir comentario", "co-addcomment"),
        c("co-delcomment", "Eliminar comentario", "co-delcomment"),
        c("co-showcomment", "Mostrar comentarios", "co-showcomment"),
        c("co-chat", "Chat", "co-chat"),
        c("co-history", "Historial de versiones", "co-history"),
    ]},
    Tab { name: "Protección", cmds: &[
        c("prot-encrypt", "Cifrar", "prot-encrypt"),
        xt("Proteger libro", "protect-workbook"),
        c("prot-doc", "Proteger hoja", "protect-sheet"),
        xt("Proteger rango", "protect-range"),
        c("prot-sign", "Agregar firma digital", "prot-sign"),
        c("cell-lock", "Bloquear celda", "cell-lock"),
        c("prot-allow", "Operaciones permitidas", "prot-allow"),
        c("recover", "Recuperar", "recover"),
        c("recover-every", "Intervalo de copias", "recover-every"),
        c("read-only-rec", "Sugerir solo lectura", "read-only-rec"),
    ]},
    Tab { name: "Mostrar", cmds: &[
        c("sheet-view", "Vista de hoja", "sheet-view"),
        xm("Normal", "view-normal"),
        xm("Vista previa de salto de página", "view-pagebreak"),
        c("zoom-in", "Acercar", "zoom-in"),
        c("zoom-out", "Alejar", "zoom-out"),
        c("zoom100", "Zoom al 100%", "zoom100"),
        c("ui-bigger", "Agrandar texto de la pantalla", "ui-bigger"),
        c("ui-smaller", "Reducir texto de la pantalla", "ui-smaller"),
        t("darkmode", "Modo oscuro", "theme"),
        c("freeze", "Congelar paneles", "freeze"),
        t("split", "Dividir ventana", "split"),
        t("formula-bar", "Barra de fórmulas", "formula-bar"),
        c("show-gridlines", "Líneas de cuadrícula", "show-gridlines"),
        t("show-headings", "Títulos", "show-headings"),
        t("show-zeros", "Mostrar ceros", "show-zeros"),
        t("show-left", "Panel izquierdo", "show-left"),
        t("show-right", "Panel derecho", "show-right"),
    ]},
];

