//! リボンの ja の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py ja > face/src/ribbon_ja.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "コメントを追加"),
    ("Add Text", "テキストの追加"),
    ("Add digital signature", "デジタル署名を追加"),
    ("Add link", "ハイパーリンクを追加"),
    ("Add to area", "範囲を足す"),
    ("Align bottom", "下揃え"),
    ("Align left", "左揃え"),
    ("Align middle", "上下中央揃え"),
    ("Align right", "右揃え"),
    ("Align top", "上揃え"),
    ("Alignment", "配置"),
    ("Allowed actions", "許可する操作"),
    ("Always Show Toolbar", "ツールバーを常に表示する"),
    ("AutoSum", "オートSUM"),
    ("Backup interval", "控えの間隔"),
    ("Banded Rows", "縞模様の行"),
    ("Banded columns", "縞模様の列"),
    ("Bigger UI text", "画面の文字を大きく"),
    ("Blank Rows", "空行"),
    ("Bold", "太字"),
    ("Bookmark", "ブックマーク"),
    ("Borders", "罫線"),
    ("Breaks", "区切り"),
    ("Bring forward", "前面ヘ移動"),
    ("Bullet", "箇条書き"),
    ("CSV format", "CSV の形"),
    ("Calculation options", "計算方法"),
    ("Caption", "図表番号"),
    ("Cell Style", "セルのスタイル"),
    ("Cell lock", "セルのロック"),
    ("Centre", "中央揃え"),
    ("Change case", "大文字小文字を変更"),
    ("Change colour theme", "配色の変更"),
    ("Change hyphenation", "ハイフン設定の変更"),
    ("Change page colour", "ページ色の変更"),
    ("Chat", "チャット"),
    ("Checkbox", "チェックボックス"),
    ("Circle invalid data", "無効データのマーク"),
    ("Clear", "消去"),
    ("Clear filter", "フィルターを解除"),
    ("Clear style", "スタイルのクリア"),
    ("Co-editing mode", "共同編集モード"),
    ("Collaboration", "共同編集"),
    ("Combo box", "コンボボックス"),
    ("Comma style", "カンマスタイル"),
    ("Comment", "コメント"),
    ("Complex Field", "複合フィールド"),
    ("Conditional formatting", "条件付き書式"),
    ("Convert to range", "範囲に変換する"),
    ("Copy", "コピー"),
    ("Cross-reference", "相互参照"),
    ("Currency style", "通貨スタイル"),
    ("Cut", "切り取り"),
    ("Dark mode", "ダークモード"),
    ("Data", "データ"),
    ("Data Validation", "データの入力規則"),
    ("Data source", "データソース"),
    ("Data table", "データテーブル"),
    ("Date & Time", "日付/時刻"),
    ("Decrease decimal", "小数点以下の表示桁数を減らす"),
    ("Decrease indent", "インデントを減らす"),
    ("Decrement font size", "フォントサイズの縮小"),
    ("Delete cells", "セルを削除"),
    ("Delete comment", "コメントを削除"),
    ("Distributed", "均等割付"),
    ("Draw", "描画"),
    ("Dropdown", "ドロップダウン"),
    ("Edit footer", "フッターの編集"),
    ("Edit header", "ヘッダーの編集"),
    ("Edit watermark", "透かしを編集する"),
    ("Email Address", "メールアドレス"),
    ("Encrypt", "暗号化する"),
    ("Eraser", "消しゴム"),
    ("External links (import as values)", "外部リンク(値で取り込む)"),
    ("Field list", "フィールドリスト"),
    ("File", "ファイル"),
    ("Fill", "フィル"),
    ("Fill by example", "フラッシュフィル"),
    ("Fill colour", "塗りつぶしの色"),
    ("Filter button", "フィルタのボタン"),
    ("Filters", "フィルター"),
    ("Financial", "財務"),
    ("First column", "最初の列"),
    ("Fit to page", "ページに合わせる"),
    ("Fit to paper", "紙に収める"),
    ("Fit to width", "幅に合わせる"),
    ("Font", "フォント"),
    ("Font colour", "フォントの色"),
    ("Font size", "フォントのサイズ"),
    ("Footnote", "脚注"),
    ("Forecast Sheet", "予測シート"),
    ("Format as table template", "表として書式設定"),
    ("Format cells", "セルの書式設定"),
    ("Format painter", "書式のコピー"),
    ("Forms", "フォーム"),
    ("Formula", "数式"),
    ("Formula Bar", "数式バー"),
    ("Freeze panes", "ウィンドウ枠の固定"),
    ("Furigana", "ふりがな"),
    ("Goal Seek", "ゴールシーク"),
    ("Grand Total", "総計"),
    ("Gridlines", "枠線表示"),
    ("Group", "グループ化"),
    ("Header & Footer", "ヘッダー/フッター"),
    ("Header row", "ヘッダー行"),
    ("Headings", "見出し"),
    ("Hide detail", "詳細の非表示"),
    ("Highlight colour", "ハイライトの色"),
    ("Highlighter", "蛍光ペン"),
    ("Home", "ホーム"),
    ("Increase decimal", "小数点以下の表示桁数を増やす"),
    ("Increase indent", "インデントを増やす"),
    ("Increment font size", "フォントサイズの拡大"),
    ("Insert", "挿入"),
    ("Insert Pivot Table", "ピボットテーブルを挿入"),
    ("Insert SmartArt", "SmartArtの挿入"),
    ("Insert Text Art", "テキストアートの挿入"),
    ("Insert blank page", "空白ページの挿入"),
    ("Insert cells", "セルを挿入"),
    ("Insert chart", "グラフを挿入"),
    ("Insert column", "列の挿入"),
    ("Insert content controls", "コンテンツコントロールの挿入"),
    ("Insert drop cap", "ドロップキャップの挿入"),
    ("Insert equation", "方程式を挿入"),
    ("Insert function", "関数の挿入"),
    ("Insert image", "画像を挿入"),
    ("Insert recommended chart", "推奨チャートを挿入"),
    ("Insert shape", "図形を挿入"),
    ("Insert slicer", "スライサーを挿入"),
    ("Insert sparkline", "スパークラインを挿入する"),
    ("Insert symbol", "記号を挿入"),
    ("Insert table", "表の挿入"),
    ("Insert text box", "テキストボックスの挿入"),
    ("Italic", "斜体"),
    ("Justified", "両端揃え"),
    ("Last column", "最後の列"),
    ("Layout", "レイアウト"),
    ("Left Panel", "左パネル"),
    ("Logical", "論理"),
    ("Lookup & Reference", "検索/行列"),
    ("Macro list", "一覧"),
    ("Macros", "マクロ"),
    ("Margins", "余白"),
    ("Math & Trig", "数学/三角"),
    ("Merge and centre", "結合して、中央に配置する"),
    ("Merge shapes", "図形を結合"),
    ("More functions", "その他の関数"),
    ("Multilevel list", "複数レベルのリスト"),
    ("Multiple pages", "複数ページ"),
    ("Name", "名前"),
    ("Name manager", "名前の管理"),
    ("Navigation", "ナビゲーション"),
    ("New .py", "新しい .py"),
    ("Nonprinting characters", "非表示文字"),
    ("Normal", "標準"),
    ("Number format", "数値の書式"),
    ("Number of pages", "ページ数"),
    ("Numbering", "ナンバリング"),
    ("Open", "開く"),
    ("Open folder", "置き場を開く"),
    ("Page Break Preview", "改ページ プレビュー"),
    ("Page breaks", "紙の切れ目"),
    ("Page number", "ページ番号"),
    ("Page orientation", "印刷の向き"),
    ("Page size", "ページのサイズ"),
    ("Paragraph line spacing", "段落の行間"),
    ("Paragraph style", "段落のスタイル"),
    ("Paste", "貼り付け"),
    ("Paste name", "名前を貼り付け"),
    ("Pen", "ペン"),
    ("Percent style", "パーセントのスタイル"),
    ("Phone Number", "電話番号"),
    ("Picture", "画像"),
    ("Pivot Table", "ピボットテーブル"),
    ("PivotChart", "ピボットグラフ"),
    ("Print", "印刷"),
    ("Print Area", "印刷範囲"),
    ("Print gridlines", "枠線も印刷"),
    ("Print headings", "見出しも印刷"),
    ("Print layout", "印刷レイアウト"),
    ("Print titles", "タイトルを印刷する"),
    ("Protect Range", "範囲を保護する"),
    ("Protect sheet", "シートを保護する"),
    ("Protect workbook", "ブックを保護する"),
    ("Protection", "保護"),
    ("Python functions", "Python の関数"),
    ("Radio Button", "ラジオボタン"),
    ("Recently used", "最近使った関数"),
    ("Record actions", "操作を記録"),
    ("Recover", "復旧"),
    ("References", "参考資料"),
    ("Remove Duplicates", "重複データを削除"),
    ("Remove arrows", "トレース矢印の削除"),
    ("Remove duplicates", "重複の削除"),
    ("Replace", "置き換え"),
    ("Report Layout", "レポートのレイアウト"),
    ("Resize table", "テーブルのサイズ変更"),
    ("Ribbon macros", "リボンのマクロ"),
    ("Right Panel", "右パネル"),
    ("Right-to-left text", "文字の向き(右横書き)"),
    ("Ruby", "ルビ"),
    ("Rulers", "ルーラー"),
    ("Save", "保存"),
    ("Scale To Fit", "拡大縮小印刷"),
    ("Scenario", "シナリオ"),
    ("Select all", "すべて選択"),
    ("Send Backward", "背面ヘ移動"),
    ("Shading", "段落の背景色"),
    ("Sheet View", "シートの表示"),
    ("Show comments", "コメントの表示"),
    ("Show details", "詳細の表示"),
    ("Show formulas", "数式の表示"),
    ("Show line numbers", "行番号を表示する"),
    ("Show values as", "計算の種類"),
    ("Show zeros", "0を表示する"),
    ("Signature", "署名"),
    ("Smaller UI text", "画面の文字を小さく"),
    ("Solver", "ソルバー"),
    ("Sort", "並べ替え"),
    ("Sort ascending", "昇順並べ替え"),
    ("Sort descending", "降順並べ替え"),
    ("Split", "分割"),
    ("Status Bar", "ステータスバー"),
    ("Strikethrough", "取り消し線"),
    ("Style", "スタイル"),
    ("Subscript", "下付き"),
    ("Subtotals", "小計"),
    ("Suggest read-only", "読み取り専用を勧める"),
    ("Superscript", "上付き"),
    ("Switch the sheet direction so that the first column is on the right side", "最初の列が右側に来るようにシートの方向を切り替える"),
    ("Table Design", "表のデザイン"),
    ("Table of contents", "目次"),
    ("Table of figures", "図表目次"),
    ("Text Field", "テキストフィールド"),
    ("Text direction", "テキスト方向"),
    ("Text from File", "ファイルからのテキスト"),
    ("Text functions", "文字列操作"),
    ("Text orientation", "文字の向き"),
    ("Text to columns", "区切り位置"),
    ("Text to data", "テキストからデータ"),
    ("Total row", "合計行"),
    ("Trace Dependents", "参照先のトレース"),
    ("Trace Precedents", "参照元のトレース"),
    ("Track changes", "変更履歴"),
    ("Underline", "下線"),
    ("Ungroup", "グループ解除"),
    ("Update", "更新"),
    ("Update all", "すべて更新"),
    ("Update table of contents", "目次の更新"),
    ("Update table of figures", "図表目次の更新"),
    ("Version history", "バージョン履歴"),
    ("View", "表示"),
    ("Watch window", "ウォッチウィンドウ"),
    ("Wrap text", "折り返して全体を表示する"),
    ("Write macro", "マクロを書く"),
    ("Zoom in", "拡大"),
    ("Zoom out", "縮小"),
    ("Zoom to 100%", "100%に拡大する"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
    ("draw-select", "選択"),
    ("pivot-select", "選択する"),
];

