//! リボンの fr 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py fr > face/src/ribbon_fr.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, x, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Fichier", cmds: &[
        c("open", "Ouvrir", "open"),
        c("save", "Enregistrer", "save"),
        c("pdf", "Imprimer", "print"),
    ]},
    Tab { name: "Accueil", cmds: &[
        c("copy", "Copier", "copy"),
        c("cut", "Couper", "cut"),
        c("paste", "Coller", "paste"),
        c("fontname", "Police", "fontname"),
        c("fontsize", "Taille de police", "fontsize"),
        c("incfont", "Augmenter la taille de police", "incfont"),
        c("decfont", "Diminuer la taille de police", "decfont"),
        c("changecase", "Modifier la casse", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Gras", "bold"),
        c("italic", "Italique", "italic"),
        c("underline", "Souligné", "underline"),
        c("strikeout", "Barré", "strikeout"),
        c("superscript", "Exposant", "superscript"),
        c("subscript", "Indice", "subscript"),
        c("highlight", "Couleur de surlignage", "highlight"),
        c("fontcolor", "Couleur de police", "fontcolor"),
        c("clearstyle", "Effacer le style", "clearstyle"),
        c("markers", "Puce", "markers"),
        c("numbering", "Numérotation", "numbering"),
        c("multilevels", "Liste multiniveau", "multilevels"),
        c("decoffset", "Réduire le retrait", "decoffset"),
        c("incoffset", "Augmenter le retrait", "incoffset"),
        c("linespace", "Interligne du paragraphe", "linespace"),
        c("direction", "Orientation du texte", "direction"),
        c("align-left", "Aligner à gauche", "align-left"),
        c("align-center", "Au centre", "align-center"),
        c("align-right", "Aligner à droite", "align-right"),
        c("align-just", "Justifié", "align-just"),
        c("align-dist", "Réparti", "align-dist"),
        c("hidenchars", "Caractères non imprimables", "hidenchars"),
        c("paracolor", "Ombrage", "paracolor"),
        c("borders", "Bordures", "borders"),
        c("parastyle", "Style de paragraphe", "styles"),
        c("replace", "Remplacer", "replace"),
        c("selectall", "Sélectionner tout", "select-all"),
    ]},
    Tab { name: "Insertion", cmds: &[
        c("blankpage", "Insérer page vide", "blankpage"),
        c("pagebreak", "Insérer un saut de page ou de section", "pagebreak"),
        c("instable", "Insérer un tableau", "instable"),
        c("insimage", "Insérer une image", "insertimage"),
        c("insshape", "Insérer une forme", "insshape"),
        c("inssmartart", "Insérer un graphique SmartArt", "inssmartart"),
        c("inschart", "Insérer un graphique", "inschart"),
        c("smartpicker", "Insérer un graphique", "smartpicker"),
        c("instext", "Insérez zone de texte", "instext"),
        c("instextart", "Insérer Text Art", "instextart"),
        c("dropcap", "Insérer une lettrine", "dropcap"),
        c("text-from-file", "Texte à partir d'un fichier", "text-from-file"),
        c("edit-header", "Modifier l'en-tête", "edit-header"),
        c("edit-footer", "Modifier le pied de page", "edit-footer"),
        c("pagenum", "Numérotation des pages", "pagenum"),
        c("datetime", "Date et heure", "datetime"),
        c("numpages", "Nombre de pages", "numpages"),
        c("insequation", "Insérer une équation", "insequation"),
        c("inssymbol", "Insérer un symbole", "inssymbol"),
        c("controls", "Insérer des contrôles de contenu", "controls"),
    ]},
    Tab { name: "Dessiner", cmds: &[
        c("pen", "Stylo", "pen"),
        c("highlighter", "Surligneur", "highlighter"),
        c("eraser", "Gomme", "eraser"),
    ]},
    Tab { name: "Mise en page", cmds: &[
        c("pagemargins", "Marges", "pagemargins"),
        c("pageorient", "Orientation de page", "pageorient"),
        c("pagesize", "Taille de la page", "pagesize"),
        c("columns", "Insérer une colonne", "columns"),
        c("line-numbers", "Afficher les numéros de ligne", "line-numbers"),
        c("hyphenation", "Modifier la coupure de mots", "hyphenation"),
        c("watermark", "Modifier le filigrane", "watermark"),
        c("pagecolor", "Modifier la couleur de page", "pagecolor"),
        c("colorschemas", "Modifier le jeu de couleurs", "colorschemas"),
    ]},
    Tab { name: "Références", cmds: &[
        c("toc", "Table des matières", "contents"),
        c("add-text", "Ajouter du texte", "add-text"),
        c("toc-update", "Mettre à jour la table des matières", "contents-update"),
        c("bookmarks", "Signet", "bookmarks"),
        c("caption", "Légende", "caption"),
        c("crossref", "Renvoi", "crossref"),
        c("footnote", "Note de bas de page", "footnote"),
        c("tof", "Table des illustrations", "tof"),
        c("tof-update", "Mettre à jour la table des illustrations", "tof-update"),
    ]},
    Tab { name: "Formulaires", cmds: &[
        c("form-text", "Champ texte", "form-text"),
        c("form-combo", "Zone de liste déroulante", "form-combo"),
        c("form-dropdown", "Liste déroulante", "form-dropdown"),
        c("form-checkbox", "Case à cocher", "form-checkbox"),
        c("form-radio", "Bouton radio", "form-radio"),
        c("form-image", "Image", "form-image"),
        c("form-email", "Adresse E-mail", "form-email"),
        c("form-phone", "Numéro de téléphone", "form-phone"),
        c("form-complex", "Champ complexe", "form-complex"),
        c("form-signature", "Signature", "form-signature"),
        c("form-name", "Nom", "form-name"),
    ]},
    Tab { name: "Collaboration", cmds: &[
        c("coauth-mode", "Mode coédition", "coauth-mode"),
        c("co-addcomment", "Ajouter un commentaire", "co-addcomment"),
        c("co-delcomment", "Supprimer le commentaire", "co-delcomment"),
        c("co-showcomment", "Afficher les commentaires", "co-showcomment"),
        c("co-chat", "Discussion", "co-chat"),
        c("track-changes", "Suivi des modifications", "track-changes"),
        c("co-history", "Historique des versions", "co-history"),
    ]},
    Tab { name: "Protection", cmds: &[
        c("prot-encrypt", "Chiffrer", "prot-encrypt"),
        c("prot-sign", "Ajouter une signature numérique", "prot-sign"),
        c("prot-doc", "Protection", "prot-doc"),
    ]},
    Tab { name: "Afficher", cmds: &[
        c("nav", "Navigation", "nav"),
        c("fit-page", "Ajuster à la page", "fit-page"),
        c("fit-width", "Ajuster à la largeur", "fit-width"),
        c("zoom100", "Zoom à 100 %", "zoom100"),
        c("zoom-in", "Zoom avant", "zoom-in"),
        c("zoom-out", "Zoom arrière", "zoom-out"),
        c("printview", "Mise en page", "printview"),
        c("multipage", "Plusieurs pages", "multipage"),
        c("darkmode", "Mode sombre", "darkmode"),
        c("ruler", "Règles", "ruler"),
        c("show-toolbar", "Toujours afficher la barre d'outils", "show-toolbar"),
        c("show-statusbar", "Barre d'état", "show-statusbar"),
        c("show-left", "Panneau gauche", "show-left"),
        c("show-right", "Panneau droit", "show-right"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("plug-manage", "Liste", "plug-manage"),
        c("ai-macro", "Écrire une macro", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Fichier", cmds: &[
        c("open", "Ouvrir", "open"),
        c("save", "Enregistrer", "save"),
        c("pdf", "Imprimer", "print"),
    ]},
    Tab { name: "Accueil", cmds: &[
        c("copy", "Copier", "copy"),
        c("cut", "Couper", "cut"),
        c("paste", "Coller", "paste"),
        c("copystyle", "Copier le format", "copystyle"),
        c("fontname", "Police", "fontname"),
        c("fontsize", "Taille de police", "fontsize"),
        c("incfont", "Augmenter la taille de police", "incfont"),
        c("decfont", "Diminuer la taille de police", "decfont"),
        c("changecase", "Modifier la casse", "changecase"),
        c("bold", "Gras", "bold"),
        c("italic", "Italique", "italic"),
        c("underline", "Souligné", "underline"),
        c("strikeout", "Barré", "strikeout"),
        c("subscript", "Indice", "subscript"),
        c("fontcolor", "Couleur de police", "fontcolor"),
        c("fillparag", "Couleur de remplissage", "fillparag"),
        c("borders", "Bordures", "borders"),
        c("top", "Aligner en haut", "top"),
        c("middle", "Au centre", "middle"),
        c("bottom", "Aligner en bas", "bottom"),
        c("wrap", "Renvoyer à la ligne", "wrap"),
        c("text-orient", "Orientation de page", "text-orient"),
        c("align-left", "Aligner à gauche", "align-left"),
        c("align-center", "Au centre", "align-center"),
        c("align-right", "Aligner à droite", "align-right"),
        c("align-just", "Justifié", "align-just"),
        c("align-dist", "Réparti", "align-dist"),
        c("merge", "Fusionner et centrer", "merge"),
        c("direction", "Sens du texte (droite à gauche)", "direction"),
        c("sum", "Somme automatique", "autosum"),
        c("fill-num", "Recopier", "fill-num"),
        c("defname", "Gestionnaire de noms", "named-range"),
        c("clear", "Effacer", "clear"),
        c("sort-desc", "Trier par ordre décroissant", "sortdesc"),
        c("sort-asc", "Trier par ordre croissant", "sortasc"),
        c("setfilter", "Filtres", "setfilter"),
        c("clear-filter", "Effacer le filtre", "clear-filter"),
        c("format", "Format de nombre", "format"),
        c("currency", "Style monétaire", "currency"),
        c("percents", "Style de pourcentage", "percents"),
        c("comma", "Style de virgule", "comma"),
        c("digit-dec", "Réduire les décimales", "digit-dec"),
        c("digit-inc", "Ajouter une décimale", "digit-inc"),
        c("cell-ins", "Insérer les cellules", "cell-ins"),
        c("cell-del", "Supprimer les cellules", "cell-del"),
        c("cell-format", "Style de cellule", "cell-format"),
        c("condformat", "Mise en forme conditionnelle", "condformat"),
        c("table-tpl", "Insérer un tableau", "table-tpl"),
        c("cell-styles", "Style de cellule", "styles"),
        c("replace", "Remplacer", "replace"),
        c("selectall", "Sélectionner tout", "select-all"),
    ]},
    Tab { name: "Insertion", cmds: &[
        c("pivot-insert", "Insérer un tableau croisé dynamique", "add-pivot"),
        c("instable", "Insérer un tableau", "instable"),
        c("insimage", "Insérer une image", "insimage-c"),
        c("insshape", "Insérer une forme", "insshape"),
        c("inssmartart", "Insérer un graphique SmartArt", "inssmartart"),
        c("inscheckbox", "Case à cocher", "inscheckbox"),
        c("insrecommend", "Insérer le graphique recommandé", "insrecommend"),
        c("inschart", "Insérer un graphique", "inschart"),
        c("inssparkline", "Insérer un graphique sparkline", "inssparkline"),
        c("addcomment", "Commentaire", "ins-comment"),
        c("inshyperlink", "Ajouter un lien", "inshyperlink"),
        c("insslicer", "Isérer un segment", "insslicer"),
        c("instext", "Insérez zone de texte", "instext"),
        c("instextart", "Insérer Text Art", "instextart"),
        c("editheader", "En-tête/Pied de page", "editheader"),
        c("insequation", "Insérer une équation", "insequation"),
        c("inssymbol", "Insérer un symbole", "inssymbol"),
    ]},
    Tab { name: "Dessiner", cmds: &[
        c("draw-select", "Sélectionner", "select-tool"),
        c("pen", "Stylo", "pen"),
        c("highlighter", "Surligneur", "highlighter"),
        c("eraser", "Gomme", "eraser"),
    ]},
    Tab { name: "Mise en page", cmds: &[
        c("pagemargins", "Marges", "pagemargins"),
        c("pageorient", "Orientation de page", "pageorient"),
        c("pagesize", "Taille de la page", "pagesize"),
        c("printarea", "Zone d'impression", "printarea"),
        c("pagebreak", "Ajoutez un saut de page où vous voulez que le prochain page commence dans la copie imprimée.", "pagebreak"),
        c("editheader", "En-tête/Pied de page", "editheader"),
        c("scale", "Mettre à l’échelle", "scale"),
        c("fit-pages", "Ajuster au papier", "fit-pages"),
        c("printarea-add", "Ajouter la plage", "printarea-add"),
        c("show-breaks", "Sauts de page", "show-breaks"),
        c("printtitles", "Titres à imprimer", "printtitles"),
        c("rtl-sheet", "Inverser le sens de la feuille de manière à ce que la première colonne se trouve sur le côté droit", "rtl-sheet"),
        c("print-gridlines", "Imprimer le quadrillage", "print-gridlines"),
        c("print-headings", "Imprimer les en-têtes", "print-headings"),
        x("Déplacer vers l'avant", "img-movefrwd"),
        x("Reculer", "img-movebkwd"),
        x("Alignement", "img-align"),
        x("Grouper", "img-group"),
        x("Combiner les formes", "shapes-merge"),
        c("colorschemas", "Modifier le jeu de couleurs", "colorschemas"),
    ]},
    Tab { name: "Formule", cmds: &[
        c("insert-function", "Insérer une fonction", "additional-formula"),
        c("func-list", "Fonctions Python", "py-list"),
        c("sum", "Somme automatique", "autosum"),
        c("fn-recent", "Récemment utilisées", "recent"),
        c("fn-financial", "Financier", "financial"),
        c("fn-logical", "Logique", "logical"),
        c("fn-text", "Texte", "text"),
        c("fn-datetime", "Date et heure", "datetime"),
        c("fn-lookup", "Recherche et référence", "lookup"),
        c("fn-math", "Math et trigonométrie", "math"),
        c("fn-more", "Plus de fonctions", "more"),
        c("defname", "Gestionnaire de noms", "named-range-huge"),
        c("paste-name", "Coller un nom", "paste-name"),
        c("trace-prec", "Tracer les précédents", "trace-prec"),
        c("trace-dep", "Tracer les dépendants", "trace-dep"),
        c("remove-arrows", "Supprimer les flèches", "remove-arrows"),
        c("show-formulas", "Afficher les formules", "show-formulas"),
        c("watch", "Fenêtre Espion", "watch-window"),
        c("calc-mode", "Mode de calcul", "calculate"),
    ]},
    Tab { name: "Données", cmds: &[
        c("data-from-text", "Texte en données", "data-from-text"),
        c("data-external-links", "Liens externes (importer en valeurs)", "data-external-links"),
        c("setfilter", "Filtres", "setfilter"),
        c("clear-filter", "Effacer le filtre", "clear-filter"),
        c("sort-desc", "Trier par ordre décroissant", "sortdesc"),
        c("sort-asc", "Trier par ordre croissant", "sortasc"),
        c("custom-sort", "Trier", "custom-sort"),
        c("text-column", "Convertir", "text-column"),
        c("rem-duplicates", "Supprimer les doublons", "rem-duplicates"),
        c("data-validation", "Validation des données", "data-validation"),
        c("goal-seek", "Valeur cible", "goal-seek"),
        c("solver", "Solveur", "solver"),
        c("group", "Grouper", "group"),
        c("ungroup", "Dissocier", "ungroup"),
        c("show-details", "Afficher les détails", "show-details"),
        c("hide-details", "Masquer le détail", "hide-details"),
        c("subtotal", "Sous-totaux", "subtotal"),
        c("datatable", "Table de données", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Format CSV", "csv-kind"),
        c("flash-fill", "Remplissage instantané", "flash-fill"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("rec-toggle", "Enregistrer les actions", "py-run"),
        c("py-new", "Nouveau .py", "py-new"),
        c("py-list", "Liste", "py-list"),
        c("ribbon-list", "Macros du ruban", "py-line"),
        c("py-folder", "Ouvrir le dossier", "py-folder"),
    ]},
    Tab { name: "Tableau croisé dynamique", cmds: &[
        c("pivot-insert", "Insérer un tableau croisé dynamique", "pivot-insert"),
        c("pivot-fields", "Liste des champs", "pivot-fields"),
        c("pivot-refresh", "Mettre à jour", "pivot-refresh"),
        c("pivot-refresh-all", "Tout mettre à jour", "pivot-refresh-all"),
        c("pivot-select", "Sélectionner", "pivot-select"),
        c("pivot-totals", "Total général", "pivot-totals"),
        c("pivot-subtotals", "Sous-totaux", "pivot-subtotals"),
        c("pivot-blank", "Lignes vides", "pivot-blank"),
        c("pivot-showas", "Type de calcul", "pivot-showas"),
        c("pivot-layout", "Disposition du rapport", "pivot-layout"),
        c("pivot-style", "Style", "pivot-style"),
    ]},
    Tab { name: "Création de tableau", cmds: &[
        c("td-header", "Ligne d’en-tête", "td-header"),
        c("td-total", "Ligne des totaux", "td-total"),
        c("td-band-row", "Lignes à bandes", "td-band-row"),
        c("td-first", "Première colonne", "td-first"),
        c("td-last", "Dernière colonne", "td-last"),
        c("td-band-col", "Colonnes à bandes", "td-band-col"),
        c("td-filter", "Bouton de filtre", "td-filter"),
        c("rem-duplicates", "Supprimer les doublons", "td-remdup"),
        c("td-torange", "Convertir en plage", "td-torange"),
        c("td-resize", "Redimensionner le tableau", "td-resize"),
    ]},
    Tab { name: "Collaboration", cmds: &[
        c("coauth-mode", "Mode coédition", "coauth-mode"),
        c("addcomment", "Ajouter un commentaire", "co-addcomment"),
        c("co-delcomment", "Supprimer le commentaire", "co-delcomment"),
        c("co-showcomment", "Afficher les commentaires", "co-showcomment"),
        c("co-chat", "Discussion", "co-chat"),
        c("co-history", "Historique des versions", "co-history"),
    ]},
    Tab { name: "Protection", cmds: &[
        c("prot-encrypt", "Chiffrer", "prot-encrypt"),
        x("Protéger le classeur", "protect-workbook"),
        c("prot-doc", "Protéger la feuille de calcul", "protect-sheet"),
        x("Protéger la plage", "protect-range"),
        c("prot-sign", "Ajouter une signature numérique", "prot-sign"),
        c("cell-lock", "Verrouiller la cellule", "cell-lock"),
        c("prot-allow", "Actions permises", "prot-allow"),
        c("recover", "Récupérer", "recover"),
        c("recover-every", "Intervalle des copies", "recover-every"),
        c("read-only-rec", "Suggérer la lecture seule", "read-only-rec"),
    ]},
    Tab { name: "Afficher", cmds: &[
        c("sheet-view", "Mode Feuille", "sheet-view"),
        x("Normal", "view-normal"),
        x("Aperçu des sauts de page", "view-pagebreak"),
        c("zoom-in", "Zoom avant", "zoom-in"),
        c("zoom-out", "Zoom arrière", "zoom-out"),
        c("ui-bigger", "Agrandir le texte de l'écran", "ui-bigger"),
        c("ui-smaller", "Réduire le texte de l'écran", "ui-smaller"),
        c("theme", "Thème de l'interface", "theme"),
        c("freeze", "Figer les volets", "freeze"),
        c("formula-bar", "Barre de formule", "formula-bar"),
        c("show-gridlines", "Quadrillage", "show-gridlines"),
        c("show-headings", "Titres", "show-headings"),
        c("show-zeros", "Afficher les zéros", "show-zeros"),
        c("show-left", "Panneau gauche", "show-left"),
        c("show-right", "Panneau droit", "show-right"),
    ]},
];

