//! リボンの zh-tw の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py zh-tw > face/src/ribbon_zh-tw.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "新增註解"),
    ("Add Text", "新增文字"),
    ("Add digital signature", "新增數位簽章"),
    ("Add link", "新增超連結"),
    ("Add to area", "加入列印範圍"),
    ("Align bottom", "對齊底部"),
    ("Align left", "靠左對齊"),
    ("Align middle", "置於中央對齊"),
    ("Align right", "靠右對齊"),
    ("Align top", "靠上對齊"),
    ("Alignment", "對齊"),
    ("Allowed actions", "允許的操作"),
    ("Always Show Toolbar", "顯示工具列"),
    ("AutoSum", "自動加總"),
    ("Backup interval", "備份間隔"),
    ("Banded Rows", "交替行"),
    ("Banded columns", "帶狀欄"),
    ("Bigger UI text", "放大介面文字"),
    ("Blank Rows", "空白行"),
    ("Bold", "粗體"),
    ("Bookmark", "書籤"),
    ("Borders", "框線"),
    ("Breaks", "分頁符號"),
    ("Bring forward", "向前移動"),
    ("Bullet", "項目符號"),
    ("CSV format", "CSV 格式"),
    ("Calculation options", "計算方式"),
    ("Caption", "標號"),
    ("Cell Style", "儲存格樣式"),
    ("Cell lock", "鎖定儲存格"),
    ("Centre", "置中"),
    ("Change case", "大小寫轉換"),
    ("Change colour theme", "變更色彩配置"),
    ("Change hyphenation", "斷字"),
    ("Change page colour", "變更頁面顏色"),
    ("Chat", "聊天"),
    ("Checkbox", "核取方塊"),
    ("Circle invalid data", "圈選無效資料"),
    ("Clear", "清除"),
    ("Clear filter", "清除篩選"),
    ("Clear style", "清除樣式"),
    ("Co-editing mode", "共同編輯模式"),
    ("Collaboration", "共同編輯"),
    ("Combo box", "下拉式方框"),
    ("Comma style", "千分位樣式"),
    ("Comment", "評論"),
    ("Complex Field", "複雜字段"),
    ("Conditional formatting", "條件格式設定"),
    ("Convert to range", "轉換為範圍"),
    ("Copy", "複製"),
    ("Cross-reference", "交互參照"),
    ("Currency style", "貨幣樣式"),
    ("Cut", "剪下"),
    ("Dark mode", "深色模式"),
    ("Data", "資料"),
    ("Data Validation", "資料驗證"),
    ("Data source", "資料來源"),
    ("Data table", "運算列表"),
    ("Date & Time", "日期/時間"),
    ("Decrease decimal", "減少小數位數"),
    ("Decrease indent", "減少縮排"),
    ("Decrement font size", "縮小文字"),
    ("Delete cells", "刪除儲存格"),
    ("Delete comment", "刪除註解"),
    ("Distributed", "分散對齊"),
    ("Draw", "繪製"),
    ("Dropdown", "下拉式選單"),
    ("Edit footer", "編輯頁尾"),
    ("Edit header", "編輯頁首"),
    ("Edit watermark", "編輯浮水印"),
    ("Email Address", "電子郵件"),
    ("Encrypt", "加密"),
    ("Eraser", "橡皮擦"),
    ("External links (import as values)", "外部連結(以值匯入)"),
    ("Field list", "欄位清單"),
    ("File", "檔案"),
    ("Fill", "填滿"),
    ("Fill by example", "快速填入"),
    ("Fill colour", "填充顏色"),
    ("Filter button", "篩選按鈕"),
    ("Filters", "過濾器"),
    ("Financial", "財務"),
    ("First column", "第一欄"),
    ("Fit to page", "縮放至整頁"),
    ("Fit to paper", "配合紙張大小"),
    ("Fit to width", "縮放至頁面寬度"),
    ("Font", "字型"),
    ("Font colour", "字型顏色"),
    ("Font size", "字型大小"),
    ("Footnote", "註腳"),
    ("Forecast Sheet", "預測工作表"),
    ("Format as table template", "格式作為表格樣板"),
    ("Format cells", "格式化儲存格"),
    ("Format painter", "複製格式"),
    ("Forms", "表單"),
    ("Formula", "公式"),
    ("Formula Bar", "公式欄"),
    ("Freeze panes", "凍結窗格"),
    ("Furigana", "注音"),
    ("Goal Seek", "單變數求解"),
    ("Grand Total", "總計"),
    ("Gridlines", "網格線"),
    ("Group", "分組"),
    ("Header & Footer", "頁首及頁尾"),
    ("Header row", "頁首列"),
    ("Headings", "標題"),
    ("Hide detail", "隱藏詳細資料"),
    ("Highlight colour", "文字醒目提示色彩"),
    ("Highlighter", "螢光筆"),
    ("Home", "首頁"),
    ("Increase decimal", "增加小數位數"),
    ("Increase indent", "縮排"),
    ("Increment font size", "放大文字"),
    ("Insert", "插入"),
    ("Insert Pivot Table", "插入樞紐分析表"),
    ("Insert SmartArt", "插入SmartArt"),
    ("Insert Text Art", "插入藝術文字"),
    ("Insert blank page", "插入空白頁"),
    ("Insert cells", "插入儲存格"),
    ("Insert chart", "插入圖表"),
    ("Insert column", "插入欄"),
    ("Insert content controls", "插入內容控制項"),
    ("Insert drop cap", "插入首字下沉"),
    ("Insert equation", "插入方程式"),
    ("Insert function", "插入函數"),
    ("Insert image", "插入圖片"),
    ("Insert recommended chart", "插入建議圖表"),
    ("Insert shape", "插入形狀"),
    ("Insert slicer", "插入切片器"),
    ("Insert sparkline", "插入迷你圖"),
    ("Insert symbol", "插入符號"),
    ("Insert table", "插入表格"),
    ("Insert text box", "插入文字方塊"),
    ("Italic", "斜體"),
    ("Justified", "兩端對齊"),
    ("Last column", "最後一欄"),
    ("Layout", "版面配置"),
    ("Left Panel", "左側面板"),
    ("Logical", "邏輯"),
    ("Lookup & Reference", "查閱與參照"),
    ("Macro list", "清單"),
    ("Macros", "巨集"),
    ("Margins", "邊框"),
    ("Math & Trig", "數學/三角函數"),
    ("Merge and centre", "合併和居中"),
    ("Merge shapes", "合併圖形"),
    ("More functions", "更多函數"),
    ("Multilevel list", "多層次清單"),
    ("Multiple pages", "多頁"),
    ("Name", "名稱"),
    ("Name manager", "名稱管理員"),
    ("Navigation", "導覽"),
    ("New .py", "新增 .py"),
    ("Nonprinting characters", "顯示/隱藏編輯標記"),
    ("Normal", "一般"),
    ("Number format", "數字格式"),
    ("Number of pages", "頁數"),
    ("Numbering", "編號"),
    ("Open", "開啟"),
    ("Open folder", "開啟資料夾"),
    ("Page Break Preview", "分頁預覽"),
    ("Page breaks", "分頁線"),
    ("Page number", "頁碼"),
    ("Page orientation", "頁面方向"),
    ("Page size", "頁面大小"),
    ("Paragraph line spacing", "段落行距"),
    ("Paragraph style", "段落風格"),
    ("Paste", "貼上"),
    ("Paste name", "貼上名稱"),
    ("Pen", "筆"),
    ("Percent style", "百分比樣式"),
    ("Phone Number", "電話號碼"),
    ("Picture", "圖片"),
    ("Pivot Table", "樞紐分析表"),
    ("PivotChart", "樞紐分析圖"),
    ("Print", "列印"),
    ("Print Area", "列印範圍"),
    ("Print gridlines", "列印格線"),
    ("Print headings", "列印列標和欄標"),
    ("Print titles", "列印標題"),
    ("Protect Range", "保護範圍"),
    ("Protect sheet", "保護工作表"),
    ("Protect workbook", "保護工作簿"),
    ("Protection", "保護"),
    ("Python functions", "Python 函式"),
    ("Radio Button", "單選按鈕"),
    ("Recently used", "最近使用的函數"),
    ("Record actions", "記錄操作"),
    ("Recover", "檔案復原"),
    ("References", "參考文獻"),
    ("Remove Duplicates", "移除重複項目"),
    ("Remove arrows", "移除箭號"),
    ("Remove duplicates", "移除重複"),
    ("Replace", "取代"),
    ("Report Layout", "報表版面配置"),
    ("Resize table", "調整表格大小"),
    ("Ribbon macros", "功能區的巨集"),
    ("Right Panel", "右側面板"),
    ("Right-to-left text", "文字方向(右起橫書)"),
    ("Ruby", "注音標示"),
    ("Rulers", "尺規"),
    ("Save", "儲存"),
    ("Scale To Fit", "縮放以適合"),
    ("Scenario", "分析藍本"),
    ("Select", "選擇"),
    ("Select all", "全選"),
    ("Send Backward", "向後發送"),
    ("Shading", "網底"),
    ("Sheet View", "工作表檢視"),
    ("Show comments", "顯示註解"),
    ("Show details", "顯示詳細資料"),
    ("Show formulas", "顯示公式"),
    ("Show line numbers", "顯示行號"),
    ("Show values as", "值的顯示方式"),
    ("Show zeros", "顯示 0"),
    ("Signature", "簽名"),
    ("Smaller UI text", "縮小介面文字"),
    ("Solver", "規劃求解"),
    ("Sort", "排序"),
    ("Sort ascending", "升序"),
    ("Sort descending", "降序"),
    ("Split", "分割視窗"),
    ("Status Bar", "狀態列"),
    ("Strikethrough", "刪除線"),
    ("Style", "樣式"),
    ("Subscript", "下標"),
    ("Subtotals", "小計"),
    ("Suggest read-only", "建議唯讀"),
    ("Superscript", "上標"),
    ("Switch the sheet direction so that the first column is on the right side", "切換工作表方向，使第一列位於右側"),
    ("Table Design", "表格設計"),
    ("Table of contents", "目錄"),
    ("Table of figures", "圖表目錄"),
    ("Text Field", "文字段落"),
    ("Text direction", "文字方向"),
    ("Text from File", "從檔案匯入文字"),
    ("Text functions", "文字"),
    ("Text orientation", "文字方向"),
    ("Text to columns", "資料剖析"),
    ("Text to data", "文字轉資料"),
    ("Total row", "總行數"),
    ("Trace Dependents", "追蹤從屬參照"),
    ("Trace Precedents", "追蹤前導參照"),
    ("Track changes", "追蹤變更"),
    ("Underline", "下劃線"),
    ("Ungroup", "取消分組"),
    ("Update", "更新"),
    ("Update all", "全部更新"),
    ("Update table of contents", "更新目錄"),
    ("Update table of figures", "更新圖表目錄"),
    ("Version history", "版本歷程"),
    ("View", "檢視"),
    ("Watch window", "監看視窗"),
    ("Wrap text", "自動換列"),
    ("Write macro", "撰寫巨集"),
    ("Zoom in", "放大"),
    ("Zoom out", "縮小"),
    ("Zoom to 100%", "縮放至 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

