//! リボンの zh の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py zh > face/src/ribbon_zh.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "添加批注"),
    ("Add Text", "添加文字"),
    ("Add digital signature", "添加数字签名"),
    ("Add link", "添加链接"),
    ("Add to area", "添加范围"),
    ("Align bottom", "底部对齐"),
    ("Align left", "左对齐"),
    ("Align middle", "居中对齐"),
    ("Align right", "右对齐"),
    ("Align top", "顶端对齐"),
    ("Alignment", "对齐"),
    ("Allowed actions", "允许的操作"),
    ("Always Show Toolbar", "始终显示工具栏"),
    ("AutoSum", "自动求和"),
    ("Backup interval", "备份间隔"),
    ("Banded Rows", "镶边行"),
    ("Banded columns", "镶边列"),
    ("Bigger UI text", "放大界面文字"),
    ("Blank Rows", "空白行"),
    ("Bold", "粗体"),
    ("Bookmark", "书签"),
    ("Borders", "边框"),
    ("Breaks", "换行符"),
    ("Bring forward", "向前移动"),
    ("Bullet", "项目符号"),
    ("CSV format", "CSV 格式"),
    ("Calculation options", "计算选项"),
    ("Caption", "题注"),
    ("Cell Style", "单元格样式"),
    ("Cell lock", "锁定单元格"),
    ("Centre", "中心"),
    ("Change case", "更改大小写"),
    ("Change colour theme", "更改配色主题"),
    ("Change hyphenation", "更改连字符号"),
    ("Change page colour", "更改页面颜色"),
    ("Chat", "聊天"),
    ("Checkbox", "复选框"),
    ("Circle invalid data", "圈释无效数据"),
    ("Clear", "清除"),
    ("Clear filter", "清除筛选"),
    ("Clear style", "清除样式"),
    ("Co-editing mode", "共同编辑模式"),
    ("Collaboration", "协作"),
    ("Combo box", "下拉式方框"),
    ("Comma style", "逗号样式"),
    ("Comment", "批注"),
    ("Complex Field", "复合字段"),
    ("Conditional formatting", "条件格式"),
    ("Convert to range", "转换为范围"),
    ("Copy", "复制"),
    ("Cross-reference", "交叉引用"),
    ("Currency style", "货币样式"),
    ("Cut", "剪切"),
    ("Dark mode", "深色模式"),
    ("Data", "数据"),
    ("Data Validation", "数据验证"),
    ("Data source", "数据来源"),
    ("Data table", "数据表"),
    ("Date & Time", "日期/时间"),
    ("Decrease decimal", "减少小数"),
    ("Decrease indent", "减少缩进"),
    ("Decrement font size", "减小字体大小"),
    ("Delete cells", "删除单元格"),
    ("Delete comment", "删除批注"),
    ("Distributed", "分散对齐"),
    ("Draw", "绘图"),
    ("Dropdown", "下拉菜单"),
    ("Edit footer", "编辑页脚"),
    ("Edit header", "编辑页眉"),
    ("Edit watermark", "编辑水印"),
    ("Email Address", "Email地址"),
    ("Encrypt", "加密"),
    ("Eraser", "橡皮擦"),
    ("External links (import as values)", "外部链接(以值导入)"),
    ("Field list", "字段列表"),
    ("File", "文件"),
    ("Fill", "填充"),
    ("Fill by example", "快速填充"),
    ("Fill colour", "填充顏色"),
    ("Filter button", "筛选按钮"),
    ("Filters", "筛选"),
    ("Financial", "金融"),
    ("First column", "第一列"),
    ("Fit to page", "调整至页面大小"),
    ("Fit to paper", "适合纸张"),
    ("Fit to width", "调整至合适宽度"),
    ("Font", "字体 "),
    ("Font colour", "字体颜色"),
    ("Font size", "字体大小"),
    ("Footnote", "脚注"),
    ("Forecast Sheet", "预测工作表"),
    ("Format as table template", "格式化为表格模板"),
    ("Format cells", "单元格格式"),
    ("Format painter", "格式刷"),
    ("Forms", "表单"),
    ("Formula", "公式"),
    ("Formula Bar", "公式栏"),
    ("Freeze panes", "冻结窗格"),
    ("Furigana", "注音"),
    ("Goal Seek", "单变量求解"),
    ("Grand Total", "总计"),
    ("Gridlines", "网格线"),
    ("Group", "组"),
    ("Header & Footer", "页眉和页脚"),
    ("Header row", "标题行"),
    ("Headings", "标题"),
    ("Hide detail", "隐藏明细"),
    ("Highlight colour", "高亮色"),
    ("Highlighter", "荧光笔"),
    ("Home", "开始"),
    ("Increase decimal", "增加小数"),
    ("Increase indent", "增加缩进"),
    ("Increment font size", "增加字体大小"),
    ("Insert", "插入"),
    ("Insert Pivot Table", "插入数据透视表"),
    ("Insert SmartArt", "插入智能图形"),
    ("Insert Text Art", "插入艺术字"),
    ("Insert blank page", "插入空白页"),
    ("Insert cells", "插入单元格"),
    ("Insert chart", "插入图表"),
    ("Insert column", "插入列"),
    ("Insert content controls", "插入內容控件"),
    ("Insert drop cap", "插入首字下沉"),
    ("Insert equation", "插入方程"),
    ("Insert function", "插入函数"),
    ("Insert image", "插入图片"),
    ("Insert recommended chart", "插入推荐图表"),
    ("Insert shape", "插入形狀"),
    ("Insert slicer", "插入切片器"),
    ("Insert sparkline", "插入迷你图"),
    ("Insert symbol", "插入符号"),
    ("Insert table", "插入表格"),
    ("Insert text box", "插入文本框"),
    ("Italic", "斜体"),
    ("Justified", "两端对齐"),
    ("Last column", "最后一列"),
    ("Layout", "布局"),
    ("Left Panel", "左侧面板"),
    ("Logical", "合乎逻辑"),
    ("Lookup & Reference", "查找和参考"),
    ("Macro list", "列表"),
    ("Macros", "宏"),
    ("Margins", "边距"),
    ("Math & Trig", "数学/三角函数"),
    ("Merge and centre", "合并和居中"),
    ("Merge shapes", "合并形状"),
    ("More functions", "更多函数"),
    ("Multilevel list", "多级列表"),
    ("Multiple pages", "多页"),
    ("Name", "名称"),
    ("Name manager", "名称管理"),
    ("Navigation", "导航"),
    ("New .py", "新建 .py"),
    ("Nonprinting characters", "非打印字符"),
    ("Normal", "常规"),
    ("Number format", "数字格式"),
    ("Number of pages", "页数"),
    ("Numbering", "编号"),
    ("Open", "打开"),
    ("Open folder", "打开文件夹"),
    ("Page Break Preview", "分页预览"),
    ("Page breaks", "分页处"),
    ("Page number", "页面编号"),
    ("Page orientation", "页面方向"),
    ("Page size", "页面大小"),
    ("Paragraph line spacing", "段落行距"),
    ("Paragraph style", "段落样式"),
    ("Paste", "粘贴"),
    ("Paste name", "粘贴名称"),
    ("Pen", "笔"),
    ("Percent style", "百分比样式"),
    ("Phone Number", "电话号码"),
    ("Picture", "图片"),
    ("Pivot Table", "数据透视表"),
    ("PivotChart", "数据透视图"),
    ("Print", "打印"),
    ("Print Area", "打印区域"),
    ("Print gridlines", "打印网格线"),
    ("Print headings", "打印行标签和列标签"),
    ("Print titles", "打印标题"),
    ("Protect Range", "保护范围"),
    ("Protect sheet", "保护工作表"),
    ("Protect workbook", "保护工作簿"),
    ("Protection", "保护"),
    ("Python functions", "Python 函数"),
    ("Radio Button", "单选按钮"),
    ("Recently used", "最近使用的函数"),
    ("Record actions", "记录操作"),
    ("Recover", "恢复"),
    ("References", "引用"),
    ("Remove Duplicates", "删除重复项"),
    ("Remove arrows", "删除追踪箭头"),
    ("Remove duplicates", "删除重复项"),
    ("Replace", "替换"),
    ("Report Layout", "报表布局"),
    ("Resize table", "调整表格大小"),
    ("Ribbon macros", "功能区的宏"),
    ("Right Panel", "右侧面板"),
    ("Right-to-left text", "文字方向(从右横排)"),
    ("Ruby", "亚洲文本标音"),
    ("Rulers", "标尺"),
    ("Save", "保存"),
    ("Scale To Fit", "缩放以适合"),
    ("Scenario", "方案"),
    ("Select", "选择"),
    ("Select all", "全选"),
    ("Send Backward", "下移一层"),
    ("Shading", "阴影"),
    ("Sheet View", "工作表视图"),
    ("Show comments", "显示批注"),
    ("Show details", "显示详细资料"),
    ("Show formulas", "显示公式"),
    ("Show line numbers", "显示行号"),
    ("Show values as", "值的显示方式"),
    ("Show zeros", "显示 0"),
    ("Signature", "签名"),
    ("Smaller UI text", "缩小界面文字"),
    ("Solver", "规划求解"),
    ("Sort", "分类"),
    ("Sort ascending", "升序排序"),
    ("Sort descending", "降序排序"),
    ("Split", "拆分窗口"),
    ("Status Bar", "状态栏"),
    ("Strikethrough", "删除线"),
    ("Style", "样式"),
    ("Subscript", "下标"),
    ("Subtotals", "小计"),
    ("Suggest read-only", "建议只读"),
    ("Superscript", "上标"),
    ("Switch the sheet direction so that the first column is on the right side", "切换工作表方向，使第一列在右侧"),
    ("Table Design", "表格设计"),
    ("Table of contents", "目录"),
    ("Table of figures", "图表目录"),
    ("Text Field", "文本字段"),
    ("Text direction", "文字方向"),
    ("Text from File", "来自文件的文本"),
    ("Text functions", "文本"),
    ("Text orientation", "文字方向"),
    ("Text to columns", "分列"),
    ("Text to data", "文本转数据"),
    ("Total row", "汇总行"),
    ("Trace Dependents", "追踪从属单元格"),
    ("Trace Precedents", "追踪引用单元格"),
    ("Track changes", "跟踪更改"),
    ("Underline", "下划线"),
    ("Ungroup", "取消组合"),
    ("Update", "更新"),
    ("Update all", "全部更新"),
    ("Update table of contents", "更新目录"),
    ("Update table of figures", "更新图表目录"),
    ("Version history", "版本历史"),
    ("View", "显示"),
    ("Watch window", "监视窗口"),
    ("Wrap text", "自动换行"),
    ("Write macro", "编写宏"),
    ("Zoom in", "放大"),
    ("Zoom out", "缩小"),
    ("Zoom to 100%", "缩放到 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

