//! リボンの es の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py es > face/src/ribbon_es.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Añadir comentario"),
    ("Add Text", "Añadir texto"),
    ("Add digital signature", "Agregar firma digital"),
    ("Add link", "Añadir enlace "),
    ("Add to area", "Añadir rango"),
    ("Align bottom", "Alinear hacia abajo"),
    ("Align left", "Alinear a la izquierda"),
    ("Align middle", "Alinear al medio"),
    ("Align right", "Alinear a la derecha"),
    ("Align top", "Alinear hacia arriba"),
    ("Alignment", "Alineación"),
    ("Allowed actions", "Operaciones permitidas"),
    ("Always Show Toolbar", "Mostrar siempre la barra de herramientas"),
    ("AutoSum", "Autosuma"),
    ("Backup interval", "Intervalo de copias"),
    ("Banded Rows", "Filas con bandas"),
    ("Banded columns", "Columnas con bandas"),
    ("Bigger UI text", "Agrandar texto de la pantalla"),
    ("Blank Rows", "Filas en blanco"),
    ("Bold", "Negrita"),
    ("Bookmark", "Marcador"),
    ("Borders", "Bordes"),
    ("Breaks", "Saltos"),
    ("Bring forward", "Traer adelante"),
    ("Bullet", "Viñeta"),
    ("CSV format", "Formato CSV"),
    ("Calculation options", "Cálculo"),
    ("Caption", "Título"),
    ("Cell Style", "Estilo de celda"),
    ("Cell lock", "Bloquear celda"),
    ("Centre", "Alinear al centro"),
    ("Change case", "Cambiar mayúsculas y minúsculas"),
    ("Change colour theme", "Cambiar combinación de colores"),
    ("Change hyphenation", "Cambiar guiones"),
    ("Change page colour", "Cambiar color de página"),
    ("Checkbox", "Casilla"),
    ("Circle invalid data", "Rodear con un círculo los datos no válidos"),
    ("Clear", "Limpiar"),
    ("Clear filter", "Borrar filtro"),
    ("Clear style", "Eliminar estilo"),
    ("Co-editing mode", "Modo de coedición"),
    ("Collaboration", "Colaboración"),
    ("Combo box", "Cuadro combinado"),
    ("Comma style", "Estilo de coma"),
    ("Comment", "Comentario"),
    ("Complex Field", "Campo complejo"),
    ("Conditional formatting", "Formato condicional"),
    ("Convert to range", "Convertir al intervalo "),
    ("Copy", "Copiar "),
    ("Cross-reference", "Referencia cruzada"),
    ("Currency style", "Estilo de moneda"),
    ("Cut", "Cortar"),
    ("Dark mode", "Modo oscuro"),
    ("Data", "Datos"),
    ("Data Validation", "Validación de datos"),
    ("Data source", "Origen de datos"),
    ("Data table", "Tabla de datos"),
    ("Date & Time", "Fecha y hora"),
    ("Decrease decimal", "Disminuir decimales"),
    ("Decrease indent", "Reducir sangría"),
    ("Decrement font size", "Reducir tamaño de letra"),
    ("Delete cells", "Eliminar celdas"),
    ("Delete comment", "Eliminar comentario"),
    ("Distributed", "Distribuido"),
    ("Draw", "Dibujar"),
    ("Dropdown", "Desplegable"),
    ("Edit footer", "Editar pie de página"),
    ("Edit header", "Editar encabezado"),
    ("Edit watermark", "Editar marca de agua"),
    ("Email Address", "Dirección de correo electrónico"),
    ("Encrypt", "Cifrar"),
    ("Eraser", "Borrador"),
    ("External links (import as values)", "Vínculos externos (importar como valores)"),
    ("Field list", "Lista de campos"),
    ("File", "Archivo"),
    ("Fill", "Rellenar"),
    ("Fill by example", "Relleno rápido"),
    ("Fill colour", "Color de relleno"),
    ("Filter button", "Botón de filtro"),
    ("Filters", "Filtros"),
    ("Financial", "Financiero"),
    ("First column", "Primera columna"),
    ("Fit to page", "Ajustar a la página"),
    ("Fit to paper", "Ajustar al papel"),
    ("Fit to width", "Ajustar al ancho"),
    ("Font", "Fuente"),
    ("Font colour", "Color de la fuente"),
    ("Font size", "Tamaño de la fuente"),
    ("Footnote", "Nota a pie de página"),
    ("Forecast Sheet", "Hoja de pronóstico"),
    ("Format as table template", "Formatear como plantilla de tabla"),
    ("Format cells", "Dar formato a celdas"),
    ("Format painter", "Copiar formato"),
    ("Forms", "Formularios"),
    ("Formula", "Fórmula"),
    ("Formula Bar", "Barra de fórmulas"),
    ("Freeze panes", "Congelar paneles"),
    ("Goal Seek", "Buscar Objetivo"),
    ("Grand Total", "Total general"),
    ("Gridlines", "Líneas de cuadrícula"),
    ("Group", "Agrupar"),
    ("Header & Footer", "Encabezado/Pie de página"),
    ("Header row", "Fila de encabezado"),
    ("Headings", "Títulos"),
    ("Hide detail", "Ocultar detalle"),
    ("Highlight colour", "Color de resaltado"),
    ("Highlighter", "Marcador de resaltado"),
    ("Home", "Inicio"),
    ("Increase decimal", "Aumentar decimales"),
    ("Increase indent", "Aumentar sangría"),
    ("Increment font size", "Aumentar tamaño de letra"),
    ("Insert", "Insertar"),
    ("Insert Pivot Table", "Insertar tabla dinámica"),
    ("Insert SmartArt", "Insertar SmartArt"),
    ("Insert Text Art", "Insertar Galería de Texto"),
    ("Insert blank page", "Insertar página en blanco"),
    ("Insert cells", "Insertar celdas"),
    ("Insert chart", "Insertar gráfico"),
    ("Insert column", "Insertar columna"),
    ("Insert content controls", "Insertar controles de contenido"),
    ("Insert drop cap", "Insertar letra capitular"),
    ("Insert equation", "Insertar ecuación"),
    ("Insert function", "Insertar función"),
    ("Insert image", "Insertar imagen"),
    ("Insert recommended chart", "Insertar gráfico recomendado"),
    ("Insert shape", "Insertar forma"),
    ("Insert slicer", "Insertar segmentación de datos"),
    ("Insert sparkline", "Insertar minigráfico"),
    ("Insert symbol", "Insertar symboló"),
    ("Insert table", "Insertar tabla"),
    ("Insert text box", "Insertar cuadro de texto"),
    ("Justified", "Alineado"),
    ("Last column", "Última columna"),
    ("Layout", "Diseño"),
    ("Left Panel", "Panel izquierdo"),
    ("Logical", "Lógico"),
    ("Lookup & Reference", "Búsqueda y referencia"),
    ("Macro list", "Lista"),
    ("Margins", "Márgenes"),
    ("Math & Trig", "Matemáticas y trigonometría"),
    ("Merge and centre", "Combinar y centrar"),
    ("Merge shapes", "Fusionar formas"),
    ("More functions", "Más funciones"),
    ("Multilevel list", "Esquema"),
    ("Multiple pages", "Múltiples páginas"),
    ("Name", "Nombre"),
    ("Name manager", "Administrador de nombres"),
    ("Navigation", "Navegación"),
    ("New .py", "Nuevo .py"),
    ("Nonprinting characters", "Caracteres no imprimibles"),
    ("Number format", "Formato de número"),
    ("Number of pages", "Número de páginas"),
    ("Numbering", "Numeración"),
    ("Open", "Abrir"),
    ("Open folder", "Abrir carpeta"),
    ("Page Break Preview", "Vista previa de salto de página"),
    ("Page breaks", "Cortes del papel"),
    ("Page number", "Numeración de páginas"),
    ("Page orientation", "Orientación"),
    ("Page size", "Tamaño de la página"),
    ("Paragraph line spacing", "Espaciado de línea de párrafo"),
    ("Paragraph style", "Estilo de párrafo"),
    ("Paste", "Pegar"),
    ("Paste name", "Pegar nombre"),
    ("Pen", "Bolígrafo"),
    ("Percent style", "Estilo de porcentajes"),
    ("Phone Number", "Número de teléfono"),
    ("Picture", "Imagen"),
    ("Pivot Table", "Tabla dinámica"),
    ("PivotChart", "Gráfico dinámico"),
    ("Print", "Imprimir"),
    ("Print Area", "Área de impresión"),
    ("Print gridlines", "Imprimir líneas de cuadrícula"),
    ("Print headings", "Imprimir encabezados"),
    ("Print layout", "Diseño de impresión"),
    ("Print titles", "Imprimir títulos"),
    ("Protect Range", "Proteger rango"),
    ("Protect sheet", "Proteger hoja"),
    ("Protect workbook", "Proteger libro"),
    ("Protection", "Protección"),
    ("Python functions", "Funciones de Python"),
    ("Radio Button", "Botón de opción"),
    ("Recently used", "Usadas recientemente"),
    ("Record actions", "Grabar acciones"),
    ("Recover", "Recuperar"),
    ("References", "Referencias"),
    ("Remove Duplicates", "Eliminar duplicados"),
    ("Remove arrows", "Quitar flechas"),
    ("Remove duplicates", "Quitar duplicados"),
    ("Replace", "Reemplazar"),
    ("Report Layout", "Diseño de informe"),
    ("Resize table", "Tamaño de la tabla"),
    ("Ribbon macros", "Macros de la cinta"),
    ("Right Panel", "Panel derecho"),
    ("Right-to-left text", "Texto de derecha a izquierda"),
    ("Rulers", "Reglas"),
    ("Save", "Guardar"),
    ("Scale To Fit", "Ajustar área de impresión"),
    ("Scenario", "Escenario"),
    ("Select", "Seleccionar"),
    ("Select all", "Seleccionar todo"),
    ("Send Backward", "Enviar atrás"),
    ("Shading", "Sombreado"),
    ("Sheet View", "Vista de hoja"),
    ("Show comments", "Mostrar comentarios"),
    ("Show details", "Mostrar detalles"),
    ("Show formulas", "Mostrar fórmulas"),
    ("Show line numbers", "Mostrar números de línea"),
    ("Show values as", "Tipo de cálculo"),
    ("Show zeros", "Mostrar ceros"),
    ("Signature", "Firma"),
    ("Smaller UI text", "Reducir texto de la pantalla"),
    ("Sort", "Ordenar"),
    ("Sort ascending", "Clasificar en orden ascendente"),
    ("Sort descending", "Clasificar en orden descendente"),
    ("Split", "Dividir ventana"),
    ("Status Bar", "Barra de estado"),
    ("Strikethrough", "Tachado"),
    ("Style", "Estilo"),
    ("Subscript", "Subíndice"),
    ("Subtotals", "Subtotales"),
    ("Suggest read-only", "Sugerir solo lectura"),
    ("Superscript", "Sobreíndice"),
    ("Switch the sheet direction so that the first column is on the right side", "Cambiar la dirección de la hoja para que la primera columna esté a la derecha"),
    ("Table Design", "Diseño de tabla"),
    ("Table of contents", "Tabla de contenidos"),
    ("Table of figures", "Tabla de ilustraciones"),
    ("Text Field", "Campo de texto"),
    ("Text direction", "Dirección del texto"),
    ("Text from File", "Texto de archivo"),
    ("Text functions", "Texto"),
    ("Text orientation", "Orientación del texto"),
    ("Text to columns", "Texto en columnas"),
    ("Text to data", "Texto a datos"),
    ("Total row", "Fila de totales"),
    ("Trace Dependents", "Rastrear dependientes"),
    ("Trace Precedents", "Rastrear precedentes"),
    ("Track changes", "Rastrear cambios"),
    ("Underline", "Subrayar"),
    ("Ungroup", "Desagrupar"),
    ("Update", "Actualizar"),
    ("Update all", "Actualizar todo"),
    ("Update table of contents", "Actualizar tabla de contenido"),
    ("Update table of figures", "Actualizar tabla de ilustraciones"),
    ("Version history", "Historial de versiones"),
    ("View", "Mostrar"),
    ("Watch window", "Ventana Inspección"),
    ("Wrap text", "Ajustar texto"),
    ("Write macro", "Escribir macro"),
    ("Zoom in", "Acercar"),
    ("Zoom out", "Alejar"),
    ("Zoom to 100%", "Zoom al 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

