//! リボンの tr 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py tr > face/src/ribbon_tr.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Dosya", cmds: &[
        c("open", "Aç", "open"),
        c("save", "Kaydet", "save"),
        c("pdf", "Yazdır", "print"),
    ]},
    Tab { name: "Ana Sayfa", cmds: &[
        c("copy", "Kopyala", "copy"),
        c("cut", "Kes", "cut"),
        c("paste", "Yapıştır", "paste"),
        c("fontname", "Yazı Tipi", "fontname"),
        c("fontsize", "Yazıtipi boyutu", "fontsize"),
        c("incfont", "Yazı boyutunu arttır", "incfont"),
        c("decfont", "Yazı boyutunu azalt", "decfont"),
        c("changecase", "Büyük/küçük harf değiştir", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Kalın", "bold"),
        c("italic", "Eğik", "italic"),
        c("underline", "Altı çizili", "underline"),
        c("strikeout", "Üstü çizili", "strikeout"),
        c("superscript", "Üst Simge", "superscript"),
        c("subscript", "Altsimge", "subscript"),
        c("highlight", "Vurgu Rengi", "highlight"),
        c("fontcolor", "Yazı Tipi Rengi", "fontcolor"),
        c("clearstyle", "Stili Temizle", "clearstyle"),
        c("markers", "Madde", "markers"),
        c("numbering", "Numaralandırma", "numbering"),
        c("multilevels", "Çok düzeyli liste", "multilevels"),
        c("decoffset", "Girintiyi azalt", "decoffset"),
        c("incoffset", "Girintiyi arttır", "incoffset"),
        c("linespace", "Paragraf satır aralığı", "linespace"),
        c("direction", "Metin yönü", "direction"),
        c("align-left", "Sola Hizala", "align-left"),
        c("align-center", "Orta", "align-center"),
        c("align-right", "Sağa Hizala", "align-right"),
        c("align-just", "İki yana yaslı", "align-just"),
        c("align-dist", "Dağıtılmış", "align-dist"),
        c("hidenchars", "Basılmaz Karakterler", "hidenchars"),
        c("paracolor", "Paragraf Arka Plan Rengi", "paracolor"),
        c("borders", "Kenarlıklar", "borders"),
        c("parastyle", "Paragraf Stili", "styles"),
        c("replace", "Değiştir", "replace"),
        c("selectall", "Tümünü seç", "select-all"),
    ]},
    Tab { name: "Ekle", cmds: &[
        c("blankpage", "Boş sayfa ekle", "blankpage"),
        c("pagebreak", "Sonlar", "pagebreak"),
        c("instable", "Tablo ekle", "instable"),
        c("insimage", "Resim ekle", "insertimage"),
        c("insshape", "Şekil ekle", "insshape"),
        c("inssmartart", "SmartArt ekle", "inssmartart"),
        c("inschart", "Grafik ekle", "inschart"),
        c("instext", "Metin kutusu ekle", "instext"),
        c("instextart", "Yazı Sanatı Ekle", "instextart"),
        c("dropcap", "Büyük Harf Ekle", "dropcap"),
        c("text-from-file", "Dosyadan metin", "text-from-file"),
        c("edit-header", "Üst Bilgiyi Düzenle", "edit-header"),
        c("edit-footer", "Altlığı Düzenle", "edit-footer"),
        c("pagenum", "Sayfa Numarası", "pagenum"),
        c("datetime", "Tarih/Saat", "datetime"),
        c("numpages", "Sayfa sayısı", "numpages"),
        c("insequation", "Denklem Ekle", "insequation"),
        c("inssymbol", "Simge ekle", "inssymbol"),
        c("controls", "İçerik kontrolleri ekle ", "controls"),
    ]},
    Tab { name: "Çizim", cmds: &[
        c("pen", "Kalem", "pen"),
        c("highlighter", "Vurgulayıcı", "highlighter"),
        c("eraser", "Silgi", "eraser"),
    ]},
    Tab { name: "Tasarım", cmds: &[
        c("pagemargins", "Kenar Boşlukları", "pagemargins"),
        c("pageorient", "Oryantasyon", "pageorient"),
        c("pagesize", "Sayfa Boyutu", "pagesize"),
        c("columns", "Sütun Ekle", "columns"),
        c("line-numbers", "Satır numaralarını göster", "line-numbers"),
        c("hyphenation", "Hecelemeyi Değiştir", "hyphenation"),
        x("İleri Taşı", "img-movefrwd"),
        x("Geri Gönder", "img-movebkwd"),
        x("Hiza", "img-align"),
        x("Grup", "img-group"),
        x("Şekilleri birleştir", "shapes-merge"),
        c("watermark", "Filigranı düzenle", "watermark"),
        c("pagecolor", "Sayfa Rengini Değiştir", "pagecolor"),
        c("colorschemas", "Renk Şemasını Değiştir", "colorschemas"),
    ]},
    Tab { name: "Kaynakça", cmds: &[
        c("toc", "İçindekiler Tablosu", "contents"),
        c("add-text", "Metin Ekle", "add-text"),
        c("toc-update", "İçindekiler tablosunu güncelle", "contents-update"),
        c("bookmarks", "Yer imi", "bookmarks"),
        c("caption", "Resim yazısı", "caption"),
        c("crossref", "Çapraz referans", "crossref"),
        c("footnote", "Dipnot", "footnote"),
        c("tof", "Şekiller tablosu", "tof"),
        c("tof-update", "Şekiller tablosunu güncelle", "tof-update"),
    ]},
    Tab { name: "Formlar", cmds: &[
        c("form-text", "Metin Alanı", "form-text"),
        c("form-combo", "Açılan kutu", "form-combo"),
        c("form-dropdown", "Aşağı açılır", "form-dropdown"),
        c("form-checkbox", "Onay kutusu", "form-checkbox"),
        c("form-radio", "Seçenek Düğmesi", "form-radio"),
        c("form-image", "Resim", "form-image"),
        c("form-email", "Eposta adresi", "form-email"),
        c("form-phone", "Telefon numarası", "form-phone"),
        c("form-complex", "Karmaşık alan", "form-complex"),
        c("form-signature", "İmza", "form-signature"),
        c("form-name", "Ad", "form-name"),
    ]},
    Tab { name: "Ortak Çalışma", cmds: &[
        c("coauth-mode", "Birlikte düzenleme modu", "coauth-mode"),
        c("co-addcomment", "Yorum Ekle", "co-addcomment"),
        c("co-delcomment", "Açıklamayı sil", "co-delcomment"),
        c("co-showcomment", "Yorumu göster", "co-showcomment"),
        c("co-chat", "Sohbet", "co-chat"),
        c("track-changes", "Değişiklikleri izle", "track-changes"),
        c("co-history", "Sürüm geçmişi", "co-history"),
    ]},
    Tab { name: "Koruma", cmds: &[
        c("prot-sign", "Dijital imza ekle", "prot-sign"),
        c("prot-doc", "Koruma", "prot-doc"),
    ]},
    Tab { name: "Görüntüle", cmds: &[
        t("nav", "Gezinti", "nav"),
        c("fit-page", "Sayfaya Sığdır", "fit-page"),
        c("fit-width", "Genişliğe Sığdır", "fit-width"),
        c("zoom100", "%100'e yakınlaştır", "zoom100"),
        c("zoom-in", "Yakınlaştır", "zoom-in"),
        c("zoom-out", "Uzaklaştır", "zoom-out"),
        c("printview", "Yazdırma düzeni", "printview"),
        c("multipage", "Çoklu sayfa", "multipage"),
        t("darkmode", "Karanlık mod", "darkmode"),
        c("ui-bigger", "Ekran yazısını büyüt", "ui-bigger"),
        c("ui-smaller", "Ekran yazısını küçült", "ui-smaller"),
        c("ruler", "Cetveller", "ruler"),
        t("show-toolbar", "Her zaman araç çubuğunu göster", "show-toolbar"),
        t("show-statusbar", "Durum Çubuğu", "show-statusbar"),
        t("show-left", "Sol Panel", "show-left"),
        t("show-right", "Sağ Panel", "show-right"),
    ]},
    Tab { name: "Makrolar", cmds: &[
        c("py-list", "Liste", "plug-manage"),
        c("py-folder", "Klasörü aç", "py-folder"),
        c("ai-macro", "Makro yaz", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Dosya", cmds: &[
        c("open", "Aç", "open"),
        c("save", "Kaydet", "save"),
        c("pdf", "Yazdır", "print"),
    ]},
    Tab { name: "Ana Sayfa", cmds: &[
        c("copy", "Kopyala", "copy"),
        c("cut", "Kes", "cut"),
        c("paste", "Yapıştır", "paste"),
        c("copystyle", "Biçim boyacısı", "copystyle"),
        c("fontname", "Yazı Tipi", "fontname"),
        c("fontsize", "Yazıtipi boyutu", "fontsize"),
        c("incfont", "Yazı boyutunu arttır", "incfont"),
        c("decfont", "Yazı boyutunu azalt", "decfont"),
        c("changecase", "Büyük/küçük harf değiştir", "changecase"),
        c("bold", "Kalın", "bold"),
        c("italic", "Eğik", "italic"),
        c("underline", "Altı çizili", "underline"),
        c("strikeout", "Üstü çizili", "strikeout"),
        c("subscript", "Altsimge", "subscript"),
        c("fontcolor", "Yazı Tipi Rengi", "fontcolor"),
        c("fillparag", "Dolgu Rengi", "fillparag"),
        c("borders", "Kenarlıklar", "borders"),
        c("top", "Üste Hizala", "top"),
        c("middle", "Ortaya hizala", "middle"),
        c("bottom", "Alta Hizala", "bottom"),
        c("wrap", "Metni kaydır", "wrap"),
        c("text-orient", "Oryantasyon", "text-orient"),
        c("align-left", "Sola Hizala", "align-left"),
        c("align-center", "Orta", "align-center"),
        c("align-right", "Sağa Hizala", "align-right"),
        c("align-just", "İki yana yaslı", "align-just"),
        c("align-dist", "Dağıtılmış", "align-dist"),
        c("merge", "Birleştir ve ortala", "merge"),
        c("direction", "Metin yönü (sağdan sola)", "direction"),
        c("sum", "Otomatik Toplam", "autosum"),
        c("fill-num", "Doldur", "fill-num"),
        c("defname", "Manager", "named-range"),
        c("clear", "Temizle", "clear"),
        c("sort-desc", "En yüksekten en aza sırala", "sortdesc"),
        c("sort-asc", "En düşükten en yükseğe sırala", "sortasc"),
        c("setfilter", "Filtreler", "setfilter"),
        c("clear-filter", "Filtreyi temizle", "clear-filter"),
        c("format", "Sayı Formatı", "format"),
        c("currency", "Kur Stili", "currency"),
        c("percents", "Yüzde Stili", "percents"),
        c("comma", "Virgül stili", "comma"),
        c("digit-dec", "Ondalık Azalt", "digit-dec"),
        c("digit-inc", "Ondalık Arttır", "digit-inc"),
        c("cell-ins", "Hücre Ekle", "cell-ins"),
        c("cell-del", "Hücre Sil", "cell-del"),
        c("cell-format", "Hücreleri biçimlendir", "cell-format"),
        c("condformat", "Koşullu biçimlendirme", "condformat"),
        c("table-tpl", "Tablo Şablonu olarak biçimlendir", "table-tpl"),
        c("cell-styles", "Hücre Stili", "styles"),
        c("replace", "Değiştir", "replace"),
        c("selectall", "Tümünü seç", "select-all"),
    ]},
    Tab { name: "Ekle", cmds: &[
        c("pivot-insert", "Pivot Tablo Ekle", "add-pivot"),
        c("instable", "Tablo ekle", "instable"),
        c("insimage", "Resim ekle", "insimage-c"),
        c("insshape", "Şekil ekle", "insshape"),
        c("inssmartart", "SmartArt ekle", "inssmartart"),
        c("inscheckbox", "Onay kutusu", "inscheckbox"),
        c("insrecommend", "Önerilen grafik ekle", "insrecommend"),
        c("inschart", "Grafik ekle", "inschart"),
        c("inssparkline", "Mini grafik ekle", "inssparkline"),
        c("co-addcomment", "Yorumlar", "ins-comment"),
        c("inshyperlink", "Köprü Ekle", "inshyperlink"),
        c("insslicer", "Dilimleyici Ekle ", "insslicer"),
        c("instext", "Metin kutusu ekle", "instext"),
        c("instextart", "Yazı Sanatı Ekle", "instextart"),
        c("edit-header", "Üst/Alt Bilgi", "editheader"),
        c("insequation", "Denklem Ekle", "insequation"),
        c("inssymbol", "Simge ekle", "inssymbol"),
    ]},
    Tab { name: "Çizim", cmds: &[
        c("draw-select", "Seç", "select-tool"),
        c("pen", "Kalem", "pen"),
        c("highlighter", "Vurgulayıcı", "highlighter"),
        c("eraser", "Silgi", "eraser"),
    ]},
    Tab { name: "Tasarım", cmds: &[
        c("pagemargins", "Kenar Boşlukları", "pagemargins"),
        c("pageorient", "Oryantasyon", "pageorient"),
        c("pagesize", "Sayfa Boyutu", "pagesize"),
        c("printarea", "Yazdırma Alanı", "printarea"),
        c("pagebreak", "Sonlar", "pagebreak"),
        c("edit-header", "Üst/Alt Bilgi", "editheader"),
        c("scale", "Sığdırmak için Ölçekle", "scale"),
        c("fit-pages", "Kâğıda sığdır", "fit-pages"),
        c("printarea-add", "Aralık ekle", "printarea-add"),
        c("show-breaks", "Sayfa sonları", "show-breaks"),
        c("printtitles", "Başlıkları yazdır", "printtitles"),
        c("rtl-sheet", "Sayfa yönünü ilk sütun sağda olacak şekilde değiştir", "rtl-sheet"),
        c("print-gridlines", "Kılavuz çizgileri de yazdır", "print-gridlines"),
        c("print-headings", "Başlıkları da yazdır", "print-headings"),
        x("İleri Taşı", "img-movefrwd"),
        x("Geri Gönder", "img-movebkwd"),
        x("Hiza", "img-align"),
        x("Grup", "img-group"),
        x("Şekilleri birleştir", "shapes-merge"),
        c("colorschemas", "Renk Şemasını Değiştir", "colorschemas"),
    ]},
    Tab { name: "Formül", cmds: &[
        c("insert-function", "İşlev ekle", "additional-formula"),
        c("func-list", "Python işlevleri", "py-list"),
        c("sum", "Otomatik Toplam", "autosum"),
        c("fn-recent", "Son kullanılan işlevler", "recent"),
        c("fn-financial", "Finansal", "financial"),
        c("fn-logical", "Mantıksal", "logical"),
        c("fn-text", "Metin", "text"),
        c("fn-datetime", "Tarih/Saat", "datetime"),
        c("fn-lookup", "Arama ve Referans", "lookup"),
        c("fn-math", "Matematik/Trigonometri", "math"),
        c("fn-more", "Daha fazla fonksiyon", "more"),
        c("defname", "Manager", "named-range-huge"),
        c("paste-name", "Ad yapıştır", "paste-name"),
        c("trace-prec", "Etkileyenleri izle", "trace-prec"),
        c("trace-dep", "Etkilenenleri izle", "trace-dep"),
        c("remove-arrows", "Okları kaldır", "remove-arrows"),
        c("show-formulas", "Formülleri göster", "show-formulas"),
        c("watch", "Gözcü penceresi", "watch-window"),
        c("calc-mode", "Hesaplama", "calculate"),
    ]},
    Tab { name: "Veri", cmds: &[
        c("data-from-text", "Metinden veri", "data-from-text"),
        c("data-external-links", "Dış bağlantılar (değer olarak al)", "data-external-links"),
        c("setfilter", "Filtreler", "setfilter"),
        c("clear-filter", "Filtreyi temizle", "clear-filter"),
        c("sort-desc", "En yüksekten en aza sırala", "sortdesc"),
        c("sort-asc", "En düşükten en yükseğe sırala", "sortasc"),
        c("custom-sort", "Sırala", "custom-sort"),
        c("text-column", "Metni sütunlara dönüştür", "text-column"),
        c("rem-duplicates", "Yinelenenleri kaldır", "rem-duplicates"),
        c("data-validation", "Veri doğrulama", "data-validation"),
        c("goal-seek", "Hedef Ara", "goal-seek"),
        c("solver", "Çözücü", "solver"),
        c("group", "Grup", "group"),
        c("ungroup", "Gruptan çıkar", "ungroup"),
        c("show-details", "Detayları Göster", "show-details"),
        c("hide-details", "Ayrıntıyı gizle", "hide-details"),
        c("subtotal", "Ara toplamlar", "subtotal"),
        c("datatable", "Veri tablosu", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "CSV biçimi", "csv-kind"),
        c("flash-fill", "Hızlı doldurma", "flash-fill"),
    ]},
    Tab { name: "Makrolar", cmds: &[
        c("rec-toggle", "İşlemleri kaydet", "py-run"),
        c("py-new", "Yeni .py", "py-new"),
        c("py-list", "Liste", "py-list"),
        c("ribbon-list", "Şerit makroları", "py-line"),
        c("py-folder", "Klasörü aç", "py-folder"),
    ]},
    Tab { name: "Pivot Tablo", cmds: &[
        c("pivot-insert", "Pivot Tablo Ekle", "pivot-insert"),
        c("pivot-fields", "Alan listesi", "pivot-fields"),
        c("pivot-refresh", "Yenile", "pivot-refresh"),
        c("pivot-refresh-all", "Tümünü yenile", "pivot-refresh-all"),
        c("pivot-select", "Seç", "pivot-select"),
        c("pivot-totals", "Genel Toplamlar", "pivot-totals"),
        c("pivot-subtotals", "Ara toplamlar", "pivot-subtotals"),
        c("pivot-blank", "Boş Satırlar", "pivot-blank"),
        c("pivot-showas", "Hesaplama türü", "pivot-showas"),
        c("pivot-layout", "Rapor Düzeni", "pivot-layout"),
        c("pivot-style", "Stil", "pivot-style"),
    ]},
    Tab { name: "Tablo tasarımı", cmds: &[
        c("td-header", "Üst bilgi satırı", "td-header"),
        c("td-total", "Toplam satırı", "td-total"),
        c("td-band-row", "Bantlı Satırlar", "td-band-row"),
        c("td-first", "İlk Sütun", "td-first"),
        c("td-last", "Son sütun", "td-last"),
        c("td-band-col", "Şeritli sütunlar", "td-band-col"),
        c("td-filter", "Filtre düğmesi", "td-filter"),
        c("rem-duplicates", "Yinelenenleri Kaldır", "td-remdup"),
        c("td-torange", "Aralığa dönüştür", "td-torange"),
        c("td-resize", "Tabloyu yeniden boyutlandır", "td-resize"),
    ]},
    Tab { name: "Ortak Çalışma", cmds: &[
        c("coauth-mode", "Birlikte düzenleme modu", "coauth-mode"),
        c("co-addcomment", "Yorum Ekle", "co-addcomment"),
        c("co-delcomment", "Açıklamayı sil", "co-delcomment"),
        c("co-showcomment", "Yorumu göster", "co-showcomment"),
        c("co-chat", "Sohbet", "co-chat"),
        c("co-history", "Sürüm geçmişi", "co-history"),
    ]},
    Tab { name: "Koruma", cmds: &[
        c("prot-encrypt", "Şifrele", "prot-encrypt"),
        xt("Çalışma Kitabını Koru", "protect-workbook"),
        c("prot-doc", "Sayfayı Koruyun", "protect-sheet"),
        xt("Aralığı koru", "protect-range"),
        c("prot-sign", "Dijital imza ekle", "prot-sign"),
        c("cell-lock", "Hücre kilidi", "cell-lock"),
        c("prot-allow", "İzin verilen işlemler", "prot-allow"),
        c("recover", "Kurtarma", "recover"),
        c("recover-every", "Yedek aralığı", "recover-every"),
        c("read-only-rec", "Salt okunur öner", "read-only-rec"),
    ]},
    Tab { name: "Görüntüle", cmds: &[
        c("sheet-view", "Sayfa Görünümü", "sheet-view"),
        xm("Normal", "view-normal"),
        xm("Sayfa Sonu Önizlemesi", "view-pagebreak"),
        c("zoom-in", "Yakınlaştır", "zoom-in"),
        c("zoom-out", "Uzaklaştır", "zoom-out"),
        c("zoom100", "%100'e yakınlaştır", "zoom100"),
        c("ui-bigger", "Ekran yazısını büyüt", "ui-bigger"),
        c("ui-smaller", "Ekran yazısını küçült", "ui-smaller"),
        t("darkmode", "Karanlık mod", "theme"),
        c("freeze", "Parçaları Dondur", "freeze"),
        t("formula-bar", "Formül çubuğu", "formula-bar"),
        c("show-gridlines", "Gridlines", "show-gridlines"),
        t("show-headings", "Başlıklar", "show-headings"),
        t("show-zeros", "Sıfırları göster", "show-zeros"),
        t("show-left", "Sol Panel", "show-left"),
        t("show-right", "Sağ Panel", "show-right"),
    ]},
];

