//! リボンの pt 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py pt > face/src/ribbon_pt.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Ficheiro", cmds: &[
        c("open", "Abrir", "open"),
        c("save", "Guardar", "save"),
        c("pdf", "Imprimir", "print"),
    ]},
    Tab { name: "Base", cmds: &[
        c("copy", "Copiar", "copy"),
        c("cut", "Cortar", "cut"),
        c("paste", "Colar", "paste"),
        c("fontname", "Tipo de letra", "fontname"),
        c("fontsize", "Tamanho do tipo de letra", "fontsize"),
        c("incfont", "Aumentar tamanho do tipo de letra", "incfont"),
        c("decfont", "Diminuir tamanho do tipo de letra", "decfont"),
        c("changecase", "Alternar maiúscula/minúscula", "changecase"),
        c("ruby", "Ruby", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Negrito", "bold"),
        c("italic", "Itálico", "italic"),
        c("underline", "Sublinhado", "underline"),
        c("strikeout", "Rasurado", "strikeout"),
        c("superscript", "Sobrescrito", "superscript"),
        c("subscript", "Subscrito", "subscript"),
        c("highlight", "Cor de destaque", "highlight"),
        c("fontcolor", "Cor do tipo de letra", "fontcolor"),
        c("clearstyle", "Limpar estilo", "clearstyle"),
        c("markers", "Marcador", "markers"),
        c("numbering", "Numeração", "numbering"),
        c("multilevels", "Lista multi-níveis", "multilevels"),
        c("decoffset", "Diminuir o Recuo", "decoffset"),
        c("incoffset", "Aumentar recuo", "incoffset"),
        c("linespace", "Espaçamento entre linhas do parágrafo", "linespace"),
        c("direction", "Direção do texto", "direction"),
        c("align-left", "Alinhar à esquerda", "align-left"),
        c("align-center", "Centro", "align-center"),
        c("align-right", "Alinhar à direita", "align-right"),
        c("align-just", "Justificado", "align-just"),
        c("align-dist", "Distribuído", "align-dist"),
        c("hidenchars", "Caracteres não imprimíveis", "hidenchars"),
        c("paracolor", "Cor de fundo do parágrafo", "paracolor"),
        c("borders", "Bordas", "borders"),
        c("parastyle", "Estilo do parágrafo", "styles"),
        c("replace", "Substituir", "replace"),
        c("selectall", "Selecionar tudo", "select-all"),
    ]},
    Tab { name: "Inserir", cmds: &[
        c("blankpage", "Inserir página vazia", "blankpage"),
        c("pagebreak", "Quebras", "pagebreak"),
        c("instable", "Inserir tabela", "instable"),
        c("insimage", "Inserir imagem", "insertimage"),
        c("insshape", "Inserir forma", "insshape"),
        c("inssmartart", "Inserir SmartArt", "inssmartart"),
        c("inschart", "Inserir gráfico", "inschart"),
        c("instext", "Inserir caixa de texto", "instext"),
        c("instextart", "Inserir arte de texto", "instextart"),
        c("dropcap", "Inserir letra capitular", "dropcap"),
        c("text-from-file", "Texto de um ficheiro", "text-from-file"),
        c("edit-header", "Editar cabeçalho", "edit-header"),
        c("edit-footer", "Editar rodapé", "edit-footer"),
        c("pagenum", "Número de página", "pagenum"),
        c("datetime", "Data e hora", "datetime"),
        c("numpages", "Número de páginas", "numpages"),
        c("insequation", "Inserir equação", "insequation"),
        c("inssymbol", "Inserir símbolo", "inssymbol"),
        c("controls", "Adicionar controlos de conteúdo", "controls"),
    ]},
    Tab { name: "Desenhar", cmds: &[
        c("pen", "Caneta", "pen"),
        c("highlighter", "Marcador", "highlighter"),
        c("eraser", "Borracha", "eraser"),
    ]},
    Tab { name: "Disposição", cmds: &[
        c("pagemargins", "Margens", "pagemargins"),
        c("pageorient", "Orientação da página", "pageorient"),
        c("pagesize", "Tamanho da página", "pagesize"),
        c("columns", "Inserir coluna", "columns"),
        c("line-numbers", "Mostrar número das linhas", "line-numbers"),
        c("hyphenation", "Alterar a hifenização", "hyphenation"),
        c("img-movefrwd", "Trazer para a frente", "img-movefrwd"),
        c("img-movebkwd", "Enviar para trás", "img-movebkwd"),
        c("img-align", "Alinhamento", "img-align"),
        c("img-group", "Grupo", "img-group"),
        x("Unir formas", "shapes-merge"),
        c("watermark", "Editar marca d'água", "watermark"),
        c("pagecolor", "Alterar a cor da página", "pagecolor"),
        c("colorschemas", "Alterar esquema de cor", "colorschemas"),
    ]},
    Tab { name: "Referências", cmds: &[
        c("toc", "Índice remissivo", "contents"),
        c("add-text", "Adicionar texto", "add-text"),
        c("toc-update", "Atualizar o índice", "contents-update"),
        c("bookmarks", "Marcador", "bookmarks"),
        c("caption", "Legenda", "caption"),
        c("crossref", "Referência-cruzada", "crossref"),
        c("footnote", "Nota de rodapé", "footnote"),
        c("tof", "Índice de ilustrações", "tof"),
        c("tof-update", "Atualizar o índice de ilustrações", "tof-update"),
    ]},
    Tab { name: "Formulários", cmds: &[
        c("form-text", "Campo de texto", "form-text"),
        c("form-combo", "Caixa de combinação", "form-combo"),
        c("form-dropdown", "Suspenso", "form-dropdown"),
        c("form-checkbox", "Caixa de verificação", "form-checkbox"),
        c("form-radio", "Botão Seleção", "form-radio"),
        c("form-image", "Imagem", "form-image"),
        c("form-email", "Endereço de e-mail", "form-email"),
        c("form-phone", "Número de telefone", "form-phone"),
        c("form-complex", "Campo complexo", "form-complex"),
        c("form-signature", "Assinatura", "form-signature"),
        c("form-name", "Nome", "form-name"),
    ]},
    Tab { name: "Colaboração", cmds: &[
        c("coauth-mode", "Modo de coedição", "coauth-mode"),
        c("co-addcomment", "Adicionar comentário", "co-addcomment"),
        c("co-delcomment", "Eliminar comentário", "co-delcomment"),
        c("co-showcomment", "Mostrar Comentário", "co-showcomment"),
        c("co-chat", "Conversa", "co-chat"),
        c("track-changes", "Rastrear alterações", "track-changes"),
        c("co-history", "Histórico de versões", "co-history"),
    ]},
    Tab { name: "Proteção", cmds: &[
        c("prot-sign", "Adicionar assinatura digital", "prot-sign"),
        c("prot-doc", "Proteção", "prot-doc"),
    ]},
    Tab { name: "Mostrar", cmds: &[
        t("nav", "Navegação", "nav"),
        c("fit-page", "Ajustar à página", "fit-page"),
        c("fit-width", "Ajustar à Largura", "fit-width"),
        c("zoom100", "Ampliar para 100%", "zoom100"),
        c("zoom-in", "Ampliar", "zoom-in"),
        c("zoom-out", "Reduzir", "zoom-out"),
        c("printview", "Esquema de impressão", "printview"),
        c("multipage", "Várias páginas", "multipage"),
        t("darkmode", "Modo escuro", "darkmode"),
        c("ui-bigger", "Aumentar o texto do ecrã", "ui-bigger"),
        c("ui-smaller", "Diminuir o texto do ecrã", "ui-smaller"),
        c("ruler", "Réguas", "ruler"),
        t("show-toolbar", "Mostrar sempre a barra de ferramentas", "show-toolbar"),
        t("show-statusbar", "Barra de estado", "show-statusbar"),
        t("show-left", "Painel esquerdo", "show-left"),
        t("show-right", "Painel direito", "show-right"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("py-list", "Lista", "plug-manage"),
        c("py-folder", "Abrir a pasta", "py-folder"),
        c("ai-macro", "Escrever macro", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Ficheiro", cmds: &[
        c("open", "Abrir", "open"),
        c("save", "Guardar", "save"),
        c("pdf", "Imprimir", "print"),
    ]},
    Tab { name: "Base", cmds: &[
        c("copy", "Copiar", "copy"),
        c("cut", "Cortar", "cut"),
        c("paste", "Colar", "paste"),
        c("copystyle", "Copiar formato", "copystyle"),
        c("fontname", "Tipo de letra", "fontname"),
        c("fontsize", "Tamanho do tipo de letra", "fontsize"),
        c("incfont", "Aumentar tamanho do tipo de letra", "incfont"),
        c("decfont", "Diminuir tamanho do tipo de letra", "decfont"),
        c("changecase", "Alternar maiúscula/minúscula", "changecase"),
        c("bold", "Negrito", "bold"),
        c("italic", "Itálico", "italic"),
        c("underline", "Sublinhado", "underline"),
        c("strikeout", "Rasurado", "strikeout"),
        c("subscript", "Subscrito", "subscript"),
        c("fontcolor", "Cor do tipo de letra", "fontcolor"),
        c("fillparag", "Cor de preenchimento", "fillparag"),
        c("borders", "Bordas", "borders"),
        c("top", "Alinhar em cima", "top"),
        c("middle", "Alinhar ao meio", "middle"),
        c("bottom", "Alinhar em baixo", "bottom"),
        c("wrap", "Moldar o texto", "wrap"),
        c("text-orient", "Orientação do texto", "text-orient"),
        c("align-left", "Alinhar à esquerda", "align-left"),
        c("align-center", "Centro", "align-center"),
        c("align-right", "Alinhar à direita", "align-right"),
        c("align-just", "Justificado", "align-just"),
        c("align-dist", "Distribuído", "align-dist"),
        c("merge", "Unir e centrar", "merge"),
        c("direction", "Direção do texto (da direita para a esquerda)", "direction"),
        c("sum", "Soma automática", "autosum"),
        c("fill-num", "Preencher", "fill-num"),
        c("defname", "Manager", "named-range"),
        c("clear", "Limpar", "clear"),
        c("sort-desc", "Classificar do maior para o menor", "sortdesc"),
        c("sort-asc", "Classificar do menor para o maior", "sortasc"),
        c("setfilter", "Filtros", "setfilter"),
        c("clear-filter", "Limpar filtro", "clear-filter"),
        c("format", "Formato de número", "format"),
        c("currency", "Estilo da moeda", "currency"),
        c("percents", "Estilo de percentagem", "percents"),
        c("comma", "Estilo de vírgula", "comma"),
        c("digit-dec", "Diminuir casas decimais", "digit-dec"),
        c("digit-inc", "Aumentar números decimais", "digit-inc"),
        c("cell-ins", "Inserir células", "cell-ins"),
        c("cell-del", "Eliminar células", "cell-del"),
        c("cell-format", "Formatar células", "cell-format"),
        c("condformat", "Formatação condicional", "condformat"),
        c("table-tpl", "Formatar como modelo de tabela", "table-tpl"),
        c("cell-styles", "Estilo da célula", "styles"),
        c("replace", "Substituir", "replace"),
        c("selectall", "Selecionar tudo", "select-all"),
    ]},
    Tab { name: "Inserir", cmds: &[
        c("pivot-insert", "Inserir tabela dinâmica", "add-pivot"),
        c("instable", "Inserir tabela", "instable"),
        c("insimage", "Inserir imagem", "insimage-c"),
        c("insshape", "Inserir forma", "insshape"),
        c("inssmartart", "Inserir SmartArt", "inssmartart"),
        c("inscheckbox", "Caixa de verificação", "inscheckbox"),
        c("insrecommend", "Inserir gráfico recomendado", "insrecommend"),
        c("inschart", "Inserir gráfico", "inschart"),
        c("inssparkline", "Inserir sparkline", "inssparkline"),
        c("co-addcomment", "Comentários", "ins-comment"),
        c("inshyperlink", "Adicionar hiperligação", "inshyperlink"),
        c("insslicer", "Inserir segmentação de dados", "insslicer"),
        c("instext", "Inserir caixa de texto", "instext"),
        c("instextart", "Inserir arte de texto", "instextart"),
        c("edit-header", "Cabeçalho/rodapé", "editheader"),
        c("insequation", "Inserir equação", "insequation"),
        c("inssymbol", "Inserir símbolo", "inssymbol"),
    ]},
    Tab { name: "Desenhar", cmds: &[
        c("draw-select", "Selecionar", "select-tool"),
        c("pen", "Caneta", "pen"),
        c("highlighter", "Marcador", "highlighter"),
        c("eraser", "Borracha", "eraser"),
    ]},
    Tab { name: "Disposição", cmds: &[
        c("pagemargins", "Margens", "pagemargins"),
        c("pageorient", "Orientação da página", "pageorient"),
        c("pagesize", "Tamanho da página", "pagesize"),
        c("printarea", "Área de impressão", "printarea"),
        c("pagebreak", "Quebras", "pagebreak"),
        c("edit-header", "Cabeçalho/rodapé", "editheader"),
        c("scale", "Ajustar Tamanho", "scale"),
        c("fit-pages", "Ajustar ao papel", "fit-pages"),
        c("printarea-add", "Acrescentar intervalo", "printarea-add"),
        c("show-breaks", "Quebras de página", "show-breaks"),
        c("printtitles", "Imprimir títulos", "printtitles"),
        c("rtl-sheet", "Inverta a direção da folha para que a primeira coluna fique do lado direito", "rtl-sheet"),
        c("print-gridlines", "Imprimir também as linhas de grelha", "print-gridlines"),
        c("print-headings", "Imprimir também os cabeçalhos", "print-headings"),
        c("img-movefrwd", "Trazer para a frente", "img-movefrwd"),
        c("img-movebkwd", "Enviar para trás", "img-movebkwd"),
        c("img-align", "Alinhamento", "img-align"),
        c("img-group", "Grupo", "img-group"),
        c("shapes-merge", "Unir formas", "shapes-merge"),
        c("colorschemas", "Alterar esquema de cor", "colorschemas"),
    ]},
    Tab { name: "Fórmula", cmds: &[
        c("insert-function", "Inserir função", "additional-formula"),
        c("func-list", "Funções Python", "py-list"),
        c("sum", "Soma automática", "autosum"),
        c("fn-recent", "Funções recentes", "recent"),
        c("fn-financial", "Financeiras", "financial"),
        c("fn-logical", "Logical", "logical"),
        c("fn-text", "Texto", "text"),
        c("fn-datetime", "Data e hora", "datetime"),
        c("fn-lookup", "Procura e referência", "lookup"),
        c("fn-math", "Matemática e trigonometria", "math"),
        c("fn-more", "Mais funções", "more"),
        c("defname", "Manager", "named-range-huge"),
        c("paste-name", "Colar nome", "paste-name"),
        c("trace-prec", "Rastrear Precedentes", "trace-prec"),
        c("trace-dep", "Rastrear Dependentes", "trace-dep"),
        c("remove-arrows", "Remover setas", "remove-arrows"),
        c("show-formulas", "Mostrar fórmulas", "show-formulas"),
        c("watch", "Janela de inspeção", "watch-window"),
        c("calc-mode", "Método de cálculo", "calculate"),
    ]},
    Tab { name: "Dados", cmds: &[
        c("data-from-text", "Dados a partir de texto", "data-from-text"),
        c("data-external-links", "Ligações externas (importar como valores)", "data-external-links"),
        c("setfilter", "Filtros", "setfilter"),
        c("clear-filter", "Limpar filtro", "clear-filter"),
        c("sort-desc", "Classificar do maior para o menor", "sortdesc"),
        c("sort-asc", "Classificar do menor para o maior", "sortasc"),
        c("custom-sort", "Classificar", "custom-sort"),
        c("text-column", "Texto para colunas", "text-column"),
        c("rem-duplicates", "Remover duplicados", "rem-duplicates"),
        c("data-validation", "Validação dos dados", "data-validation"),
        t("dv-mark", "Circundar dados inválidos", "dv-mark"),
        c("goal-seek", "Atingir objetivo", "goal-seek"),
        c("scenario", "Cenário", "scenario"),
        c("forecast", "Folha de previsão", "forecast"),
        c("solver", "Solver", "solver"),
        c("group", "Grupo", "group"),
        c("ungroup", "Desagrupar", "ungroup"),
        c("show-details", "Exibir detalhes", "show-details"),
        c("hide-details", "Ocultar detalhes", "hide-details"),
        c("subtotal", "Subtotais", "subtotal"),
        c("datatable", "Tabela de dados", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "Formato CSV", "csv-kind"),
        c("flash-fill", "Preencher pelo exemplo", "flash-fill"),
    ]},
    Tab { name: "Macros", cmds: &[
        c("rec-toggle", "Gravar ações", "py-run"),
        c("py-new", "Novo .py", "py-new"),
        c("py-list", "Lista", "py-list"),
        c("ribbon-list", "Macros do friso", "py-line"),
        c("py-folder", "Abrir a pasta", "py-folder"),
    ]},
    Tab { name: "Tabela dinâmica", cmds: &[
        c("pivot-insert", "Inserir tabela dinâmica", "pivot-insert"),
        c("pivot-fields", "Lista de campos", "pivot-fields"),
        c("pivot-refresh", "Recarregar", "pivot-refresh"),
        c("pivot-refresh-all", "Recarregar tudo", "pivot-refresh-all"),
        c("pivot-source", "Fonte de dados", "pivot-source"),
        c("pivot-chart", "Gráfico dinâmico", "pivot-chart"),
        c("pivot-select", "Selecionar", "pivot-select"),
        c("pivot-totals", "Totais Gerais", "pivot-totals"),
        c("pivot-subtotals", "Subtotais", "pivot-subtotals"),
        c("pivot-blank", "Linha vazias", "pivot-blank"),
        c("pivot-showas", "Mostrar os valores como", "pivot-showas"),
        c("pivot-layout", "Disposição do relatório", "pivot-layout"),
        c("pivot-style", "Estilo", "pivot-style"),
    ]},
    Tab { name: "Estrutura da Tabela", cmds: &[
        c("td-header", "Linha de cabeçalho", "td-header"),
        c("td-total", "Linha de totais", "td-total"),
        c("td-band-row", "Linhas em bandas", "td-band-row"),
        c("td-first", "Primeira coluna", "td-first"),
        c("td-last", "Última coluna", "td-last"),
        c("td-band-col", "Colunas às riscas", "td-band-col"),
        c("td-filter", "Botão de filtro", "td-filter"),
        c("rem-duplicates", "Remover duplicados", "td-remdup"),
        c("td-torange", "Converter em intervalo", "td-torange"),
        c("td-resize", "Redimensionar tabela", "td-resize"),
    ]},
    Tab { name: "Colaboração", cmds: &[
        c("coauth-mode", "Modo de coedição", "coauth-mode"),
        c("co-addcomment", "Adicionar comentário", "co-addcomment"),
        c("co-delcomment", "Eliminar comentário", "co-delcomment"),
        c("co-showcomment", "Mostrar Comentário", "co-showcomment"),
        c("co-chat", "Conversa", "co-chat"),
        c("co-history", "Histórico de versões", "co-history"),
    ]},
    Tab { name: "Proteção", cmds: &[
        c("prot-encrypt", "Encriptar", "prot-encrypt"),
        xt("Proteger livro", "protect-workbook"),
        c("prot-doc", "Proteger folha", "protect-sheet"),
        xt("Proteger intervalo", "protect-range"),
        c("prot-sign", "Adicionar assinatura digital", "prot-sign"),
        c("cell-lock", "Bloquear célula", "cell-lock"),
        c("prot-allow", "Operações permitidas", "prot-allow"),
        c("recover", "Recuperar", "recover"),
        c("recover-every", "Intervalo das cópias", "recover-every"),
        c("read-only-rec", "Sugerir só leitura", "read-only-rec"),
    ]},
    Tab { name: "Mostrar", cmds: &[
        c("sheet-view", "Vista de folha", "sheet-view"),
        xm("Normal", "view-normal"),
        xm("Pré-visualização da quebra de página", "view-pagebreak"),
        c("zoom-in", "Ampliar", "zoom-in"),
        c("zoom-out", "Reduzir", "zoom-out"),
        c("zoom100", "Ampliar para 100%", "zoom100"),
        c("ui-bigger", "Aumentar o texto do ecrã", "ui-bigger"),
        c("ui-smaller", "Diminuir o texto do ecrã", "ui-smaller"),
        t("darkmode", "Modo escuro", "theme"),
        c("freeze", "Fixar painéis", "freeze"),
        t("split", "Dividir janela", "split"),
        t("formula-bar", "Barra de fórmulas", "formula-bar"),
        c("show-gridlines", "Gridlines", "show-gridlines"),
        t("show-headings", "Títulos", "show-headings"),
        t("show-zeros", "Mostrar zeros", "show-zeros"),
        t("show-left", "Painel esquerdo", "show-left"),
        t("show-right", "Painel direito", "show-right"),
    ]},
];

