//! リボンの de 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py de > face/src/ribbon_de.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "Datei", cmds: &[
        c("open", "Offen", "open"),
        c("save", "Speichern", "save"),
        c("pdf", "Drucken", "print"),
    ]},
    Tab { name: "Startseite", cmds: &[
        c("copy", "Kopieren", "copy"),
        c("cut", "Ausschneiden", "cut"),
        c("paste", "Einfügen", "paste"),
        c("fontname", "Schriftart", "fontname"),
        c("fontsize", "Schriftgrad", "fontsize"),
        c("incfont", "Schriftart vergrößern", "incfont"),
        c("decfont", "Schriftart verkleinern", "decfont"),
        c("changecase", "Groß-/Kleinschreibung ändern", "changecase"),
        c("ruby", "Anfragen", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Fett", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Unterstrichen", "underline"),
        c("strikeout", "Durchgestrichen", "strikeout"),
        c("superscript", "Hochgestellt", "superscript"),
        c("subscript", "Tiefgestellt", "subscript"),
        c("highlight", "Texthervorhebungsfarbe", "highlight"),
        c("fontcolor", "Schriftfarbe", "fontcolor"),
        c("clearstyle", "Formatierung löschen", "clearstyle"),
        c("markers", "Aufzählungszeichen", "markers"),
        c("numbering", "Nummerierung", "numbering"),
        c("multilevels", "Liste mit mehreren Ebenen", "multilevels"),
        c("decoffset", "Einzug verkleinern", "decoffset"),
        c("incoffset", "Einzug vergrößern", "incoffset"),
        c("linespace", "Zeilenabstand", "linespace"),
        c("direction", "Ruby", "direction"),
        c("align-left", "Links ausrichten", "align-left"),
        c("align-center", "Zentriert", "align-center"),
        c("align-right", "Rechts ausrichten", "align-right"),
        c("align-just", "Blocksatz", "align-just"),
        c("align-dist", "Textrichtung", "align-dist"),
        c("hidenchars", "Formatierungszeichen", "hidenchars"),
        c("paracolor", "Absatzhintergrundfarbe", "paracolor"),
        c("borders", "Rahmen", "borders"),
        c("parastyle", "Absatzformat", "styles"),
        c("replace", "Ersetzen", "replace"),
        c("selectall", "Alles auswählen", "select-all"),
    ]},
    Tab { name: "Einfügen", cmds: &[
        c("blankpage", "Leere Seite einlegen", "blankpage"),
        c("pagebreak", "Umbrüche", "pagebreak"),
        c("instable", "Tabelle einfügen", "instable"),
        c("insimage", "Bild einfügen", "insertimage"),
        c("insshape", "Form einfügen", "insshape"),
        c("inssmartart", "SmartArt einfügen", "inssmartart"),
        c("inschart", "Diagramm einfügen", "inschart"),
        c("instext", "Textfeld einfügen", "instext"),
        c("instextart", "TextArt einfügen", "instextart"),
        c("dropcap", "Initiale einfügen", "dropcap"),
        c("text-from-file", "Text aus Datei", "text-from-file"),
        c("edit-header", "Kopfzeile bearbeiten", "edit-header"),
        c("edit-footer", "Fußzeile bearbeiten", "edit-footer"),
        c("pagenum", "Seitennummerierung", "pagenum"),
        c("datetime", "Datum/Uhrzeit", "datetime"),
        c("numpages", "Seitenzahl", "numpages"),
        c("insequation", "Formel einfügen", "insequation"),
        c("inssymbol", "Symbol einfügen", "inssymbol"),
        c("controls", "Inhaltssteuerelemente einfügen", "controls"),
    ]},
    Tab { name: "Zeichnen", cmds: &[
        c("pen", "Stift", "pen"),
        c("highlighter", "Textmarker", "highlighter"),
        c("eraser", "Radierer", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Ränder", "pagemargins"),
        c("pageorient", "Orientierung", "pageorient"),
        c("pagesize", "Seitenformat", "pagesize"),
        c("columns", "Spalte einfügen", "columns"),
        c("line-numbers", "Zeilennummern anzeigen", "line-numbers"),
        c("hyphenation", "Trennen ändern", "hyphenation"),
        x("Eine Ebene nach vorne", "img-movefrwd"),
        x("Eine Ebene nach hinten", "img-movebkwd"),
        x("Ausrichtung", "img-align"),
        x("Gruppieren", "img-group"),
        x("Formen zusammenführen", "shapes-merge"),
        c("watermark", "Wasserzeichen bearbeiten", "watermark"),
        c("pagecolor", "Seitenfarbe ändern", "pagecolor"),
        c("colorschemas", "Farbschema ändern", "colorschemas"),
    ]},
    Tab { name: "Verweise", cmds: &[
        c("toc", "Inhaltsverzeichnis", "contents"),
        c("add-text", "Text Hinzufügen", "add-text"),
        c("toc-update", "Textrichtung (rechts nach links)", "contents-update"),
        c("bookmarks", "Lesezeichen", "bookmarks"),
        c("caption", "Filter löschen", "caption"),
        c("crossref", "Querverweis", "crossref"),
        c("footnote", "Fußnote", "footnote"),
        c("tof", "Makro schreiben", "tof"),
        c("tof-update", "Text in Spalten", "tof-update"),
    ]},
    Tab { name: "Formulare", cmds: &[
        c("form-text", "Textfeld", "form-text"),
        c("form-combo", "Combobox", "form-combo"),
        c("form-dropdown", "Dropdown", "form-dropdown"),
        c("form-checkbox", "Rechts-nach-links-Text", "form-checkbox"),
        c("form-radio", "Radiobutton", "form-radio"),
        c("form-image", "Bild", "form-image"),
        c("form-email", "E-Mail-Adresse", "form-email"),
        c("form-phone", "Telefonnummer", "form-phone"),
        c("form-complex", "Komplexes Feld", "form-complex"),
        c("form-signature", "Signatur", "form-signature"),
        c("form-name", "Name", "form-name"),
    ]},
    Tab { name: "Zusammenarbeit", cmds: &[
        c("coauth-mode", "Kontrollkästchen", "coauth-mode"),
        c("co-addcomment", "Kommentar hinzufügen", "co-addcomment"),
        c("co-delcomment", "Überwachungsfenster", "co-delcomment"),
        c("co-showcomment", "Kommentare anzeigen", "co-showcomment"),
        c("co-chat", "Empfohlene Diagramme", "co-chat"),
        c("track-changes", "Nachverfolgen von Änderungen", "track-changes"),
        c("co-history", "Externe Verknüpfungen", "co-history"),
    ]},
    Tab { name: "Schutz", cmds: &[
        c("prot-sign", "Versionsverlauf", "prot-sign"),
        c("prot-doc", "Schutz", "prot-doc"),
    ]},
    Tab { name: "Anzeigen", cmds: &[
        t("nav", "Navigation", "nav"),
        c("fit-page", "Seite anpassen", "fit-page"),
        c("fit-width", "Breite anpassen", "fit-width"),
        c("zoom100", "Digitale Signatur hinzufügen", "zoom100"),
        c("zoom-in", "Vergrößern", "zoom-in"),
        c("zoom-out", "Verkleinern", "zoom-out"),
        c("printview", "Drucklayout", "printview"),
        c("multipage", "Mehrere Seiten", "multipage"),
        t("darkmode", "Dunkelmodus", "darkmode"),
        c("ui-bigger", "Oberflächentext größer", "ui-bigger"),
        c("ui-smaller", "Oberflächentext kleiner", "ui-smaller"),
        c("ruler", "Lineale", "ruler"),
        t("show-toolbar", "Symbolleiste immer anzeigen", "show-toolbar"),
        t("show-statusbar", "Statusleiste", "show-statusbar"),
        t("show-left", "Linkes Bedienfeld", "show-left"),
        t("show-right", "Rechtes Bedienungsfeld ", "show-right"),
    ]},
    Tab { name: "Makros", cmds: &[
        c("py-list", "Zelle sperren", "plug-manage"),
        c("py-folder", "Bereich hinzufügen", "py-folder"),
        c("ai-macro", "Pfeile entfernen", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "Datei", cmds: &[
        c("open", "Offen", "open"),
        c("save", "Speichern", "save"),
        c("pdf", "Drucken", "print"),
    ]},
    Tab { name: "Startseite", cmds: &[
        c("copy", "Kopieren", "copy"),
        c("cut", "Ausschneiden", "cut"),
        c("paste", "Einfügen", "paste"),
        c("copystyle", "Format übertragen", "copystyle"),
        c("fontname", "Schriftart", "fontname"),
        c("fontsize", "Schriftgrad", "fontsize"),
        c("incfont", "Schriftart vergrößern", "incfont"),
        c("decfont", "Schriftart verkleinern", "decfont"),
        c("changecase", "Groß-/Kleinschreibung ändern", "changecase"),
        c("bold", "Fett", "bold"),
        c("italic", "Italic", "italic"),
        c("underline", "Unterstrichen", "underline"),
        c("strikeout", "Durchgestrichen", "strikeout"),
        c("subscript", "Tiefgestellt", "subscript"),
        c("fontcolor", "Schriftfarbe", "fontcolor"),
        c("fillparag", "Füllfarbe", "fillparag"),
        c("borders", "Rahmen", "borders"),
        c("top", "Oben ausrichten", "top"),
        c("middle", "Mittig ausrichten", "middle"),
        c("bottom", "Unten ausrichten", "bottom"),
        c("wrap", "Musterfüllung", "wrap"),
        c("text-orient", "Textausrichtung", "text-orient"),
        c("align-left", "Links ausrichten", "align-left"),
        c("align-center", "Zentriert", "align-center"),
        c("align-right", "Rechts ausrichten", "align-right"),
        c("align-just", "Blocksatz", "align-just"),
        c("align-dist", "Textrichtung", "align-dist"),
        c("merge", "Verbinden und zentrieren", "merge"),
        c("direction", "Abbildungsverzeichnis aktualisieren", "direction"),
        c("sum", "Auf 100 % zoomen", "autosum"),
        c("fill-num", "Solver", "fill-num"),
        c("defname", "Name-Manager", "named-range"),
        c("clear", "Leeren", "clear"),
        c("sort-desc", "Absteigend sortieren", "sortdesc"),
        c("sort-asc", "Aufsteigend sortieren", "sortasc"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Text zu Daten", "clear-filter"),
        c("format", "Zahlenformat", "format"),
        c("currency", "Währungsformat", "currency"),
        c("percents", "Prozentformat", "percents"),
        c("comma", "Komma-Format", "comma"),
        c("digit-dec", "Dezimalstelle löschen", "digit-dec"),
        c("digit-inc", "Dezimalstelle erhöhen", "digit-inc"),
        c("cell-ins", "Zellen einfügen", "cell-ins"),
        c("cell-del", "Zellen löschen", "cell-del"),
        c("cell-format", "Zellen formatieren", "cell-format"),
        c("condformat", "Bedingte Formatierung", "condformat"),
        c("table-tpl", "Wie Tabellenvorlage formatieren", "table-tpl"),
        c("cell-styles", "Zellenformatvorlage", "styles"),
        c("replace", "Ersetzen", "replace"),
        c("selectall", "Alles auswählen", "select-all"),
    ]},
    Tab { name: "Einfügen", cmds: &[
        c("pivot-insert", "Pivot-Tabelle einfügen", "add-pivot"),
        c("instable", "Tabelle einfügen", "instable"),
        c("insimage", "Bild einfügen", "insimage-c"),
        c("insshape", "Form einfügen", "insshape"),
        c("inssmartart", "SmartArt einfügen", "inssmartart"),
        c("inscheckbox", "Rechts-nach-links-Text", "inscheckbox"),
        c("insrecommend", "Empfohlenes Diagramm einfügen", "insrecommend"),
        c("inschart", "Diagramm einfügen", "inschart"),
        c("inssparkline", "Sparkline einfügen", "inssparkline"),
        c("co-addcomment", "Kommentar", "ins-comment"),
        c("inshyperlink", "Link hinzufügen", "inshyperlink"),
        c("insslicer", "Datenschnitt einfügen", "insslicer"),
        c("instext", "Textfeld einfügen", "instext"),
        c("instextart", "TextArt einfügen", "instextart"),
        c("edit-header", "Kopf- und Fußzeile", "editheader"),
        c("insequation", "Formel einfügen", "insequation"),
        c("inssymbol", "Symbol einfügen", "inssymbol"),
    ]},
    Tab { name: "Zeichnen", cmds: &[
        c("draw-select", "Auswahl", "select-tool"),
        c("pen", "Stift", "pen"),
        c("highlighter", "Textmarker", "highlighter"),
        c("eraser", "Radierer", "eraser"),
    ]},
    Tab { name: "Layout", cmds: &[
        c("pagemargins", "Ränder", "pagemargins"),
        c("pageorient", "Orientierung", "pageorient"),
        c("pagesize", "Seitenformat", "pagesize"),
        c("printarea", "Druckauswahl", "printarea"),
        c("pagebreak", "Umbrüche", "pagebreak"),
        c("edit-header", "Kopf- und Fußzeile", "editheader"),
        c("scale", "An Format anpassen", "scale"),
        c("fit-pages", "Sicherungsintervall", "fit-pages"),
        c("printarea-add", "Text umbrechen", "printarea-add"),
        c("show-breaks", "Neue .py", "show-breaks"),
        c("printtitles", "Drucke Titel", "printtitles"),
        c("rtl-sheet", "Ändern Sie die Blattausrichtung, sodass die erste Spalte auf der rechten Seite liegt", "rtl-sheet"),
        c("print-gridlines", "Formeln anzeigen", "print-gridlines"),
        c("print-headings", "Gitternetzlinien drucken", "print-headings"),
        x("Eine Ebene nach vorne", "img-movefrwd"),
        x("Eine Ebene nach hinten", "img-movebkwd"),
        x("Ausrichtung", "img-align"),
        x("Gruppieren", "img-group"),
        x("Formen zusammenführen", "shapes-merge"),
        c("colorschemas", "Farbschema ändern", "colorschemas"),
    ]},
    Tab { name: "Formel", cmds: &[
        c("insert-function", "Funktion einfügen", "additional-formula"),
        c("func-list", "Python-Funktionen", "py-list"),
        c("sum", "Auf 100 % zoomen", "autosum"),
        c("fn-recent", "Externe Verknüpfungen (als Werte einlesen)", "recent"),
        c("fn-financial", "Finanzmathematik", "financial"),
        c("fn-logical", "Logisch", "logical"),
        c("fn-text", "Text", "text"),
        c("fn-datetime", "Datum/Uhrzeit", "datetime"),
        c("fn-lookup", "Suchen und Bezüge", "lookup"),
        c("fn-math", "Mathematik/Trigonometrie", "math"),
        c("fn-more", "Weitere Funktionen", "more"),
        c("defname", "Name-Manager", "named-range-huge"),
        c("paste-name", "Datentabelle", "paste-name"),
        c("trace-prec", "Präzedenzfälle", "trace-prec"),
        c("trace-dep", "Trace-Abhängige", "trace-dep"),
        c("remove-arrows", "Kommentar löschen", "remove-arrows"),
        c("show-formulas", "Abbildungsverzeichnis", "show-formulas"),
        c("watch", "Nullen anzeigen", "watch-window"),
        c("calc-mode", "Fehlkonvertierung", "calculate"),
    ]},
    Tab { name: "Daten", cmds: &[
        c("data-from-text", "Aktionen aufzeichnen", "data-from-text"),
        c("data-external-links", "Beschriftung", "data-external-links"),
        c("setfilter", "Filter", "setfilter"),
        c("clear-filter", "Text zu Daten", "clear-filter"),
        c("sort-desc", "Absteigend sortieren", "sortdesc"),
        c("sort-asc", "Aufsteigend sortieren", "sortasc"),
        c("custom-sort", "Sortieren", "custom-sort"),
        c("text-column", "Ausfüllen", "text-column"),
        c("rem-duplicates", "Gebänderte Spalten", "rem-duplicates"),
        c("data-validation", "Datenüberprüfung", "data-validation"),
        t("dv-mark", "Ungültige Daten einkreisen", "dv-mark"),
        c("goal-seek", "Zielwertsuche", "goal-seek"),
        c("scenario", "Szenario", "scenario"),
        c("forecast", "Prognoseblatt", "forecast"),
        c("solver", "AutoSumme", "solver"),
        c("group", "Gruppieren", "group"),
        c("ungroup", "Gruppierung aufheben", "ungroup"),
        c("show-details", "Details anzeigen", "show-details"),
        c("hide-details", "Inhaltsverzeichnis aktualisieren", "hide-details"),
        c("subtotal", "Zwischensumme", "subtotal"),
        c("datatable", "Funktion einfügen", "datatable"),
        c("python", "Berechnung", "python"),
        c("csv-kind", "Detail ausblenden", "csv-kind"),
        c("flash-fill", "CSV-Format", "flash-fill"),
    ]},
    Tab { name: "Makros", cmds: &[
        c("rec-toggle", "Oberflächendesign", "py-run"),
        c("py-new", "Namen einfügen", "py-new"),
        c("py-list", "Zelle sperren", "py-list"),
        c("ribbon-list", "Menüband-Makros", "py-line"),
        c("py-folder", "Bereich hinzufügen", "py-folder"),
    ]},
    Tab { name: "Pivot-Tabelle", cmds: &[
        c("pivot-insert", "Pivot-Tabelle einfügen", "pivot-insert"),
        c("pivot-fields", "Feldliste", "pivot-fields"),
        c("pivot-refresh", "Aktualisieren", "pivot-refresh"),
        c("pivot-refresh-all", "Alles aktualisieren", "pivot-refresh-all"),
        c("pivot-source", "Datenquelle", "pivot-source"),
        c("pivot-chart", "PivotChart", "pivot-chart"),
        c("pivot-select", "Auswählen", "pivot-select"),
        c("pivot-totals", "Gesamtsumme", "pivot-totals"),
        c("pivot-subtotals", "Zwischensumme", "pivot-subtotals"),
        c("pivot-blank", "Leere Zeilen", "pivot-blank"),
        c("pivot-showas", "Aufs Blatt einpassen", "pivot-showas"),
        c("pivot-layout", "Berichtslayout", "pivot-layout"),
        c("pivot-style", "Formatvorlage", "pivot-style"),
    ]},
    Tab { name: "Tabellen-Design", cmds: &[
        c("td-header", "Kopfzeile", "td-header"),
        c("td-total", "Gesamtzeile", "td-total"),
        c("td-band-row", "Verbundene Zeilen", "td-band-row"),
        c("td-first", "Erste Spalte", "td-first"),
        c("td-last", "Letzte Spalte", "td-last"),
        c("td-band-col", "Zuletzt verwendet", "td-band-col"),
        c("td-filter", "Schaltfläche Filter", "td-filter"),
        c("rem-duplicates", "Entferne Duplikate", "td-remdup"),
        c("td-torange", "In Zellenbereich konvertieren", "td-torange"),
        c("td-resize", "Tabellengröße ändern", "td-resize"),
    ]},
    Tab { name: "Zusammenarbeit", cmds: &[
        c("coauth-mode", "Kontrollkästchen", "coauth-mode"),
        c("co-addcomment", "Kommentar hinzufügen", "co-addcomment"),
        c("co-delcomment", "Überwachungsfenster", "co-delcomment"),
        c("co-showcomment", "Kommentare anzeigen", "co-showcomment"),
        c("co-chat", "Empfohlene Diagramme", "co-chat"),
        c("co-history", "Externe Verknüpfungen", "co-history"),
    ]},
    Tab { name: "Schutz", cmds: &[
        c("prot-encrypt", "Co-Bearbeitung", "prot-encrypt"),
        xt("Arbeitsmappe schützen", "protect-workbook"),
        c("prot-doc", "Blatt schützen", "protect-sheet"),
        xt("Bereich schützen", "protect-range"),
        c("prot-sign", "Versionsverlauf", "prot-sign"),
        c("cell-lock", "Duplikate entfernen", "cell-lock"),
        c("prot-allow", "Blattgrenzen", "prot-allow"),
        c("recover", "Wiederherstellen", "recover"),
        c("recover-every", "Liste", "recover-every"),
        c("read-only-rec", "Schreibschutz empfehlen", "read-only-rec"),
    ]},
    Tab { name: "Anzeigen", cmds: &[
        c("sheet-view", "Tabellenansicht", "sheet-view"),
        xm("Normal", "view-normal"),
        xm("Seitenumbruch-Vorschau", "view-pagebreak"),
        c("zoom-in", "Vergrößern", "zoom-in"),
        c("zoom-out", "Verkleinern", "zoom-out"),
        c("zoom100", "Digitale Signatur hinzufügen", "zoom100"),
        c("ui-bigger", "Oberflächentext größer", "ui-bigger"),
        c("ui-smaller", "Oberflächentext kleiner", "ui-smaller"),
        t("darkmode", "Dunkelmodus", "theme"),
        c("freeze", "Fensterausschnitt fixieren", "freeze"),
        t("split", "Fenster teilen", "split"),
        t("formula-bar", "Formelleiste", "formula-bar"),
        c("show-gridlines", "Gitternetzlinien ", "show-gridlines"),
        t("show-headings", "Überschriften", "show-headings"),
        t("show-zeros", "Verschlüsseln", "show-zeros"),
        t("show-left", "Linkes Bedienfeld", "show-left"),
        t("show-right", "Rechtes Bedienungsfeld ", "show-right"),
    ]},
];

