//! リボンの id の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py id > face/src/ribbon_id.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Tambahkan komentar"),
    ("Add Text", "Tambah Teks"),
    ("Add digital signature", "Tambahkan tanda tangan digital"),
    ("Add link", "Tambahkan hyperlink"),
    ("Add to area", "Tambah rentang"),
    ("Align bottom", "Rata bawah"),
    ("Align left", "Rata kiri"),
    ("Align middle", "Rata di tengah"),
    ("Align right", "Rata kanan"),
    ("Align top", "Rata atas"),
    ("Alignment", "Perataan"),
    ("Allowed actions", "Tindakan yang diizinkan"),
    ("Always Show Toolbar", "Selalu Tampilkan Bilah Alat"),
    ("AutoSum", "JumlahOtomatis"),
    ("Backup interval", "Selang salinan"),
    ("Banded Rows", "Baris Berpita"),
    ("Banded columns", "Kolom berpita"),
    ("Bigger UI text", "Perbesar teks layar"),
    ("Blank Rows", "Baris Kosong"),
    ("Bold", "Tebal"),
    ("Borders", "Batas"),
    ("Breaks", "Jeda"),
    ("Bring forward", "Majukan"),
    ("Bullet", "Butir"),
    ("CSV format", "Format CSV"),
    ("Calculation options", "Kalkulasi"),
    ("Caption", "Keterangan"),
    ("Cell Style", "Gaya Sel"),
    ("Cell lock", "Kunci sel"),
    ("Centre", "Tengah"),
    ("Change case", "Ubah case"),
    ("Change colour theme", "Ubah Skema Warna"),
    ("Change hyphenation", "Ubah tanda hubung"),
    ("Change page colour", "Ubah warna halaman"),
    ("Chat", "Obrolan"),
    ("Checkbox", "Kotak centang"),
    ("Circle invalid data", "Lingkari data tidak valid"),
    ("Clear", "Hapus"),
    ("Clear filter", "Bersihkan filter"),
    ("Clear style", "Hapus Model"),
    ("Co-editing mode", "Mode pengeditan bersama"),
    ("Collaboration", "Kolaborasi"),
    ("Combo box", "Kotak combo"),
    ("Comma style", "Gaya koma"),
    ("Comment", "Komentar"),
    ("Complex Field", "Bidang Kompleks"),
    ("Conditional formatting", "Format bersyarat"),
    ("Convert to range", "Konversi ke rentang"),
    ("Copy", "Salin"),
    ("Currency style", "Gaya mata uang"),
    ("Cut", "Potong"),
    ("Dark mode", "Mode gelap"),
    ("Data Validation", "Validasi data"),
    ("Data source", "Sumber data"),
    ("Data table", "Tabel data"),
    ("Date & Time", "Tanggal & Waktu"),
    ("Decrease decimal", "Kurangi desimal"),
    ("Decrease indent", "Kurangi Indentasi"),
    ("Decrement font size", "Perkecil Ukuran Huruf"),
    ("Delete cells", "Hapus Sel"),
    ("Delete comment", "Hapus komentar"),
    ("Distributed", "Terdistribusi"),
    ("Draw", "Gambar"),
    ("Edit footer", "Sunting kaki"),
    ("Edit header", "Sunting kepala"),
    ("Email Address", "Alamat Email"),
    ("Encrypt", "Enkripsi"),
    ("Eraser", "Penghapus"),
    ("External links (import as values)", "Tautan eksternal (impor sebagai nilai)"),
    ("Field list", "Daftar bidang"),
    ("Fill", "Isi"),
    ("Fill by example", "Isi menurut contoh"),
    ("Fill colour", "Isi warna"),
    ("Filter button", "Tombol filter"),
    ("Filters", "Filter"),
    ("Financial", "Finansial"),
    ("First column", "Kolom pertama"),
    ("Fit to page", "Sesuaikan Halaman"),
    ("Fit to paper", "Muatkan ke kertas"),
    ("Fit to width", "Sesuaikan Lebar"),
    ("Font", "Huruf"),
    ("Font colour", "Warna Huruf"),
    ("Font size", "Ukuran Huruf"),
    ("Forecast Sheet", "Lembar ramalan"),
    ("Format as table template", "Format sebagai template tabel"),
    ("Format cells", "Format sel"),
    ("Format painter", "Salin format"),
    ("Forms", "Fomulir"),
    ("Formula Bar", "Bar formula"),
    ("Freeze panes", "Freeze Panes"),
    ("Goal Seek", "Pencarian Tujuan"),
    ("Gridlines", "Garis Grid"),
    ("Group", "Grup"),
    ("Header row", "Baris header"),
    ("Headings", "Tajuk"),
    ("Hide detail", "Sembunyikan rincian"),
    ("Highlight colour", "Warna Sorot"),
    ("Highlighter", "Penyorot"),
    ("Home", "Halaman Depan"),
    ("Increase decimal", "Tambah desimal"),
    ("Increase indent", "Tambahkan Indentasi"),
    ("Increment font size", "Perbesar Ukuran Huruf"),
    ("Insert", "Sisipkan"),
    ("Insert Pivot Table", "Sisipkan Tabel Pivot"),
    ("Insert SmartArt", "Sisipkan SmartArt"),
    ("Insert Text Art", "Sisipkan Text Art"),
    ("Insert blank page", "Sisipkan halaman kosong"),
    ("Insert cells", "Sisipkan sel"),
    ("Insert chart", "Sisipkan Bagan"),
    ("Insert column", "Sisipkan kolom"),
    ("Insert content controls", "Sisipkan kontrol konten"),
    ("Insert drop cap", "Sisipkan Drop Cap"),
    ("Insert equation", "Masukkan Persamaan"),
    ("Insert function", "Sisipkan fungsi"),
    ("Insert image", "Sisipkan Gambar"),
    ("Insert recommended chart", "Sisipkan bagan yang disarankan"),
    ("Insert shape", "Sisipkan Bentuk"),
    ("Insert slicer", "Sisipkan Slicer"),
    ("Insert sparkline", "Sisipkan sparkline"),
    ("Insert symbol", "Sisipkan simbol"),
    ("Insert table", "Sisipkan Tabel"),
    ("Insert text box", "Sisipkan kotak teks"),
    ("Italic", "Miring"),
    ("Justified", "Rata Kiri-Kanan"),
    ("Last column", "Kolom terakhir"),
    ("Left Panel", "Panel Kiri"),
    ("Logical", "Logikal"),
    ("Lookup & Reference", "Lookup dan referensi"),
    ("Macro list", "Daftar"),
    ("Macros", "Makro"),
    ("Margins", "Margin"),
    ("Math & Trig", "Matematika & Trigonometri"),
    ("Merge and centre", "Merge dan center"),
    ("Merge shapes", "Gabungkan bentuk"),
    ("More functions", "Lebih banyak fungsi"),
    ("Multilevel list", "Ikhtisar"),
    ("Multiple pages", "Gandakan halaman"),
    ("Name", "Nama"),
    ("Name manager", "Pengaturan Nama"),
    ("Navigation", "Navigasi"),
    ("New .py", ".py baru"),
    ("Nonprinting characters", "Karakter Tidak Dicetak"),
    ("Number format", "Format nomor"),
    ("Number of pages", "Jumlah halaman"),
    ("Numbering", "Penomoran"),
    ("Open", "Buka"),
    ("Open folder", "Buka folder plugins"),
    ("Page Break Preview", "Pratinjau Jeda Halaman"),
    ("Page breaks", "Batas kertas"),
    ("Page number", "Nomor halaman"),
    ("Page orientation", "Orientasi"),
    ("Page size", "Ukuran Halaman"),
    ("Paragraph line spacing", "Spasi Antar Baris Paragraf"),
    ("Paragraph style", "Gaya paragraf"),
    ("Paste", "Tempel"),
    ("Paste name", "Tempel nama"),
    ("Pen", "Pena"),
    ("Percent style", "Gaya persen"),
    ("Phone Number", "Nomor Telepon"),
    ("Picture", "Gambar"),
    ("Pivot Table", "Tabel Pivot"),
    ("Print", "Cetak"),
    ("Print gridlines", "Cetak garis kisi"),
    ("Print headings", "Cetak judul"),
    ("Print titles", "Print judul"),
    ("Protect Range", "Proteksi Rentang"),
    ("Protect sheet", "Proteksi Sheet"),
    ("Protect workbook", "Proteksi workbook"),
    ("Protection", "Proteksi"),
    ("Python functions", "Fungsi Python"),
    ("Radio Button", "Tombol Radio"),
    ("Recently used", "Baru digunakan"),
    ("Record actions", "Rekam tindakan"),
    ("Recover", "Pemulihan"),
    ("References", "Referensi"),
    ("Remove Duplicates", "Hapus duplikat"),
    ("Remove arrows", "Hapus panah"),
    ("Remove duplicates", "Hapus duplikat"),
    ("Replace", "Ganti"),
    ("Report Layout", "Layout Laporan"),
    ("Resize table", "Ubah ukuran tabel"),
    ("Ribbon macros", "Makro pita"),
    ("Right Panel", "Panel Kanan"),
    ("Right-to-left text", "Arah teks (kanan-ke-kiri)"),
    ("Rulers", "Penggaris"),
    ("Save", "Simpan"),
    ("Scale To Fit", "Skala ke Fit"),
    ("Scenario", "Skenario"),
    ("Select", "Pilih"),
    ("Select all", "Pilih semua"),
    ("Send Backward", "Mundurkan"),
    ("Shading", "Bayangan"),
    ("Sheet View", "Tampilan sheet"),
    ("Show comments", "Tampilkan komentar"),
    ("Show details", "Tampilkan Detail"),
    ("Show formulas", "Tampilkan rumus"),
    ("Show line numbers", "Tampilkan nomor garis"),
    ("Show values as", "Jenis perhitungan"),
    ("Show zeros", "Tampilkan nol"),
    ("Signature", "Tanda Tangan"),
    ("Smaller UI text", "Perkecil teks layar"),
    ("Sort", "Sortasi"),
    ("Sort ascending", "Sortasi naik"),
    ("Sort descending", "Sortasi turun"),
    ("Split", "Belah jendela"),
    ("Status Bar", "Bar Status"),
    ("Strikethrough", "Coret ganda"),
    ("Style", "Gaya"),
    ("Subscript", "Subskrip"),
    ("Subtotals", "Subtotal"),
    ("Suggest read-only", "Sarankan hanya-baca"),
    ("Superscript", "Superskrip"),
    ("Switch the sheet direction so that the first column is on the right side", "Ubah arah lembar agar kolom pertama di kanan"),
    ("Table Design", "Desain tabel"),
    ("Table of contents", "Daftar Isi"),
    ("Table of figures", "Daftar gambar"),
    ("Text Field", "Ruas Teks"),
    ("Text direction", "Arah teks"),
    ("Text from File", "Teks dari Berkas"),
    ("Text functions", "Teks"),
    ("Text orientation", "Arah teks"),
    ("Text to columns", "Teks ke kolom"),
    ("Text to data", "Teks ke data"),
    ("Total row", "Baris total"),
    ("Trace Dependents", "Dependen Jejak"),
    ("Trace Precedents", "Preseden Jejak"),
    ("Track changes", "Lacak perubahan"),
    ("Underline", "Garis bawah"),
    ("Ungroup", "Pisahkan dari grup"),
    ("Update", "Refresh"),
    ("Update all", "Segarkan Semuanya"),
    ("Update table of contents", "Perbarui daftar isi"),
    ("Update table of figures", "Perbarui daftar gambar"),
    ("Version history", "Riwayat versi"),
    ("View", "Lihat"),
    ("Watch window", "Jendela pantauan"),
    ("Wrap text", "Bungkus teks"),
    ("Write macro", "Tulis makro"),
    ("Zoom in", "Perbesar"),
    ("Zoom out", "Perkecil"),
    ("Zoom to 100%", "Zoom ke 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

