//! リボンの fr の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py fr > face/src/ribbon_fr.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Ajouter un commentaire"),
    ("Add Text", "Ajouter du texte"),
    ("Add digital signature", "Ajouter une signature numérique"),
    ("Add link", "Ajouter un lien"),
    ("Add to area", "Ajouter la plage"),
    ("Align bottom", "Aligner en bas"),
    ("Align left", "Aligner à gauche"),
    ("Align middle", "Aligner au centre"),
    ("Align right", "Aligner à droite"),
    ("Align top", "Aligner en haut"),
    ("Alignment", "Alignement"),
    ("Allowed actions", "Actions permises"),
    ("Always Show Toolbar", "Toujours afficher la barre d'outils"),
    ("AutoSum", "Somme automatique"),
    ("Backup interval", "Intervalle des copies"),
    ("Banded Rows", "Lignes à bandes"),
    ("Banded columns", "Colonnes à bandes"),
    ("Bigger UI text", "Agrandir le texte de l'écran"),
    ("Blank Rows", "Lignes vides"),
    ("Bold", "Gras"),
    ("Bookmark", "Signet"),
    ("Borders", "Bordures"),
    ("Breaks", "Sauts"),
    ("Bring forward", "Déplacer vers l'avant"),
    ("Bullet", "Puce"),
    ("CSV format", "Format CSV"),
    ("Calculation options", "Mode de calcul"),
    ("Caption", "Légende"),
    ("Cell Style", "Style de cellule"),
    ("Cell lock", "Verrouiller la cellule"),
    ("Centre", "Au centre"),
    ("Change case", "Modifier la casse"),
    ("Change colour theme", "Modifier le jeu de couleurs"),
    ("Change hyphenation", "Modifier la coupure de mots"),
    ("Change page colour", "Modifier la couleur de page"),
    ("Chat", "Discussion"),
    ("Checkbox", "Case à cocher"),
    ("Circle invalid data", "Entourer les données non valides"),
    ("Clear", "Effacer"),
    ("Clear filter", "Effacer le filtre"),
    ("Clear style", "Effacer le style"),
    ("Co-editing mode", "Mode coédition"),
    ("Combo box", "Zone de liste déroulante"),
    ("Comma style", "Style de virgule"),
    ("Comment", "Commentaire"),
    ("Complex Field", "Champ complexe"),
    ("Conditional formatting", "Mise en forme conditionnelle"),
    ("Convert to range", "Convertir en plage"),
    ("Copy", "Copier"),
    ("Cross-reference", "Renvoi"),
    ("Currency style", "Style monétaire"),
    ("Cut", "Couper"),
    ("Dark mode", "Mode sombre"),
    ("Data", "Données"),
    ("Data Validation", "Validation des données"),
    ("Data source", "Source de données"),
    ("Data table", "Table de données"),
    ("Date & Time", "Date et heure"),
    ("Decrease decimal", "Réduire les décimales"),
    ("Decrease indent", "Réduire le retrait"),
    ("Decrement font size", "Diminuer la taille de police"),
    ("Delete cells", "Supprimer les cellules"),
    ("Delete comment", "Supprimer le commentaire"),
    ("Distributed", "Réparti"),
    ("Draw", "Dessiner"),
    ("Dropdown", "Liste déroulante"),
    ("Edit footer", "Modifier le pied de page"),
    ("Edit header", "Modifier l'en-tête"),
    ("Edit watermark", "Modifier le filigrane"),
    ("Email Address", "Adresse E-mail"),
    ("Encrypt", "Chiffrer"),
    ("Eraser", "Gomme"),
    ("External links (import as values)", "Liens externes (importer en valeurs)"),
    ("Field list", "Liste des champs"),
    ("File", "Fichier"),
    ("Fill", "Recopier"),
    ("Fill by example", "Remplissage instantané"),
    ("Fill colour", "Couleur de remplissage"),
    ("Filter button", "Bouton de filtre"),
    ("Filters", "Filtres"),
    ("Financial", "Financier"),
    ("First column", "Première colonne"),
    ("Fit to page", "Ajuster à la page"),
    ("Fit to paper", "Ajuster au papier"),
    ("Fit to width", "Ajuster à la largeur"),
    ("Font", "Police"),
    ("Font colour", "Couleur de police"),
    ("Font size", "Taille de police"),
    ("Footnote", "Note de bas de page"),
    ("Forecast Sheet", "Feuille de prévision"),
    ("Format as table template", "Mettre sous forme de modèle de tableau"),
    ("Format cells", "Format des cellules"),
    ("Format painter", "Copier le format"),
    ("Forms", "Formulaires"),
    ("Formula", "Formule"),
    ("Formula Bar", "Barre de formule"),
    ("Freeze panes", "Figer les volets"),
    ("Goal Seek", "Valeur cible"),
    ("Grand Total", "Total général"),
    ("Gridlines", "Quadrillage"),
    ("Group", "Grouper"),
    ("Header & Footer", "En-tête/Pied de page"),
    ("Header row", "Ligne d’en-tête"),
    ("Headings", "Titres"),
    ("Hide detail", "Masquer le détail"),
    ("Highlight colour", "Couleur de surlignage"),
    ("Highlighter", "Surligneur"),
    ("Home", "Accueil"),
    ("Increase decimal", "Ajouter une décimale"),
    ("Increase indent", "Augmenter le retrait"),
    ("Increment font size", "Augmenter la taille de police"),
    ("Insert", "Insertion"),
    ("Insert Pivot Table", "Insérer un tableau croisé dynamique"),
    ("Insert SmartArt", "Insérer un graphique SmartArt"),
    ("Insert Text Art", "Insérer Text Art"),
    ("Insert blank page", "Insérer page vide"),
    ("Insert cells", "Insérer les cellules"),
    ("Insert chart", "Insérer un graphique"),
    ("Insert column", "Insérer une colonne"),
    ("Insert content controls", "Insérer des contrôles de contenu"),
    ("Insert drop cap", "Insérer une lettrine"),
    ("Insert equation", "Insérer une équation"),
    ("Insert function", "Insérer une fonction"),
    ("Insert image", "Insérer une image"),
    ("Insert recommended chart", "Insérer le graphique recommandé"),
    ("Insert shape", "Insérer une forme"),
    ("Insert slicer", "Isérer un segment"),
    ("Insert sparkline", "Insérer un graphique sparkline"),
    ("Insert symbol", "Insérer un symbole"),
    ("Insert table", "Insérer un tableau"),
    ("Insert text box", "Insérez zone de texte"),
    ("Italic", "Italique"),
    ("Justified", "Justifié"),
    ("Last column", "Dernière colonne"),
    ("Layout", "Mise en page"),
    ("Left Panel", "Panneau gauche"),
    ("Logical", "Logique"),
    ("Lookup & Reference", "Recherche et référence"),
    ("Macro list", "Liste"),
    ("Margins", "Marges"),
    ("Math & Trig", "Maths et trigonométrie"),
    ("Merge and centre", "Fusionner et centrer"),
    ("Merge shapes", "Combiner les formes"),
    ("More functions", "Plus de fonctions"),
    ("Multilevel list", "Liste multiniveau"),
    ("Multiple pages", "Plusieurs pages"),
    ("Name", "Nom"),
    ("Name manager", "Gestionnaire de noms"),
    ("New .py", "Nouveau .py"),
    ("Nonprinting characters", "Caractères non imprimables"),
    ("Number format", "Format de nombre"),
    ("Number of pages", "Nombre de pages"),
    ("Numbering", "Numérotation"),
    ("Open", "Ouvrir"),
    ("Open folder", "Ouvrir le dossier"),
    ("Page Break Preview", "Aperçu des sauts de page"),
    ("Page breaks", "Sauts de page"),
    ("Page number", "Numérotation des pages"),
    ("Page orientation", "Orientation de page"),
    ("Page size", "Taille de la page"),
    ("Paragraph line spacing", "Interligne du paragraphe"),
    ("Paragraph style", "Style de paragraphe"),
    ("Paste", "Coller"),
    ("Paste name", "Coller un nom"),
    ("Pen", "Stylo"),
    ("Percent style", "Style de pourcentage"),
    ("Phone Number", "Numéro de téléphone"),
    ("Picture", "Image"),
    ("Pivot Table", "Tableau croisé dynamique"),
    ("PivotChart", "Graphique croisé dynamique"),
    ("Print", "Imprimer"),
    ("Print Area", "Zone d'impression"),
    ("Print gridlines", "Imprimer le quadrillage"),
    ("Print headings", "Imprimer les en-têtes"),
    ("Print titles", "Titres à imprimer"),
    ("Protect Range", "Protéger la plage"),
    ("Protect sheet", "Protéger la feuille de calcul"),
    ("Protect workbook", "Protéger le classeur"),
    ("Python functions", "Fonctions Python"),
    ("Radio Button", "Bouton radio"),
    ("Recently used", "Récemment utilisées"),
    ("Record actions", "Enregistrer les actions"),
    ("Recover", "Récupérer"),
    ("References", "Références"),
    ("Remove Duplicates", "Supprimer les doublons"),
    ("Remove arrows", "Supprimer les flèches"),
    ("Remove duplicates", "Supprimer les doublons"),
    ("Replace", "Remplacer"),
    ("Report Layout", "Disposition du rapport"),
    ("Resize table", "Redimensionner le tableau"),
    ("Ribbon macros", "Macros du ruban"),
    ("Right Panel", "Panneau droit"),
    ("Right-to-left text", "Sens du texte (droite à gauche)"),
    ("Rulers", "Règles"),
    ("Save", "Enregistrer"),
    ("Scale To Fit", "Mettre à l’échelle"),
    ("Scenario", "Scénario"),
    ("Select", "Sélectionner"),
    ("Select all", "Sélectionner tout"),
    ("Send Backward", "Reculer"),
    ("Shading", "Ombrage"),
    ("Sheet View", "Mode Feuille"),
    ("Show comments", "Afficher les commentaires"),
    ("Show details", "Afficher les détails"),
    ("Show formulas", "Afficher les formules"),
    ("Show line numbers", "Afficher les numéros de ligne"),
    ("Show values as", "Type de calcul"),
    ("Show zeros", "Afficher les zéros"),
    ("Smaller UI text", "Réduire le texte de l'écran"),
    ("Solver", "Solveur"),
    ("Sort", "Trier"),
    ("Sort ascending", "Trier par ordre croissant"),
    ("Sort descending", "Trier par ordre décroissant"),
    ("Split", "Scinder la fenêtre"),
    ("Status Bar", "Barre d'état"),
    ("Strikethrough", "Barré"),
    ("Subscript", "Indice"),
    ("Subtotals", "Sous-totaux"),
    ("Suggest read-only", "Recommander la lecture seule"),
    ("Superscript", "Exposant"),
    ("Switch the sheet direction so that the first column is on the right side", "Inverser le sens de la feuille de manière à ce que la première colonne se trouve sur le côté droit"),
    ("Table Design", "Création de tableau"),
    ("Table of contents", "Table des matières"),
    ("Table of figures", "Table des illustrations"),
    ("Text Field", "Champ texte"),
    ("Text direction", "Orientation du texte"),
    ("Text from File", "Texte à partir d'un fichier"),
    ("Text functions", "Texte"),
    ("Text orientation", "Orientation du texte"),
    ("Text to columns", "Convertir"),
    ("Text to data", "Texte en données"),
    ("Total row", "Ligne des totaux"),
    ("Trace Dependents", "Tracer les dépendants"),
    ("Trace Precedents", "Tracer les précédents"),
    ("Track changes", "Suivi des modifications"),
    ("Underline", "Souligné"),
    ("Ungroup", "Dissocier"),
    ("Update", "Mettre à jour"),
    ("Update all", "Tout mettre à jour"),
    ("Update table of contents", "Mettre à jour la table des matières"),
    ("Update table of figures", "Mettre à jour la table des illustrations"),
    ("Version history", "Historique des versions"),
    ("View", "Afficher"),
    ("Watch window", "Fenêtre Espion"),
    ("Wrap text", "Renvoyer à la ligne"),
    ("Write macro", "Écrire une macro"),
    ("Zoom in", "Zoom avant"),
    ("Zoom out", "Zoom arrière"),
    ("Zoom to 100%", "Zoom à 100 %"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

