//! リボンの vi の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py vi > face/src/ribbon_vi.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Thêm bình luận"),
    ("Add Text", "Thêm chữ"),
    ("Add digital signature", "Thêm chữ ký số"),
    ("Add link", "Thêm siêu liên kết"),
    ("Add to area", "Thêm vào vùng in"),
    ("Align bottom", "Căn dưới cùng"),
    ("Align left", "Căn trái"),
    ("Align middle", "Căn giữa"),
    ("Align right", "Căn phải"),
    ("Align top", "Căn trên cùng"),
    ("Alignment", "Căn chỉnh"),
    ("Allowed actions", "Thao tác được phép"),
    ("Always Show Toolbar", "Luôn hiện thanh công cụ"),
    ("Backup interval", "Tần suất sao lưu"),
    ("Banded Rows", "Hàng xen kẽ màu"),
    ("Banded columns", "Cột sọc xen kẽ"),
    ("Bigger UI text", "Phóng to chữ màn hình"),
    ("Blank Rows", "Dòng trống"),
    ("Bold", "Đậm"),
    ("Bookmark", "Dấu trang"),
    ("Borders", "Viền"),
    ("Breaks", "Ngắt trang"),
    ("Bring forward", "Đưa lên trước"),
    ("Bullet", "Dấu đầu dòng"),
    ("CSV format", "Dạng CSV"),
    ("Calculation options", "Cách tính"),
    ("Caption", "Chú thích hình/bảng"),
    ("Cell Style", "Kiểu ô"),
    ("Cell lock", "Khoá ô"),
    ("Centre", "Trung tâm"),
    ("Change case", "Đổi chữ hoa/thường"),
    ("Change colour theme", "Thay đổi Phối màu"),
    ("Change hyphenation", "Ngắt từ bằng dấu gạch nối"),
    ("Change page colour", "Màu trang"),
    ("Chat", "Trò chuyện"),
    ("Checkbox", "Hộp kiểm"),
    ("Circle invalid data", "Khoanh dữ liệu không hợp lệ"),
    ("Clear", "Xóa"),
    ("Clear filter", "Bỏ lọc"),
    ("Clear style", "Xóa Kiểu"),
    ("Co-editing mode", "Chế độ đồng soạn thảo"),
    ("Collaboration", "Cộng tác"),
    ("Combo box", "Hộp tổ hợp"),
    ("Comma style", "Kiểu dấu phẩy"),
    ("Comment", "Bình luận"),
    ("Complex Field", "Trường phức hợp"),
    ("Conditional formatting", "Định dạng có điều kiện"),
    ("Convert to range", "Chuyển đổi sang phạm vi"),
    ("Copy", "Sao chép"),
    ("Cross-reference", "Tham chiếu chéo"),
    ("Currency style", "Kiểu tiền tệ"),
    ("Cut", "Cắt"),
    ("Dark mode", "Chế độ tối"),
    ("Data", "Dữ liệu"),
    ("Data Validation", "Xác thực dữ liệu"),
    ("Data source", "Nguồn dữ liệu"),
    ("Data table", "Bảng dữ liệu"),
    ("Date & Time", "Ngày & Giờ"),
    ("Decrease decimal", "Giảm thập phân"),
    ("Decrease indent", "Giảm thụt lề"),
    ("Decrement font size", "Giảm cỡ chữ"),
    ("Delete cells", "Xóa Ô"),
    ("Delete comment", "Xóa nhận xét"),
    ("Distributed", "Phân bố đều"),
    ("Draw", "Vẽ"),
    ("Dropdown", "Danh sách thả xuống"),
    ("Edit footer", "Chỉnh sửa Footer"),
    ("Edit header", "Chỉnh sửa Header"),
    ("Edit watermark", "Sửa hình mờ"),
    ("Email Address", "Địa chỉ email"),
    ("Encrypt", "Mã hóa"),
    ("Eraser", "Tẩy"),
    ("External links (import as values)", "Liên kết ngoài (nhập theo giá trị)"),
    ("Field list", "Danh sách trường"),
    ("Fill", "Điền"),
    ("Fill by example", "Điền nhanh"),
    ("Fill colour", "Màu nền"),
    ("Filter button", "Nút lọc"),
    ("Filters", "Bộ lọc"),
    ("Financial", "Tài chính"),
    ("First column", "Cột đầu"),
    ("Fit to page", "Vừa với trang"),
    ("Fit to paper", "Thu vừa tờ giấy"),
    ("Fit to width", "Vừa với Chiều rộng"),
    ("Font", "Phông chữ"),
    ("Font colour", "Màu chữ"),
    ("Font size", "Cỡ chữ"),
    ("Footnote", "Chú thích cuối trang"),
    ("Forecast Sheet", "Trang dự báo"),
    ("Format as table template", "Định dạng như Template Bảng"),
    ("Format cells", "Định dạng ô"),
    ("Format painter", "Sao chép định dạng"),
    ("Forms", "Biểu mẫu"),
    ("Formula", "Công thức"),
    ("Formula Bar", "Thanh công thức"),
    ("Freeze panes", "Cố định ngăn"),
    ("Goal Seek", "Tìm mục tiêu"),
    ("Grand Total", "Tổng chung"),
    ("Gridlines", "Đường lưới"),
    ("Group", "Nhóm"),
    ("Header & Footer", "Header/Footer"),
    ("Header row", "Hàng tiêu đề"),
    ("Headings", "Tiêu đề"),
    ("Hide detail", "Ẩn chi tiết"),
    ("Highlight colour", "Màu tô sáng"),
    ("Highlighter", "Bút dạ quang"),
    ("Home", "Trang chủ"),
    ("Increase decimal", "Tăng thập phân"),
    ("Increase indent", "Tăng thụt lề"),
    ("Increment font size", "Tăng kích thước phông chữ"),
    ("Insert", "Chèn"),
    ("Insert Pivot Table", "Chèn PivotTable"),
    ("Insert SmartArt", "Chèn SmartArt"),
    ("Insert Text Art", "Chèn chữ nghệ thuật"),
    ("Insert blank page", "Chèn trang trống"),
    ("Insert cells", "Chèn ô"),
    ("Insert chart", "Chèn biểu đồ"),
    ("Insert column", "Chèn Cột"),
    ("Insert content controls", "Chèn điều khiển nội dung"),
    ("Insert drop cap", "Chèn Drop Cap"),
    ("Insert equation", "Chèn phương trình"),
    ("Insert function", "Chèn hàm"),
    ("Insert image", "Chèn hình ảnh"),
    ("Insert recommended chart", "Chèn biểu đồ đề xuất"),
    ("Insert shape", "Chèn Autoshape"),
    ("Insert slicer", "Chèn slicer"),
    ("Insert sparkline", "Chèn biểu đồ thu nhỏ"),
    ("Insert symbol", "Chèn ký hiệu"),
    ("Insert table", "Chèn bảng"),
    ("Insert text box", "Chèn văn bản"),
    ("Italic", "Nghiêng"),
    ("Justified", "Canh đều"),
    ("Last column", "Cột cuối cùng"),
    ("Layout", "Bố cục"),
    ("Left Panel", "Bảng bên trái"),
    ("Logical", "Logic"),
    ("Lookup & Reference", "Tra cứu & tham chiếu"),
    ("Macro list", "Danh sách"),
    ("Macros", "Macro"),
    ("Margins", "Lề"),
    ("Math & Trig", "Toán & Lượng giác"),
    ("Merge and centre", "Gộp"),
    ("Merge shapes", "Hợp nhất hình dạng"),
    ("More functions", "Hàm khác"),
    ("Multilevel list", "Danh sách Đa cấp"),
    ("Multiple pages", "Nhiều trang"),
    ("Name", "Tên"),
    ("Name manager", "Quản lý tên"),
    ("Navigation", "Dẫn hướng"),
    ("New .py", "Tệp .py mới"),
    ("Nonprinting characters", "Ký tự không in"),
    ("Normal", "Thường"),
    ("Number format", "Định dạng số"),
    ("Number of pages", "tổng số trang"),
    ("Numbering", "Đánh số"),
    ("Open", "Mở"),
    ("Open folder", "Mở thư mục"),
    ("Page Break Preview", "Xem trước ngắt trang"),
    ("Page breaks", "Chỗ hết tờ giấy"),
    ("Page number", "số trang"),
    ("Page orientation", "Hướng trang"),
    ("Page size", "Kích thước trang"),
    ("Paragraph line spacing", "Khoảng cách Dòng trong Đoạn văn bản"),
    ("Paragraph style", "Kiểu đoạn"),
    ("Paste", "Dán"),
    ("Paste name", "Dán tên"),
    ("Pen", "Bút"),
    ("Percent style", "Kiểu phần trăm"),
    ("Phone Number", "Số điện thoại"),
    ("Picture", "Hình ảnh"),
    ("Pivot Table", "PivotTable"),
    ("Print", "In"),
    ("Print Area", "Vùng in"),
    ("Print gridlines", "In cả đường lưới"),
    ("Print headings", "In cả tiêu đề"),
    ("Print titles", "In tiêu đề"),
    ("Protect Range", "Bảo vệ phạm vi"),
    ("Protect sheet", "Bảo vệ trang tính"),
    ("Protect workbook", "Bảo vệ sổ làm việc"),
    ("Protection", "Bảo vệ"),
    ("Python functions", "Hàm Python"),
    ("Radio Button", "Nút radio"),
    ("Recently used", "Dùng gần đây"),
    ("Record actions", "Ghi lại thao tác"),
    ("Recover", "Khôi phục"),
    ("References", "Tham khảo"),
    ("Remove Duplicates", "Xóa dữ liệu trùng lặp"),
    ("Remove arrows", "Xóa mũi tên truy vết"),
    ("Remove duplicates", "Xóa trùng lặp"),
    ("Replace", "Thay thế"),
    ("Report Layout", "Bố cục báo cáo"),
    ("Resize table", "Đổi cỡ bảng"),
    ("Ribbon macros", "Macro ruy-băng"),
    ("Right Panel", "Bảng bên phải"),
    ("Right-to-left text", "Hướng chữ (phải sang trái)"),
    ("Rulers", "Thước"),
    ("Save", "Lưu"),
    ("Scale To Fit", "Co giãn khi in"),
    ("Scenario", "Kịch bản"),
    ("Select", "Chọn"),
    ("Select all", "Chọn tất cả"),
    ("Send Backward", "Gửi về phía sau"),
    ("Shading", "Màu nền đoạn văn bản"),
    ("Sheet View", "Hiện trang tính"),
    ("Show comments", "Hiển thị bình luận"),
    ("Show details", "Hiển thị chi tiết"),
    ("Show formulas", "Hiển thị công thức"),
    ("Show line numbers", "Hiện số dòng"),
    ("Show values as", "Cách hiện giá trị"),
    ("Show zeros", "Hiển thị số 0"),
    ("Signature", "Chữ ký"),
    ("Smaller UI text", "Thu nhỏ chữ màn hình"),
    ("Sort", "Sắp xếp"),
    ("Sort ascending", "Sắp xếp tăng dần"),
    ("Sort descending", "Sắp xếp giảm dần"),
    ("Split", "Phân chia cửa sổ"),
    ("Status Bar", "Thanh trạng thái"),
    ("Strikethrough", "Gạch bỏ"),
    ("Style", "Kiểu"),
    ("Subscript", "Chỉ số dưới"),
    ("Subtotals", "Tổng phụ"),
    ("Suggest read-only", "Khuyên chỉ đọc"),
    ("Superscript", "Chỉ số trên"),
    ("Switch the sheet direction so that the first column is on the right side", "Đổi hướng trang tính để cột đầu ở bên phải"),
    ("Table Design", "Thiết kế bảng"),
    ("Table of contents", "Mục lục"),
    ("Table of figures", "Mục lục hình/bảng"),
    ("Text Field", "Trường văn bản"),
    ("Text direction", "Hướng văn bản"),
    ("Text from File", "Văn bản từ tệp"),
    ("Text functions", "Văn bản"),
    ("Text orientation", "Hướng chữ"),
    ("Text to columns", "Tách cột"),
    ("Text to data", "Văn bản thành dữ liệu"),
    ("Total row", "Hàng tổng"),
    ("Trace Dependents", "Truy vết ô phụ thuộc"),
    ("Trace Precedents", "Truy vết ô ảnh hưởng"),
    ("Track changes", "Theo dõi Thay đổi"),
    ("Underline", "Gạch chân"),
    ("Ungroup", "Bỏ nhóm"),
    ("Update", "Làm mới"),
    ("Update all", "Làm mới tất cả"),
    ("Update table of contents", "Cập nhật mục lục"),
    ("Update table of figures", "Cập nhật mục lục hình/bảng"),
    ("Version history", "Lịch sử phiên bản"),
    ("View", "Hiển thị"),
    ("Watch window", "Cửa sổ theo dõi"),
    ("Wrap text", "Ngắt dòng trong ô"),
    ("Write macro", "Viết macro"),
    ("Zoom in", "Phóng to"),
    ("Zoom out", "Thu nhỏ"),
    ("Zoom to 100%", "Thu phóng về 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

