//! リボンの ja 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py ja > face/src/ribbon_ja.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "ファイル", cmds: &[
        c("open", "開く", "open"),
        c("save", "保存", "save"),
        c("pdf", "印刷", "print"),
    ]},
    Tab { name: "ホーム", cmds: &[
        c("copy", "コピー", "copy"),
        c("cut", "切り取り", "cut"),
        c("paste", "貼り付け", "paste"),
        c("fontname", "フォント", "fontname"),
        c("fontsize", "フォントのサイズ", "fontsize"),
        c("incfont", "フォントサイズの拡大", "incfont"),
        c("decfont", "フォントサイズの縮小", "decfont"),
        c("changecase", "大文字小文字を変更", "changecase"),
        c("ruby", "ルビ", "ruby"),
        c("ai-furigana", "ふりがな", "ai-furigana"),
        c("bold", "太字", "bold"),
        c("italic", "斜体", "italic"),
        c("underline", "下線", "underline"),
        c("strikeout", "取り消し線", "strikeout"),
        c("superscript", "上付き", "superscript"),
        c("subscript", "下付き", "subscript"),
        c("highlight", "ハイライトの色", "highlight"),
        c("fontcolor", "フォントの色", "fontcolor"),
        c("clearstyle", "スタイルのクリア", "clearstyle"),
        c("markers", "箇条書き", "markers"),
        c("numbering", "ナンバリング", "numbering"),
        c("multilevels", "複数レベルのリスト", "multilevels"),
        c("decoffset", "インデントを減らす", "decoffset"),
        c("incoffset", "インデントを増やす", "incoffset"),
        c("linespace", "段落の行間", "linespace"),
        c("direction", "テキスト方向", "direction"),
        c("align-left", "左揃え", "align-left"),
        c("align-center", "中央揃え", "align-center"),
        c("align-right", "右揃え", "align-right"),
        c("align-just", "両端揃え", "align-just"),
        c("align-dist", "均等割付", "align-dist"),
        c("hidenchars", "非表示文字", "hidenchars"),
        c("paracolor", "段落の背景色", "paracolor"),
        c("borders", "罫線", "borders"),
        c("parastyle", "段落のスタイル", "styles"),
        c("replace", "置き換え", "replace"),
        c("selectall", "すべて選択", "select-all"),
    ]},
    Tab { name: "挿入", cmds: &[
        c("blankpage", "空白ページの挿入", "blankpage"),
        c("pagebreak", "区切り", "pagebreak"),
        c("instable", "表の挿入", "instable"),
        c("insimage", "画像を挿入", "insertimage"),
        c("insshape", "図形を挿入", "insshape"),
        c("inssmartart", "SmartArtの挿入", "inssmartart"),
        c("inschart", "グラフを挿入", "inschart"),
        c("instext", "テキストボックスの挿入", "instext"),
        c("instextart", "テキストアートの挿入", "instextart"),
        c("dropcap", "ドロップキャップの挿入", "dropcap"),
        c("text-from-file", "ファイルからのテキスト", "text-from-file"),
        c("edit-header", "ヘッダーの編集", "edit-header"),
        c("edit-footer", "フッターの編集", "edit-footer"),
        c("pagenum", "ページ番号", "pagenum"),
        c("datetime", "日付/時刻", "datetime"),
        c("numpages", "ページ数", "numpages"),
        c("insequation", "方程式を挿入", "insequation"),
        c("inssymbol", "記号を挿入", "inssymbol"),
        c("controls", "コンテンツコントロールの挿入", "controls"),
    ]},
    Tab { name: "描画", cmds: &[
        c("pen", "ペン", "pen"),
        c("highlighter", "蛍光ペン", "highlighter"),
        c("eraser", "消しゴム", "eraser"),
    ]},
    Tab { name: "レイアウト", cmds: &[
        c("pagemargins", "余白", "pagemargins"),
        c("pageorient", "印刷の向き", "pageorient"),
        c("pagesize", "ページのサイズ", "pagesize"),
        c("columns", "列の挿入", "columns"),
        c("line-numbers", "行番号を表示する", "line-numbers"),
        c("hyphenation", "ハイフン設定の変更", "hyphenation"),
        x("前面ヘ移動", "img-movefrwd"),
        x("背面ヘ移動", "img-movebkwd"),
        x("配置", "img-align"),
        x("グループ化", "img-group"),
        x("図形を結合", "shapes-merge"),
        c("watermark", "透かしを編集する", "watermark"),
        c("pagecolor", "ページ色の変更", "pagecolor"),
        c("colorschemas", "配色の変更", "colorschemas"),
    ]},
    Tab { name: "参考資料", cmds: &[
        c("toc", "目次", "contents"),
        c("add-text", "テキストの追加", "add-text"),
        c("toc-update", "目次の更新", "contents-update"),
        c("bookmarks", "ブックマーク", "bookmarks"),
        c("caption", "図表番号", "caption"),
        c("crossref", "相互参照", "crossref"),
        c("footnote", "脚注", "footnote"),
        c("tof", "図表目次", "tof"),
        c("tof-update", "図表目次の更新", "tof-update"),
    ]},
    Tab { name: "フォーム", cmds: &[
        c("form-text", "テキストフィールド", "form-text"),
        c("form-combo", "コンボボックス", "form-combo"),
        c("form-dropdown", "ドロップダウン", "form-dropdown"),
        c("form-checkbox", "チェックボックス", "form-checkbox"),
        c("form-radio", "ラジオボタン", "form-radio"),
        c("form-image", "画像", "form-image"),
        c("form-email", "メールアドレス", "form-email"),
        c("form-phone", "電話番号", "form-phone"),
        c("form-complex", "複合フィールド", "form-complex"),
        c("form-signature", "署名", "form-signature"),
        c("form-name", "名前", "form-name"),
    ]},
    Tab { name: "共同編集", cmds: &[
        c("coauth-mode", "共同編集モード", "coauth-mode"),
        c("co-addcomment", "コメントを追加", "co-addcomment"),
        c("co-delcomment", "コメントを削除", "co-delcomment"),
        c("co-showcomment", "コメントの表示", "co-showcomment"),
        c("co-chat", "チャット", "co-chat"),
        c("track-changes", "変更履歴", "track-changes"),
        c("co-history", "バージョン履歴", "co-history"),
    ]},
    Tab { name: "保護", cmds: &[
        c("prot-sign", "デジタル署名を追加", "prot-sign"),
        c("prot-doc", "保護", "prot-doc"),
    ]},
    Tab { name: "表示", cmds: &[
        t("nav", "ナビゲーション", "nav"),
        c("fit-page", "ページに合わせる", "fit-page"),
        c("fit-width", "幅に合わせる", "fit-width"),
        c("zoom100", "100%に拡大する", "zoom100"),
        c("zoom-in", "拡大", "zoom-in"),
        c("zoom-out", "縮小", "zoom-out"),
        c("printview", "印刷レイアウト", "printview"),
        c("multipage", "複数ページ", "multipage"),
        t("darkmode", "ダークモード", "darkmode"),
        c("ui-bigger", "画面の文字を大きく", "ui-bigger"),
        c("ui-smaller", "画面の文字を小さく", "ui-smaller"),
        c("ruler", "ルーラー", "ruler"),
        t("show-toolbar", "ツールバーを常に表示する", "show-toolbar"),
        t("show-statusbar", "ステータスバー", "show-statusbar"),
        t("show-left", "左パネル", "show-left"),
        t("show-right", "右パネル", "show-right"),
    ]},
    Tab { name: "マクロ", cmds: &[
        c("py-list", "一覧", "plug-manage"),
        c("py-folder", "置き場を開く", "py-folder"),
        c("ai-macro", "マクロを書く", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "ファイル", cmds: &[
        c("open", "開く", "open"),
        c("save", "保存", "save"),
        c("pdf", "印刷", "print"),
    ]},
    Tab { name: "ホーム", cmds: &[
        c("copy", "コピー", "copy"),
        c("cut", "切り取り", "cut"),
        c("paste", "貼り付け", "paste"),
        c("copystyle", "書式のコピー", "copystyle"),
        c("fontname", "フォント", "fontname"),
        c("fontsize", "フォントのサイズ", "fontsize"),
        c("incfont", "フォントサイズの拡大", "incfont"),
        c("decfont", "フォントサイズの縮小", "decfont"),
        c("changecase", "大文字小文字を変更", "changecase"),
        c("bold", "太字", "bold"),
        c("italic", "斜体", "italic"),
        c("underline", "下線", "underline"),
        c("strikeout", "取り消し線", "strikeout"),
        c("subscript", "下付き", "subscript"),
        c("fontcolor", "フォントの色", "fontcolor"),
        c("fillparag", "塗りつぶしの色", "fillparag"),
        c("borders", "罫線", "borders"),
        c("top", "上揃え", "top"),
        c("middle", "上下中央揃え", "middle"),
        c("bottom", "下揃え", "bottom"),
        c("wrap", "折り返して全体を表示する", "wrap"),
        c("text-orient", "文字の向き", "text-orient"),
        c("align-left", "左揃え", "align-left"),
        c("align-center", "中央揃え", "align-center"),
        c("align-right", "右揃え", "align-right"),
        c("align-just", "両端揃え", "align-just"),
        c("align-dist", "均等割付", "align-dist"),
        c("merge", "結合して、中央に配置する", "merge"),
        c("direction", "文字の向き(右横書き)", "direction"),
        c("sum", "オートSUM", "autosum"),
        c("fill-num", "フィル", "fill-num"),
        c("defname", "名前の管理", "named-range"),
        c("clear", "消去", "clear"),
        c("sort-desc", "降順並べ替え", "sortdesc"),
        c("sort-asc", "昇順並べ替え", "sortasc"),
        c("setfilter", "フィルター", "setfilter"),
        c("clear-filter", "フィルターを解除", "clear-filter"),
        c("format", "数値の書式", "format"),
        c("currency", "通貨スタイル", "currency"),
        c("percents", "パーセントのスタイル", "percents"),
        c("comma", "カンマスタイル", "comma"),
        c("digit-dec", "小数点以下の表示桁数を減らす", "digit-dec"),
        c("digit-inc", "小数点以下の表示桁数を増やす", "digit-inc"),
        c("cell-ins", "セルを挿入", "cell-ins"),
        c("cell-del", "セルを削除", "cell-del"),
        c("cell-format", "セルの書式設定", "cell-format"),
        c("condformat", "条件付き書式", "condformat"),
        c("table-tpl", "表として書式設定", "table-tpl"),
        c("cell-styles", "セルのスタイル", "styles"),
        c("replace", "置き換え", "replace"),
        c("selectall", "すべて選択", "select-all"),
    ]},
    Tab { name: "挿入", cmds: &[
        c("pivot-insert", "ピボットテーブルを挿入", "add-pivot"),
        c("instable", "表の挿入", "instable"),
        c("insimage", "画像を挿入", "insimage-c"),
        c("insshape", "図形を挿入", "insshape"),
        c("inssmartart", "SmartArtの挿入", "inssmartart"),
        c("inscheckbox", "チェックボックス", "inscheckbox"),
        c("insrecommend", "推奨チャートを挿入", "insrecommend"),
        c("inschart", "グラフを挿入", "inschart"),
        c("inssparkline", "スパークラインを挿入する", "inssparkline"),
        c("co-addcomment", "コメント", "ins-comment"),
        c("inshyperlink", "ハイパーリンクを追加", "inshyperlink"),
        c("insslicer", "スライサーを挿入", "insslicer"),
        c("instext", "テキストボックスの挿入", "instext"),
        c("instextart", "テキストアートの挿入", "instextart"),
        c("edit-header", "ヘッダー/フッター", "editheader"),
        c("insequation", "方程式を挿入", "insequation"),
        c("inssymbol", "記号を挿入", "inssymbol"),
    ]},
    Tab { name: "描画", cmds: &[
        c("draw-select", "選択", "select-tool"),
        c("pen", "ペン", "pen"),
        c("highlighter", "蛍光ペン", "highlighter"),
        c("eraser", "消しゴム", "eraser"),
    ]},
    Tab { name: "レイアウト", cmds: &[
        c("pagemargins", "余白", "pagemargins"),
        c("pageorient", "印刷の向き", "pageorient"),
        c("pagesize", "ページのサイズ", "pagesize"),
        c("printarea", "印刷範囲", "printarea"),
        c("pagebreak", "区切り", "pagebreak"),
        c("edit-header", "ヘッダー/フッター", "editheader"),
        c("scale", "拡大縮小印刷", "scale"),
        c("fit-pages", "紙に収める", "fit-pages"),
        c("printarea-add", "範囲を足す", "printarea-add"),
        c("show-breaks", "紙の切れ目", "show-breaks"),
        c("printtitles", "タイトルを印刷する", "printtitles"),
        c("rtl-sheet", "最初の列が右側に来るようにシートの方向を切り替える", "rtl-sheet"),
        c("print-gridlines", "枠線も印刷", "print-gridlines"),
        c("print-headings", "見出しも印刷", "print-headings"),
        x("前面ヘ移動", "img-movefrwd"),
        x("背面ヘ移動", "img-movebkwd"),
        x("配置", "img-align"),
        x("グループ化", "img-group"),
        x("図形を結合", "shapes-merge"),
        c("colorschemas", "配色の変更", "colorschemas"),
    ]},
    Tab { name: "数式", cmds: &[
        c("insert-function", "関数の挿入", "additional-formula"),
        c("func-list", "Python の関数", "py-list"),
        c("sum", "オートSUM", "autosum"),
        c("fn-recent", "最近使った関数", "recent"),
        c("fn-financial", "財務", "financial"),
        c("fn-logical", "論理", "logical"),
        c("fn-text", "テキスト", "text"),
        c("fn-datetime", "日付/時刻", "datetime"),
        c("fn-lookup", "検索/行列", "lookup"),
        c("fn-math", "数学/三角", "math"),
        c("fn-more", "その他の関数", "more"),
        c("defname", "名前の管理", "named-range-huge"),
        c("paste-name", "名前を貼り付け", "paste-name"),
        c("trace-prec", "参照元のトレース", "trace-prec"),
        c("trace-dep", "参照先のトレース", "trace-dep"),
        c("remove-arrows", "トレース矢印の削除", "remove-arrows"),
        c("show-formulas", "数式の表示", "show-formulas"),
        c("watch", "ウォッチウィンドウ", "watch-window"),
        c("calc-mode", "計算方法", "calculate"),
    ]},
    Tab { name: "データ", cmds: &[
        c("data-from-text", "テキストからデータ", "data-from-text"),
        c("data-external-links", "外部リンク(値で取り込む)", "data-external-links"),
        c("setfilter", "フィルター", "setfilter"),
        c("clear-filter", "フィルターを解除", "clear-filter"),
        c("sort-desc", "降順並べ替え", "sortdesc"),
        c("sort-asc", "昇順並べ替え", "sortasc"),
        c("custom-sort", "並べ替え", "custom-sort"),
        c("text-column", "区切り位置", "text-column"),
        c("rem-duplicates", "重複の削除", "rem-duplicates"),
        c("data-validation", "データの入力規則", "data-validation"),
        t("dv-mark", "無効データのマーク", "dv-mark"),
        c("goal-seek", "ゴールシーク", "goal-seek"),
        c("scenario", "シナリオ", "scenario"),
        c("forecast", "予測シート", "forecast"),
        c("solver", "ソルバー", "solver"),
        c("group", "グループ化", "group"),
        c("ungroup", "グループ解除", "ungroup"),
        c("show-details", "詳細の表示", "show-details"),
        c("hide-details", "詳細の非表示", "hide-details"),
        c("subtotal", "小計", "subtotal"),
        c("datatable", "データテーブル", "datatable"),
        c("python", "Python", "python"),
        c("csv-kind", "CSV の形", "csv-kind"),
        c("flash-fill", "フラッシュフィル", "flash-fill"),
    ]},
    Tab { name: "マクロ", cmds: &[
        c("rec-toggle", "操作を記録", "py-run"),
        c("py-new", "新しい .py", "py-new"),
        c("py-list", "一覧", "py-list"),
        c("ribbon-list", "リボンのマクロ", "py-line"),
        c("py-folder", "置き場を開く", "py-folder"),
    ]},
    Tab { name: "ピボットテーブル", cmds: &[
        c("pivot-insert", "ピボットテーブルを挿入", "pivot-insert"),
        c("pivot-fields", "フィールドリスト", "pivot-fields"),
        c("pivot-refresh", "更新", "pivot-refresh"),
        c("pivot-refresh-all", "すべて更新", "pivot-refresh-all"),
        c("pivot-source", "データソース", "pivot-source"),
        c("pivot-chart", "ピボットグラフ", "pivot-chart"),
        c("pivot-select", "選択する", "pivot-select"),
        c("pivot-totals", "総計", "pivot-totals"),
        c("pivot-subtotals", "小計", "pivot-subtotals"),
        c("pivot-blank", "空行", "pivot-blank"),
        c("pivot-showas", "計算の種類", "pivot-showas"),
        c("pivot-layout", "レポートのレイアウト", "pivot-layout"),
        c("pivot-style", "スタイル", "pivot-style"),
    ]},
    Tab { name: "表のデザイン", cmds: &[
        c("td-header", "ヘッダー行", "td-header"),
        c("td-total", "合計行", "td-total"),
        c("td-band-row", "縞模様の行", "td-band-row"),
        c("td-first", "最初の列", "td-first"),
        c("td-last", "最後の列", "td-last"),
        c("td-band-col", "縞模様の列", "td-band-col"),
        c("td-filter", "フィルタのボタン", "td-filter"),
        c("rem-duplicates", "重複データを削除", "td-remdup"),
        c("td-torange", "範囲に変換する", "td-torange"),
        c("td-resize", "テーブルのサイズ変更", "td-resize"),
    ]},
    Tab { name: "共同編集", cmds: &[
        c("coauth-mode", "共同編集モード", "coauth-mode"),
        c("co-addcomment", "コメントを追加", "co-addcomment"),
        c("co-delcomment", "コメントを削除", "co-delcomment"),
        c("co-showcomment", "コメントの表示", "co-showcomment"),
        c("co-chat", "チャット", "co-chat"),
        c("co-history", "バージョン履歴", "co-history"),
    ]},
    Tab { name: "保護", cmds: &[
        c("prot-encrypt", "暗号化する", "prot-encrypt"),
        xt("ブックを保護する", "protect-workbook"),
        c("prot-doc", "シートを保護する", "protect-sheet"),
        xt("範囲を保護する", "protect-range"),
        c("prot-sign", "デジタル署名を追加", "prot-sign"),
        c("cell-lock", "セルのロック", "cell-lock"),
        c("prot-allow", "許可する操作", "prot-allow"),
        c("recover", "復旧", "recover"),
        c("recover-every", "控えの間隔", "recover-every"),
        c("read-only-rec", "読み取り専用を勧める", "read-only-rec"),
    ]},
    Tab { name: "表示", cmds: &[
        c("sheet-view", "シートの表示", "sheet-view"),
        xm("標準", "view-normal"),
        xm("改ページ プレビュー", "view-pagebreak"),
        c("zoom-in", "拡大", "zoom-in"),
        c("zoom-out", "縮小", "zoom-out"),
        c("zoom100", "100%に拡大する", "zoom100"),
        c("ui-bigger", "画面の文字を大きく", "ui-bigger"),
        c("ui-smaller", "画面の文字を小さく", "ui-smaller"),
        t("darkmode", "ダークモード", "theme"),
        c("freeze", "ウィンドウ枠の固定", "freeze"),
        t("split", "分割", "split"),
        t("formula-bar", "数式バー", "formula-bar"),
        c("show-gridlines", "枠線表示", "show-gridlines"),
        t("show-headings", "見出し", "show-headings"),
        t("show-zeros", "0を表示する", "show-zeros"),
        t("show-left", "左パネル", "show-left"),
        t("show-right", "右パネル", "show-right"),
    ]},
];

