//! リボンの de の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py de > face/src/ribbon_de.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Kommentar hinzufügen"),
    ("Add Text", "Text Hinzufügen"),
    ("Add digital signature", "Digitale Signatur hinzufügen"),
    ("Add link", "Link hinzufügen"),
    ("Add to area", "Bereich hinzufügen"),
    ("Align bottom", "Unten ausrichten"),
    ("Align left", "Links ausrichten"),
    ("Align middle", "Mittig ausrichten"),
    ("Align right", "Rechts ausrichten"),
    ("Align top", "Oben ausrichten"),
    ("Alignment", "Ausrichtung"),
    ("Allowed actions", "Erlaubte Aktionen"),
    ("Always Show Toolbar", "Symbolleiste immer anzeigen"),
    ("AutoSum", "AutoSumme"),
    ("Backup interval", "Sicherungsintervall"),
    ("Banded Rows", "Verbundene Zeilen"),
    ("Banded columns", "Gebänderte Spalten"),
    ("Bigger UI text", "Oberflächentext größer"),
    ("Blank Rows", "Leere Zeilen"),
    ("Bold", "Fett"),
    ("Bookmark", "Lesezeichen"),
    ("Borders", "Rahmen"),
    ("Breaks", "Umbrüche"),
    ("Bring forward", "Eine Ebene nach vorne"),
    ("Bullet", "Aufzählungszeichen"),
    ("CSV format", "CSV-Format"),
    ("Calculation options", "Berechnung"),
    ("Caption", "Beschriftung"),
    ("Cell Style", "Zellenformatvorlage"),
    ("Cell lock", "Zelle sperren"),
    ("Centre", "Zentriert"),
    ("Change case", "Groß-/Kleinschreibung ändern"),
    ("Change colour theme", "Farbschema ändern"),
    ("Change hyphenation", "Trennen ändern"),
    ("Change page colour", "Seitenfarbe ändern"),
    ("Checkbox", "Kontrollkästchen"),
    ("Circle invalid data", "Ungültige Daten einkreisen"),
    ("Clear", "Leeren"),
    ("Clear filter", "Filter löschen"),
    ("Clear style", "Formatierung löschen"),
    ("Co-editing mode", "Co-Bearbeitung"),
    ("Collaboration", "Zusammenarbeit"),
    ("Combo box", "Combobox"),
    ("Comma style", "Komma-Format"),
    ("Comment", "Kommentar"),
    ("Complex Field", "Komplexes Feld"),
    ("Conditional formatting", "Bedingte Formatierung"),
    ("Convert to range", "In Zellenbereich konvertieren"),
    ("Copy", "Kopieren"),
    ("Cross-reference", "Querverweis"),
    ("Currency style", "Währungsformat"),
    ("Cut", "Ausschneiden"),
    ("Dark mode", "Dunkelmodus"),
    ("Data", "Daten"),
    ("Data Validation", "Datenüberprüfung"),
    ("Data source", "Datenquelle"),
    ("Data table", "Datentabelle"),
    ("Date & Time", "Datum/Uhrzeit"),
    ("Decrease decimal", "Dezimalstelle löschen"),
    ("Decrease indent", "Einzug verkleinern"),
    ("Decrement font size", "Schriftart verkleinern"),
    ("Delete cells", "Zellen löschen"),
    ("Delete comment", "Kommentar löschen"),
    ("Distributed", "Verteilt"),
    ("Draw", "Zeichnen"),
    ("Edit footer", "Fußzeile bearbeiten"),
    ("Edit header", "Kopfzeile bearbeiten"),
    ("Edit watermark", "Wasserzeichen bearbeiten"),
    ("Email Address", "E-Mail-Adresse"),
    ("Encrypt", "Verschlüsseln"),
    ("Eraser", "Radierer"),
    ("External links (import as values)", "Externe Verknüpfungen (als Werte einlesen)"),
    ("Field list", "Feldliste"),
    ("File", "Datei"),
    ("Fill", "Ausfüllen"),
    ("Fill by example", "Musterfüllung"),
    ("Fill colour", "Füllfarbe"),
    ("Filter button", "Schaltfläche Filter"),
    ("Filters", "Filter"),
    ("Financial", "Finanzmathematik"),
    ("First column", "Erste Spalte"),
    ("Fit to page", "Seite anpassen"),
    ("Fit to paper", "Aufs Blatt einpassen"),
    ("Fit to width", "Breite anpassen"),
    ("Font", "Schriftart"),
    ("Font colour", "Schriftfarbe"),
    ("Font size", "Schriftgrad"),
    ("Footnote", "Fußnote"),
    ("Forecast Sheet", "Prognoseblatt"),
    ("Format as table template", "Wie Tabellenvorlage formatieren"),
    ("Format cells", "Zellen formatieren"),
    ("Format painter", "Format übertragen"),
    ("Forms", "Formulare"),
    ("Formula", "Formel"),
    ("Formula Bar", "Formelleiste"),
    ("Freeze panes", "Fensterausschnitt fixieren"),
    ("Goal Seek", "Zielwertsuche"),
    ("Grand Total", "Gesamtsumme"),
    ("Gridlines", "Gitternetzlinien "),
    ("Group", "Gruppieren"),
    ("Header & Footer", "Kopf- und Fußzeile"),
    ("Header row", "Kopfzeile"),
    ("Headings", "Überschriften"),
    ("Hide detail", "Detail ausblenden"),
    ("Highlight colour", "Texthervorhebungsfarbe"),
    ("Highlighter", "Textmarker"),
    ("Home", "Startseite"),
    ("Increase decimal", "Dezimalstelle erhöhen"),
    ("Increase indent", "Einzug vergrößern"),
    ("Increment font size", "Schriftart vergrößern"),
    ("Insert", "Einfügen"),
    ("Insert Pivot Table", "Pivot-Tabelle einfügen"),
    ("Insert SmartArt", "SmartArt einfügen"),
    ("Insert Text Art", "TextArt einfügen"),
    ("Insert blank page", "Leere Seite einlegen"),
    ("Insert cells", "Zellen einfügen"),
    ("Insert chart", "Diagramm einfügen"),
    ("Insert column", "Spalte einfügen"),
    ("Insert content controls", "Inhaltssteuerelemente einfügen"),
    ("Insert drop cap", "Initiale einfügen"),
    ("Insert equation", "Formel einfügen"),
    ("Insert function", "Funktion einfügen"),
    ("Insert image", "Bild einfügen"),
    ("Insert recommended chart", "Empfohlenes Diagramm einfügen"),
    ("Insert shape", "Form einfügen"),
    ("Insert slicer", "Datenschnitt einfügen"),
    ("Insert sparkline", "Sparkline einfügen"),
    ("Insert symbol", "Symbol einfügen"),
    ("Insert table", "Tabelle einfügen"),
    ("Insert text box", "Textfeld einfügen"),
    ("Justified", "Blocksatz"),
    ("Last column", "Letzte Spalte"),
    ("Left Panel", "Linkes Bedienfeld"),
    ("Logical", "Logisch"),
    ("Lookup & Reference", "Suchen und Bezüge"),
    ("Macro list", "Liste"),
    ("Macros", "Makros"),
    ("Margins", "Ränder"),
    ("Math & Trig", "Mathematik/Trigonometrie"),
    ("Merge and centre", "Verbinden und zentrieren"),
    ("Merge shapes", "Formen zusammenführen"),
    ("More functions", "Weitere Funktionen"),
    ("Multilevel list", "Liste mit mehreren Ebenen"),
    ("Multiple pages", "Mehrere Seiten"),
    ("Name manager", "Name-Manager"),
    ("New .py", "Neue .py"),
    ("Nonprinting characters", "Formatierungszeichen"),
    ("Number format", "Zahlenformat"),
    ("Number of pages", "Seitenzahl"),
    ("Numbering", "Nummerierung"),
    ("Open", "Offen"),
    ("Open folder", "Ordner öffnen"),
    ("Page Break Preview", "Seitenumbruch-Vorschau"),
    ("Page breaks", "Blattgrenzen"),
    ("Page number", "Seitennummerierung"),
    ("Page orientation", "Orientierung"),
    ("Page size", "Seitenformat"),
    ("Paragraph line spacing", "Zeilenabstand"),
    ("Paragraph style", "Absatzformat"),
    ("Paste", "Einfügen"),
    ("Paste name", "Namen einfügen"),
    ("Pen", "Stift"),
    ("Percent style", "Prozentformat"),
    ("Phone Number", "Telefonnummer"),
    ("Picture", "Bild"),
    ("Pivot Table", "Pivot-Tabelle"),
    ("Print", "Drucken"),
    ("Print Area", "Druckauswahl"),
    ("Print gridlines", "Gitternetzlinien drucken"),
    ("Print headings", "Überschriften drucken"),
    ("Print layout", "Drucklayout"),
    ("Print titles", "Drucke Titel"),
    ("Protect Range", "Bereich schützen"),
    ("Protect sheet", "Blatt schützen"),
    ("Protect workbook", "Arbeitsmappe schützen"),
    ("Protection", "Schutz"),
    ("Python functions", "Python-Funktionen"),
    ("Radio Button", "Radiobutton"),
    ("Recently used", "Zuletzt verwendet"),
    ("Record actions", "Aktionen aufzeichnen"),
    ("Recover", "Wiederherstellen"),
    ("References", "Verweise"),
    ("Remove Duplicates", "Entferne Duplikate"),
    ("Remove arrows", "Pfeile entfernen"),
    ("Remove duplicates", "Duplikate entfernen"),
    ("Replace", "Ersetzen"),
    ("Report Layout", "Berichtslayout"),
    ("Resize table", "Tabellengröße ändern"),
    ("Ribbon macros", "Menüband-Makros"),
    ("Right Panel", "Rechtes Bedienungsfeld "),
    ("Right-to-left text", "Textrichtung (rechts nach links)"),
    ("Rulers", "Lineale"),
    ("Save", "Speichern"),
    ("Scale To Fit", "An Format anpassen"),
    ("Scenario", "Szenario"),
    ("Select all", "Alles auswählen"),
    ("Send Backward", "Eine Ebene nach hinten"),
    ("Shading", "Absatzhintergrundfarbe"),
    ("Sheet View", "Tabellenansicht"),
    ("Show comments", "Kommentare anzeigen"),
    ("Show details", "Details anzeigen"),
    ("Show formulas", "Formeln anzeigen"),
    ("Show line numbers", "Zeilennummern anzeigen"),
    ("Show values as", "Berechnungsart"),
    ("Show zeros", "Nullen anzeigen"),
    ("Signature", "Signatur"),
    ("Smaller UI text", "Oberflächentext kleiner"),
    ("Sort", "Sortieren"),
    ("Sort ascending", "Aufsteigend sortieren"),
    ("Sort descending", "Absteigend sortieren"),
    ("Split", "Fenster teilen"),
    ("Status Bar", "Statusleiste"),
    ("Strikethrough", "Durchgestrichen"),
    ("Style", "Formatvorlage"),
    ("Subscript", "Tiefgestellt"),
    ("Subtotals", "Teilergebnisse"),
    ("Suggest read-only", "Schreibschutz empfehlen"),
    ("Superscript", "Hochgestellt"),
    ("Switch the sheet direction so that the first column is on the right side", "Ändern Sie die Blattausrichtung, sodass die erste Spalte auf der rechten Seite liegt"),
    ("Table Design", "Tabellen-Design"),
    ("Table of contents", "Inhaltsverzeichnis"),
    ("Table of figures", "Abbildungsverzeichnis"),
    ("Text Field", "Textfeld"),
    ("Text direction", "Textrichtung"),
    ("Text from File", "Text aus Datei"),
    ("Text functions", "Text"),
    ("Text orientation", "Textausrichtung"),
    ("Text to columns", "Text in Spalten"),
    ("Text to data", "Text zu Daten"),
    ("Total row", "Gesamtzeile"),
    ("Trace Dependents", "Trace-Abhängige"),
    ("Trace Precedents", "Präzedenzfälle"),
    ("Track changes", "Nachverfolgen von Änderungen"),
    ("Underline", "Unterstrichen"),
    ("Ungroup", "Gruppierung aufheben"),
    ("Update", "Aktualisieren"),
    ("Update all", "Alles aktualisieren"),
    ("Update table of contents", "Inhaltsverzeichnis aktualisieren"),
    ("Update table of figures", "Abbildungsverzeichnis aktualisieren"),
    ("Version history", "Versionsverlauf"),
    ("View", "Anzeigen"),
    ("Watch window", "Überwachungsfenster"),
    ("Wrap text", "Text umbrechen"),
    ("Write macro", "Makro schreiben"),
    ("Zoom in", "Vergrößern"),
    ("Zoom out", "Verkleinern"),
    ("Zoom to 100%", "Auf 100 % zoomen"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
    ("draw-select", "Auswahl"),
    ("pivot-select", "Auswählen"),
];

