//! リボンの it の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py it > face/src/ribbon_it.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Aggiungi commento"),
    ("Add Text", "Aggiungi testo"),
    ("Add digital signature", "Aggiungi firma digitale"),
    ("Add link", "Aggiungi collegamento"),
    ("Add to area", "Aggiungi intervallo"),
    ("Align bottom", "Allinea in basso"),
    ("Align left", "Allinea a sinistra"),
    ("Align middle", "Allinea in mezzo"),
    ("Align right", "Allinea a destra"),
    ("Align top", "Allinea in alto"),
    ("Alignment", "Allineamento"),
    ("Allowed actions", "Operazioni consentite"),
    ("Always Show Toolbar", "Mostra sempre la barra strumenti "),
    ("AutoSum", "Somma automatica"),
    ("Backup interval", "Intervallo copie"),
    ("Banded Rows", "Righe a strisce"),
    ("Banded columns", "Colonne alternate"),
    ("Bigger UI text", "Ingrandisci testo dello schermo"),
    ("Blank Rows", "Righe vuote"),
    ("Bold", "Grassetto"),
    ("Bookmark", "Segnalibri"),
    ("Borders", "Bordi"),
    ("Breaks", "Interruzioni"),
    ("Bring forward", "Porta avanti"),
    ("Bullet", "Elenco puntato"),
    ("CSV format", "Formato CSV"),
    ("Calculation options", "Calcolo"),
    ("Caption", "Didascalia"),
    ("Cell Style", "Stile cella"),
    ("Cell lock", "Blocca cella"),
    ("Centre", "Al centro"),
    ("Change case", "Cambia forma"),
    ("Change colour theme", "Cambia combinazione di colori"),
    ("Change hyphenation", "Cambia suddivisione"),
    ("Change page colour", "Cambia colore della pagina"),
    ("Checkbox", "Casella di controllo"),
    ("Circle invalid data", "Cerchia dati non validi"),
    ("Clear", "Svuota"),
    ("Clear filter", "Cancella filtro"),
    ("Clear style", "Cancella stile"),
    ("Co-editing mode", "Modalità collaborativa"),
    ("Collaboration", "Collaborazione"),
    ("Combo box", "Casella combinata"),
    ("Comma style", "Stile della virgola"),
    ("Comment", "Commenti"),
    ("Complex Field", "Campo complesso"),
    ("Conditional formatting", "Formattazione condizionale"),
    ("Convert to range", "Converti in intervallo"),
    ("Copy", "Copia"),
    ("Cross-reference", "‎Riferimento incrociato‎"),
    ("Currency style", "Stile valuta"),
    ("Cut", "Taglia"),
    ("Dark mode", "Modalità scura"),
    ("Data", "Dati"),
    ("Data Validation", "Validazione dati"),
    ("Data source", "Origine dati"),
    ("Data table", "Tabella dati"),
    ("Date & Time", "Data e ora"),
    ("Decrease decimal", "Diminuisci decimali"),
    ("Decrease indent", "Riduci rientro"),
    ("Decrement font size", "Riduci dimensione caratteri"),
    ("Delete cells", "Elimina celle"),
    ("Delete comment", "Elimina commento"),
    ("Distributed", "Distribuito"),
    ("Draw", "Disegna"),
    ("Dropdown", "Menù a discesa"),
    ("Edit footer", "Modifica piè di pagina"),
    ("Edit header", "Modifica intestazione"),
    ("Edit watermark", "Modifica filigrana"),
    ("Email Address", "Indirizzo email"),
    ("Encrypt", "Crittografa"),
    ("Eraser", "Gomma"),
    ("External links (import as values)", "Collegamenti esterni (importa come valori)"),
    ("Field list", "Elenco campi"),
    ("Fill", "Riempimento"),
    ("Fill by example", "Riempimento rapido"),
    ("Fill colour", "Colore di riempimento"),
    ("Filter button", "Pulsante filtro"),
    ("Filters", "Filtri"),
    ("Financial", "Finanziario"),
    ("First column", "Prima colonna"),
    ("Fit to page", "Adatta alla pagina"),
    ("Fit to paper", "Adatta alla pagina"),
    ("Fit to width", "Adatta alla larghezza"),
    ("Font", "Carattere"),
    ("Font colour", "Colore caratteri"),
    ("Font size", "Dimensione carattere"),
    ("Footnote", "Nota a piè di pagina"),
    ("Forecast Sheet", "Foglio di previsione"),
    ("Format as table template", "Formatta come modello di tabella"),
    ("Format cells", "Formatta celle"),
    ("Format painter", "Copia formato"),
    ("Forms", "Forme‎"),
    ("Formula Bar", "Barra della formula"),
    ("Freeze panes", "Blocca riquadri"),
    ("Goal Seek", "Goal seek"),
    ("Grand Total", "Totale complessivo"),
    ("Gridlines", "Linee griglia"),
    ("Group", "Raggruppa"),
    ("Header & Footer", "Intestazione e piè di pagina"),
    ("Header row", "Riga di intestazione"),
    ("Headings", "Intestazioni"),
    ("Hide detail", "Nascondi dettaglio"),
    ("Highlight colour", "Colore evidenziatore"),
    ("Highlighter", "Evidenziatore"),
    ("Home", "Base"),
    ("Increase decimal", "Aumenta decimali"),
    ("Increase indent", "Aumenta rientro"),
    ("Increment font size", "Aumenta dimensione caratteri "),
    ("Insert", "Inserisci"),
    ("Insert Pivot Table", "Inserisci tabella pivot"),
    ("Insert SmartArt", "Inserisci SmartArt"),
    ("Insert Text Art", "Inserisci Text Art"),
    ("Insert blank page", "Inserisci pagina vuota"),
    ("Insert cells", "Inserisci celle"),
    ("Insert chart", "Inserisci grafico"),
    ("Insert column", "Inserisci colonna"),
    ("Insert content controls", "Inserisci controlli del contenuto"),
    ("Insert drop cap", "Inserisci capolettera"),
    ("Insert equation", "Inserisci equazione"),
    ("Insert function", "Inserisci funzione"),
    ("Insert image", "Inserisci immagine"),
    ("Insert recommended chart", "Inserisci grafico consigliato"),
    ("Insert shape", "Inserisci forma"),
    ("Insert slicer", "Inserisci filtro dati"),
    ("Insert sparkline", "Inserire grafico sparkline"),
    ("Insert symbol", "Inserisci simbolo"),
    ("Insert table", "Inserisci tabella"),
    ("Insert text box", "Inserisci casella di testo"),
    ("Italic", "Corsivo"),
    ("Justified", "Giustificato"),
    ("Last column", "Ultima colonna"),
    ("Layout", "Schema di pagina"),
    ("Left Panel", "Pannello sinistro"),
    ("Logical", "Logico"),
    ("Lookup & Reference", "Ricerca e riferimento"),
    ("Macro list", "Elenco"),
    ("Macros", "Macro"),
    ("Margins", "Margini"),
    ("Math & Trig", "Matematica e trigonometria"),
    ("Merge and centre", "Unisci e centra"),
    ("Merge shapes", "Fondi forme"),
    ("More functions", "Altre funzioni"),
    ("Multilevel list", "Elenco multilivello"),
    ("Multiple pages", "Pagine multiple"),
    ("Name", "Nome"),
    ("Name manager", "Gestore nomi"),
    ("Navigation", "Navigazione"),
    ("New .py", "Nuovo .py"),
    ("Nonprinting characters", "Caratteri non stampabili"),
    ("Normal", "Normale"),
    ("Number format", "Formato del numero"),
    ("Number of pages", "Numero di pagine"),
    ("Numbering", "Numerazione"),
    ("Open", "Apri"),
    ("Open folder", "Apri cartella"),
    ("Page Break Preview", "Anteprima interruzione di pagina"),
    ("Page breaks", "Fine pagina"),
    ("Page number", "Numero di pagina"),
    ("Page orientation", "Orientamento pagina"),
    ("Page size", "Dimensione pagina"),
    ("Paragraph line spacing", "Interlinea tra i paragrafi"),
    ("Paragraph style", "Stile paragrafo"),
    ("Paste", "Incolla"),
    ("Paste name", "Incolla nome"),
    ("Pen", "Penna"),
    ("Percent style", "Stile percentuale"),
    ("Phone Number", "Numero di telefono"),
    ("Picture", "Immagine"),
    ("Pivot Table", "Tabella pivot"),
    ("PivotChart", "Grafico pivot"),
    ("Print", "Stampa"),
    ("Print Area", "Area di stampa"),
    ("Print gridlines", "Stampa griglia"),
    ("Print headings", "Stampa intestazioni"),
    ("Print titles", "Stampa titoli"),
    ("Protect Range", "Proteggi rango"),
    ("Protect sheet", "Proteggi foglio"),
    ("Protect workbook", "Proteggere libro di lavoro"),
    ("Protection", "Protezione"),
    ("Python functions", "Funzioni Python"),
    ("Radio Button", "Pulsante Radio"),
    ("Recently used", "Usate di recente"),
    ("Record actions", "Registra azioni"),
    ("Recover", "Ripristino"),
    ("References", "Riferimenti"),
    ("Remove Duplicates", "Rimuovi duplicati"),
    ("Remove arrows", "Rimuovi frecce"),
    ("Remove duplicates", "Rimuovi duplicati"),
    ("Replace", "Sostituisci"),
    ("Report Layout", "Schema del rapporto"),
    ("Resize table", "Ridimensiona tabella"),
    ("Ribbon macros", "Macro della barra"),
    ("Right Panel", "Pannello destro"),
    ("Right-to-left text", "Orientamento del testo (da destra a sinistra)"),
    ("Rulers", "Righelli"),
    ("Save", "Salva"),
    ("Scale To Fit", "Adatta"),
    ("Select", "Seleziona"),
    ("Select all", "Seleziona tutto"),
    ("Send Backward", "Porta indietro"),
    ("Shading", "Ombreggiato"),
    ("Sheet View", "Visualizzazione foglio"),
    ("Show comments", "Mostra commento"),
    ("Show details", "Mostra dettagli"),
    ("Show formulas", "Mostra formule"),
    ("Show line numbers", "‎Mostra numeri di riga‎"),
    ("Show values as", "Tipo di calcolo"),
    ("Show zeros", "Mostra zeri"),
    ("Signature", "Firma"),
    ("Smaller UI text", "Riduci testo dello schermo"),
    ("Solver", "Risolutore"),
    ("Sort", "Ordina"),
    ("Sort ascending", "Ordine crescente"),
    ("Sort descending", "Ordine decrescente"),
    ("Split", "Dividi finestra"),
    ("Status Bar", "Barra di stato"),
    ("Strikethrough", "Barrato"),
    ("Style", "Stile"),
    ("Subscript", "Pedice"),
    ("Subtotals", "Subtotali"),
    ("Suggest read-only", "Consiglia sola lettura"),
    ("Superscript", "Apice"),
    ("Switch the sheet direction so that the first column is on the right side", "Inverti la direzione del foglio in modo da visualizzare la prima colonna sul lato destro"),
    ("Table Design", "Struttura tabella"),
    ("Table of contents", "Sommario"),
    ("Table of figures", "Indice delle figure"),
    ("Text Field", "‎Campo di testo‎"),
    ("Text direction", "Direzione del testo"),
    ("Text from File", "Testo da file"),
    ("Text functions", "Testo"),
    ("Text orientation", "Orientamento del testo"),
    ("Text to columns", "Testo in colonne"),
    ("Text to data", "Da testo a dati"),
    ("Total row", "Riga totale"),
    ("Trace Dependents", "Traccia le dipendenti"),
    ("Trace Precedents", "Traccia le precedenti"),
    ("Track changes", "Traccia cambiamenti"),
    ("Underline", "Sottolineato"),
    ("Ungroup", "Separa"),
    ("Update", "Aggiorna"),
    ("Update all", "Aggiorna tutto"),
    ("Update table of contents", "Aggiorna sommario"),
    ("Update table of figures", "Aggiorna indice delle figure"),
    ("Version history", "Cronologia versioni"),
    ("View", "Visualizza"),
    ("Watch window", "Finestra controllo celle"),
    ("Wrap text", "Testo a capo"),
    ("Write macro", "Scrivi macro"),
    ("Zoom in", "Zoom avanti"),
    ("Zoom out", "Zoom indietro"),
    ("Zoom to 100%", "Zoom al 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

