//! リボンの ko の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py ko > face/src/ribbon_ko.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "코멘트 추가"),
    ("Add Text", "텍스트 추가"),
    ("Add digital signature", "디지털 서명 추가"),
    ("Add link", "링크 추가"),
    ("Add to area", "범위 더하기"),
    ("Align bottom", "아래쪽 정렬"),
    ("Align left", "왼쪽 정렬"),
    ("Align middle", "중간 정렬"),
    ("Align right", "오른쪽 정렬"),
    ("Align top", "정렬"),
    ("Alignment", "정렬"),
    ("Allowed actions", "허용할 동작"),
    ("Always Show Toolbar", "항상 도구 모음 표시"),
    ("AutoSum", "자동 합계"),
    ("Backup interval", "사본 간격"),
    ("Banded Rows", "줄무늬 행"),
    ("Banded columns", "줄무늬 열"),
    ("Bigger UI text", "화면 글자 크게"),
    ("Blank Rows", "빈 행"),
    ("Bold", "굵게"),
    ("Bookmark", "즐겨찾기"),
    ("Borders", "테두리"),
    ("Breaks", "나누기"),
    ("Bring forward", "앞으로 보내기"),
    ("Bullet", "글머리 기호"),
    ("CSV format", "CSV 형식"),
    ("Calculation options", "계산 방법"),
    ("Caption", "캡션"),
    ("Cell Style", "셀 스타일"),
    ("Cell lock", "셀 잠금"),
    ("Centre", "Center"),
    ("Change case", "대소문자 변경"),
    ("Change colour theme", "색상 구성 변경"),
    ("Change hyphenation", "하이픈 연결 변경"),
    ("Change page colour", "페이지 색 변경"),
    ("Chat", "채팅"),
    ("Checkbox", "확인란"),
    ("Circle invalid data", "잘못된 데이터에 표시"),
    ("Clear", "지우기"),
    ("Clear filter", "필터 해제"),
    ("Clear style", "스타일 지우기"),
    ("Co-editing mode", "공동 편집 모드"),
    ("Collaboration", "협업"),
    ("Combo box", "콤보박스"),
    ("Comma style", "쉼표 스타일"),
    ("Comment", "코멘트"),
    ("Complex Field", "복합 필드"),
    ("Conditional formatting", "조건부 서식"),
    ("Convert to range", "범위로 변환"),
    ("Copy", "복사"),
    ("Cross-reference", "상호 참조"),
    ("Currency style", "통화 스타일"),
    ("Cut", "잘라 내기"),
    ("Dark mode", "다크 모드"),
    ("Data", "데이터"),
    ("Data Validation", "데이터 유효성"),
    ("Data source", "데이터 소스"),
    ("Data table", "데이터 표"),
    ("Date & Time", "날짜/시간"),
    ("Decrease decimal", "자리수 줄임"),
    ("Decrease indent", "들여쓰기 줄이기"),
    ("Decrement font size", "글꼴 크기 감소"),
    ("Delete cells", "셀 삭제"),
    ("Delete comment", "메모 삭제"),
    ("Distributed", "균등 분할"),
    ("Draw", "그리기"),
    ("Dropdown", "드롭다운"),
    ("Edit footer", "바닥글 편집"),
    ("Edit header", "머리글 편집"),
    ("Edit watermark", "워터마크 수정"),
    ("Email Address", "이메일 주소"),
    ("Encrypt", "암호화"),
    ("Eraser", "지우개"),
    ("External links (import as values)", "외부 링크(값으로 가져오기)"),
    ("Field list", "필드 목록"),
    ("File", "파일"),
    ("Fill", "채우기"),
    ("Fill by example", "빠른 채우기"),
    ("Fill colour", "채우기 색"),
    ("Filter button", "필터 버튼"),
    ("Filters", "필터"),
    ("Financial", "재무"),
    ("First column", "첫째 열"),
    ("Fit to page", "페이지에 맞춤"),
    ("Fit to paper", "종이에 맞추기"),
    ("Fit to width", "너비에 맞춤"),
    ("Font", "글꼴"),
    ("Font colour", "글꼴 색"),
    ("Font size", "글꼴 크기"),
    ("Footnote", "각주"),
    ("Forecast Sheet", "예측 시트"),
    ("Format as table template", "표 템플릿으로 서식 지정"),
    ("Format cells", "셀 서식"),
    ("Format painter", "서식 복사"),
    ("Forms", "폼"),
    ("Formula", "수식"),
    ("Formula Bar", "수식 입력줄"),
    ("Freeze panes", "창 고정"),
    ("Furigana", "후리가나"),
    ("Goal Seek", "목표값 찾기"),
    ("Grand Total", "총합계"),
    ("Gridlines", "눈금선"),
    ("Group", "그룹"),
    ("Header & Footer", "머리말/꼬리말"),
    ("Header row", "머리글 행"),
    ("Headings", "제목"),
    ("Hide detail", "하위 수준 숨기기"),
    ("Highlight colour", "색상 강조 표시"),
    ("Highlighter", "하이라이터"),
    ("Home", "홈"),
    ("Increase decimal", "자리수 늘림"),
    ("Increase indent", "들여쓰기 늘리기"),
    ("Increment font size", "글꼴 크기 증가"),
    ("Insert", "삽입"),
    ("Insert Pivot Table", "피벗 테이블 삽입"),
    ("Insert SmartArt", "SmartArt 삽입"),
    ("Insert Text Art", "텍스트 아트 삽입"),
    ("Insert blank page", "빈 페이지 삽입"),
    ("Insert cells", "셀 삽입"),
    ("Insert chart", "차트 삽입"),
    ("Insert column", "열 삽입"),
    ("Insert content controls", "콘텐츠 컨트롤 추가"),
    ("Insert drop cap", "드롭 캡 삽입"),
    ("Insert equation", "수식 삽입"),
    ("Insert function", "함수 삽입"),
    ("Insert image", "그림 삽입"),
    ("Insert recommended chart", "추천 차트 삽입"),
    ("Insert shape", "도형 삽입"),
    ("Insert slicer", "슬라이서추가"),
    ("Insert sparkline", "스파크라인 삽입"),
    ("Insert symbol", "기호 삽입"),
    ("Insert table", "표 삽입"),
    ("Insert text box", "텍스트 상자 삽입"),
    ("Italic", "기울림꼴"),
    ("Justified", "균등분할"),
    ("Last column", "마지막 열"),
    ("Layout", "레이아웃"),
    ("Left Panel", "왼쪽 패널"),
    ("Logical", "논리적"),
    ("Lookup & Reference", "조회 및 참조"),
    ("Macro list", "목록"),
    ("Macros", "매크로"),
    ("Margins", "여백"),
    ("Math & Trig", "수학/삼각"),
    ("Merge and centre", "병합하고 가운데 맞춤"),
    ("Merge shapes", "도형 병합"),
    ("More functions", "더 많은 기능"),
    ("Multilevel list", "다중 레벨 목록"),
    ("Multiple pages", "여러 페이지"),
    ("Name", "이름"),
    ("Name manager", "이름 관리자"),
    ("Navigation", "내비게이션"),
    ("New .py", "새 .py"),
    ("Nonprinting characters", "인쇄되지 않는 문자"),
    ("Normal", "일반"),
    ("Number format", "숫자 형식"),
    ("Number of pages", "페이지 수"),
    ("Numbering", "번호 매기기"),
    ("Open", "열기"),
    ("Open folder", "폴더 열기"),
    ("Page Break Preview", "페이지 나누기 미리보기"),
    ("Page breaks", "종이 끊기는 자리"),
    ("Page number", "페이지 번호"),
    ("Page orientation", "페이지 방향"),
    ("Page size", "페이지 크기"),
    ("Paragraph line spacing", "단락 줄 간격"),
    ("Paragraph style", "단락 스타일"),
    ("Paste", "붙여 넣기"),
    ("Paste name", "이름 붙여넣기"),
    ("Pen", "펜"),
    ("Percent style", "백분율 스타일"),
    ("Phone Number", "전화 번호"),
    ("Picture", "그림"),
    ("Pivot Table", "피벗 테이블"),
    ("PivotChart", "피벗 차트"),
    ("Print", "인쇄"),
    ("Print Area", "인쇄 영역"),
    ("Print gridlines", "눈금선 인쇄"),
    ("Print headings", "머리글 인쇄"),
    ("Print layout", "인쇄 모양"),
    ("Print titles", "제목 인쇄"),
    ("Protect Range", "보호 범위"),
    ("Protect sheet", "시트 보호"),
    ("Protect workbook", "통합 문서 보호"),
    ("Protection", "보호"),
    ("Python functions", "Python 함수"),
    ("Radio Button", "라디오 버튼"),
    ("Recently used", "최근에 사용한 함수"),
    ("Record actions", "동작 기록"),
    ("Recover", "복구"),
    ("References", "참조"),
    ("Remove Duplicates", "중복된 항목 제거"),
    ("Remove arrows", "연결선 제거"),
    ("Remove duplicates", "중복된 항목 제거"),
    ("Replace", "바꾸기"),
    ("Report Layout", "레이아웃 리포트"),
    ("Resize table", "크기 조정 테이블"),
    ("Ribbon macros", "리본 매크로"),
    ("Right Panel", "오른쪽 패널"),
    ("Right-to-left text", "텍스트 방향(오른쪽부터 쓰기)"),
    ("Ruby", "루비"),
    ("Rulers", "자"),
    ("Save", "저장"),
    ("Scale To Fit", "크기에 맞게 확대/축소"),
    ("Scenario", "시나리오"),
    ("Select", "선택"),
    ("Select all", "모두 선택"),
    ("Send Backward", "뒤로 보내기"),
    ("Shading", "단락 배경색"),
    ("Sheet View", "시트보기"),
    ("Show comments", "댓글 표시"),
    ("Show details", "세부 정보 표시"),
    ("Show formulas", "수식 표시"),
    ("Show line numbers", "행 번호 표시"),
    ("Show values as", "계산 종류"),
    ("Show zeros", "0 표시"),
    ("Signature", "서명"),
    ("Smaller UI text", "화면 글자 작게"),
    ("Solver", "해 찾기"),
    ("Sort", "정렬"),
    ("Sort ascending", "텍스트 오름차순 정렬"),
    ("Sort descending", "텍스트 내림차순 정렬"),
    ("Split", "창 분할"),
    ("Status Bar", "상태 바"),
    ("Strikethrough", "취소선"),
    ("Style", "스타일"),
    ("Subscript", "아래 첨자"),
    ("Subtotals", "부분합"),
    ("Suggest read-only", "읽기 전용 권하기"),
    ("Superscript", "위첨자"),
    ("Switch the sheet direction so that the first column is on the right side", "첫 번째 열이 오른쪽에 오도록 시트 방향을 전환합니다"),
    ("Table Design", "표 디자인"),
    ("Table of contents", "목차"),
    ("Table of figures", "그림 목차"),
    ("Text Field", "텍스트 필드"),
    ("Text direction", "텍스트 방향"),
    ("Text from File", "파일에서 텍스트 삽입"),
    ("Text functions", "텍스트"),
    ("Text orientation", "글자 방향"),
    ("Text to columns", "텍스트 나누기"),
    ("Text to data", "텍스트에서 데이터로"),
    ("Total row", "총 행"),
    ("Trace Dependents", "종속 항목 추적"),
    ("Trace Precedents", "선행 항목 추적"),
    ("Track changes", "변경 내용 추적"),
    ("Underline", "밑줄"),
    ("Ungroup", "그룹 해제"),
    ("Update", "업데이트"),
    ("Update all", "모두 업데이트"),
    ("Update table of contents", "목차 업데이트"),
    ("Update table of figures", "그림 목차 업데이트"),
    ("Version history", "버전 기록"),
    ("View", "보기"),
    ("Watch window", "조사식 창"),
    ("Wrap text", "텍스트 줄 바꿈"),
    ("Write macro", "매크로 작성"),
    ("Zoom in", "확대"),
    ("Zoom out", "축소"),
    ("Zoom to 100%", "100%로 확대"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

