//! リボンの pt-br の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py pt-br > face/src/ribbon_pt-br.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Adicionar comentário"),
    ("Add Text", "Adicionar Texto"),
    ("Add digital signature", "Adicionar assinatura digital"),
    ("Add link", "Adicionar Link"),
    ("Add to area", "Acrescentar intervalo"),
    ("Align bottom", "Alinhar à parte inferior"),
    ("Align left", "Alinhar à esquerda"),
    ("Align middle", "Alinhar ao meio"),
    ("Align right", "Alinhar à direita"),
    ("Align top", "Alinhar à parte superior"),
    ("Alignment", "Alinhamento"),
    ("Allowed actions", "Operações permitidas"),
    ("Always Show Toolbar", "Sempre mostrar a barra de ferramentas"),
    ("AutoSum", "AutoSoma"),
    ("Backup interval", "Intervalo das cópias"),
    ("Banded Rows", "Linhas em faixas"),
    ("Banded columns", "Colunas em tiras"),
    ("Bigger UI text", "Aumentar texto da tela"),
    ("Blank Rows", "Linhas em branco"),
    ("Bold", "Negrito"),
    ("Bookmark", "Favoritos"),
    ("Borders", "Bordas"),
    ("Breaks", "Quebras"),
    ("Bring forward", "Trazer para frente"),
    ("Bullet", "Marcador"),
    ("CSV format", "Formato CSV"),
    ("Calculation options", "Cálculo"),
    ("Caption", "Legenda"),
    ("Cell Style", "Estilo da célula"),
    ("Cell lock", "Bloquear célula"),
    ("Centre", "Centro"),
    ("Change case", "Mudar maiúsculas e minúsculas"),
    ("Change colour theme", "Alterar esquema de cor"),
    ("Change hyphenation", "Alterar hifenização"),
    ("Change page colour", "Alterar a cor da página"),
    ("Checkbox", "Caixa de seleção"),
    ("Circle invalid data", "Circular dados inválidos"),
    ("Clear", "Limpar"),
    ("Clear filter", "Limpar filtro"),
    ("Clear style", "Limpar estilo"),
    ("Co-editing mode", "Modo de coedição"),
    ("Collaboration", "Colaboração"),
    ("Combo box", "Caixa de combinação"),
    ("Comma style", "Estilo vírgula"),
    ("Comment", "Comentários"),
    ("Complex Field", "Campo complexo"),
    ("Conditional formatting", "Formatação condicional"),
    ("Convert to range", "Converter para intervalo"),
    ("Copy", "Copiar"),
    ("Cross-reference", "Referência cruzada"),
    ("Currency style", "Estilo da moeda"),
    ("Cut", "Cortar"),
    ("Dark mode", "Modo escuro"),
    ("Data", "Dados"),
    ("Data Validation", "Validação de dados"),
    ("Data source", "Fonte de dados"),
    ("Data table", "Tabela de dados"),
    ("Date & Time", "Data e hora"),
    ("Decrease decimal", "Diminuir casas decimais"),
    ("Decrease indent", "Diminuir o Recuo"),
    ("Decrement font size", "Diminuir tamanho da fonte"),
    ("Delete cells", "Excluir células"),
    ("Delete comment", "Excluir comentário"),
    ("Distributed", "Distribuído"),
    ("Draw", "Desenhar"),
    ("Dropdown", "Suspenso"),
    ("Edit footer", "Editar rodapé"),
    ("Edit header", "Editar cabeçalho"),
    ("Edit watermark", "Editar marca d'água"),
    ("Email Address", "Endereço de e-mail"),
    ("Encrypt", "Criptografar"),
    ("Eraser", "Apagador"),
    ("External links (import as values)", "Links externos (importar como valores)"),
    ("Field list", "Lista de campos"),
    ("File", "Arquivo"),
    ("Fill", "Preencher"),
    ("Fill by example", "Preencher pelo exemplo"),
    ("Fill colour", "Cor de preenchimento"),
    ("Filter button", "Botão de filtro"),
    ("Filters", "Filtros"),
    ("Financial", "Financeiro"),
    ("First column", "Primeira coluna"),
    ("Fit to page", "Ajustar a página"),
    ("Fit to paper", "Ajustar ao papel"),
    ("Fit to width", "Ajustar largura"),
    ("Font", "Fonte"),
    ("Font colour", "Cor da fonte"),
    ("Font size", "Tamanho da fonte"),
    ("Footnote", "Nota de rodapé"),
    ("Forecast Sheet", "Planilha de previsão"),
    ("Format as table template", "Formato como Modelo de tabela"),
    ("Format cells", "Formatar celulas"),
    ("Format painter", "Copiar formato"),
    ("Forms", "Formulários"),
    ("Formula", "Fórmula"),
    ("Formula Bar", "Barra de fórmula"),
    ("Freeze panes", "Congelar painéis"),
    ("Goal Seek", "Busca de meta"),
    ("Grand Total", "Total geral"),
    ("Group", "Grupo"),
    ("Header & Footer", "Cabeçalho/rodapé"),
    ("Header row", "Linha de Cabeçalho"),
    ("Headings", "Títulos"),
    ("Hide detail", "Ocultar detalhes"),
    ("Highlight colour", "Cor de realce"),
    ("Highlighter", "Marcador"),
    ("Home", "Página Inicial"),
    ("Increase decimal", "Aumentar números decimais"),
    ("Increase indent", "Aumentar recuo"),
    ("Increment font size", "Aumentar tamanho da fonte"),
    ("Insert", "Inserir"),
    ("Insert Pivot Table", "Inserir tabela dinâmica"),
    ("Insert SmartArt", "Inserir SmartArt"),
    ("Insert Text Art", "Inserir arte de texto"),
    ("Insert blank page", "Inserir página em branco"),
    ("Insert cells", "Inserir células"),
    ("Insert chart", "Inserir gráfico"),
    ("Insert column", "Inserir coluna"),
    ("Insert content controls", "Adicionar controles de conteúdo"),
    ("Insert drop cap", "Inserir letra capitular"),
    ("Insert equation", "Inserir equação"),
    ("Insert function", "Inserir função"),
    ("Insert image", "Inserir imagem"),
    ("Insert recommended chart", "Inserir gráfico recomendado"),
    ("Insert shape", "Inserir Forma"),
    ("Insert slicer", "Inserir Segmentação de Dados"),
    ("Insert sparkline", "Inserir sparkline"),
    ("Insert symbol", "Inserir símbolo"),
    ("Insert table", "Inserir tabela"),
    ("Insert text box", "Inserir caixa de texto"),
    ("Italic", "Itálico"),
    ("Justified", "Justificado"),
    ("Last column", "Última coluna"),
    ("Left Panel", "Painel esquerdo"),
    ("Logical", "Lógico"),
    ("Lookup & Reference", "Pesquisa e Referência"),
    ("Macro list", "Lista"),
    ("Margins", "Margens"),
    ("Math & Trig", "Matemática e trigonometria"),
    ("Merge and centre", "Mesclar e centralizar"),
    ("Merge shapes", "Mesclar formas"),
    ("More functions", "Mais funções"),
    ("Multilevel list", "Contorno"),
    ("Multiple pages", "Múltiplas páginas"),
    ("Name", "Nome"),
    ("Name manager", "Gerenciador de nomes"),
    ("Navigation", "Navegação"),
    ("New .py", "Novo .py"),
    ("Nonprinting characters", "Caracteres não imprimíveis"),
    ("Number format", "Formato Numérico"),
    ("Number of pages", "Número de páginas"),
    ("Numbering", "Numeração"),
    ("Open", "Abrir"),
    ("Open folder", "Abrir a pasta"),
    ("Page Break Preview", "Visualização de quebra de página"),
    ("Page breaks", "Quebras de página"),
    ("Page number", "Número da página"),
    ("Page orientation", "Orientação da página"),
    ("Page size", "Tamanho da página"),
    ("Paragraph line spacing", "Espaçamento entre linhas do parágrafo"),
    ("Paragraph style", "Estilo do parágrafo"),
    ("Paste", "Colar"),
    ("Paste name", "Colar nome"),
    ("Pen", "Caneta"),
    ("Percent style", "Estilo de Porcentagem"),
    ("Phone Number", "Número de telefone"),
    ("Picture", "Imagem"),
    ("Pivot Table", "Tabela Dinâmica"),
    ("PivotChart", "Gráfico dinâmico"),
    ("Print", "Imprimir"),
    ("Print Area", "Área de impressão"),
    ("Print gridlines", "Imprimir linhas de grade"),
    ("Print headings", "Imprimir cabeçalhos de linhas e colunas"),
    ("Print titles", "Imprimir títulos"),
    ("Protect Range", "Proteger Intervalo"),
    ("Protect sheet", "Proteger folha"),
    ("Protect workbook", "Proteger a pasta de trabalho"),
    ("Protection", "Proteção"),
    ("Python functions", "Funções Python"),
    ("Radio Button", "Botao de radio"),
    ("Recently used", "Usadas recentemente"),
    ("Record actions", "Gravar ações"),
    ("Recover", "Recuperar"),
    ("References", "Referências"),
    ("Remove Duplicates", "Remover Duplicatas"),
    ("Remove arrows", "Remover setas"),
    ("Remove duplicates", "Remover duplicatas"),
    ("Replace", "Substituir"),
    ("Report Layout", "Layout do Relatório"),
    ("Resize table", "Redimensionar tabela"),
    ("Ribbon macros", "Macros da faixa"),
    ("Right Panel", "Painel direito"),
    ("Right-to-left text", "Direção do texto (direita para a esquerda)"),
    ("Rulers", "Regras"),
    ("Save", "Salvar"),
    ("Scale To Fit", "Dimensionar"),
    ("Scenario", "Cenário"),
    ("Select", "Selecionar"),
    ("Select all", "Selecionar todos"),
    ("Send Backward", "Enviar para trás"),
    ("Shading", "Cor do plano de fundo do parágrafo"),
    ("Sheet View", "Visualização de folha"),
    ("Show comments", "Mostrar comentários"),
    ("Show details", "Exibir detalhes"),
    ("Show formulas", "Mostrar fórmulas"),
    ("Show line numbers", "Mostrar números de linha"),
    ("Show values as", "Mostrar os valores como"),
    ("Show zeros", "Mostrar zeros"),
    ("Signature", "Assinatura"),
    ("Smaller UI text", "Diminuir texto da tela"),
    ("Sort", "Classificar"),
    ("Sort ascending", "Classificar do menor para o maior"),
    ("Sort descending", "Classificar do maior para o menor"),
    ("Split", "Dividir janela"),
    ("Status Bar", "Barra de status"),
    ("Strikethrough", "Tachado"),
    ("Style", "Estilo"),
    ("Subscript", "Subscrito"),
    ("Subtotals", "Subtotais"),
    ("Suggest read-only", "Sugerir somente leitura"),
    ("Superscript", "Sobrescrito"),
    ("Switch the sheet direction so that the first column is on the right side", "Altere a direção da folha de modo que a primeira coluna fique no lado direito"),
    ("Table Design", "Design da Tabela"),
    ("Table of contents", "Tabela de Conteúdo"),
    ("Table of figures", "Índice de ilustrações"),
    ("Text Field", "Campo de texto"),
    ("Text direction", "Direção do texto"),
    ("Text from File", "Texto do arquivo"),
    ("Text functions", "Texto"),
    ("Text orientation", "Orientação do texto"),
    ("Text to columns", "Texto para colunas"),
    ("Text to data", "Texto para dados"),
    ("Total row", "Linha de Totais"),
    ("Trace Dependents", "Rastrear Dependentes"),
    ("Trace Precedents", "Rastrear precedentes"),
    ("Track changes", "Rastrear alterações"),
    ("Underline", "Sublinhado"),
    ("Ungroup", "Desagrupar"),
    ("Update", "Atualizar"),
    ("Update all", "Atualize tudo"),
    ("Update table of contents", "Atualizar sumário"),
    ("Update table of figures", "Atualizar índice de ilustrações"),
    ("Version history", "Histórico de versões"),
    ("View", "Exibir"),
    ("Watch window", "Janela de Inspeção"),
    ("Wrap text", "Moldar texto"),
    ("Write macro", "Escrever macro"),
    ("Zoom in", "Ampliar"),
    ("Zoom out", "Reduzir"),
    ("Zoom to 100%", "Zoom de 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

