//! リボンの ru の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py ru > face/src/ribbon_ru.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Добавить комментарий"),
    ("Add Text", "Добавить текст"),
    ("Add digital signature", "Добавить цифровую подпись"),
    ("Add link", "Добавить ссылку"),
    ("Add to area", "Добавить в область печати"),
    ("Align bottom", "Выровнять по нижнему краю"),
    ("Align left", "Выровнять по левому краю"),
    ("Align middle", "Выровнять по середине"),
    ("Align right", "Выровнять по правому краю"),
    ("Align top", "Выровнять по верхнему краю"),
    ("Alignment", "Выравнивание"),
    ("Allowed actions", "Разрешённые действия"),
    ("Always Show Toolbar", "Всегда показывать панель инструментов"),
    ("AutoSum", "Автосумма"),
    ("Backup interval", "Интервал копий"),
    ("Banded Rows", "Чередовать строки"),
    ("Banded columns", "Чередующиеся столбцы"),
    ("Bigger UI text", "Крупнее текст интерфейса"),
    ("Blank Rows", "Пустые строки"),
    ("Bold", "Полужирный"),
    ("Bookmark", "Закладка"),
    ("Borders", "Границы"),
    ("Breaks", "Разрывы"),
    ("Bring forward", "Перенести вперед"),
    ("Bullet", "Маркер"),
    ("CSV format", "Формат CSV"),
    ("Calculation options", "Вычисления"),
    ("Caption", "Название"),
    ("Cell Style", "Стиль ячейки"),
    ("Cell lock", "Блокировка ячейки"),
    ("Centre", "По центру"),
    ("Change case", "Изменить регистр"),
    ("Change colour theme", "Изменение цветовой темы"),
    ("Change hyphenation", "Изменить расстановку переносов"),
    ("Change page colour", "Изменить цвет страницы"),
    ("Chat", "Чат"),
    ("Checkbox", "Флажок"),
    ("Circle invalid data", "Обвести неверные данные"),
    ("Clear", "Очистить"),
    ("Clear filter", "Снять фильтр"),
    ("Clear style", "Очистить стиль"),
    ("Co-editing mode", "Режим совместной работы"),
    ("Collaboration", "Совместная работа"),
    ("Combo box", "Поле со списком"),
    ("Comma style", "Формат с разделителями"),
    ("Comment", "Комментарии"),
    ("Complex Field", "Составное поле"),
    ("Conditional formatting", "Условное форматирование"),
    ("Convert to range", "Преобразовать в диапазон"),
    ("Copy", "Копировать"),
    ("Cross-reference", "Перекрестная ссылка"),
    ("Currency style", "Денежный формат"),
    ("Cut", "Вырезать"),
    ("Dark mode", "Темный режим"),
    ("Data", "Данные"),
    ("Data Validation", "Проверка данных"),
    ("Data source", "Источник данных"),
    ("Data table", "Таблица данных"),
    ("Date & Time", "Дата и время"),
    ("Decrease decimal", "Уменьшить разрядность"),
    ("Decrease indent", "Уменьшить отступ"),
    ("Decrement font size", "Уменьшить размер шрифта"),
    ("Delete cells", "Удалить ячейки"),
    ("Delete comment", "Удалить примечание"),
    ("Distributed", "Распределённый"),
    ("Draw", "Рисование"),
    ("Dropdown", "Выпадающий список"),
    ("Edit footer", "Изменить нижний колонтитул"),
    ("Edit header", "Изменить верхний колонтитул"),
    ("Edit watermark", "Изменить подложку"),
    ("Email Address", "Адрес email"),
    ("Encrypt", "Зашифровать"),
    ("Eraser", "Ластик"),
    ("External links (import as values)", "Внешние ссылки (импорт значениями)"),
    ("Field list", "Список полей"),
    ("File", "Файл"),
    ("Fill", "Заполнить"),
    ("Fill by example", "Мгновенное заполнение"),
    ("Fill colour", "Цвет заливки"),
    ("Filter button", "Кнопка фильтра"),
    ("Filters", "Фильтры"),
    ("Financial", "Финансовые"),
    ("First column", "Первый столбец"),
    ("Fit to page", "По размеру страницы"),
    ("Fit to paper", "Уместить на листе"),
    ("Fit to width", "По ширине"),
    ("Font", "Шрифт"),
    ("Font colour", "Цвет шрифта"),
    ("Font size", "Размер шрифта"),
    ("Footnote", "Сноска"),
    ("Forecast Sheet", "Лист прогноза"),
    ("Format as table template", "Форматировать как шаблон таблицы"),
    ("Format cells", "Форматировать ячейки"),
    ("Format painter", "Формат по образцу"),
    ("Forms", "Формы"),
    ("Formula", "Формула"),
    ("Formula Bar", "Строка формул"),
    ("Freeze panes", "Закрепить области"),
    ("Furigana", "Фуригана"),
    ("Goal Seek", "Подбор параметра"),
    ("Grand Total", "Общий итог"),
    ("Gridlines", "Линии сетки"),
    ("Group", "Группировка"),
    ("Header & Footer", "Колонтитулы"),
    ("Header row", "Строка заголовка"),
    ("Headings", "Заголовки"),
    ("Hide detail", "Скрыть детали"),
    ("Highlight colour", "Цвет выделения"),
    ("Highlighter", "Маркер"),
    ("Home", "Главная"),
    ("Increase decimal", "Увеличить разрядность"),
    ("Increase indent", "Увеличить отступ"),
    ("Increment font size", "Увеличить размер шрифта"),
    ("Insert", "Вставить"),
    ("Insert Pivot Table", "Вставить сводную таблицу"),
    ("Insert SmartArt", "Вставить SmartArt"),
    ("Insert Text Art", "Вставить объект Text Art"),
    ("Insert blank page", "Вставить пустую страницу"),
    ("Insert cells", "Вставить ячейки"),
    ("Insert chart", "Вставить диаграмму"),
    ("Insert column", "Вставить колонки"),
    ("Insert content controls", "Вставить элемент управления содержимым"),
    ("Insert drop cap", "Вставить буквицу"),
    ("Insert equation", "Вставить уравнение"),
    ("Insert function", "Вставка функции"),
    ("Insert image", "Вставить изображение"),
    ("Insert recommended chart", "Вставить рекомендованную диаграмму"),
    ("Insert shape", "Вставить фигуру"),
    ("Insert slicer", "Вставить срез"),
    ("Insert sparkline", "Вставить спарклайн"),
    ("Insert symbol", "Вставить символ"),
    ("Insert table", "Вставить таблицу"),
    ("Insert text box", "Вставить надпись"),
    ("Justified", "По ширине"),
    ("Last column", "Последний столбец"),
    ("Layout", "Макет"),
    ("Left Panel", "Левая панель"),
    ("Logical", "Логические"),
    ("Lookup & Reference", "Поиск и ссылки"),
    ("Macro list", "Список"),
    ("Macros", "Макросы"),
    ("Margins", "Поля"),
    ("Math & Trig", "Математические"),
    ("Merge and centre", "Объединить и поместить в центре"),
    ("Merge shapes", "Объединить фигуры"),
    ("More functions", "Другие функции"),
    ("Multilevel list", "Многоуровневый список"),
    ("Multiple pages", "Несколько страниц"),
    ("Name", "Имя"),
    ("Name manager", "Диспетчер имен"),
    ("Navigation", "Навигация"),
    ("New .py", "Новый .py"),
    ("Nonprinting characters", "Непечатаемые символы"),
    ("Normal", "Обычные"),
    ("Number format", "Числовой формат"),
    ("Number of pages", "Количество страниц"),
    ("Numbering", "Нумерация"),
    ("Open", "Открыть"),
    ("Open folder", "Открыть папку"),
    ("Page Break Preview", "Страничный режим"),
    ("Page breaks", "Разрывы страниц"),
    ("Page number", "Нумерация страниц"),
    ("Page orientation", "Ориентация страницы"),
    ("Page size", "Размер страницы"),
    ("Paragraph line spacing", "Междустрочный интервал в абзацах"),
    ("Paragraph style", "Стиль абзаца"),
    ("Paste", "Вставить"),
    ("Paste name", "Вставить имя"),
    ("Pen", "Ручка"),
    ("Percent style", "Процентный формат"),
    ("Phone Number", "Номер телефона"),
    ("Picture", "Изображение"),
    ("Pivot Table", "Сводная таблица"),
    ("PivotChart", "Сводная диаграмма"),
    ("Print", "Печать"),
    ("Print Area", "Область печати"),
    ("Print gridlines", "Печатать сетку"),
    ("Print headings", "Печатать заголовки строк и столбцов"),
    ("Print layout", "Разметка страницы"),
    ("Print titles", "Печатать заголовки"),
    ("Protect Range", "Защитить диапазон"),
    ("Protect sheet", "Защитить лист"),
    ("Protect workbook", "Защитить книгу"),
    ("Protection", "Защита"),
    ("Python functions", "Функции Python"),
    ("Radio Button", "Переключатель"),
    ("Recently used", "Недавно использованные"),
    ("Record actions", "Записывать действия"),
    ("Recover", "Восстановление"),
    ("References", "Ссылки"),
    ("Remove Duplicates", "Удалить дубликаты"),
    ("Remove arrows", "Убрать стрелки"),
    ("Remove duplicates", "Удалить дубликаты"),
    ("Replace", "Заменить"),
    ("Report Layout", "Макет отчета"),
    ("Resize table", "Размер таблицы"),
    ("Ribbon macros", "Макросы ленты"),
    ("Right Panel", "Правая панель"),
    ("Right-to-left text", "Направление текста (справа налево)"),
    ("Ruby", "Руби"),
    ("Rulers", "Линейки"),
    ("Save", "Сохранить"),
    ("Scale To Fit", "Вписать"),
    ("Scenario", "Сценарий"),
    ("Select all", "Выделить всё"),
    ("Send Backward", "Перенести назад"),
    ("Shading", "Заливка"),
    ("Sheet View", "Представление листа"),
    ("Show comments", "Показать комментарии"),
    ("Show details", "Показать детали"),
    ("Show formulas", "Показать формулы"),
    ("Show line numbers", "Показывать номера строк"),
    ("Show values as", "Как считать"),
    ("Show zeros", "Показывать нули"),
    ("Signature", "Подпись"),
    ("Smaller UI text", "Мельче текст интерфейса"),
    ("Solver", "Поиск решения"),
    ("Sort", "Сортировка"),
    ("Sort ascending", "Сортировка по возрастанию"),
    ("Sort descending", "Сортировка по убыванию"),
    ("Split", "Разделить окно"),
    ("Status Bar", "Строка состояния"),
    ("Strikethrough", "Зачёркнутый"),
    ("Style", "Стиль"),
    ("Subscript", "Подстрочные"),
    ("Subtotals", "Промежуточные итоги"),
    ("Suggest read-only", "Рекомендовать только чтение"),
    ("Superscript", "Надстрочный"),
    ("Switch the sheet direction so that the first column is on the right side", "Переключить направление листа, чтобы первый столбец был справа"),
    ("Table Design", "Дизайн таблицы"),
    ("Table of contents", "Оглавление"),
    ("Table of figures", "Список иллюстраций"),
    ("Text Field", "Текстовое поле"),
    ("Text direction", "Направление текста"),
    ("Text from File", "Текст из файла"),
    ("Text functions", "Текстовые"),
    ("Text orientation", "Направление текста"),
    ("Text to columns", "Текст по столбцам"),
    ("Text to data", "Данные из текста"),
    ("Total row", "Строка итогов"),
    ("Trace Dependents", "Зависимые ячейки"),
    ("Trace Precedents", "Влияющие ячейки"),
    ("Track changes", "Отслеживать изменения"),
    ("Underline", "Подчёркнутый"),
    ("Ungroup", "Разгруппировать"),
    ("Update", "Обновить"),
    ("Update all", "Обновить все"),
    ("Update table of contents", "Обновить оглавление"),
    ("Update table of figures", "Обновить список иллюстраций"),
    ("Version history", "Журнал версий"),
    ("View", "Показать"),
    ("Watch window", "Окно контрольного значения"),
    ("Wrap text", "Перенос текста"),
    ("Write macro", "Написать макрос"),
    ("Zoom in", "Увеличить"),
    ("Zoom out", "Уменьшить"),
    ("Zoom to 100%", "Масштаб 100%"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
    ("draw-select", "Выделить"),
    ("pivot-select", "Выбрать"),
];

