//! リボンの it 版 — **語だけが ja(ribbon.rs)と違う**。
//! id・並び・ready・icon は ja と同一(ribbon.rs の試験が保証する)。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py it > face/src/ribbon_it.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

use super::ribbon::{c, t, x, xt, xm, Tab};

pub const WRITER: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Apri", "open"),
        c("save", "Salva", "save"),
        c("pdf", "Stampa", "print"),
    ]},
    Tab { name: "Base", cmds: &[
        c("copy", "Copia", "copy"),
        c("cut", "Taglia", "cut"),
        c("paste", "Incolla", "paste"),
        c("fontname", "Carattere", "fontname"),
        c("fontsize", "Dimensione carattere", "fontsize"),
        c("incfont", "Aumenta dimensione caratteri ", "incfont"),
        c("decfont", "Riduci dimensione caratteri", "decfont"),
        c("changecase", "Cambia forma", "changecase"),
        c("ruby", "Chiedi", "ruby"),
        c("ai-furigana", "Furigana", "ai-furigana"),
        c("bold", "Grassetto", "bold"),
        c("italic", "Corsivo", "italic"),
        c("underline", "Sottolineato", "underline"),
        c("strikeout", "Barrato", "strikeout"),
        c("superscript", "Apice", "superscript"),
        c("subscript", "Pedice", "subscript"),
        c("highlight", "Colore evidenziatore", "highlight"),
        c("fontcolor", "Colore caratteri", "fontcolor"),
        c("clearstyle", "Cancella stile", "clearstyle"),
        c("markers", "Elenco puntato", "markers"),
        c("numbering", "Numerazione", "numbering"),
        c("multilevels", "Elenco multilivello", "multilevels"),
        c("decoffset", "Riduci rientro", "decoffset"),
        c("incoffset", "Aumenta rientro", "incoffset"),
        c("linespace", "Interlinea tra i paragrafi", "linespace"),
        c("direction", "Ruby", "direction"),
        c("align-left", "Allinea a sinistra", "align-left"),
        c("align-center", "Al centro", "align-center"),
        c("align-right", "Allinea a destra", "align-right"),
        c("align-just", "Giustificato", "align-just"),
        c("align-dist", "Direzione del testo", "align-dist"),
        c("hidenchars", "Caratteri non stampabili", "hidenchars"),
        c("paracolor", "Ombreggiato", "paracolor"),
        c("borders", "Bordi", "borders"),
        c("parastyle", "Stile paragrafo", "styles"),
        c("replace", "Sostituisci", "replace"),
        c("selectall", "Seleziona tutto", "select-all"),
    ]},
    Tab { name: "Inserisci", cmds: &[
        c("blankpage", "Inserisci pagina vuota", "blankpage"),
        c("pagebreak", "Interruzioni", "pagebreak"),
        c("instable", "Inserisci tabella", "instable"),
        c("insimage", "Inserisci immagine", "insertimage"),
        c("insshape", "Inserisci forma", "insshape"),
        c("inssmartart", "Inserisci SmartArt", "inssmartart"),
        c("inschart", "Inserisci grafico", "inschart"),
        c("instext", "Inserisci casella di testo", "instext"),
        c("instextart", "Inserisci Text Art", "instextart"),
        c("dropcap", "Inserisci capolettera", "dropcap"),
        c("text-from-file", "Testo da file", "text-from-file"),
        c("edit-header", "Modifica intestazione", "edit-header"),
        c("edit-footer", "Modifica piè di pagina", "edit-footer"),
        c("pagenum", "Numero di pagina", "pagenum"),
        c("datetime", "Data e ora", "datetime"),
        c("numpages", "Numero di pagine", "numpages"),
        c("insequation", "Inserisci equazione", "insequation"),
        c("inssymbol", "Inserisci simbolo", "inssymbol"),
        c("controls", "Inserisci controlli del contenuto", "controls"),
    ]},
    Tab { name: "Disegna", cmds: &[
        c("pen", "Penna", "pen"),
        c("highlighter", "Evidenziatore", "highlighter"),
        c("eraser", "Gomma", "eraser"),
    ]},
    Tab { name: "Schema di pagina", cmds: &[
        c("pagemargins", "Margini", "pagemargins"),
        c("pageorient", "Orientamento pagina", "pageorient"),
        c("pagesize", "Dimensione pagina", "pagesize"),
        c("columns", "Inserisci colonna", "columns"),
        c("line-numbers", "‎Mostra numeri di riga‎", "line-numbers"),
        c("hyphenation", "Cambia suddivisione", "hyphenation"),
        x("Porta avanti", "img-movefrwd"),
        x("Porta indietro", "img-movebkwd"),
        x("Allineamento", "img-align"),
        x("Raggruppa", "img-group"),
        x("Fondi forme", "shapes-merge"),
        c("watermark", "Modifica filigrana", "watermark"),
        c("pagecolor", "Cambia colore della pagina", "pagecolor"),
        c("colorschemas", "Cambia combinazione di colori", "colorschemas"),
    ]},
    Tab { name: "Riferimenti", cmds: &[
        c("toc", "Sommario", "contents"),
        c("add-text", "Aggiungi testo", "add-text"),
        c("toc-update", "Orientamento del testo (da destra a sinistra)", "contents-update"),
        c("bookmarks", "Segnalibri", "bookmarks"),
        c("caption", "Cancella filtro", "caption"),
        c("crossref", "‎Riferimento incrociato‎", "crossref"),
        c("footnote", "Nota a piè di pagina", "footnote"),
        c("tof", "Scrivi macro", "tof"),
        c("tof-update", "Testo in colonne", "tof-update"),
    ]},
    Tab { name: "Forme‎", cmds: &[
        c("form-text", "‎Campo di testo‎", "form-text"),
        c("form-combo", "Casella combinata", "form-combo"),
        c("form-dropdown", "Menù a discesa", "form-dropdown"),
        c("form-checkbox", "Testo da destra a sinistra", "form-checkbox"),
        c("form-radio", "Pulsante Radio", "form-radio"),
        c("form-image", "Immagine", "form-image"),
        c("form-email", "Indirizzo email", "form-email"),
        c("form-phone", "Numero di telefono", "form-phone"),
        c("form-complex", "Campo complesso", "form-complex"),
        c("form-signature", "Firma", "form-signature"),
        c("form-name", "Nome", "form-name"),
    ]},
    Tab { name: "Collaborazione", cmds: &[
        c("coauth-mode", "Casella di controllo", "coauth-mode"),
        c("co-addcomment", "Aggiungi commento", "co-addcomment"),
        c("co-delcomment", "Finestra controllo celle", "co-delcomment"),
        c("co-showcomment", "Mostra commento", "co-showcomment"),
        c("co-chat", "Grafico consigliato", "co-chat"),
        c("track-changes", "Traccia cambiamenti", "track-changes"),
        c("co-history", "Collegamenti esterni", "co-history"),
    ]},
    Tab { name: "Protezione", cmds: &[
        c("prot-sign", "Cronologia versioni", "prot-sign"),
        c("prot-doc", "Protezione", "prot-doc"),
    ]},
    Tab { name: "Visualizza", cmds: &[
        t("nav", "Navigazione", "nav"),
        c("fit-page", "Adatta alla pagina", "fit-page"),
        c("fit-width", "Adatta alla larghezza", "fit-width"),
        c("zoom100", "Aggiungi firma digitale", "zoom100"),
        c("zoom-in", "Zoom avanti", "zoom-in"),
        c("zoom-out", "Zoom indietro", "zoom-out"),
        c("printview", "Layout di stampa", "printview"),
        c("multipage", "Pagine multiple", "multipage"),
        t("darkmode", "Modalità scura", "darkmode"),
        c("ui-bigger", "Ingrandisci testo dello schermo", "ui-bigger"),
        c("ui-smaller", "Riduci testo dello schermo", "ui-smaller"),
        c("ruler", "Righelli", "ruler"),
        t("show-toolbar", "Mostra sempre la barra strumenti ", "show-toolbar"),
        t("show-statusbar", "Barra di stato", "show-statusbar"),
        t("show-left", "Pannello sinistro", "show-left"),
        t("show-right", "Pannello destro", "show-right"),
    ]},
    Tab { name: "Macro", cmds: &[
        c("py-list", "Blocca cella", "plug-manage"),
        c("py-folder", "Aggiungi intervallo", "py-folder"),
        c("ai-macro", "Rimuovi frecce", "ai-macro"),
    ]},
];

pub const CALC: &[Tab] = &[
    Tab { name: "File", cmds: &[
        c("open", "Apri", "open"),
        c("save", "Salva", "save"),
        c("pdf", "Stampa", "print"),
    ]},
    Tab { name: "Base", cmds: &[
        c("copy", "Copia", "copy"),
        c("cut", "Taglia", "cut"),
        c("paste", "Incolla", "paste"),
        c("copystyle", "Copia formato", "copystyle"),
        c("fontname", "Carattere", "fontname"),
        c("fontsize", "Dimensione carattere", "fontsize"),
        c("incfont", "Aumenta dimensione caratteri ", "incfont"),
        c("decfont", "Riduci dimensione caratteri", "decfont"),
        c("changecase", "Cambia forma", "changecase"),
        c("bold", "Grassetto", "bold"),
        c("italic", "Corsivo", "italic"),
        c("underline", "Sottolineato", "underline"),
        c("strikeout", "Barrato", "strikeout"),
        c("subscript", "Pedice", "subscript"),
        c("fontcolor", "Colore caratteri", "fontcolor"),
        c("fillparag", "Colore di riempimento", "fillparag"),
        c("borders", "Bordi", "borders"),
        c("top", "Allinea in alto", "top"),
        c("middle", "Allinea in mezzo", "middle"),
        c("bottom", "Allinea in basso", "bottom"),
        c("wrap", "Riempimento rapido", "wrap"),
        c("text-orient", "Orientamento del testo", "text-orient"),
        c("align-left", "Allinea a sinistra", "align-left"),
        c("align-center", "Al centro", "align-center"),
        c("align-right", "Allinea a destra", "align-right"),
        c("align-just", "Giustificato", "align-just"),
        c("align-dist", "Direzione del testo", "align-dist"),
        c("merge", "Unisci e centra", "merge"),
        c("direction", "Aggiorna indice delle figure", "direction"),
        c("sum", "Zoom al 100%", "autosum"),
        c("fill-num", "Risolutore", "fill-num"),
        c("defname", "Gestore nomi", "named-range"),
        c("clear", "Svuota", "clear"),
        c("sort-desc", "Ordine decrescente", "sortdesc"),
        c("sort-asc", "Ordine crescente", "sortasc"),
        c("setfilter", "Filtri", "setfilter"),
        c("clear-filter", "Da testo a dati", "clear-filter"),
        c("format", "Formato del numero", "format"),
        c("currency", "Stile valuta", "currency"),
        c("percents", "Stile percentuale", "percents"),
        c("comma", "Stile della virgola", "comma"),
        c("digit-dec", "Diminuisci decimali", "digit-dec"),
        c("digit-inc", "Aumenta decimali", "digit-inc"),
        c("cell-ins", "Inserisci celle", "cell-ins"),
        c("cell-del", "Elimina celle", "cell-del"),
        c("cell-format", "Formatta celle", "cell-format"),
        c("condformat", "Formattazione condizionale", "condformat"),
        c("table-tpl", "Formatta come modello di tabella", "table-tpl"),
        c("cell-styles", "Stile cella", "styles"),
        c("replace", "Sostituisci", "replace"),
        c("selectall", "Seleziona tutto", "select-all"),
    ]},
    Tab { name: "Inserisci", cmds: &[
        c("pivot-insert", "Inserisci tabella pivot", "add-pivot"),
        c("instable", "Inserisci tabella", "instable"),
        c("insimage", "Inserisci immagine", "insimage-c"),
        c("insshape", "Inserisci forma", "insshape"),
        c("inssmartart", "Inserisci SmartArt", "inssmartart"),
        c("inscheckbox", "Testo da destra a sinistra", "inscheckbox"),
        c("insrecommend", "Inserisci grafico consigliato", "insrecommend"),
        c("inschart", "Inserisci grafico", "inschart"),
        c("inssparkline", "Inserire grafico sparkline", "inssparkline"),
        c("co-addcomment", "Commenti", "ins-comment"),
        c("inshyperlink", "Aggiungi collegamento", "inshyperlink"),
        c("insslicer", "Inserisci filtro dati", "insslicer"),
        c("instext", "Inserisci casella di testo", "instext"),
        c("instextart", "Inserisci Text Art", "instextart"),
        c("edit-header", "Intestazione e piè di pagina", "editheader"),
        c("insequation", "Inserisci equazione", "insequation"),
        c("inssymbol", "Inserisci simbolo", "inssymbol"),
    ]},
    Tab { name: "Disegna", cmds: &[
        c("draw-select", "Seleziona", "select-tool"),
        c("pen", "Penna", "pen"),
        c("highlighter", "Evidenziatore", "highlighter"),
        c("eraser", "Gomma", "eraser"),
    ]},
    Tab { name: "Schema di pagina", cmds: &[
        c("pagemargins", "Margini", "pagemargins"),
        c("pageorient", "Orientamento pagina", "pageorient"),
        c("pagesize", "Dimensione pagina", "pagesize"),
        c("printarea", "Area di stampa", "printarea"),
        c("pagebreak", "Interruzioni", "pagebreak"),
        c("edit-header", "Intestazione e piè di pagina", "editheader"),
        c("scale", "Adatta", "scale"),
        c("fit-pages", "Intervallo copie", "fit-pages"),
        c("printarea-add", "Testo a capo", "printarea-add"),
        c("show-breaks", "Nuovo .py", "show-breaks"),
        c("printtitles", "Stampa titoli", "printtitles"),
        c("rtl-sheet", "Inverti la direzione del foglio in modo da visualizzare la prima colonna sul lato destro", "rtl-sheet"),
        c("print-gridlines", "Mostra formule", "print-gridlines"),
        c("print-headings", "Stampa griglia", "print-headings"),
        x("Porta avanti", "img-movefrwd"),
        x("Porta indietro", "img-movebkwd"),
        x("Allineamento", "img-align"),
        x("Raggruppa", "img-group"),
        x("Fondi forme", "shapes-merge"),
        c("colorschemas", "Cambia combinazione di colori", "colorschemas"),
    ]},
    Tab { name: "Formula", cmds: &[
        c("insert-function", "Inserisci funzione", "additional-formula"),
        c("func-list", "Funzioni Python", "py-list"),
        c("sum", "Zoom al 100%", "autosum"),
        c("fn-recent", "Collegamenti esterni (importa come valori)", "recent"),
        c("fn-financial", "Finanziario", "financial"),
        c("fn-logical", "Logico", "logical"),
        c("fn-text", "Testo", "text"),
        c("fn-datetime", "Data e ora", "datetime"),
        c("fn-lookup", "Ricerca e riferimento", "lookup"),
        c("fn-math", "Matematica e trigonometria", "math"),
        c("fn-more", "Altre funzioni", "more"),
        c("defname", "Gestore nomi", "named-range-huge"),
        c("paste-name", "Tabella dati", "paste-name"),
        c("trace-prec", "Traccia le precedenti", "trace-prec"),
        c("trace-dep", "Traccia le dipendenti", "trace-dep"),
        c("remove-arrows", "Elimina commento", "remove-arrows"),
        c("show-formulas", "Indice delle figure", "show-formulas"),
        c("watch", "Mostra zeri", "watch-window"),
        c("calc-mode", "Errori di conversione", "calculate"),
    ]},
    Tab { name: "Dati", cmds: &[
        c("data-from-text", "Registra azioni", "data-from-text"),
        c("data-external-links", "Didascalia", "data-external-links"),
        c("setfilter", "Filtri", "setfilter"),
        c("clear-filter", "Da testo a dati", "clear-filter"),
        c("sort-desc", "Ordine decrescente", "sortdesc"),
        c("sort-asc", "Ordine crescente", "sortasc"),
        c("custom-sort", "Ordina", "custom-sort"),
        c("text-column", "Riempimento", "text-column"),
        c("rem-duplicates", "Colonne alternate", "rem-duplicates"),
        c("data-validation", "Validazione dati", "data-validation"),
        t("dv-mark", "Cerchia dati non validi", "dv-mark"),
        c("goal-seek", "Goal seek", "goal-seek"),
        c("scenario", "Scenario", "scenario"),
        c("forecast", "Foglio di previsione", "forecast"),
        c("solver", "Somma automatica", "solver"),
        c("group", "Raggruppa", "group"),
        c("ungroup", "Separa", "ungroup"),
        c("show-details", "Mostra dettagli", "show-details"),
        c("hide-details", "Aggiorna sommario", "hide-details"),
        c("subtotal", "Totali Parziali", "subtotal"),
        c("datatable", "Inserisci funzione", "datatable"),
        c("python", "Calcolo", "python"),
        c("csv-kind", "Nascondi dettaglio", "csv-kind"),
        c("flash-fill", "Formato CSV", "flash-fill"),
    ]},
    Tab { name: "Macro", cmds: &[
        c("rec-toggle", "Tema dell'interfaccia", "py-run"),
        c("py-new", "Incolla nome", "py-new"),
        c("py-list", "Blocca cella", "py-list"),
        c("ribbon-list", "Macro della barra", "py-line"),
        c("py-folder", "Aggiungi intervallo", "py-folder"),
    ]},
    Tab { name: "Tabella pivot", cmds: &[
        c("pivot-insert", "Inserisci tabella pivot", "pivot-insert"),
        c("pivot-fields", "Elenco campi", "pivot-fields"),
        c("pivot-refresh", "Aggiorna", "pivot-refresh"),
        c("pivot-refresh-all", "Aggiorna tutto", "pivot-refresh-all"),
        c("pivot-source", "Origine dati", "pivot-source"),
        c("pivot-chart", "Grafico pivot", "pivot-chart"),
        c("pivot-select", "Seleziona", "pivot-select"),
        c("pivot-totals", "Totale complessivo", "pivot-totals"),
        c("pivot-subtotals", "Totali Parziali", "pivot-subtotals"),
        c("pivot-blank", "Righe vuote", "pivot-blank"),
        c("pivot-showas", "Adatta alla pagina", "pivot-showas"),
        c("pivot-layout", "Schema del rapporto", "pivot-layout"),
        c("pivot-style", "Stile", "pivot-style"),
    ]},
    Tab { name: "Struttura tabella", cmds: &[
        c("td-header", "Riga di intestazione", "td-header"),
        c("td-total", "Riga totale", "td-total"),
        c("td-band-row", "Righe a strisce", "td-band-row"),
        c("td-first", "Prima colonna", "td-first"),
        c("td-last", "Ultima colonna", "td-last"),
        c("td-band-col", "Usate di recente", "td-band-col"),
        c("td-filter", "Pulsante filtro", "td-filter"),
        c("rem-duplicates", "Rimuovi duplicati", "td-remdup"),
        c("td-torange", "Converti in intervallo", "td-torange"),
        c("td-resize", "Ridimensiona tabella", "td-resize"),
    ]},
    Tab { name: "Collaborazione", cmds: &[
        c("coauth-mode", "Casella di controllo", "coauth-mode"),
        c("co-addcomment", "Aggiungi commento", "co-addcomment"),
        c("co-delcomment", "Finestra controllo celle", "co-delcomment"),
        c("co-showcomment", "Mostra commento", "co-showcomment"),
        c("co-chat", "Grafico consigliato", "co-chat"),
        c("co-history", "Collegamenti esterni", "co-history"),
    ]},
    Tab { name: "Protezione", cmds: &[
        c("prot-encrypt", "Modalità collaborativa", "prot-encrypt"),
        xt("Proteggere libro di lavoro", "protect-workbook"),
        c("prot-doc", "Proteggi foglio", "protect-sheet"),
        xt("Proteggi rango", "protect-range"),
        c("prot-sign", "Cronologia versioni", "prot-sign"),
        c("cell-lock", "Rimuovi duplicati", "cell-lock"),
        c("prot-allow", "Fine pagina", "prot-allow"),
        c("recover", "Ripristino", "recover"),
        c("recover-every", "Elenco", "recover-every"),
        c("read-only-rec", "Consiglia sola lettura", "read-only-rec"),
    ]},
    Tab { name: "Visualizza", cmds: &[
        c("sheet-view", "Visualizzazione foglio", "sheet-view"),
        xm("Normale", "view-normal"),
        xm("Anteprima interruzione di pagina", "view-pagebreak"),
        c("zoom-in", "Zoom avanti", "zoom-in"),
        c("zoom-out", "Zoom indietro", "zoom-out"),
        c("zoom100", "Aggiungi firma digitale", "zoom100"),
        c("ui-bigger", "Ingrandisci testo dello schermo", "ui-bigger"),
        c("ui-smaller", "Riduci testo dello schermo", "ui-smaller"),
        t("darkmode", "Modalità scura", "theme"),
        c("freeze", "Blocca riquadri", "freeze"),
        t("split", "Dividi finestra", "split"),
        t("formula-bar", "Barra della formula", "formula-bar"),
        c("show-gridlines", "Linee griglia", "show-gridlines"),
        t("show-headings", "Intestazioni", "show-headings"),
        t("show-zeros", "Crittografa", "show-zeros"),
        t("show-left", "Pannello sinistro", "show-left"),
        t("show-right", "Pannello destro", "show-right"),
    ]},
];

