//! リボンの tr の**語の表** — 構造は持たない(2026-08-31 の作り替え)。
//! 骨組みは ribbon.rs の1本だけで、ここには (英語の札, 語) の対しか無い。
//! 言語の表は実行時に ribbon::localized が骨組みへ差し込んで組む —
//! 骨組みが言語ごとにずれる余地は、作りから消してある。
//!
//! このファイルは手で書かない:
//!
//! ```text
//! python3 ui/gen_ribbon_locale.py tr > face/src/ribbon_tr.rs
//! ```
//!
//! 対訳は vendor/web-apps のロケール(本家の語)。本家に無いこちらの
//! ボタンは gen_ribbon_locale.py の OVERRIDES 表で訳す。

pub const WORDS: &[(&str, &str)] = &[
    ("Add Comment", "Yorum Ekle"),
    ("Add Text", "Metin Ekle"),
    ("Add digital signature", "Dijital imza ekle"),
    ("Add link", "Köprü Ekle"),
    ("Add to area", "Aralık ekle"),
    ("Align bottom", "Alta Hizala"),
    ("Align left", "Sola Hizala"),
    ("Align middle", "Ortaya hizala"),
    ("Align right", "Sağa Hizala"),
    ("Align top", "Üste Hizala"),
    ("Alignment", "Hiza"),
    ("Allowed actions", "İzin verilen işlemler"),
    ("Always Show Toolbar", "Her zaman araç çubuğunu göster"),
    ("AutoSum", "Otomatik Toplam"),
    ("Backup interval", "Yedek aralığı"),
    ("Banded Rows", "Bantlı Satırlar"),
    ("Banded columns", "Şeritli sütunlar"),
    ("Bigger UI text", "Ekran yazısını büyüt"),
    ("Blank Rows", "Boş Satırlar"),
    ("Bold", "Kalın"),
    ("Bookmark", "Yer imi"),
    ("Borders", "Kenarlıklar"),
    ("Breaks", "Sonlar"),
    ("Bring forward", "İleri Taşı"),
    ("Bullet", "Madde"),
    ("CSV format", "CSV biçimi"),
    ("Calculation options", "Hesaplama"),
    ("Caption", "Resim yazısı"),
    ("Cell Style", "Hücre Stili"),
    ("Cell lock", "Hücre kilidi"),
    ("Centre", "Orta"),
    ("Change case", "Büyük/küçük harf değiştir"),
    ("Change colour theme", "Renk Şemasını Değiştir"),
    ("Change hyphenation", "Hecelemeyi Değiştir"),
    ("Change page colour", "Sayfa Rengini Değiştir"),
    ("Chat", "Sohbet"),
    ("Checkbox", "Onay kutusu"),
    ("Circle invalid data", "Geçersiz verileri daire içine al"),
    ("Clear", "Temizle"),
    ("Clear filter", "Filtreyi temizle"),
    ("Clear style", "Stili Temizle"),
    ("Co-editing mode", "Birlikte düzenleme modu"),
    ("Collaboration", "Ortak Çalışma"),
    ("Combo box", "Açılan kutu"),
    ("Comma style", "Virgül stili"),
    ("Comment", "Yorumlar"),
    ("Complex Field", "Karmaşık alan"),
    ("Conditional formatting", "Koşullu biçimlendirme"),
    ("Convert to range", "Aralığa dönüştür"),
    ("Copy", "Kopyala"),
    ("Cross-reference", "Çapraz referans"),
    ("Currency style", "Kur Stili"),
    ("Cut", "Kes"),
    ("Dark mode", "Karanlık mod"),
    ("Data", "Veri"),
    ("Data Validation", "Veri doğrulama"),
    ("Data source", "Veri kaynağı"),
    ("Data table", "Veri tablosu"),
    ("Date & Time", "Tarih/Saat"),
    ("Decrease decimal", "Ondalık Azalt"),
    ("Decrease indent", "Girintiyi azalt"),
    ("Decrement font size", "Yazı boyutunu azalt"),
    ("Delete cells", "Hücre Sil"),
    ("Delete comment", "Açıklamayı sil"),
    ("Distributed", "Dağıtılmış"),
    ("Draw", "Çizim"),
    ("Dropdown", "Aşağı açılır"),
    ("Edit footer", "Altlığı Düzenle"),
    ("Edit header", "Üst Bilgiyi Düzenle"),
    ("Edit watermark", "Filigranı düzenle"),
    ("Email Address", "Eposta adresi"),
    ("Encrypt", "Şifrele"),
    ("Eraser", "Silgi"),
    ("External links (import as values)", "Dış bağlantılar (değer olarak al)"),
    ("Field list", "Alan listesi"),
    ("File", "Dosya"),
    ("Fill", "Doldur"),
    ("Fill by example", "Hızlı doldurma"),
    ("Fill colour", "Dolgu Rengi"),
    ("Filter button", "Filtre düğmesi"),
    ("Filters", "Filtreler"),
    ("Financial", "Finansal"),
    ("First column", "İlk Sütun"),
    ("Fit to page", "Sayfaya Sığdır"),
    ("Fit to paper", "Kâğıda sığdır"),
    ("Fit to width", "Genişliğe Sığdır"),
    ("Font", "Yazı Tipi"),
    ("Font colour", "Yazı Tipi Rengi"),
    ("Font size", "Yazıtipi boyutu"),
    ("Footnote", "Dipnot"),
    ("Forecast Sheet", "Tahmin sayfası"),
    ("Format as table template", "Tablo Şablonu olarak biçimlendir"),
    ("Format cells", "Hücreleri biçimlendir"),
    ("Format painter", "Biçim boyacısı"),
    ("Forms", "Formlar"),
    ("Formula", "Formül"),
    ("Formula Bar", "Formül çubuğu"),
    ("Freeze panes", "Parçaları Dondur"),
    ("Goal Seek", "Hedef Ara"),
    ("Grand Total", "Genel Toplamlar"),
    ("Group", "Grup"),
    ("Header & Footer", "Üst/Alt Bilgi"),
    ("Header row", "Üst bilgi satırı"),
    ("Headings", "Başlıklar"),
    ("Hide detail", "Ayrıntıyı gizle"),
    ("Highlight colour", "Vurgu Rengi"),
    ("Highlighter", "Vurgulayıcı"),
    ("Home", "Ana Sayfa"),
    ("Increase decimal", "Ondalık Arttır"),
    ("Increase indent", "Girintiyi arttır"),
    ("Increment font size", "Yazı boyutunu arttır"),
    ("Insert", "Ekle"),
    ("Insert Pivot Table", "Pivot Tablo Ekle"),
    ("Insert SmartArt", "SmartArt ekle"),
    ("Insert Text Art", "Yazı Sanatı Ekle"),
    ("Insert blank page", "Boş sayfa ekle"),
    ("Insert cells", "Hücre Ekle"),
    ("Insert chart", "Grafik ekle"),
    ("Insert column", "Sütun Ekle"),
    ("Insert content controls", "İçerik kontrolleri ekle "),
    ("Insert drop cap", "Büyük Harf Ekle"),
    ("Insert equation", "Denklem Ekle"),
    ("Insert function", "İşlev ekle"),
    ("Insert image", "Resim ekle"),
    ("Insert recommended chart", "Önerilen grafik ekle"),
    ("Insert shape", "Şekil ekle"),
    ("Insert slicer", "Dilimleyici Ekle "),
    ("Insert sparkline", "Mini grafik ekle"),
    ("Insert symbol", "Simge ekle"),
    ("Insert table", "Tablo ekle"),
    ("Insert text box", "Metin kutusu ekle"),
    ("Italic", "Eğik"),
    ("Justified", "İki yana yaslı"),
    ("Last column", "Son sütun"),
    ("Layout", "Tasarım"),
    ("Left Panel", "Sol Panel"),
    ("Logical", "Mantıksal"),
    ("Lookup & Reference", "Arama ve Referans"),
    ("Macro list", "Liste"),
    ("Macros", "Makrolar"),
    ("Margins", "Kenar Boşlukları"),
    ("Math & Trig", "Matematik/Trigonometri"),
    ("Merge and centre", "Birleştir ve ortala"),
    ("Merge shapes", "Şekilleri birleştir"),
    ("More functions", "Daha fazla fonksiyon"),
    ("Multilevel list", "Çok düzeyli liste"),
    ("Multiple pages", "Çoklu sayfa"),
    ("Name", "Ad"),
    ("Name manager", "Manager"),
    ("Navigation", "Gezinti"),
    ("New .py", "Yeni .py"),
    ("Nonprinting characters", "Basılmaz Karakterler"),
    ("Number format", "Sayı Formatı"),
    ("Number of pages", "Sayfa sayısı"),
    ("Numbering", "Numaralandırma"),
    ("Open", "Aç"),
    ("Open folder", "Klasörü aç"),
    ("Page Break Preview", "Sayfa Sonu Önizlemesi"),
    ("Page breaks", "Sayfa sonları"),
    ("Page number", "Sayfa Numarası"),
    ("Page orientation", "Oryantasyon"),
    ("Page size", "Sayfa Boyutu"),
    ("Paragraph line spacing", "Paragraf satır aralığı"),
    ("Paragraph style", "Paragraf Stili"),
    ("Paste", "Yapıştır"),
    ("Paste name", "Ad yapıştır"),
    ("Pen", "Kalem"),
    ("Percent style", "Yüzde Stili"),
    ("Phone Number", "Telefon numarası"),
    ("Picture", "Resim"),
    ("Pivot Table", "Pivot Tablo"),
    ("Print", "Yazdır"),
    ("Print Area", "Yazdırma Alanı"),
    ("Print gridlines", "Kılavuz çizgileri de yazdır"),
    ("Print headings", "Başlıkları da yazdır"),
    ("Print titles", "Başlıkları yazdır"),
    ("Protect Range", "Aralığı koru"),
    ("Protect sheet", "Sayfayı Koruyun"),
    ("Protect workbook", "Çalışma Kitabını Koru"),
    ("Protection", "Koruma"),
    ("Python functions", "Python işlevleri"),
    ("Radio Button", "Seçenek Düğmesi"),
    ("Recently used", "Son kullanılan işlevler"),
    ("Record actions", "İşlemleri kaydet"),
    ("Recover", "Kurtarma"),
    ("References", "Kaynakça"),
    ("Remove Duplicates", "Yinelenenleri Kaldır"),
    ("Remove arrows", "Okları kaldır"),
    ("Remove duplicates", "Yinelenenleri kaldır"),
    ("Replace", "Değiştir"),
    ("Report Layout", "Rapor Düzeni"),
    ("Resize table", "Tabloyu yeniden boyutlandır"),
    ("Ribbon macros", "Şerit makroları"),
    ("Right Panel", "Sağ Panel"),
    ("Right-to-left text", "Metin yönü (sağdan sola)"),
    ("Rulers", "Cetveller"),
    ("Save", "Kaydet"),
    ("Scale To Fit", "Sığdırmak için Ölçekle"),
    ("Scenario", "Senaryo"),
    ("Select", "Seç"),
    ("Select all", "Tümünü seç"),
    ("Send Backward", "Geri Gönder"),
    ("Shading", "Paragraf Arka Plan Rengi"),
    ("Sheet View", "Sayfa Görünümü"),
    ("Show comments", "Yorumu göster"),
    ("Show details", "Detayları Göster"),
    ("Show formulas", "Formülleri göster"),
    ("Show line numbers", "Satır numaralarını göster"),
    ("Show values as", "Hesaplama türü"),
    ("Show zeros", "Sıfırları göster"),
    ("Signature", "İmza"),
    ("Smaller UI text", "Ekran yazısını küçült"),
    ("Solver", "Çözücü"),
    ("Sort", "Sırala"),
    ("Sort ascending", "En düşükten en yükseğe sırala"),
    ("Sort descending", "En yüksekten en aza sırala"),
    ("Split", "Pencereyi böl"),
    ("Status Bar", "Durum Çubuğu"),
    ("Strikethrough", "Üstü çizili"),
    ("Style", "Stil"),
    ("Subscript", "Altsimge"),
    ("Subtotals", "Ara toplamlar"),
    ("Suggest read-only", "Salt okunuru öner"),
    ("Superscript", "Üst Simge"),
    ("Switch the sheet direction so that the first column is on the right side", "Sayfa yönünü ilk sütun sağda olacak şekilde değiştir"),
    ("Table Design", "Tablo tasarımı"),
    ("Table of contents", "İçindekiler Tablosu"),
    ("Table of figures", "Şekiller tablosu"),
    ("Text Field", "Metin Alanı"),
    ("Text direction", "Metin yönü"),
    ("Text from File", "Dosyadan metin"),
    ("Text functions", "Metin"),
    ("Text orientation", "Metin yönü"),
    ("Text to columns", "Metni sütunlara dönüştür"),
    ("Text to data", "Metinden veri"),
    ("Total row", "Toplam satırı"),
    ("Trace Dependents", "Etkilenenleri izle"),
    ("Trace Precedents", "Etkileyenleri izle"),
    ("Track changes", "Değişiklikleri izle"),
    ("Underline", "Altı çizili"),
    ("Ungroup", "Gruptan çıkar"),
    ("Update", "Yenile"),
    ("Update all", "Tümünü yenile"),
    ("Update table of contents", "İçindekiler tablosunu güncelle"),
    ("Update table of figures", "Şekiller tablosunu güncelle"),
    ("Version history", "Sürüm geçmişi"),
    ("View", "Görüntüle"),
    ("Watch window", "Gözcü penceresi"),
    ("Wrap text", "Metni kaydır"),
    ("Write macro", "Makro yaz"),
    ("Zoom in", "Yakınlaştır"),
    ("Zoom out", "Uzaklaştır"),
    ("Zoom to 100%", "%100'e yakınlaştır"),
];

/// 同じ札で働きが違うボタンの語(id か icon で引く)
pub const WORDS_BY_ID: &[(&str, &str)] = &[
];

